-- SANKHYA.TRG_DLT_TRIDRR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIDRR
"SANKHYA".TRG_DLT_TRIDRR
AFTER DELETE  ON TRIDRR  
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIAPPR T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
	  AND :OLD.CODPARC = T.CODPARC
      AND :OLD.CODIMP = T.CODIMP
      AND :OLD.SEQITE = T.SEQITE;
   

	IF P_COUNT > 0 THEN
		DELETE FROM TRIAPPR
		WHERE :OLD.CODEMP = TRIAPPR.CODEMP 
		  AND :OLD.DTREF = TRIAPPR.DTREF 
		  AND :OLD.TPAMB = TRIAPPR.TPAMB 
		  AND :OLD.SEQUENCIA = TRIAPPR.SEQUENCIA 
		  AND :OLD.CHAVE = TRIAPPR.CHAVE
          AND :OLD.NRODOCUMENTO = TRIAPPR.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIAPPR.TIPODOCUMENTO
          AND :OLD.NATREND = TRIAPPR.NATREND 
          AND :OLD.CODPARC = TRIAPPR.CODPARC
          AND :OLD.CODIMP = TRIAPPR.CODIMP
          AND :OLD.SEQITE = TRIAPPR.SEQITE;
	END IF;
END;		

/
