-- SANKHYA.TRG_DLT_TRIPPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIPPJ
"SANKHYA".TRG_DLT_TRIPPJ 
AFTER DELETE ON TRIPPJ
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIIRPJ T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIIRPJ
		WHERE :OLD.CODEMP = TRIIRPJ.CODEMP 
		  AND :OLD.DTREF = TRIIRPJ.DTREF 
		  AND :OLD.TPAMB = TRIIRPJ.TPAMB 
		  AND :OLD.SEQUENCIA = TRIIRPJ.SEQUENCIA
		  AND :OLD.CHAVE = TRIIRPJ.CHAVE;
	END IF;
END;	

/
