-- SANKHYA.TRG_INC_UPD_TGFCRI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCRI
"SANKHYA".TRG_INC_UPD_TGFCRI BEFORE INSERT OR UPDATE ON TGFCRI  FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
    ERRMSG  VARCHAR2(255);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;


  IF :NEW.CODEMP IS NOT NULL AND :NEW.CODEMP <> NVL(:OLD.CODEMP,0) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFEMP E
    WHERE E.CODEMP = NVL(:NEW.CODEMP, 1)
    AND E.ATIVO = 'S';
    IF (P_COUNT = 0) THEN
      ERRMSG := 'Empresa '||:NEW.CODEMP||' não esta ativa.';
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF;
  END IF;

  IF :NEW.CODNAT IS NOT NULL AND :NEW.CODNAT <> NVL(:OLD.CODNAT,0) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFNAT E
    WHERE E.CODNAT = :NEW.CODNAT
    AND E.ATIVA = 'S' AND E.ANALITICA= 'S' ;
    IF (P_COUNT = 0) THEN
       ERRMSG := 'Natureza '||:NEW.CODNAT||' não esta ativa, não e analítica ou não existe';
       RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF;
  END IF;

  IF :NEW.CODCENCUS IS NOT NULL AND :NEW.CODCENCUS <> NVL(:OLD.CODCENCUS,0) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TSICUS E
    WHERE E.CODCENCUS = :NEW.CODCENCUS
    AND E.ATIVO = 'S'
    AND E.ANALITICO= 'S' ;
    IF (P_COUNT = 0) THEN
      ERRMSG := 'Centro de resultado '||:NEW.CODCENCUS||' não esta ativo, não é analítico ou não existe.';
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF;
  END IF;

  IF :NEW.CODPROJ IS NOT NULL AND :NEW.CODPROJ <> NVL(:OLD.CODPROJ,0) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TCSPRJ E
    WHERE E.CODPROJ = :NEW.CODPROJ
    AND E.ATIVO = 'S'
    AND E.ANALITICO= 'S';
    IF (P_COUNT = 0) THEN
      ERRMSG := 'Projeto '||:NEW.CODPROJ||' não esta ativo, não e analítico ou não existe.';
      RAISE_APPLICATION_ERROR(-20101,ERRMSG);
    END IF;
  END IF;
END;

/
