-- SANKHYA.TRG_DLT_TCIBEM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCIBEM
"SANKHYA".TRG_DLT_TCIBEM BEFORE DELETE ON TCIBEM FOR EACH ROW

DECLARE
  P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (VARIAVEIS_PKG.V_SBPRODUTO) THEN
    RETURN;
  END IF;
  
  SELECT COUNT (1) INTO P_COUNT
  FROM TSIPAR
  WHERE CHAVE = 'SBPRODUTO';

  IF (P_COUNT > 0) THEN
    RETURN;
  END IF;
  
  IF (NVL(:OLD.NUNOTA, 0) <> 0) OR
     (NVL(:OLD.NUNOTABAIXA, 0) <> 0) OR
     (NVL(:OLD.NUNOTADEV, 0) <> 0) OR
     (NVL(:OLD.NUNOTASAIDA, 0) <> 0) OR
     (NVL(:OLD.NUNOTADEVVENDA, 0) <> 0) THEN 
    RAISE_APPLICATION_ERROR(-20101, 'Bem não pode ser deletado pois existe movimentação.');
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TCILOC
  WHERE CODPROD = :OLD.CODPROD 
    AND CODBEM = :OLD.CODBEM;
  
  IF P_COUNT > 0 THEN
    DELETE FROM TCILOC WHERE CODPROD = :OLD.CODPROD AND CODBEM = :OLD.CODBEM;
  END IF;
  
END;

/
