-- SANKHYA.TRG_INC_TGFTBR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFTBR
"SANKHYA".TRG_INC_TGFTBR
BEFORE INSERT ON TGFTBR 
FOR EACH ROW

BEGIN
  SELECT SEQ_TGFTBR.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
