-- SANKHYA.TRG_INC_TGFCOI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFCOI
"SANKHYA".TRG_INC_TGFCOI BEFORE INSERT ON TGFCOI FOR EACH ROW

DECLARE
    P_COUNT_COL               INT:= 0;
    P_COUNT_CON               INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT_COL
  FROM  TGFCOL
  WHERE NUCONF = :NEW.NUCONF;
  SELECT COUNT(1) INTO P_COUNT_CON
  FROM  TGFCON
  WHERE NUCONF = :NEW.NUCONF
    AND SEQUENCIA = :NEW.SEQUENCIA;
  IF  ((P_COUNT_COL = 0) AND (P_COUNT_CON = 0)) THEN
     RAISE_APPLICATION_ERROR (-20101, 'Registro referenciado na TGFCOI n?o existe. Verifique na TGFCON ou na TGFCOL.');
  END IF;
END;

/
