-- SANKHYA.TRG_DLT_TGFEFDC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFEFDC
"SANKHYA".TRG_DLT_TGFEFDC
BEFORE DELETE ON TGFEFDC
FOR EACH ROW

DECLARE P_COUNT NUMBER(10);
BEGIN 
	SELECT COUNT(1) INTO P_COUNT FROM TGFDOCRECSCP WHERE CODEMP = :OLD.CODEMP AND DTREF = :OLD.DTREF;
	
	IF P_COUNT > 0 THEN
		DELETE FROM TGFDOCRECSCP WHERE CODEMP = :OLD.CODEMP AND DTREF = :OLD.DTREF;
	END IF;
END;

/
