-- SANKHYA.TRG_INC_AUDITTFPFOL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_AUDITTFPFOL
"SANKHYA".TRG_INC_AUDITTFPFOL
BEFORE INSERT ON AUDITTFPFOL 
FOR EACH ROW

BEGIN
  SELECT AUDITTFPFOL_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
