-- SANKHYA.TRG_INC_UPD_DLT_TPRAPF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TPRAPF
"SANKHYA".TRG_INC_UPD_DLT_TPRAPF
BEFORE INSERT OR UPDATE OR DELETE
ON TPRAPF
FOR EACH ROW

BEGIN
     IF INSERTING OR UPDATING THEN
        IF UPDATING AND (
        (NVL(:NEW.NUAPO, 0) <> NVL(:OLD.NUAPO, 0)) OR
        (NVL(:NEW.SEQAPA, 0) <> NVL(:OLD.SEQAPA, 0)) OR
         (NVL(:NEW.NUNOTA, 0) <> NVL(:OLD.NUNOTA, 0)) OR
         (NVL(:NEW.SEQITE, 0) <> NVL(:OLD.SEQITE, 0))) THEN
            RAISE_APPLICATION_ERROR(-20101, 'Tabela TPRAPF não permite alterações em campos da chave-primária.'); 
         END IF;
     
           UPDATE TPRAPA SET
             QTDFAT =  CASE WHEN NVL(:NEW.SEQITE, 0) = 0 THEN QTDFAT ELSE QTDFAT + NVL(:NEW.QTD, 0) - NVL(:OLD.QTD, 0) END
           , QTDFATSP =  CASE WHEN NVL(:NEW.SEQITE, 0) = 0 THEN QTDFATSP + NVL(:NEW.QTD, 0) - NVL(:OLD.QTD, 0) ELSE QTDFATSP END
           WHERE NUAPO = :NEW.NUAPO
             AND SEQAPA = :NEW.SEQAPA;
     
     ELSE --DELETE
          UPDATE TPRAPA SET
             QTDFAT = CASE WHEN NVL(:OLD.SEQITE, 0) = 0 THEN QTDFAT ELSE QTDFAT - NVL(:OLD.QTD, 0) END
           , QTDFATSP = CASE WHEN NVL(:OLD.SEQITE, 0) = 0 THEN QTDFATSP - NVL(:OLD.QTD, 0) ELSE QTDFATSP END             
         WHERE NUAPO = :OLD.NUAPO
           AND SEQAPA = :OLD.SEQAPA;               
     END IF;
END;

/
