-- SANKHYA.TRG_INC_UPD_DLT_TGAMOV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGAMOV
"SANKHYA".TRG_INC_UPD_DLT_TGAMOV
BEFORE DELETE OR INSERT OR UPDATE
ON TGAMOV FOR EACH ROW

DECLARE
  P_COUNT          INT;
  P_SALDO   FLOAT;
  P_REFERENCIA    DATE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (DELETING OR UPDATING) AND (:OLD.ATUALESTOQUE <> 0) THEN
     SELECT COUNT(1) INTO P_COUNT
       FROM TGASAL
      WHERE CODPROD = :OLD.CODPROD
        AND CODLOCAL = :OLD.CODLOCAL
        AND CODPARC = :OLD.CODPARC
        AND NUMCONTRATO = :OLD.NUMCONTRATO
        AND REFERENCIA = :OLD.DTREFCOB
        AND CONTROLE = :OLD.CONTROLE;

     IF (P_COUNT = 0) THEN
        SELECT MAX(REFERENCIA) INTO P_REFERENCIA 
          FROM TGASAL
         WHERE CODPROD = :OLD.CODPROD
           AND CODLOCAL = :OLD.CODLOCAL
           AND CODPARC = :OLD.CODPARC
           AND REFERENCIA <= :OLD.DTREFCOB
           AND NUMCONTRATO = :OLD.NUMCONTRATO
           AND CONTROLE = :OLD.CONTROLE;

        P_SALDO := 0;

        IF (P_REFERENCIA IS NOT NULL) AND (P_REFERENCIA < :NEW.DTREFCOB) THEN
           SELECT SALDO INTO P_SALDO FROM TGASAL
            WHERE CODPROD = :OLD.CODPROD
              AND CODLOCAL = :OLD.CODLOCAL
              AND CODPARC = :OLD.CODPARC
              AND NUMCONTRATO = :OLD.NUMCONTRATO
              AND CONTROLE = :OLD.CONTROLE 
              AND REFERENCIA = P_REFERENCIA;
        END IF;

        IF (P_REFERENCIA IS NULL) OR (P_REFERENCIA < :NEW.DTREFCOB) THEN 
           INSERT INTO TGASAL (REFERENCIA, CODPROD, CODLOCAL, CODPARC, NUMCONTRATO, SALDO, CONTROLE)
                       VALUES (:OLD.DTREFCOB, :OLD.CODPROD, :OLD.CODLOCAL, :OLD.CODPARC, :OLD.NUMCONTRATO, P_SALDO, :OLD.CONTROLE );
        END IF;        
     END IF;

     UPDATE TGASAL
        SET SALDO = SALDO - (:OLD.QTDNEG * :OLD.ATUALESTOQUE)
      WHERE CODPROD = :OLD.CODPROD
        AND CODLOCAL = :OLD.CODLOCAL
        AND CODPARC = :OLD.CODPARC
        AND NUMCONTRATO = :OLD.NUMCONTRATO
        AND CONTROLE = :OLD.CONTROLE 
        AND REFERENCIA >= :OLD.DTREFCOB;
  END IF;

  IF (INSERTING OR UPDATING) AND (:NEW.ATUALESTOQUE <> 0) THEN
      SELECT COUNT(1)
        INTO P_COUNT
        FROM TGASAL
       WHERE CODPROD = :NEW.CODPROD
         AND CODLOCAL = :NEW.CODLOCAL
         AND CODPARC = :NEW.CODPARC
         AND NUMCONTRATO = :NEW.NUMCONTRATO
         AND CONTROLE = :NEW.CONTROLE 
         AND REFERENCIA = :NEW.DTREFCOB;

     IF (P_COUNT = 0) THEN
        SELECT MAX(REFERENCIA) INTO P_REFERENCIA FROM TGASAL
         WHERE CODPROD = :NEW.CODPROD
           AND CODLOCAL = :NEW.CODLOCAL
           AND CODPARC = :NEW.CODPARC
           AND REFERENCIA <= :NEW.DTREFCOB
           AND CONTROLE = :NEW.CONTROLE 
           AND NUMCONTRATO = :NEW.NUMCONTRATO;
     
        P_SALDO := 0;

        IF P_REFERENCIA IS NOT NULL AND (P_REFERENCIA < :NEW.DTREFCOB) THEN
           SELECT SALDO INTO P_SALDO FROM TGASAL
            WHERE CODPROD = :NEW.CODPROD
              AND CODLOCAL = :NEW.CODLOCAL
              AND CODPARC = :NEW.CODPARC
              AND NUMCONTRATO = :NEW.NUMCONTRATO 
              AND CONTROLE = :NEW.CONTROLE 
              AND REFERENCIA = P_REFERENCIA;
        END IF;

  
        IF (P_REFERENCIA IS NULL) OR (P_REFERENCIA < :NEW.DTREFCOB) THEN 
           INSERT INTO TGASAL (REFERENCIA, CODPROD, CODLOCAL, CODPARC, NUMCONTRATO, SALDO, CONTROLE)
                       VALUES (:NEW.DTREFCOB, :NEW.CODPROD, :NEW.CODLOCAL, :NEW.CODPARC, :NEW.NUMCONTRATO, P_SALDO, :NEW.CONTROLE );
        END IF;        
     END IF;

     UPDATE TGASAL
        SET SALDO = SALDO + (:NEW.QTDNEG * :NEW.ATUALESTOQUE)
      WHERE CODPROD = :NEW.CODPROD
        AND CODLOCAL = :NEW.CODLOCAL
        AND CODPARC = :NEW.CODPARC
        AND NUMCONTRATO = :NEW.NUMCONTRATO
        AND CONTROLE = :NEW.CONTROLE 
        AND REFERENCIA >= :NEW.DTREFCOB;
  END IF;
END;

/
