-- SANKHYA.TRG_INC_UPD_TGFCTB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCTB
"SANKHYA".TRG_INC_UPD_TGFCTB BEFORE UPDATE OR INSERT ON TGFCTB FOR EACH ROW

DECLARE
  P_COUNT INT;
  ERRMSG  VARCHAR2(255);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:NEW.CTACTBCONST = 'S') AND (:NEW.CODCTACTB IS NOT NULL) THEN
     SELECT COUNT(1) INTO P_COUNT
       FROM TCBPLA
      WHERE CODCTACTB = :NEW.CODCTACTB
        AND ATIVA = 'S' AND ANALITICA = 'S';
     IF (P_COUNT = 0) THEN
        ERRMSG := 'Código contábil '||:NEW.CODCTACTB||' não esta ativo, não analítico ou não existe.';
        RAISE_APPLICATION_ERROR(-20101,ERRMSG);
     END IF;
  END IF;
  
  IF (:NEW.CENCUSCONST = 'S') AND (:NEW.CODCENCUS IS NOT NULL) THEN
     SELECT COUNT(1) INTO P_COUNT
       FROM TSICUS
      WHERE CODCENCUS = :NEW.CODCENCUS
        AND ATIVO = 'S' AND ANALITICO = 'S';
     IF (P_COUNT = 0) THEN
        ERRMSG := 'Centro de resultado '||:NEW.CODCENCUS||' não esta ativo, não é analítico ou não existe.';
        RAISE_APPLICATION_ERROR(-20101,ERRMSG);
     END IF;
  END IF;
  IF (:NEW.PROJCONST = 'S') AND (:NEW.CODPROJ IS NOT NULL) THEN
     SELECT COUNT(1) INTO P_COUNT
       FROM TCSPRJ
      WHERE CODPROJ = :NEW.CODPROJ
        AND ATIVO = 'S' AND ANALITICO = 'S';
     IF (P_COUNT = 0) THEN
        ERRMSG := 'Projeto '||:NEW.CODPROJ||' não esta ativo, não e analítico ou não existe.';
        RAISE_APPLICATION_ERROR(-20101,ERRMSG);
     END IF;
  END IF;
END;

/
