-- SANKHYA.TRG_DLT_TRICPRB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRICPRB
"SANKHYA".TRG_DLT_TRICPRB
BEFORE DELETE ON TRICPRB
FOR EACH ROW

BEGIN
    DELETE TRITCAE
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;
END;

/
