-- SANKHYA.TRG_INC_TGWRXN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGWRXN
"SANKHYA".TRG_INC_TGWRXN
BEFORE INSERT ON TGWRXN
FOR EACH ROW

DECLARE
  P_COUNT   NUMBER(5);
BEGIN
	SELECT COUNT(*) INTO P_COUNT FROM TGWEMPE
	WHERE NUNOTA = :NEW.NUNOTA;
	IF P_COUNT > 0 THEN
		UPDATE TGWEMPE 
		SET NURECEBIMENTO = :NEW.NURECEBIMENTO
		WHERE NUNOTA = :NEW.NUNOTA;
	END IF;
END;

/
