-- SANKHYA.TRG_DLT_TGFITE_TGFPROI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_TGFPROI
"SANKHYA".TRG_DLT_TGFITE_TGFPROI
BEFORE DELETE ON TGFPROI 
FOR EACH ROW

DECLARE
  P_COUNT           NUMBER(10);
  ERRMSG            VARCHAR2(255);
  ERROR             EXCEPTION;

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
	
	SELECT COUNT(1) INTO P_COUNT
	FROM TGFITE
	WHERE CODPROMO = :OLD.CODPROMO
	AND CODPROD = :OLD.CODPROD;
	
	IF ((P_COUNT <> 0) AND (P_COUNT IS NOT NULL)) THEN
		ERRMSG := 'Código da promoção não pode ser deletado. Existe ítens pendentes.';
		RAISE ERROR;
	END IF;

  RETURN;  
EXCEPTION
  WHEN ERROR THEN
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
