-- SANKHYA.TRG_DLT_TGFCAB_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCAB_AFTER
"SANKHYA".TRG_DLT_TGFCAB_AFTER 
AFTER DELETE ON TGFCAB

DECLARE
  P_LOOPINDEX         BINARY_INTEGER;
  P_NUNOTA            TGFCAB.NUNOTA%TYPE;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF TGFCAB_PKG.V_CONTADOR <> 0 THEN
    FOR P_LOOPINDEX IN 1..TGFCAB_PKG.V_CONTADOR LOOP
      P_NUNOTA := TGFCAB_PKG.V_NUNOTA(P_LOOPINDEX);
      
      IF P_NUNOTA <> 0 THEN
        DELETE FROM TGFITE WHERE NUNOTA = P_NUNOTA;        
      END IF;

      TGFCAB_PKG.V_NUNOTA(P_LOOPINDEX) := 0;      
    END LOOP;
    TGFCAB_PKG.V_CONTADOR := 0;
  END IF;
 DELETE FROM TGFCAB_DLT;
END;

/
