-- SANKHYA.TRG_FX_TFXINU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXINU
"SANKHYA".TRG_FX_TFXINU
   BEFORE INSERT OR UPDATE
   ON TFXINU
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
