-- SANKHYA.TRG_DLT_TGFLOC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFLOC
"SANKHYA".TRG_DLT_TGFLOC  
BEFORE DELETE ON TGFLOC FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  EXISTSRESTRICAO('TGFLOC',:OLD.CODLOCAL);
  
  IF (:OLD.CODLOCAL = 0) THEN
     raise_application_error(-20101, 'Registro padr?o do sistema. N?o pode ser excluido.');
  END IF;
  
END;

/
