-- SANKHYA.TRG_INC_UPD_TGFSTG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFSTG
"SANKHYA".TRG_INC_UPD_TGFSTG
BEFORE INSERT OR UPDATE ON TGFSTG FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF NOT Fpodevalidar('TGFSTG') THEN
    RETURN;
  END IF;
  
  IF :NEW.CHAVE = 1 AND :NEW.CODIGO > 99 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Código do Genero deve estar entre 0 e 99');
  END IF;

END;

/
