-- SANKHYA.TRG_INC_TFPPONRAIO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPPONRAIO
"SANKHYA".TRG_INC_TFPPONRAIO
   BEFORE INSERT
   ON TFPPONRAIO
   FOR EACH ROW

BEGIN
   SELECT TFPPONRAIO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
