-- SANKHYA.TRG_FX_TGFGRD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFGRD
"SANKHYA".TRG_FX_TGFGRD
   BEFORE INSERT OR UPDATE
   ON TGFGRD
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   	IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S')
	THEN
		SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

		:NEW.NUVERSAO := P_CONTADOR;
		:NEW.ATUNUVERSAO := 'N';
	END IF;
END;

/
