-- SANKHYA.TRG_FX_TSIEMP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TSIEMP
"SANKHYA".TRG_FX_TSIEMP
  BEFORE INSERT OR UPDATE
  ON TSIEMP
  FOR EACH ROW

DECLARE
  P_CONTADOR   NUMBER (19);
  P_VALIDAR    BOOLEAN;
  P_TEM_CHECKOUT BOOLEAN;
  
BEGIN
  IF Stp_Get_Atualizando
  THEN
     RETURN;
  END IF;

  /*
  Sincronização de dados
  */
  P_VALIDAR := Fpodevalidar ('TSIEMP');

  IF (NOT P_VALIDAR)
  THEN
     RETURN;
  END IF;
  
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;

  IF ((NVL (:NEW.RAZAOSOCIAL, '') <> NVL (:OLD.RAZAOSOCIAL, ''))
      OR (NVL (:NEW.NOMEFANTASIA, '') <> NVL (:OLD.NOMEFANTASIA, ''))
	  OR (NVL (:NEW.CGC, '') <> NVL (:OLD.CGC, ''))
	  OR (NVL (:NEW.INSCESTAD, '') <> NVL (:OLD.INSCESTAD, ''))
	  OR (NVL (:NEW.COMPLEMENTO, '') <> NVL (:OLD.COMPLEMENTO, ''))
	  OR (NVL (:NEW.NUMEND, '') <> NVL (:OLD.NUMEND, ''))
	  OR (NVL (:NEW.CEP, '') <> NVL (:OLD.CEP, ''))
	  OR (NVL (:NEW.TELEFONE, '') <> NVL (:OLD.TELEFONE, ''))
	  OR (NVL (:NEW.CODREGTRIB, '') <> NVL (:OLD.CODREGTRIB, ''))
	  OR (NVL (:NEW.SIMPLES, '') <> NVL (:OLD.SIMPLES, ''))
	  OR (NVL (:NEW.CODEND, '') <> NVL (:OLD.CODEND, ''))
	  OR (NVL (:NEW.CODBAI, '') <> NVL (:OLD.CODBAI, ''))
	  OR (NVL (:NEW.CODCID, '') <> NVL (:OLD.CODCID, '')))
  THEN
     SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

     :NEW.NUVERSAO := P_CONTADOR;
  END IF;
END;

/
