-- SANKHYA.TRG_FX_TGFTAB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFTAB
"SANKHYA".TRG_FX_TGFTAB
   BEFORE UPDATE OR DELETE
   ON TGFTAB
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
BEGIN
   IF Stp_Get_Atualizando
   THEN
		RETURN;
   END IF;

   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFTAB');

   IF (NOT P_VALIDAR) THEN
		RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
		RETURN;
   END IF;
 
   /* SE ESTOU DELETANDO PRECISO DELETAR OS PRECOS NA TFXPRC */
   IF (DELETING) THEN
		DELETE FROM TFXPRC WHERE NUTAB = :OLD.NUTAB;
		RETURN;
   END IF;
   
   /* SE ESTOU EDITANDO A DATA DE VIGOR, ATUALIZO TODO MUNDO NA TFXPRC COM O MESMO NUTAB */
   IF ( :NEW.DTVIGOR <> :OLD.DTVIGOR) THEN
		UPDATE TFXPRC P SET P.DATAVIGOR = :NEW.DTVIGOR WHERE P.NUTAB = :NEW.NUTAB;
		RETURN;
   END IF;
END;

/
