-- SANKHYA.TRG_FX_TGFGEM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFGEM
"SANKHYA".TRG_FX_TGFGEM
   BEFORE INSERT OR UPDATE
   ON TGFGEM
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
   
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;
  
  P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;
   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFGEM');

   IF (NOT P_VALIDAR)
   THEN
      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
