-- SANKHYA.TRG_DLT_TRIDRTF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIDRTF
"SANKHYA".TRG_DLT_TRIDRTF 
AFTER DELETE  ON TRIDRTF
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDBPF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE 
      AND :OLD.CODIMP = T.CODIMP
      AND :OLD.INDTPDEDUCAO = T.INDTPDEDUCAO;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDBPF
		WHERE :OLD.CODEMP = TRIDBPF.CODEMP 
		  AND :OLD.DTREF = TRIDBPF.DTREF 
		  AND :OLD.TPAMB = TRIDBPF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDBPF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDBPF.CHAVE
          AND :OLD.NRODOCUMENTO = TRIDBPF.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIDBPF.TIPODOCUMENTO
          AND :OLD.NATREND = TRIDBPF.NATREND
          AND :OLD.SEQITE = TRIDBPF.SEQITE 
          AND :OLD.CODIMP = TRIDBPF.CODIMP
          AND :OLD.INDTPDEDUCAO = TRIDBPF.INDTPDEDUCAO;
	END IF;
END;		

/
