-- SANKHYA.TRG_FX_TFXIVD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXIVD
"SANKHYA".TRG_FX_TFXIVD
   BEFORE INSERT OR UPDATE
   ON TFXIVD
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   IF (   (NVL (:NEW.CODEMP, 0) <> NVL (:OLD.CODEMP, 0))
       OR (NVL (:NEW.CODPROD, 0) <> NVL (:OLD.CODPROD, 0))
       OR (NVL (:NEW.CODLOCALORIG, 0) <> NVL (:OLD.CODLOCALORIG, 0))
       OR (:NEW.CONTROLE <> :OLD.CONTROLE)
       OR (:NEW.USOPROD <> :OLD.USOPROD)
       OR (:NEW.ALIQICMS <> :OLD.ALIQICMS)
       OR (:NEW.ALIQICMSRED <> :OLD.ALIQICMSRED)
       OR (:NEW.CODTRIB <> :OLD.CODTRIB)
       OR (:NEW.CSOSN <> :OLD.CSOSN)
       OR (:NEW.CODCFO <> :OLD.CODCFO)
       OR (:NEW.IDALIQICMS <> :OLD.IDALIQICMS))
   THEN
      SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

      :NEW.NUVERSAO := P_CONTADOR;
   END IF;
END;

/
