-- SANKHYA.TRG_INC_UPD_TCSCON
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSCON
"SANKHYA".TRG_INC_UPD_TCSCON 
BEFORE INSERT OR UPDATE ON TCSCON 
FOR EACH ROW

DECLARE 
    P_COUNT                INT:= 0; 
    ERRMSG                 VARCHAR2(255);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:NEW.CODPARC<>:OLD.CODPARC) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TGFPAR P 
    WHERE :NEW.CODPARC = P.CODPARC AND P.ATIVO = 'S'; 
     IF (P_COUNT = 0 ) THEN 
        ERRMSG := 'Parceiro '||:NEW.CODPARC||' n¿o esta ativo.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 
  IF (:NEW.CODCONTATO<>:OLD.CODCONTATO) OR (:NEW.CODPARC<>:OLD.CODPARC)  THEN 
     SELECT COUNT(1) INTO P_COUNT  FROM  TGFCTT C 
    WHERE :NEW.CODPARC = C.CODPARC 
      AND :NEW.CODCONTATO = C.CODCONTATO AND C.ATIVO = 'S'; 
     IF (P_COUNT = 0 ) THEN
        ERRMSG := 'Contato '||:NEW.CODCONTATO||' n¿o esta ativo.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 
  IF ((:NEW.CODIMPLANT<>:OLD.CODIMPLANT) OR (:NEW.CODPARC<>:OLD.CODPARC)) AND (:NEW.CODIMPLANT IS NOT NULL) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM  TGFCTT C 
      WHERE :NEW.CODPARC = C.CODPARC 
      AND :NEW.CODIMPLANT = C.CODCONTATO AND C.ATIVO = 'S'; 
     IF (P_COUNT = 0) THEN 
        ERRMSG := 'Implantador '||:NEW.CODIMPLANT||' n¿o esta ativo.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 
 
  IF (:NEW.CODNAT<>:OLD.CODNAT) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TGFNAT N 
      WHERE :NEW.CODNAT = N.CODNAT AND N.ATIVA = 'S' AND N.ANALITICA = 'S'; 
     IF (P_COUNT = 0 ) THEN
        ERRMSG := 'Natureza '||:NEW.CODNAT||' n¿o esta ativa, n¿o e anal¿tica ou n¿o existe'; 
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 
 
  IF (:NEW.CODEMP<>:OLD.CODEMP) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TGFEMP E 
      WHERE :NEW.CODEMP = E.CODEMP AND E.ATIVO = 'S'; 
     IF (P_COUNT = 0 ) THEN 
        ERRMSG := 'Empresa '||:NEW.CODEMP||' n¿o esta ativa.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 
 
  IF (:NEW.CODPROJ<>:OLD.CODPROJ) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TCSPRJ E 
      WHERE :NEW.CODPROJ = E.CODPROJ AND E.ATIVO = 'S' AND E.ANALITICO ='S'; 
     IF (P_COUNT = 0 ) THEN 
        ERRMSG := 'Projeto '||:NEW.CODPROJ||' n¿o esta ativo, n¿o e anal¿tico ou n¿o existe.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG); 
     END IF; 
  END IF; 

  IF (:NEW.CODPROJSINT<>:OLD.CODPROJSINT) AND (:NEW.CODPROJSINT<> 0) THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TCSPRJ E 
      WHERE :NEW.CODPROJSINT = E.CODPROJ AND E.ATIVO = 'S' AND E.ANALITICO ='N'; 
     IF (P_COUNT = 0 ) THEN 
        RAISE_APPLICATION_ERROR (-20101, 'Projeto '||:NEW.CODPROJSINT||' n¿o esta ativo, n¿o ¿ sint¿tico ou n¿o existe.'); 
     END IF; 
  END IF; 
  
  IF (:NEW.CODCENCUS<>:OLD.CODCENCUS)  THEN
     SELECT COUNT(1) INTO P_COUNT FROM  TSICUS C 
      WHERE :NEW.CODCENCUS = C.CODCENCUS AND C.ATIVO = 'S' AND C.ANALITICO = 'S';
     IF (P_COUNT = 0 ) THEN
        ERRMSG := 'Centro de resultado '||:NEW.CODCENCUS||' n¿o esta ativo, n¿o ¿ anal¿tico ou n¿o existe.';
        RAISE_APPLICATION_ERROR (-20101, ERRMSG);
     END IF;
  END IF;
 
END;

/
