-- SANKHYA.TRG_INC_UPD_TGWEAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGWEAS
"SANKHYA".TRG_INC_UPD_TGWEAS
BEFORE INSERT OR UPDATE ON TGWEAS
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT ENDERECO
  INTO :NEW.ENDERECOINI
  FROM TGWEND
  WHERE CODEND = :NEW.CODENDINI;

  SELECT ENDERECO
  INTO :NEW.ENDERECOFIM
  FROM TGWEND
  WHERE CODEND = :NEW.CODENDFIM;
  
  IF :NEW.ENDERECOFIM < :NEW.ENDERECOINI THEN

     RAISE_APPLICATION_ERROR(-20101, 'Endereço final deve ser maior que endereço inicial.');
  END IF;
END;

/
