-- SANKHYA.TRG_INC_UPD_TCBLAN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCBLAN
TRG_INC_UPD_TCBLAN
BEFORE INSERT OR UPDATE ON TCBLAN
FOR EACH ROW

BEGIN
    IF :NEW.CODCTACTB = 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'Não é permitido fazer lançamentos para a conta contábil ZERO.');
    END IF;
END;

/
