-- SANKHYA.TRG_INC_UPD_TGFCTS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCTS
"SANKHYA".TRG_INC_UPD_TGFCTS
BEFORE INSERT OR UPDATE ON TGFCTS  
FOR EACH ROW

DECLARE
  ERRMSG            VARCHAR2(255);
  ERROR             EXCEPTION;
  P_CODLOCAL          INT;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  P_CODLOCAL := 0;
  
  BEGIN
    SELECT CODLOCAL INTO P_CODLOCAL
    FROM TGFCTS
    WHERE DTCONTAGEM = :NEW.DTCONTAGEM 
      AND TIPCONTAGEM = :NEW.TIPCONTAGEM
      AND CODPROD = :NEW.CODPROD
      AND SERIE = :NEW.SERIE
      AND CODEMP = :NEW.CODEMP
      AND CODLOCAL <> :NEW.CODLOCAL
      AND :NEW.ESTOQUE <> 0;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_CODLOCAL := 0;
  END;

  IF P_CODLOCAL <> 0 THEN
      ERRMSG := 'Série '||:NEW.SERIE||' já contada no local '||P_CODLOCAL||'.';
      RAISE_APPLICATION_ERROR (-20101, ERRMSG);
  END IF;
  COMMIT;
  RETURN; 
EXCEPTION
  WHEN ERROR THEN
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
