-- SANKHYA.TRG_INC_TGFISS_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFISS_SEQ
"SANKHYA".TRG_INC_TGFISS_SEQ
BEFORE INSERT OR UPDATE
  ON TGFISS
  FOR EACH ROW

DECLARE
  ERROR         EXCEPTION;
  ERRMSG        VARCHAR2(255);
  P_COUNTROWS   INT;
BEGIN
  IF INSERTING THEN
    SELECT SEQ_TGFISS_IDALIQ.NEXTVAL
    INTO :NEW.IDALIQ
    FROM DUAL;
  END IF;
  IF NVL(:NEW.IDALIQ, 0) <> 0 AND NVL(:NEW.IDALIQ, 0) <> NVL(:OLD.IDALIQ, 0) AND SNK_EXISTE_IDALIQ_TGFISS(:NEW.IDALIQ) THEN
    ERRMSG := 'Aliquota de codigo ' || :NEW.IDALIQ || ' ja foi utilizada em outro cadastro.';
    RAISE ERROR;
  END IF;
  RETURN;
  EXCEPTION
    WHEN ERROR THEN
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
