-- SANKHYA.TRG_DLT_TRIIRPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIIRPJ
"SANKHYA".TRG_DLT_TRIIRPJ
AFTER DELETE  ON TRIIRPJ
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRPJ T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NATREND = T.NATREND;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRPJ
		WHERE :OLD.CODEMP = TRIDRPJ.CODEMP 
		  AND :OLD.DTREF = TRIDRPJ.DTREF 
		  AND :OLD.TPAMB = TRIDRPJ.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRPJ.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRPJ.CHAVE
          AND :OLD.NATREND = TRIDRPJ.NATREND;
	END IF;
END;		

/
