-- SANKHYA.TRG_INC_UPD_TCSITE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSITE
"SANKHYA".TRG_INC_UPD_TCSITE 
   BEFORE INSERT OR UPDATE
   ON TCSITE
   FOR EACH ROW

DECLARE
   P_COUNT   INT := 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF INSERTING OR (NVL(:NEW.CODPROD, 0) <> NVL(:OLD.CODPROD, 0)) THEN
     SELECT COUNT (1)
       INTO P_COUNT
       FROM TGFPRO P
      WHERE NVL(:NEW.CODPROD, 0) = P.CODPROD
        AND P.ATIVO = 'S';

     IF (P_COUNT = 0) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_PRODUTO_NAOATIVO);
     END IF;
  END IF;
   
  IF INSERTING OR  (NVL(:NEW.CODPROJ, 0) <> NVL(:OLD.CODPROJ, 0)) THEN
     SELECT COUNT (1)
       INTO P_COUNT
       FROM TCSPRJ P
      WHERE NVL(:NEW.CODPROJ, 0) = P.CODPROJ
        AND P.ATIVO = 'S' AND P.ANALITICO = 'S';
 
     IF (P_COUNT = 0) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_PROJ_ATIV_ANALI_EXIST);
     END IF;
  END IF;
   
  IF UPDATING('HRINICIAL') OR UPDATING('HRFINAL') OR UPDATING('CODSERV') 
     OR UPDATING('COBRAR') OR UPDATING('RETRABALHO') OR UPDATING('CODUSU') THEN
     SELECT COUNT (1)
       INTO P_COUNT
     FROM TGFCOM
    WHERE NUMOSORIG = :NEW.NUMOS
      AND NUMITEMORIG = :NEW.NUMITEM;
     IF (P_COUNT <> 0) THEN
        RAISE_APPLICATION_ERROR (-20101, 'Existe comissão para esse item. Alteração proibida');
     END IF;
  END IF;
END;

/
