-- SANKHYA.TRG_INC_AUDITTFPBAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_AUDITTFPBAS
"SANKHYA".TRG_INC_AUDITTFPBAS
BEFORE INSERT ON AUDITTFPBAS 
FOR EACH ROW


BEGIN
  SELECT AUDITTFPBAS_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
