-- SANKHYA.TRG_INC_UPD_TGFITE_TGFGXE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFITE_TGFGXE
"SANKHYA".TRG_INC_UPD_TGFITE_TGFGXE
   AFTER INSERT OR UPDATE
   ON TGFITE
   FOR EACH ROW


DECLARE
   P_VALIDAR   BOOLEAN;
BEGIN
   P_VALIDAR := FPODEVALIDAR ('TGFITE');

   IF NOT (P_VALIDAR)
   THEN
      RETURN;
   END IF;

   IF INSERTING OR UPDATING (:NEW.CODPROD)
   THEN
      SNK_VAL_UTIL_PRODUTO_GENERICO (:NEW.NUNOTA, :NEW.CODPROD);
   END IF;
END;

/
