-- SANKHYA.TRG_DLT_TGFTIT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTIT
"SANKHYA".TRG_DLT_TGFTIT BEFORE DELETE ON TGFTIT FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODTIPTIT = 0) THEN
     raise_application_error(-20101, 'Registro padr?o do sistema. N?o pode ser excluido.');
  END IF;
END;

/
