-- SANKHYA.TRG_INC_TGFCAI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFCAI
TRG_INC_TGFCAI
BEFORE INSERT ON TGFCAI
FOR EACH ROW

DECLARE
    v_count INT;
BEGIN

    SELECT COUNT(*)
    INTO v_count
    FROM TGFCAI
    WHERE SEQCAIXA = :NEW.SEQCAIXA
      AND ASSINATURA = :NEW.ASSINATURA
      AND DTABERTURA = :NEW.DTABERTURA
      AND CODCTABCOINT = :NEW.CODCTABCOINT
      AND CODUSU = :NEW.CODUSU;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'Não é permitido duplicar registros com os mesmos valores em SEQCAIXA, ASSINATURA, DTABERTURA, CODCTABCOINT e CODUSU.');
    END IF;
END;

/
