-- SANKHYA.TRG_INC_TGFTPV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFTPV
"SANKHYA".TRG_INC_TGFTPV BEFORE INSERT ON TGFTPV FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
    P_VALCTA				 CHAR(1);
BEGIN
  BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

    SELECT LOGICO INTO P_VALCTA
    FROM TSIPAR 
    WHERE CHAVE = 'VALCTA';
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_VALCTA := 'N';
  END;
  
  IF (P_VALCTA = 'S') THEN
	  IF (:NEW.CODCTACTB_1 IS NOT NULL) AND (:NEW.CODCTACTB_1 <> 0) THEN
	    SELECT COUNT(1) INTO P_COUNT
	    FROM  TCBPLA
	    WHERE CODCTACTB = :NEW.CODCTACTB_1
	    AND ATIVA = 'S'
	    AND ANALITICA = 'S';
	    IF (P_COUNT = 0 ) THEN
	      Stp_Popula_Msg('TCBPLA');
	    END IF;
	  END IF;
	
	  IF (:NEW.CODCTACTB_2 IS NOT NULL) AND (:NEW.CODCTACTB_2 <> 0) THEN
	    SELECT COUNT(1) INTO P_COUNT
	    FROM  TCBPLA
	    WHERE CODCTACTB = :NEW.CODCTACTB_2
	    AND ATIVA = 'S'
	    AND ANALITICA = 'S';
	    IF (P_COUNT = 0) THEN
	      Stp_Popula_Msg('TCBPLA');
		END IF;
	  END IF;
  END IF;

  IF (:NEW.NUNOTA IS NOT NULL) THEN
    SELECT NVL(COUNT(1),0) INTO P_COUNT
    FROM TGFCAB
    WHERE NUNOTA = :NEW.NUNOTA
      AND TIPMOV = 'Z';
    IF (P_COUNT = 0) THEN
	 RAISE_APPLICATION_ERROR(-20101, ' Não existe o número ínico da nota referenciado. Inclusão cancelada.');
	END IF;
  END IF;
END;

/
