-- SANKHYA.TRG_INC_UPD_DLT_TGMTME_AF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGMTME_AF
"SANKHYA".TRG_INC_UPD_DLT_TGMTME_AF 
AFTER INSERT OR UPDATE OR DELETE ON TGMTME

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	IF (Tgmtme_Pkg.V_FLAG = 0) THEN
		Tgmtme_Pkg.V_FLAG := 1;
		IF (INSERTING) THEN 
			INSERT INTO TGMTME
			(CODTIPOPER, CODMETA, RECDESP, CODUSU, DTALTER, COMPROMISSO)
			SELECT Tgmtme_Pkg.V_CODTIPOPER, CFG.CODMETA, Tgmtme_Pkg.V_RECDESP, Tgmtme_Pkg.V_CODUSU, Tgmtme_Pkg.V_DTALTER, Tgmtme_Pkg.V_COMPROMISSO 
			FROM TGMCFG CFG 
			WHERE CFG.SIMPLIFICADA IS NOT NULL
			AND CFG.CODMETA <> Tgmtme_Pkg.V_CODMETA
			AND NOT EXISTS (SELECT 1 FROM TGMTME MTE WHERE MTE.CODMETA = CFG.CODMETA AND MTE.CODTIPOPER = Tgmtme_Pkg.V_CODTIPOPER);
    ELSIF (UPDATING) THEN       
      UPDATE TGMTME SET 
        CODTIPOPER = Tgmtme_Pkg.V_CODTIPOPER, 
        RECDESP = Tgmtme_Pkg.V_RECDESP, 
        CODUSU = Tgmtme_Pkg.V_CODUSU, 
        DTALTER = Tgmtme_Pkg.V_DTALTER, 
        COMPROMISSO = Tgmtme_Pkg.V_COMPROMISSO
      WHERE CODTIPOPER = Tgmtme_Pkg.V_CODTIPOPER_D
      AND CODMETA IN (SELECT CFG.CODMETA FROM TGMCFG CFG WHERE CFG.SIMPLIFICADA IS NOT NULL AND CFG.CODMETA <> Tgmtme_Pkg.V_CODMETA);
    ELSE
      DELETE FROM TGMTME 
      WHERE CODTIPOPER = Tgmtme_Pkg.V_CODTIPOPER_D 
      AND CODMETA IN (SELECT CFG.CODMETA FROM TGMCFG CFG 
                 WHERE CFG.SIMPLIFICADA IS NOT NULL
                 AND CFG.CODMETA <> Tgmtme_Pkg.V_CODMETA_D);
    END IF;
  END IF;
  Tgmtme_Pkg.V_FLAG := 0;  
  RETURN;
END;

/
