-- SANKHYA.TRG_INC_UPD_TGFPLM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPLM
"SANKHYA".TRG_INC_UPD_TGFPLM
BEFORE UPDATE OR INSERT ON TGFPLM
FOR EACH ROW

DECLARE
    P_COUNT          NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  IF SNK_TGFTOKCFG AND SNK_TGFTOKCAM('TGFMVE') THEN
    INSERT INTO TGFATUTOK (CODPROD, DHALTER) VALUES(:NEW.CODPROD, SYSDATE);
  END IF;
END;

/
