-- SANKHYA.TRG_INC_TGFIFE_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFIFE_SEQ
"SANKHYA".TRG_INC_TGFIFE_SEQ
BEFORE INSERT OR UPDATE
  ON TGFIFE
  FOR EACH ROW

DECLARE
  ERROR         EXCEPTION;
  ERRMSG        VARCHAR2(255);
  P_COUNTROWS   INT;
BEGIN
  IF INSERTING THEN
    SELECT SEQ_TGFIFE_IDALIQ.NEXTVAL
    INTO :NEW.IDALIQ
    FROM DUAL;
  END IF;
  IF NVL(:NEW.IDALIQ, 0) <> 0 AND NVL(:NEW.IDALIQ, 0) <> NVL(:OLD.IDALIQ, 0) AND SNK_EXISTE_IDALIQ_TGFIFE(:NEW.IDALIQ) THEN
    ERRMSG := 'Alíquota de código ' || :NEW.IDALIQ || ' jÃ¿Â¡ foi utilizada em outro cadastro.';
    RAISE ERROR;
  END IF;
  RETURN;
  EXCEPTION
    WHEN ERROR THEN
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
