-- SANKHYA.TRG_DLT_TRITPCO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRITPCO
"SANKHYA".TRG_DLT_TRITPCO
BEFORE DELETE ON TRITPCO
FOR EACH ROW

BEGIN
    DELETE TRINFPR
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND INDCOM = :OLD.INDCOM;
        
    DELETE TRIIPFC
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND INDCOM = :OLD.INDCOM;
END;

/
