-- SANKHYA.TRG_DLT_TGFDRCSTR2130
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR2130
"SANKHYA".TRG_DLT_TGFDRCSTR2130
BEFORE DELETE ON TGFDRCSTR2130
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2131
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI4 = :OLD.REGPAI3
        AND REGPAI3 = :OLD.REGPAI2
        AND CODPROD = :OLD.CODPROD
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND NUNOTA = :OLD.NUNOTA
        AND SEQUENCIA = :OLD.SEQUENCIA
		AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2131
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI4 = :OLD.REGPAI3
            AND REGPAI3 = :OLD.REGPAI2
            AND CODPROD = :OLD.CODPROD
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND NUNOTA = :OLD.NUNOTA
            AND SEQUENCIA = :OLD.SEQUENCIA
			AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2132
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI4 = :OLD.REGPAI3
        AND REGPAI3 = :OLD.REGPAI2
        AND CODPROD = :OLD.CODPROD
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND NUNOTA = :OLD.NUNOTA
        AND SEQUENCIA = :OLD.SEQUENCIA
		AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2132
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI4 = :OLD.REGPAI3
            AND REGPAI3 = :OLD.REGPAI2
            AND CODPROD = :OLD.CODPROD
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND NUNOTA = :OLD.NUNOTA
            AND SEQUENCIA = :OLD.SEQUENCIA
			AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
