-- SANKHYA.TRG_FX_TSIKIT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TSIKIT
"SANKHYA".TRG_FX_TSIKIT
   BEFORE INSERT OR UPDATE OR DELETE
   ON TSIKIT
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TSIKIT');

   IF (NOT P_VALIDAR) THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;

   IF (DELETING) THEN
      INSERT INTO TFXADE (NOMETAB, STRPK)
          VALUES ('TKIT', 'CODCONFKIT = ' || TO_CHAR (:OLD.CODCONFKIT));

      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
