-- SANKHYA.TRG_DLT_TGCINF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGCINF
"SANKHYA".TRG_DLT_TGCINF 
BEFORE DELETE ON TGCINF FOR EACH ROW
  
DECLARE P_COUNT INT;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TGCCAL 
  WHERE CODCRED = :OLD.CODCRED
  AND CHAVE = :OLD.CHAVE; 
  IF (P_COUNT > 0) THEN
     raise_application_error(-20101, 'Não pode ser excluído, existem informações registradas na TGCCAL.');
  END IF;
END;

/
