-- SANKHYA.TRG_DLT_TFPSIT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPSIT
"SANKHYA".TRG_DLT_TFPSIT BEFORE DELETE ON TFPSIT FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODSITESTAT = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
