-- SANKHYA.BI_TBDATABASEINTEGRATIONENTRY
CREATE OR REPLACE TRIGGER SANKHYA.BI_TBDATABASEINTEGRATIONENTRY
"SANKHYA".BI_TBDATABASEINTEGRATIONENTRY
   BEFORE INSERT
   ON TBDATABASEINTEGRATIONENTRY
   FOR EACH ROW
   
BEGIN
   SELECT TBDATABASEINTEGRATIONENTRY_SEQ.NEXTVAL
     INTO :NEW.CONNECTORINTEGRATIONID
     FROM DUAL;
END;

/
