-- SANKHYA.TRG_INC_UPD_TGFNAT_DATA_LAKE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFNAT_DATA_LAKE
TRG_INC_UPD_TGFNAT_DATA_LAKE
BEFORE INSERT OR UPDATE ON TGFNAT
FOR EACH ROW

BEGIN
	:NEW.DHALTER := SYSTIMESTAMP;
END;

/
