-- SANKHYA.TRG_DLT_TCBLAN_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCBLAN_AFTER
TRG_DLT_TCBLAN_AFTER
AFTER DELETE ON TCBLAN
FOR EACH ROW

BEGIN
  STP_EXCLUI_ESTORNO_CONTABIL(
      :OLD.CODEMP,
      :OLD.REFERENCIA,
      :OLD.NUMLOTE,
      :OLD.NUMLANC,
      :OLD.SEQUENCIA,
      :OLD.TIPLANC
  );
END;

/
