-- SANKHYA.TRG_INC_TGFVOL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFVOL
"SANKHYA".TRG_INC_TGFVOL 
BEFORE INSERT ON TGFVOL FOR EACH ROW

DECLARE
     P_COUNT    NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
  INTO P_COUNT
  FROM TGFVOL
  WHERE UPPER(CODVOL) = UPPER(:NEW.CODVOL);
   
  IF (P_COUNT > 0) THEN
     RAISE_APPLICATION_ERROR(-20101, 'Já existe um volume cadastrado com o código '|| UPPER(:NEW.CODVOL) ||'.');
  END IF;
END;

/
