-- SANKHYA.TRG_INC_UPD_TFPHOR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPHOR
"SANKHYA".TRG_INC_UPD_TFPHOR 
BEFORE INSERT OR UPDATE ON TFPHOR 
FOR EACH ROW

BEGIN
    IF STP_GET_ATUALIZANDO THEN
        RETURN;
    END IF;

     :NEW.CODCARGAHORESOCIAL := TRIM(TO_CHAR(:NEW.CODCARGAHOR,'000009')) ||TRIM(TO_CHAR(:NEW.DIASEM,'09'));

END;

/
