-- SANKHYA.TRG_INC_UPD_DLT_DHPARAMETROS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_DHPARAMETROS
"SANKHYA".TRG_INC_UPD_DLT_DHPARAMETROS
   AFTER UPDATE
   ON TSIPAR
   FOR EACH ROW


DECLARE 
   P_COUNT   NUMBER(10);
   
BEGIN
   IF    :NEW.CHAVE = 'CUSMEDSOMA'
      OR :NEW.CHAVE = 'EMPPDESMCUS'
      OR :NEW.CHAVE = 'CONSIMPRETNOTA'
      OR :NEW.CHAVE = 'CUSTOPOREMP'
      OR :NEW.CHAVE = 'CUSTOPORLOC'
      OR :NEW.CHAVE = 'CUSTOPORCONT'
      OR :NEW.CHAVE = 'CUSTODEC'
      OR :NEW.CHAVE = 'INICIOCONTEST'
      OR :NEW.CHAVE = 'DIASLIMALTCUSTO' 
      -- INICIO NOVOS PARAMETROS 
      OR :NEW.CHAVE = 'TIPTITCREDCLI' 
      OR :NEW.CHAVE = 'USACODVOLPARC'  
      OR :NEW.CHAVE = 'CODOBSGARANTIDO'  
      OR :NEW.CHAVE = 'CODIMPGARANTIDO'  
      OR :NEW.CHAVE = 'ENTIPISEMDESC'  
      OR :NEW.CHAVE = 'SAIIPISEMDESC'  
      OR :NEW.CHAVE = 'SOMASERVNOTA'  
      OR :NEW.CHAVE = 'TEMFUNRURAL'  
      OR :NEW.CHAVE = 'TOPSREQCON'  
      OR :NEW.CHAVE = 'NATVA'  
      OR :NEW.CHAVE = 'NATVT'  
      OR :NEW.CHAVE = 'FORMIRFFRETE' 
      OR :NEW.CHAVE = 'VLRCALIRRF'  
      OR :NEW.CHAVE = 'TOPPISREDAQUIS'  
      OR :NEW.CHAVE = 'DISTJDCONF'
      OR :NEW.CHAVE = 'DISDESAUTANTIMP'  
      OR :NEW.CHAVE = 'EDITMPSOMAEXT'  
      OR :NEW.CHAVE = 'HABALIQESPICMS' 
      OR :NEW.CHAVE = 'UTILZFECHACTB'
      OR :NEW.CHAVE = 'ESTOQUEGRPPROD'
      OR :NEW.CHAVE = 'WMSDESCONESTBLQ'
      OR :NEW.CHAVE = 'SUBESTDOCAWMS'
	  
      --FIM NOVOS PARAMETROS
      
      THEN
          SELECT COUNT(1) INTO P_COUNT
          FROM TSIALTPARAM
          WHERE CHAVE = :NEW.CHAVE;
         
        IF P_COUNT = 0 THEN
              INSERT INTO TSIALTPARAM VALUES (:NEW.CHAVE,SYSDATE);
              
        ELSE IF P_COUNT > 0 THEN
              
              UPDATE TSIALTPARAM
              SET DTALTER = SYSDATE
              WHERE CHAVE = :NEW.CHAVE;
        END IF;      
      END IF;
   END IF;
END;

/
