-- SANKHYA.TRG_DLT_TRINRN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRINRN
"SANKHYA".TRG_DLT_TRINRN 
AFTER DELETE  ON TRINRN
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPBN T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NATREND = T.NATREND;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPBN
		WHERE :OLD.CODEMP = TRIPBN.CODEMP 
		  AND :OLD.DTREF = TRIPBN.DTREF 
		  AND :OLD.TPAMB = TRIPBN.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPBN.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPBN.CHAVE
          AND :OLD.NATREND = TRIPBN.NATREND;
	END IF;
END;		

/
