-- SANKHYA.TRG_DLT_TGWSEP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWSEP
"SANKHYA".TRG_DLT_TGWSEP AFTER DELETE ON TGWSEP
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGWSEPA
  WHERE NUSEPARACAO = :OLD.NUSEPARACAO
    AND NUTAREFA    = :OLD.NUTAREFA;
    
  IF P_COUNT > 0 THEN
    DELETE FROM TGWSEPA
    WHERE NUSEPARACAO = :OLD.NUSEPARACAO
      AND NUTAREFA    = :OLD.NUTAREFA;
  END IF;  
END;

/
