-- SANKHYA.TRG_INC_UPD_DLT_TGFRAV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFRAV
"SANKHYA".TRG_INC_UPD_DLT_TGFRAV 
BEFORE INSERT OR UPDATE OR DELETE ON TGFRAV
FOR EACH ROW
  
DECLARE P_COUNT           NUMBER(10);
          P_PERCRATEIO      FLOAT;  
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF UPDATING OR DELETING THEN
    SELECT COUNT(1), MAX(PERCRATEIO) 
      INTO P_COUNT, P_PERCRATEIO
    FROM TGFRAT
    WHERE ORIGEM    = :OLD.ORIGEM
      AND NUFIN     = :OLD.NUFIN
      AND CODNAT    = :OLD.CODNAT
      AND CODCENCUS = :OLD.CODCENCUS
      AND CODPROJ   = :OLD.CODPROJ
      AND CODSITE   = :OLD.CODSITE
      AND CODPARC   = :OLD.CODPARC;
      
    IF P_COUNT > 0 THEN
      IF P_PERCRATEIO > NVL(:OLD.PERCRATEIO, 0) THEN
        UPDATE TGFRAT SET PERCRATEIO = PERCRATEIO - NVL(:OLD.PERCRATEIO, 0)
        WHERE ORIGEM    = :OLD.ORIGEM
          AND NUFIN     = :OLD.NUFIN
          AND CODNAT    = :OLD.CODNAT
          AND CODCENCUS = :OLD.CODCENCUS
          AND CODPROJ   = :OLD.CODPROJ
          AND CODSITE   = :OLD.CODSITE
          AND CODPARC   = :OLD.CODPARC;      
      ELSE
        DELETE FROM TGFRAT
        WHERE ORIGEM    = :OLD.ORIGEM
          AND NUFIN     = :OLD.NUFIN
          AND CODNAT    = :OLD.CODNAT
          AND CODCENCUS = :OLD.CODCENCUS
          AND CODPROJ   = :OLD.CODPROJ
          AND CODSITE   = :OLD.CODSITE
          AND CODPARC   = :OLD.CODPARC;        
      END IF;
    END IF;
  END IF;
  
  IF INSERTING OR UPDATING THEN  
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFRAT
    WHERE ORIGEM    = :NEW.ORIGEM
      AND NUFIN     = :NEW.NUFIN
      AND CODNAT    = :NEW.CODNAT
      AND CODCENCUS = :NEW.CODCENCUS
      AND CODPROJ   = :NEW.CODPROJ
      AND CODSITE   = :NEW.CODSITE
      AND CODPARC   = :NEW.CODPARC;
    IF P_COUNT > 0 THEN
      UPDATE TGFRAT SET PERCRATEIO = PERCRATEIO + NVL(:NEW.PERCRATEIO, 0)
                      , CODCTACTB = :NEW.CODCTACTB
                      , NUMCONTRATO = :NEW.NUMCONTRATO
                      , DIGITADO = :NEW.DIGITADO
                      , CODUSU = :NEW.CODUSU
                      , DTALTER = :NEW.DTALTER
      WHERE ORIGEM    = :NEW.ORIGEM
        AND NUFIN     = :NEW.NUFIN
        AND CODNAT    = :NEW.CODNAT
        AND CODCENCUS = :NEW.CODCENCUS
        AND CODPROJ   = :NEW.CODPROJ
        AND CODSITE   = :NEW.CODSITE
        AND CODPARC   = :NEW.CODPARC;
    ELSE
      INSERT INTO TGFRAT (ORIGEM, NUFIN, CODNAT, CODCENCUS, CODPROJ, CODSITE, CODPARC, CODCTACTB, 
                          NUMCONTRATO, DIGITADO, CODUSU, DTALTER, PERCRATEIO)
                   VALUES(:NEW.ORIGEM, :NEW.NUFIN, :NEW.CODNAT, :NEW.CODCENCUS, :NEW.CODPROJ, :NEW.CODSITE, :NEW.CODPARC, :NEW.CODCTACTB,
                          :NEW.NUMCONTRATO, :NEW.DIGITADO, :NEW.CODUSU, :NEW.DTALTER, :NEW.PERCRATEIO);
    END IF;
  END IF;
END;

/
