-- SANKHYA.TRG_INC_UPD_TGFFAD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFAD
"SANKHYA".TRG_INC_UPD_TGFFAD 
BEFORE INSERT OR UPDATE ON TGFFAD 
FOR EACH ROW

DECLARE
   P_COUNT          INT:= 0;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  IF (:NEW.CODSERV <> 0) AND (:NEW.CODSERV <> :OLD.CODSERV) THEN
     SELECT COUNT(1) INTO P_COUNT 
	   FROM TGFPRO 
	  WHERE CODPROD = :NEW.CODSERV 
	    AND USOPROD = 'S';    
	 IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR (-20101, 'Código informado no Serviço não existe ou não é um Serviço!');
     END IF;		 
  END IF;
  IF (:NEW.CODGRUPOPROD <> 0) AND (:NEW.CODGRUPOPROD <> :OLD.CODGRUPOPROD) THEN
     SELECT COUNT(1) INTO P_COUNT 
	   FROM TGFGRU 
	  WHERE CODGRUPOPROD = :NEW.CODGRUPOPROD 
	    AND ANALITICO = 'S';    
	 IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_GRU_ANALI_NAOEXISTE);
     END IF;		 
  END IF;
END;

/
