-- SANKHYA.TRG_INC_UPD_TGFVEI_PROD_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFVEI_PROD_AFTER
"SANKHYA".TRG_INC_UPD_TGFVEI_PROD_AFTER 
AFTER INSERT OR UPDATE 
ON TGFVEI 


DECLARE
    P_CODPROD  TGFVEI.CODPROD%TYPE;
    P_CODBEM   TGFVEI.CODBEM%TYPE;
    P_COUNT       INT;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
     
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFVEI 
    WHERE CODPROD = TGFVEI_PKG.V_CODPROD
    AND CODBEM = TGFVEI_PKG.V_CODBEM;
    
    IF (P_COUNT > 1) THEN
        RAISE_APPLICATION_ERROR(-20101,'Já existe um veículo cadastrado com o código de Bem: ' || TGFVEI_PKG.V_CODBEM);
    END IF;
END;

/
