-- SANKHYA.TRG_DLT_TFPATR_MOV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPATR_MOV
"SANKHYA".TRG_DLT_TFPATR_MOV
  BEFORE DELETE ON TFPATR
  FOR EACH ROW

DECLARE
    P_CODEVENTO  TFPPRE.CODEVENATRASO%TYPE;
    P_DIAAPURA   TFPFUN.DIAAPURAPONTO%TYPE;
    P_UNIDADE    TFPEVE.UNIDADE%TYPE;
    P_REFERENCIA TFPMOV.REFERENCIA%TYPE;
    P_INDICE     TFPMOV.INDICE%TYPE;
    P_MOVINDICE  TFPMOV.INDICE%TYPE;
    P_COUNT      INT;
    P_DATAINI    DATE;
    P_DATAFIM    DATE;
    P_REFPONTO   DATE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :OLD.ORIGEM = 'M' THEN
    SELECT PRE.CODEVENATRASO,
           NVL(FUN.DIAAPURAPONTO, 1)
    INTO   P_CODEVENTO, P_DIAAPURA
    FROM   TFPFUN FUN,
           TFPSIN SIN,
           TFPPRE PRE
    WHERE  FUN.CODEMP = :OLD.CODEMP
           AND FUN.CODFUNC = :OLD.CODFUNC
           AND FUN.CODSIND = SIN.CODSIND
           AND SIN.CODPREF = PRE.CODPREF;

    BEGIN
      SELECT UNIDADE
      INTO   P_UNIDADE
      FROM   TFPEVE
      WHERE  CODEVENTO = P_CODEVENTO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20101, 'CODEVENTO = '|| P_CODEVENTO ||' nÃ£o existe na tabela TFPEVE.');
    END;

    P_REFERENCIA := TRUNC(:OLD.DTATRASO, 'MONTH');
    P_REFPONTO := P_REFERENCIA;
    IF P_DIAAPURA > 1 THEN
      P_REFPONTO := SNK_DATE_ADD(P_REFPONTO, 'MM', -1);
    END IF;

    P_DATAINI := SNK_DATE_ADD(P_REFPONTO,'DD', P_DIAAPURA - 1);
    P_DATAFIM := SNK_DATE_ADD(SNK_DATE_ADD(P_DATAINI, 'MM', 1), 'DD', -1);

    IF :OLD.DTATRASO > P_DATAFIM THEN
      P_REFERENCIA := SNK_DATE_ADD(P_REFERENCIA, 'MM', 1);
    END IF;

    SELECT COUNT(*), MIN(NVL(INDICE, 0))
    INTO   P_COUNT, P_MOVINDICE
    FROM   TFPMOV
    WHERE  CODEMP = :OLD.CODEMP
           AND CODFUNC = :OLD.CODFUNC
           AND REFERENCIA = P_REFERENCIA
           AND CODEVENTO = P_CODEVENTO
           AND TIPMOV = 'M'
           AND SEQUENCIA = 1;
    
    IF P_COUNT > 0 THEN 
      IF P_UNIDADE = 'H' THEN
        P_INDICE := ( TRUNC(NVL(P_MOVINDICE, 0)) * 60 ) + ( ( NVL(P_MOVINDICE, 0) - TRUNC(NVL(P_MOVINDICE, 0)) ) * 100 ) - :OLD.MINUTOS;

        P_INDICE := TRUNC(P_INDICE / 60) + ( MOD(P_INDICE, 60) / 100 );
      ELSE
        P_INDICE := NVL(P_MOVINDICE, 0) - :OLD.MINUTOS;
      END IF;

      IF P_INDICE > 0 THEN
        UPDATE TFPMOV
        SET    INDICE = P_INDICE,
               CODUSU = :OLD.CODUSU,
               DTALTER = :OLD.DTALTER
        WHERE  CODEMP = :OLD.CODEMP
               AND CODFUNC = :OLD.CODFUNC
               AND REFERENCIA = P_REFERENCIA
               AND CODEVENTO = P_CODEVENTO
               AND TIPMOV = 'M'
               AND SEQUENCIA = 1;
      ELSE
        DELETE FROM TFPMOV
        WHERE  CODEMP = :OLD.CODEMP
               AND CODFUNC = :OLD.CODFUNC
               AND REFERENCIA = P_REFERENCIA
               AND CODEVENTO = P_CODEVENTO
               AND TIPMOV = 'M'
               AND SEQUENCIA = 1;
      END IF;
    END IF;
  END IF;

END;

/
