-- SANKHYA.TRG_FX_TGFICP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFICP
"SANKHYA".TRG_FX_TGFICP
   BEFORE INSERT OR UPDATE OR DELETE
   ON TGFICP
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
   P_CONFIGKIT   BOOLEAN;
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFICP');

   IF (NOT P_VALIDAR) THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;

   P_CONFIGKIT := FTEM_KIT_INDEPENDENTE;
   
   IF (NOT P_CONFIGKIT) THEN
	  RETURN;
   END IF;
   
   /* SE ESTOU DELETANDO OU ALTERANDO A VARIACAO, APENAS DELETO NA TFXPKI */
   IF ( (DELETING) OR ( (NVL(:OLD.VARIACAO, 0) = 30000) AND (NVL(:NEW.VARIACAO, 0) <> 30000) ) ) THEN
	  DELETE FROM TFXPKI WHERE CODPRODUTO = :OLD.CODPROD AND MATERIAPRIMA = :OLD.CODMATPRIMA;
      RETURN;
   END IF;
   
   /* SE ESTOU EDITANDO A MATERIA PRIMA OU O PRODUTO, PRECISO DELETAR NA TFXPKI PARA DEPOIS INSERIR O NOVO */
   IF ( (NVL(:NEW.CODPROD,0) <> NVL(:OLD.CODPROD,0)) OR (NVL(:NEW.CODMATPRIMA,0) <> NVL(:OLD.CODMATPRIMA,0)) ) THEN
      DELETE FROM TFXPKI WHERE CODPRODUTO = :OLD.CODPROD AND MATERIAPRIMA = :OLD.CODMATPRIMA; 
   END IF;
   
   IF ( (NVL(:NEW.CODPROD,0) <> NVL(:OLD.CODPROD,0))
		OR (NVL(:NEW.CODMATPRIMA, 0) <> NVL(:OLD.CODMATPRIMA, 0))
		OR (NVL(:NEW.QTDMISTURA, 0) <> NVL(:OLD.QTDMISTURA, 0))
		OR (NVL(:NEW.CODVOL, ' ') <> NVL(:OLD.CODVOL, ' '))
		OR (NVL(:NEW.PRECO, 0) <> NVL(:OLD.PRECO, 0)) ) THEN
      SELECT COUNT (1)
        INTO P_CONTADOR
        FROM TFXPKI TFX
       WHERE TFX.CODPRODUTO = :NEW.CODPROD AND TFX.MATERIAPRIMA = :NEW.CODMATPRIMA;
      IF (NVL (:NEW.VARIACAO, 0) = 30000) THEN
          IF (NVL (P_CONTADOR, 0) = 0)
          THEN
             INSERT INTO TFXPKI (CODPRODUTO, MATERIAPRIMA, QTDMISTURA, CODVOLUME, PRECO)
                 VALUES (:NEW.CODPROD, :NEW.CODMATPRIMA, :NEW.QTDMISTURA, :NEW.CODVOL, :NEW.PRECO);
          ELSE
             UPDATE TFXPKI
                SET MATERIAPRIMA = :NEW.CODMATPRIMA,
                    QTDMISTURA = :NEW.QTDMISTURA,
                    CODVOLUME = :NEW.CODVOL,
                    PRECO = :NEW.PRECO
              WHERE CODPRODUTO = :NEW.CODPROD AND MATERIAPRIMA = :NEW.CODMATPRIMA;
          END IF;
      END IF;
   END IF;
END;

/
