-- SANKHYA.TRG_DLT_EVTLOTE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_EVTLOTE
"SANKHYA".TRG_DLT_EVTLOTE
BEFORE DELETE ON EVTLOTE

BEGIN
  RAISE_APPLICATION_ERROR(-20101, 'NÃO É PERMITIDO DELETAR AS INFORMAÇÕES DE ENVIO PARA O ESOCIAL. ESTAS TAMBÉM SÃO UTILIZADAS COMO LOG.');  
END;

/
