-- SANKHYA.TRG_INC_TGFVAR_BLOQ_SAFRA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFVAR_BLOQ_SAFRA
"SANKHYA".TRG_INC_TGFVAR_BLOQ_SAFRA 
BEFORE INSERT ON TGFVAR
FOR EACH ROW

DECLARE
   P_CODPROJ     TGFCAB.CODPROJ%TYPE;
   P_TIPMOV      TGFCAB.TIPMOV%TYPE;
   P_BLOQUEAR    TGABDLC.BLOQUEAR%TYPE;
   P_OBS         TGABDLC.OBS%TYPE;
   P_DESCRDIG    TGADIG.DESCRDIG%TYPE;
   ERRMSG            VARCHAR2(255);
 ERROR             EXCEPTION;
 P_VALIDAR BOOLEAN;    
BEGIN

 IF STP_GET_ATUALIZANDO THEN
   RETURN;
 END IF;
 
 /* 
 Sincronização de dados
 */
   P_VALIDAR := Fpodevalidar('TGFVAR'); 

 IF ((:NEW.SEQUENCIA = 0) AND (:NEW.SEQUENCIAORIG = 0) AND (:NEW.QTDATENDIDA = 0)) THEN
   RETURN;
 END IF;

 BEGIN
     SELECT TIPMOV, CODPROJ 
     INTO P_TIPMOV, P_CODPROJ
     FROM TGFCAB
     WHERE NUNOTA = :NEW.NUNOTAORIG;
 EXCEPTION
   WHEN NO_DATA_FOUND THEN
       RETURN;
 END;

 IF (P_TIPMOV = 'P' AND P_CODPROJ <> 0)  THEN
   BEGIN
     SELECT BLC.BLOQUEAR, MOT.DESCRDIG, BLC.OBS 
     INTO P_BLOQUEAR, P_DESCRDIG, P_OBS 
     FROM TGABDLC BLC
     , TGADIG MOT
     WHERE BLC.CODPROJ = P_CODPROJ
     AND BLC.SEQUENCIA = (SELECT MAX(SEQUENCIA) FROM TGABDLC LM WHERE CODPROJ = P_CODPROJ)
     AND BLC.TIPO = MOT.TIPO
     AND BLC.NUDIG = MOT.NUDIG;
   EXCEPTION WHEN NO_DATA_FOUND THEN
     RETURN;
   END;
   
   IF P_BLOQUEAR = 'S' THEN
     ERRMSG := 'Pedido bloqueado. Motivo:'|| P_DESCRDIG || '. Obs.:'|| P_OBS || '.';
     RAISE ERROR;
   END IF;
 END IF;
 RETURN;
EXCEPTION
 WHEN ERROR THEN
   /* 
   Sincronização de dados não faz validações
   */
   IF (P_VALIDAR) THEN 
     RAISE_APPLICATION_ERROR(-20101, ERRMSG);
   END IF; 
END;

/
