-- SANKHYA.TRG_DLT_TGFDIRFIDREC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDIRFIDREC
"SANKHYA".TRG_DLT_TGFDIRFIDREC
BEFORE DELETE ON TGFDIRFIDREC
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFBPJDEC
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPJRTRT
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC;
    END IF;
END;

/
