-- SANKHYA.TRG_DLT_TGFDRCSTR2113
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR2113
"SANKHYA".TRG_DLT_TGFDRCSTR2113
BEFORE DELETE ON TGFDRCSTR2113
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2114
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI3 = :OLD.REGPAI2
        AND REGPAI2 = :OLD.REGPAI
        AND CODPROD = :OLD.CODPROD
        AND REGPAI = :OLD.REG
        AND NUNOTA = :OLD.NUNOTA
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2114
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI3 = :OLD.REGPAI2
            AND REGPAI2 = :OLD.REGPAI
            AND CODPROD = :OLD.CODPROD
            AND REGPAI = :OLD.REG
            AND NUNOTA = :OLD.NUNOTA
            AND SEQUENCIA = :OLD.SEQUENCIA
            AND CNPJDECLPAR = :OLD.CNPJDECLPAR
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
