-- SANKHYA.TRG_INC_UPD_TGFFIN_DTVENC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFIN_DTVENC
"SANKHYA".TRG_INC_UPD_TGFFIN_DTVENC
BEFORE INSERT OR UPDATE ON TGFFIN
FOR EACH ROW

DECLARE
  P_VALIDAR                 BOOLEAN;
  ERRMSG                    VARCHAR2(255);
  ERROR                      EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO() THEN
    RETURN;
  END IF;
  
  P_VALIDAR := Fpodevalidar('TGFFIN');
  
  IF :NEW.DTVENC <> TRUNC(:NEW.DTVENC) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Data de vencimento com Hora');
  END IF;

  RETURN;
END;

/
