-- SANKHYA.TRG_DLT_TFPHIS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPHIS
"SANKHYA".TRG_DLT_TFPHIS BEFORE DELETE ON TFPHIS FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODHISTOCOR = 0) THEN
     raise_application_error(-20101, 'Registro padr?o do sistema. N?o pode ser excluido.');
  END IF;
END;

/
