-- SANKHYA.TRG_INC_DEL_UPD_TGFEMB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_DEL_UPD_TGFEMB
"SANKHYA".TRG_INC_DEL_UPD_TGFEMB
AFTER DELETE OR INSERT OR UPDATE
ON TGFEMB
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING AND UPDATING('PESOLIQUIDO') THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFCTF
    WHERE NUCTF = :NEW.NUCTF;
    
    IF P_COUNT > 0 THEN 
      UPDATE TGFCTF SET PESOEMBALADO = PESOEMBALADO + :NEW.PESOLIQUIDO - :OLD.PESOLIQUIDO
      WHERE NUCTF = :NEW.NUCTF;
    END IF;
  END IF;
  
  IF INSERTING THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFCTF
    WHERE NUCTF = :NEW.NUCTF;
    
    IF P_COUNT > 0 THEN
      UPDATE TGFCTF SET PESOEMBALADO = PESOEMBALADO + :NEW.PESOLIQUIDO
      WHERE NUCTF = :NEW.NUCTF;
    END IF;
  END IF;
  
  IF DELETING THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFCTF
    WHERE NUCTF = :OLD.NUCTF;
    
    IF P_COUNT > 0 THEN
      UPDATE TGFCTF SET PESOEMBALADO = PESOEMBALADO - :OLD.PESOLIQUIDO
      WHERE NUCTF = :OLD.NUCTF;
    END IF;
  END IF;
END;

/
