-- SANKHYA.TRG_BEFORE_DELETE_TCBLOT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_BEFORE_DELETE_TCBLOT
TRG_BEFORE_DELETE_TCBLOT
  BEFORE DELETE ON TCBLOT
  FOR EACH ROW
  
DECLARE
      v_logico CHAR(1);
  BEGIN
      BEGIN
      SELECT LOGICO INTO v_logico
      FROM TSIPAR
      WHERE TSIPAR.CHAVE = 'CTBPERMEXCLT';
	  EXCEPTION
          WHEN NO_DATA_FOUND THEN
              v_logico := 'S';
	END;

      IF v_logico = 'S' THEN
          INSERT INTO TCBLOT_EXC (
              CODEMP, REFERENCIA, NUMLOTE, DTMOV, TOTLOTE,
              COMENTARIOS, SITUACAO, ULTLANC, CODUSU,CODEMPCONSOLID,
              CODUSUEXC, DHEXC, SEQUENCIA
          )
          VALUES (
              :OLD.CODEMP, :OLD.REFERENCIA, :OLD.NUMLOTE, :OLD.DTMOV, :OLD.TOTLOTE,
              :OLD.COMENTARIOS, :OLD.SITUACAO, :OLD.ULTLANC, :OLD.CODUSU, :OLD.CODEMPCONSOLID,
              Tsiusu_Log_Pkg.V_CODUSULOG, SYSDATE, SEQ_TCBLOT_EXC_SEQUENCIA.NEXTVAL
          );
      ELSE
          RAISE_APPLICATION_ERROR(-20001, 'Exclusão não permitida.');
      END IF;
  END;

/
