-- SANKHYA.TRG_DLT_TGFDIRF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDIRF
"SANKHYA".TRG_DLT_TGFDIRF
BEFORE DELETE ON TGFDIRF
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFRESPO
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFRESPO
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFDECPJ
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFDECPJ
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL;
    END IF;        
END;

/
