-- SANKHYA.TRG_INC_UPD_TCSPRE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSPRE
"SANKHYA".TRG_INC_UPD_TCSPRE 
BEFORE INSERT OR UPDATE ON TCSPRE 
FOR EACH ROW

DECLARE
  P_COUNT                INT:= 0;
  ERROR                  EXCEPTION;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODPROD') THEN
    SELECT COUNT(1)
      INTO P_COUNT
    FROM TGFPRO P
    WHERE :NEW.CODPROD = P.CODPROD 
      AND P.ATIVO = 'S';
      
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101,  'Produto nao esta ativo ou nao esta cadastrado.');
    END IF;
  END IF;
END;

/
