-- SANKHYA.TRG_DLT_TSITAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSITAR
"SANKHYA".TRG_DLT_TSITAR
BEFORE DELETE ON TSITAR
FOR EACH ROW

DECLARE P_COUNT       INTEGER;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 
  SELECT COUNT(1) 
  INTO P_COUNT 
  FROM TSIATA
  WHERE CODATA = :OLD.CODTAR 
  AND TIPO = 'F'; 
     
  IF P_COUNT > 0 THEN
    DELETE FROM TSIATA 
    WHERE CODATA = :OLD.CODTAR 
      AND TIPO = 'F';
  END IF;       
END;

/
