-- SANKHYA.TRG_INC_TFPFUN_REC_SELECAO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPFUN_REC_SELECAO
"SANKHYA".TRG_INC_TFPFUN_REC_SELECAO BEFORE INSERT ON TFPFUN FOR EACH ROW

DECLARE
    P_QTDFUNCCONTRADOS       INT;
	P_QTDVAGAS				 INT;
	P_QTDVAGASSELECAO		 INT;
	P_NUSELECAO				 INT;
BEGIN
  SELECT COUNT(1) INTO P_QTDFUNCCONTRADOS
  FROM TFPFUN
  WHERE NUREQUISICAO = :NEW.NUREQUISICAO;
  
  SELECT QTDVAGAS INTO P_QTDVAGAS
  FROM TRSREQ
  WHERE NUREQUISICAO = :NEW.NUREQUISICAO;
  
  IF P_QTDVAGAS = (P_QTDFUNCCONTRADOS + 1) THEN
    --Fecha Requisição
    UPDATE TRSREQ SET STATUS = 'F' WHERE NUREQUISICAO = :NEW.NUREQUISICAO;
	--Fecha Anuncio
	UPDATE TRSANU SET STATUS = 'F' WHERE NUREQUISICAO = :NEW.NUREQUISICAO;
	--Fecha Seleção
	UPDATE TRSSEL SET SITSELECAO = 1
	WHERE EXISTS (SELECT 1 FROM TRSRQS WHERE NUSELECAO = TRSSEL.NUSELECAO AND NUREQUISICAO = :NEW.NUREQUISICAO)
	  AND NOT EXISTS (SELECT 1 
	                  FROM TRSREQ REQ
					     , TRSRQS RQS
	                  WHERE REQ.STATUS <> 'F' 
					    AND RQS.NUREQUISICAO = REQ.NUREQUISICAO
						AND RQS.NUSELECAO = TRSSEL.NUSELECAO
						AND RQS.NUREQUISICAO <> :NEW.NUREQUISICAO);	
  END IF;  
END;

/
