-- SANKHYA.TRG_INC_UPD_TCISAL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCISAL
"SANKHYA".TRG_INC_UPD_TCISAL
BEFORE INSERT OR UPDATE ON TCISAL
FOR EACH ROW

DECLARE 
	P_COUNT			NUMBER(5);
	P_ALTEROU		CHAR(1);
BEGIN

	IF UPDATING  AND :NEW.CODBEM <> :OLD.CODBEM THEN 
		UPDATE TCISAL_ATUAL SET CODBEM = :NEW.CODBEM WHERE CODPROD = :NEW.CODPROD AND CODBEM = :OLD.CODBEM;
	ELSE 
		BEGIN
        SELECT 1, CASE WHEN (REFERENCIA < :NEW.REFERENCIA OR 
                                        (REFERENCIA = :NEW.REFERENCIA AND 
                                          (NVL(SALDO, 0.0) <> NVL(:NEW.SALDO, 0.0) OR NVL(TOTALDEP, 0.0) <> NVL(:NEW.TOTALDEP, 0.0)))
                                   ) THEN 'S' ELSE 'N' END  
        INTO P_COUNT, P_ALTEROU
        FROM TCISAL_ATUAL
        WHERE CODPROD = :NEW.CODPROD
            AND CODBEM = :NEW.CODBEM;

		EXCEPTION WHEN NO_DATA_FOUND THEN
			P_COUNT := 0;
		END;

		IF P_COUNT = 0 THEN
			INSERT INTO TCISAL_ATUAL(CODPROD, CODBEM, REFERENCIA, SALDO, TOTALDEP, DELETADO)
				VALUES(:NEW.CODPROD, :NEW.CODBEM, :NEW.REFERENCIA, NVL(:NEW.SALDO, 0), NVL(:NEW.TOTALDEP, 0), 'N');

		ELSIF P_ALTEROU = 'S' THEN
			UPDATE TCISAL_ATUAL 
			SET REFERENCIA = :NEW.REFERENCIA
			  , SALDO = NVL(:NEW.SALDO, 0)
			  , TOTALDEP = NVL(:NEW.TOTALDEP, 0)
			WHERE CODPROD = :NEW.CODPROD
				AND CODBEM = :NEW.CODBEM;

		END IF;
	END IF;
END;

/
