-- SANKHYA.TRG_INC_UPD_TCSCON_PEDLOC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSCON_PEDLOC
"SANKHYA".TRG_INC_UPD_TCSCON_PEDLOC
BEFORE INSERT OR UPDATE ON TCSCON
FOR EACH ROW

DECLARE
    P_COUNT   NUMBER(10);   
BEGIN
  IF :NEW.NUNOTAPEDLOC IS NOT NULL AND (INSERTING OR NVL(:OLD.NUNOTAPEDLOC,0) <> NVL(:NEW.NUNOTAPEDLOC,0)) THEN
    SELECT COUNT(*) INTO P_COUNT FROM TGFCAB WHERE NUNOTA = :NEW.NUNOTAPEDLOC;
    IF P_COUNT = 0 THEN
       RAISE_APPLICATION_ERROR(-20101, 'TCSCON, N¿mero da nota n¿o existe: ' || :NEW.NUNOTAPEDLOC);
    END IF;
  END IF;
END;

/
