-- SANKHYA.TRG_INC_UPD_TGFORD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFORD
"SANKHYA".TRG_INC_UPD_TGFORD BEFORE INSERT OR UPDATE ON TGFORD  FOR EACH ROW 

DECLARE 
    P_COUNT                  INT := 0; 
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF; 
  IF :NEW.CODPARCTRANSP IS NOT NULL AND :NEW.CODPARCTRANSP <> NVL(:OLD.CODPARCTRANSP,0) THEN 
     SELECT COUNT(1) INTO P_COUNT 
       FROM TGFPAR 
      WHERE CODPARC = NVL(:NEW.CODPARCTRANSP, 0) 
        AND ATIVO = 'S'; 
     IF (P_COUNT = 0) THEN 
        RAISE_APPLICATION_ERROR(-20101,'Transportadora não está ativa. '); 
     END IF; 
  END IF; 
 
  IF :NEW.CODEMP IS NOT NULL AND :NEW.CODEMP <> NVL(:OLD.CODEMP, 1) THEN 
     SELECT COUNT(1) INTO P_COUNT 
       FROM TGFEMP 
      WHERE CODEMP = NVL(:NEW.CODEMP, 1) 
        AND ATIVO = 'S'; 
     IF (P_COUNT = 0) THEN 
        RAISE_APPLICATION_ERROR(-20101,'Empresa não está ativa. '); 
     END IF; 
  END IF; 
 
  IF UPDATING('CODVEICULO') and :NEW.CODVEICULO IS NOT NULL THEN 
     STP_VALIDA_VEICULO(:NEW.CODVEICULO); 
  END IF; 
END;

/
