-- SANKHYA.TRG_DLT_TRIRCSP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIRCSP
"SANKHYA".TRG_DLT_TRIRCSP
BEFORE DELETE ON TRIRCSP
FOR EACH ROW

BEGIN
    DELETE TRINFSP
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;

    DELETE TRIPPSP
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;

    DELETE TRIPASP
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;
END;

/
