-- SANKHYA.TRG_INC_TGFMBS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFMBS
"SANKHYA".TRG_INC_TGFMBS 
AFTER INSERT ON TGFMBS FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  UPDATE TGFMBC SET SALDO = SALDO - :NEW.VALOR
  WHERE NUBCO = :NEW.NUBCOREC;
END;

/
