-- SANKHYA.TRG_DLT_TGFTPP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTPP
"SANKHYA".TRG_DLT_TGFTPP
  BEFORE DELETE
  ON TGFTPP
  FOR EACH ROW

DECLARE
  P_COUNT   INT            := 0;
  ERROR     EXCEPTION;
  ERRMSG    VARCHAR2 (255);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  EXISTSRESTRICAO('TGFTPP',:OLD.CODTIPPARC);

  SELECT COUNT (1)
    INTO P_COUNT
    FROM TGFICM
   WHERE TIPRESTRICAO = 'T'
     AND CODRESTRICAO = :OLD.CODTIPPARC;

  IF (P_COUNT <> 0) THEN
    RAISE_APPLICATION_ERROR (-20101,
                             'Registro nao pode ser deletado. Existe uma ref.nas excessoes das aliquotas de ICMS. TIPO 1: ' || TO_CHAR (:OLD.CODTIPPARC));
  END IF;

  SELECT COUNT (1)
    INTO P_COUNT
    FROM TGFICM
   WHERE TIPRESTRICAO2 = 'T'
     AND CODRESTRICAO2 = :OLD.CODTIPPARC;

  IF (P_COUNT <> 0) THEN
    RAISE_APPLICATION_ERROR (-20101,
                             'Registro nao pode ser deletado. Existe uma ref.nas excessoes das aliquotas de ICMS. TIPO 2: ' || TO_CHAR (:OLD.CODTIPPARC));
  END IF;

  IF (:OLD.CODTIPPARC = 0) THEN
     RAISE_APPLICATION_ERROR(-20101, ERROS_PKG.ERRO_REGISTRO_PADRAO);
  END IF;
EXCEPTION
  WHEN ERROR THEN
    RAISE_APPLICATION_ERROR (-20101, ERRMSG);
END;

/
