-- SANKHYA.TRG_DEL_TGWRXN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGWRXN
"SANKHYA".TRG_DEL_TGWRXN
AFTER DELETE ON TGWRXN
FOR EACH ROW

DECLARE
  P_COUNT   NUMBER(5);
BEGIN
	SELECT COUNT(*) INTO P_COUNT FROM TGWEMPE
	WHERE NUNOTA = :OLD.NUNOTA;
	IF P_COUNT > 0 THEN
		UPDATE TGWEMPE 
		SET NURECEBIMENTO = NULL
		WHERE NUNOTA = :OLD.NUNOTA;
	END IF;
END;

/
