-- SANKHYA.TRG_DLT_TGFDES_TGFDPQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDES_TGFDPQ
"SANKHYA".TRG_DLT_TGFDES_TGFDPQ 
BEFORE DELETE 
ON TGFDES
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGFDPQ 
  WHERE NUPROMOCAO = :OLD.NUPROMOCAO;
  IF P_COUNT > 0 THEN
	 DELETE FROM TGFDPQ WHERE NUPROMOCAO = :OLD.NUPROMOCAO;
  END IF;
END;

/
