-- SANKHYA.TRG_DLT_TGFTOP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTOP
"SANKHYA".TRG_DLT_TGFTOP 
BEFORE DELETE ON TGFTOP FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  EXISTSRESTRICAO('TGFTOP',:OLD.CODTIPOPER);

  IF (:OLD.CODTIPOPER = 0) THEN
      RAISE_APPLICATION_ERROR(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;

  INSERT INTO TGFTOP_DLT (CODTIPOPER) VALUES (:OLD.CODTIPOPER);
END;

/
