-- SANKHYA.TRG_DLT_TFPFUN_TGPFCF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPFUN_TGPFCF
"SANKHYA".TRG_DLT_TFPFUN_TGPFCF
AFTER DELETE ON TFPFUN FOR EACH ROW

BEGIN

    DELETE FROM TGPFCF
    WHERE CODFUNC = :OLD.CODFUNC;

END;

/
