-- SANKHYA.TRG_INC_UPD_TGFAJD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFAJD
"SANKHYA".TRG_INC_UPD_TGFAJD
BEFORE INSERT OR DELETE ON TGFAJD
FOR EACH ROW

DECLARE
    P_COUNT             NUMBER(10);   
    ERRMSG              VARCHAR2(255);
    ERROR               EXCEPTION;
    P_VALIDAR           BOOLEAN;
    P_OBS               NUMBER(5);
BEGIN

    IF STP_GET_ATUALIZANDO THEN
        RETURN;
    END IF;

    P_VALIDAR := Fpodevalidar('TGFAJD');
    
    SELECT TRIM(TEXTO) 
    INTO P_OBS 
    FROM TSIPAR 
    WHERE CHAVE = 'OBSPADRASTEST';
    
    IF :NEW.CODOBSPADRAO = P_OBS THEN
        UPDATE TGFITE 
        SET 
          BASESTANT = :NEW.BCICMSSTANT,
          VLRSUBSTANT = :NEW.VLROUTROS
        WHERE NUNOTA = :NEW.NUNOTA
          AND SEQUENCIA = :NEW.SEQUENCIA;
    END IF;

    RETURN;

EXCEPTION
  WHEN ERROR THEN
    IF (P_VALIDAR) THEN 
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF;  
END;

/
