-- SANKHYA.TRG_INC_UPD_TCSITE_NEGOCIACAO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSITE_NEGOCIACAO
"SANKHYA".TRG_INC_UPD_TCSITE_NEGOCIACAO
BEFORE INSERT OR UPDATE ON TCSITE FOR EACH ROW

DECLARE
  P_COUNT             NUMBER(5);       
  P_HORASCRUZADAS     BOOLEAN;
  P_IGNORAHORASCRUZ   VARCHAR2(1);
  P_NUMCONTRATO       NUMBER;
  P_TSICUS_CODUNN     NUMBER;
  P_TSIGRU_CODUNN     NUMBER;
  P_NATCUSTOMIZACAO   VARCHAR2(4000);
  P_SQL               VARCHAR2(4000);
  P_CODNAT            NUMBER;
  P_NUNEGOCIACAO      NUMBER(10);

BEGIN
   IF STP_GET_ATUALIZANDO THEN 
     RETURN;
   END IF;

   -- Se o incio da execução não está preenchido, não há como buscar a negociação.
   -- Se já está vinculado a uma negociação, não devemos alterar.
   IF :NEW.INICEXEC IS NULL OR :NEW.NUNEGOCIACAO IS NOT NULL THEN
     RETURN;
   END IF;
   
   -- OS 745343/67
   IF UPDATING AND :NEW.TEMPGASTO = 0 THEN
     RETURN;
   END IF;

   P_HORASCRUZADAS := (Get_Tsipar_Logico('HORASCRUZADAS') = 'S');
   IF NOT P_HORASCRUZADAS THEN
     RETURN;
   END IF;
   
   SELECT IGNORAHORASCRUZ
   INTO P_IGNORAHORASCRUZ
   FROM TSIUSU
   WHERE CODUSU = :NEW.CODUSU;
   IF P_IGNORAHORASCRUZ= 'S' THEN
     RETURN;
   END IF;
   
   IF :NEW.RETRABALHO = 'S' THEN
     RETURN;
   END IF;
   
   BEGIN
     SELECT CUS.CODUNN, CAB.CODNAT
     INTO P_TSICUS_CODUNN, P_CODNAT
     FROM TCSOSE OSE INNER JOIN TGFCAB CAB ON (OSE.NUNOTA = CAB.NUNOTA)
                      INNER JOIN TSICUS CUS ON (CAB.CODCENCUS = CUS.CODCENCUS)
     WHERE OSE.NUMOS = :NEW.NUMOS;
   EXCEPTION
     WHEN OTHERS THEN
       P_TSICUS_CODUNN := 0;
       P_CODNAT  := 0;
   END;
   
   SELECT GRU.CODUNN
   INTO P_TSIGRU_CODUNN
   FROM TSIUSU USU INNER JOIN TSIGRU GRU ON (USU.CODGRUPO = GRU.CODGRUPO)
   WHERE USU.CODUSU = :NEW.CODUSU;
   
   IF (P_TSIGRU_CODUNN IS NULL) OR (P_TSICUS_CODUNN = P_TSIGRU_CODUNN) THEN
     RETURN;
   END IF;
   
   SELECT NUMCONTRATO
   INTO P_NUMCONTRATO
   FROM TCSOSE
   WHERE NUMOS = :NEW.NUMOS;
   IF P_NUMCONTRATO IS NOT NULL THEN
     RETURN;
   END IF;
   
   BEGIN
       SELECT TEXTO 
       INTO P_NATCUSTOMIZACAO
       FROM TSIPAR WHERE CHAVE = 'NATCUSTOMIZACAO';
   EXCEPTION
     WHEN OTHERS THEN
     P_NATCUSTOMIZACAO := NULL;
   END;

   IF (P_NATCUSTOMIZACAO IS NOT NULL) THEN
      P_SQL := 'SELECT COUNT(1) FROM DUAL WHERE ' || P_CODNAT || ' IN (' || P_NATCUSTOMIZACAO || ')';
      EXECUTE IMMEDIATE P_SQL INTO P_COUNT;
      IF P_COUNT > 0 THEN
         RETURN;
      END IF;
   END IF;
 
     BEGIN  
        SELECT NEGOC INTO P_NUNEGOCIACAO
        FROM
           (SELECT
            CASE WHEN EXISTS (SELECT 1 FROM TCSEXN EXN WHERE EXN.NUNEGOCIACAO = NHC.NUNEGOCIACAO AND EXN.CODEXECUTANTE = :NEW.CODUSU) THEN
                0
            ELSE 
                1
            END AS EXECUTANTE,
            CASE WHEN (NHC.CODPARC IS NOT NULL AND NHC.CODPARC = OSE.CODPARC) THEN
                0            
            ELSE
                1
            END AS PARCEIRO,
            CASE WHEN ((NHC.NUNOTA IS NOT NULL AND NHC.NUNOTA = PED.NUNOTA) OR (NHC.NUFAP IS NOT NULL AND NHC.NUFAP = OSE.NUFAP)) THEN
                0
            ELSE
                1
            END AS PEDIDO_FAP,
            NHC.NUNEGOCIACAO AS NEGOC
        FROM
            TCSOSE OSE
            INNER JOIN TGFCAB PED ON PED.NUNOTA = OSE.NUNOTA
            INNER JOIN TSICUS CUS ON CUS.CODCENCUS = PED.CODCENCUS
            INNER JOIN TCSNHC NHC ON NHC.CODUNNCOMPRADORA = CUS.CODUNN AND (OSE.CODPARC = NHC.CODPARC OR NHC.CODPARC IS NULL) 
        WHERE
            OSE.NUMOS = :NEW.NUMOS
            AND NHC.CODUNNVENDEDORA = P_TSIGRU_CODUNN
            AND :NEW.INICEXEC BETWEEN NHC.DTINI AND NHC.DTFIN 
             AND (
                NOT EXISTS(SELECT 1 FROM TCSEXN EXN WHERE EXN.NUNEGOCIACAO = NHC.NUNEGOCIACAO)
                OR  EXISTS(SELECT 1 FROM TCSEXN EXN WHERE EXN.NUNEGOCIACAO = NHC.NUNEGOCIACAO AND EXN.CODEXECUTANTE = :NEW.CODUSU)
            )
        ORDER BY 
            EXECUTANTE, PARCEIRO, DTINI, PEDIDO_FAP DESC) SUB        
        WHERE ROWNUM = 1;        
    EXCEPTION
         WHEN NO_DATA_FOUND THEN
         RAISE_APPLICATION_ERROR(-20101, 'Não há negociação de horas cruzadas vigente entre a sua Unidade e a Unidade do cliente.');
       END;
   :NEW.NUNEGOCIACAO := P_NUNEGOCIACAO;
END;

/
