-- SANKHYA.TRG_INC_DLT_TFPFAL_FALTPER_AFT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_DLT_TFPFAL_FALTPER_AFT
"SANKHYA".TRG_INC_DLT_TFPFAL_FALTPER_AFT
AFTER INSERT OR DELETE ON TFPFAL

DECLARE
	CURSOR UPDITENS IS
     SELECT CODEMP, CODFUNC, DTINIAQUI, DTFINAQUI
     FROM TFPFAL_INC_DLT;
    P_DTINIAQUI DATE;
    P_DTFINAQUI DATE;
    P_FALTAS NUMBER;
    P_CODEMP NUMBER;
    P_CODFUNC NUMBER;
    P_COUNT   NUMBER;
     P_DESABILITAR_TRIGGER NUMBER;
BEGIN
    IF STP_GET_ATUALIZANDO THEN
        RETURN;
     END IF;

    SELECT COUNT(1) INTO P_DESABILITAR_TRIGGER
    FROM TSIPAR
    WHERE CHAVE = 'DISABLEDTRGFER'
    AND LOGICO = 'S';

    IF (P_DESABILITAR_TRIGGER > 0) THEN
      RETURN;
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TFPFAL_INC_DLT;

    IF P_COUNT > 0 THEN
	  OPEN UPDITENS;
      LOOP
        FETCH UPDITENS INTO P_CODEMP, P_CODFUNC, P_DTINIAQUI, P_DTFINAQUI;

        P_FALTAS := SNK_CALCULA_FALTAS_TFPFAL(P_CODEMP, P_CODFUNC, P_DTFINAQUI, P_DTINIAQUI);

       UPDATE TFPFER
		   SET FALTPER = P_FALTAS
		 WHERE
		   CODEMP = P_CODEMP
		   AND CODFUNC = P_CODFUNC
		   AND DTSAIDA IS NULL
		   AND ATUALFERGOZ='N'
		   AND DTINIAQUI = P_DTINIAQUI
		   AND DTFINAQUI = P_DTFINAQUI;

		EXIT WHEN UPDITENS%NOTFOUND;
      END LOOP;
      DELETE FROM TFPFAL_INC_DLT;
      CLOSE UPDITENS;
   END IF;
END;

/
