-- SANKHYA.TRG_INC_TFPVPS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPVPS
"SANKHYA".TRG_INC_TFPVPS 
BEFORE INSERT ON TFPVPS 
FOR EACH ROW

DECLARE
 P_COUNT      INTEGER;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF :NEW.SEQUENCIA > 0 THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TFPDPD
    WHERE CODEMP = :NEW.CODEMP
      AND CODFUNC = :NEW.CODFUNC
	    AND SEQUENCIA = :NEW.SEQUENCIA;
    IF P_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20101, 'Dependente '  || :NEW.SEQUENCIA ||' não cadastrado.');
    END IF;
	END IF;
END;

/
