-- SANKHYA.TRG_INC_TFPMON
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPMON
"SANKHYA".TRG_INC_TFPMON
BEFORE INSERT ON TFPMON
FOR EACH ROW
    
DECLARE P_CAMPOSCHAVE   TFPMON.CAMPOSCHAVE%TYPE := ' ';
BEGIN
    P_CAMPOSCHAVE := SNK_GET_PK_FOR_ESOCIAL(:NEW.NOMETAB);

    IF LENGTH(TRIM(P_CAMPOSCHAVE)) = 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'Não foi possível identificar os campos da PK da tabela '||:NEW.NOMETAB);
    END IF;

    :NEW.CAMPOSCHAVE := P_CAMPOSCHAVE;
END;

/
