-- SANKHYA.TRG_INC_UPD_TFPFER_FALTPER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPFER_FALTPER
"SANKHYA".TRG_INC_UPD_TFPFER_FALTPER
BEFORE INSERT OR UPDATE ON TFPFER
FOR EACH ROW

DECLARE
	P_FALTAS NUMBER;
    P_DESABILITAR_TRIGGER NUMBER;
BEGIN
     IF STP_GET_ATUALIZANDO THEN
        RETURN;
     END IF;

	SELECT COUNT(1) INTO P_DESABILITAR_TRIGGER
    FROM TSIPAR 
    WHERE CHAVE = 'DISABLEDTRGFER'
    AND LOGICO = 'S';

    IF (P_DESABILITAR_TRIGGER > 0) THEN
      RETURN;
    END IF;

	P_FALTAS := SNK_CALCULA_FALTAS_TFPFAL(:NEW.CODEMP, :NEW.CODFUNC, :NEW.DTFINAQUI, :NEW.DTINIAQUI);
    
    IF (P_FALTAS <> :NEW.FALTPER) THEN
        :NEW.FALTPER := P_FALTAS;
    END IF;
END;

/
