-- SANKHYA.TRG_DLT_TRIRRAD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIRRAD
"SANKHYA".TRG_DLT_TRIRRAD 
AFTER DELETE  ON TRIRRAD
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDREE T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDREE
		WHERE :OLD.CODEMP = TRIDREE.CODEMP 
		  AND :OLD.DTREF = TRIDREE.DTREF 
		  AND :OLD.TPAMB = TRIDREE.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDREE.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDREE.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRRE T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRRE
		WHERE :OLD.CODEMP = TRIDRRE.CODEMP 
		  AND :OLD.DTREF = TRIDRRE.DTREF 
		  AND :OLD.TPAMB = TRIDRRE.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRRE.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRRE.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPRRC T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPRRC
		WHERE :OLD.CODEMP = TRIPRRC.CODEMP 
		  AND :OLD.DTREF = TRIPRRC.DTREF 
		  AND :OLD.TPAMB = TRIPRRC.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPRRC.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPRRC.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIRRAD_NFS T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIRRAD_NFS
		WHERE :OLD.CODEMP = TRIRRAD_NFS.CODEMP 
		  AND :OLD.DTREF = TRIRRAD_NFS.DTREF 
		  AND :OLD.TPAMB = TRIRRAD_NFS.TPAMB 
		  AND :OLD.SEQUENCIA = TRIRRAD_NFS.SEQUENCIA 
		  AND :OLD.CHAVE = TRIRRAD_NFS.CHAVE;
	END IF;
END;

/
