-- SANKHYA.TRG_DEL_TCSFATHC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TCSFATHC
"SANKHYA".TRG_DEL_TCSFATHC 
AFTER DELETE ON TCSFATHC


DECLARE 
    P_COUNT     NUMBER(05);
    
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    BEGIN
        SELECT COUNT(*) INTO P_COUNT FROM TCSFATHC;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 THEN
        UPDATE TSIVARBD SET UTILIZA_HCRUZADAS = 'N';
        COMMIT;
    END IF;
END;

/
