-- SANKHYA.TRG_DLT_TSICUS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSICUS
"SANKHYA".TRG_DLT_TSICUS 
BEFORE DELETE ON TSICUS
FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.CODCENCUS = 0) THEN
    raise_application_error(-20101, ERROS_PKG.ERRO_REGISTRO_PADRAO);
  END IF;

  EXISTSRESTRICAO('TSICUS',:OLD.CODCENCUS);
    
  SELECT COUNT(1)
  INTO P_COUNT
  FROM TSIFOP 
  WHERE TABELA = 'TSICUS' 
  AND CODCHAVE = :OLD.CODCENCUS;
 
  IF P_COUNT > 0 THEN
    DELETE FROM TSIFOP 
    WHERE TABELA = 'TSICUS' 
    AND CODCHAVE = :OLD.CODCENCUS;
  END IF;

END;

/
