-- SANKHYA.TRG_DLT_TGFFOR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFFOR
"SANKHYA".TRG_DLT_TGFFOR BEFORE DELETE ON TGFFOR FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.CODFORMPREC = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
