-- SANKHYA.TRG_INC_TFPGESAVI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPGESAVI
"SANKHYA".TRG_INC_TFPGESAVI
BEFORE INSERT ON TFPGESAVI
FOR EACH ROW

BEGIN
  SELECT TFPGESAVI_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
