-- SANKHYA.TRG_DLT_TGFCLP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCLP
"SANKHYA".TRG_DLT_TGFCLP
BEFORE DELETE ON TGFCLP
FOR EACH ROW

DECLARE
    P_COUNT          NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  IF SNK_TGFTOKCFG AND SNK_TGFTOKCAM('TGFCLA') THEN
    INSERT INTO TGFATUTOK (CODPROD, DHALTER) VALUES(:OLD.CODPROD, SYSDATE);
  END IF;
  
END;

/
