-- SANKHYA.TRG_DLT_TFPNIV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPNIV
"SANKHYA".TRG_DLT_TFPNIV BEFORE DELETE ON TFPNIV FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODNIVELREF = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
