-- SANKHYA.TRG_DEL_TGFFAM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGFFAM
"SANKHYA".TRG_DEL_TGFFAM
AFTER DELETE ON TGFFAM


DECLARE 
    P_COUNT     NUMBER(05);

BEGIN
    BEGIN
        SELECT COUNT(1) INTO P_COUNT FROM TGFFAM;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 THEN
        UPDATE TSIVARBD SET EXISTE_REGISTRO_TGFFAM = 'N';
    END IF;
END;

/
