-- SANKHYA.TRG_DLT_TGFMBS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFMBS
"SANKHYA".TRG_DLT_TGFMBS 
AFTER DELETE ON TGFMBS FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1)
      INTO P_COUNT
  FROM TGFMBC 
  WHERE NUBCO = :OLD.NUBCOREC;
  
  IF P_COUNT > 0 THEN  
    UPDATE TGFMBC SET SALDO = SALDO + :OLD.VALOR
    WHERE NUBCO = :OLD.NUBCOREC;
  END IF;
END;

/
