-- SANKHYA.TRG_INC_UPD_DLT_TPRAPA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TPRAPA
"SANKHYA".TRG_INC_UPD_DLT_TPRAPA
BEFORE INSERT OR UPDATE
ON TPRAPA
FOR EACH ROW

DECLARE ERRMSG VARCHAR2(100);
BEGIN
	ERRMSG := 'Qtd.Faturada ('|| :NEW.QTDFAT ||') não pode ser maior que Qtd.Apontada ('|| :NEW.QTDAPONTADA ||').';
     RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
