-- SANKHYA.TRG_INC_TGFSBC_INC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFSBC_INC
"SANKHYA".TRG_INC_TGFSBC_INC
AFTER INSERT ON TGFSBC_INC
FOR EACH ROW

DECLARE
    P_COUNT     NUMBER(05);
    P_VALIDAR   BOOLEAN;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  P_VALIDAR := FPODEVALIDAR('TGFSBC_INC');
  IF P_VALIDAR THEN
    RETURN;
  END IF;

  BEGIN
      SELECT COUNT(*) INTO P_COUNT
      FROM TGFSBC I 
      WHERE I.CODCTABCOINT = :NEW.CODCTABCOINT 
        AND I.REFERENCIA = :NEW.REFERENCIA;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_COUNT := 0;
  END;
    
  IF P_COUNT = 0 THEN

    INSERT INTO TGFSBC (CODCTABCOINT, REFERENCIA, SALDOREAL, SALDOBCO)
    VALUES (:NEW.CODCTABCOINT, :NEW.REFERENCIA, :NEW.SALDOREAL, :NEW.SALDOBCO);  

    COMMIT;
  END IF;
  
END;

/
