-- SANKHYA.TRG_INC_UPD_DLT_TGMAI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGMAI
"SANKHYA".TRG_INC_UPD_DLT_TGMAI BEFORE INSERT OR UPDATE OR DELETE ON TGMAI FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;


  IF UPDATING OR DELETING THEN
    SELECT COUNT(1)
        INTO P_COUNT
    FROM TGMMET
    WHERE CODMETA = :OLD.CODMETA
         AND CODEMP = :OLD.CODEMP
         AND CODNAT = :OLD.CODNAT
         AND CODCENCUS = :OLD.CODCENCUS
         AND CODPROJ = :OLD.CODPROJ
         AND DTREF = TRUNC(:OLD.DTAUTINV, 'MONTH');

      IF P_COUNT > 0 THEN
        UPDATE TGMMET SET TOTALAUTINV = TOTALAUTINV - (:OLD.VLRAUTINV - NVL(:OLD.VLRCANCELADO,0)) 
        WHERE CODMETA = :OLD.CODMETA
        AND CODEMP = :OLD.CODEMP
        AND CODNAT = :OLD.CODNAT
        AND CODCENCUS = :OLD.CODCENCUS
        AND CODPROJ = :OLD.CODPROJ
        AND DTREF = TRUNC(:OLD.DTAUTINV, 'MONTH');
      END IF;  
  END IF;

  IF INSERTING OR UPDATING THEN
    SELECT COUNT(1)
         INTO P_COUNT
    FROM TGMMET
    WHERE CODMETA = :NEW.CODMETA
    AND CODEMP = :NEW.CODEMP
    AND CODNAT = :NEW.CODNAT
    AND CODCENCUS = :NEW.CODCENCUS
    AND CODPROJ = :NEW.CODPROJ
    AND DTREF = TRUNC(:NEW.DTAUTINV, 'MONTH');

    IF P_COUNT > 0 THEN
      UPDATE TGMMET SET TOTALAUTINV = TOTALAUTINV + (:NEW.VLRAUTINV - NVL(:NEW.VLRCANCELADO,0)) 
      WHERE CODMETA = :NEW.CODMETA
      AND CODEMP = :NEW.CODEMP
      AND CODNAT = :NEW.CODNAT
      AND CODCENCUS = :NEW.CODCENCUS
      AND CODPROJ = :NEW.CODPROJ
      AND DTREF = TRUNC(:NEW.DTAUTINV, 'MONTH');
    END IF;
  END IF;
END;

/
