-- SANKHYA.TRG_INC_UPD_TGFEST_ROUND
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFEST_ROUND
"SANKHYA".TRG_INC_UPD_TGFEST_ROUND
BEFORE INSERT OR UPDATE ON TGFEST 
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  -- OS 717072
  IF (NVL(:NEW.RESERVADO,0) <> NVL(:OLD.RESERVADO,0)) THEN
    :NEW.RESERVADO := ROUND(:NEW.RESERVADO, 9);
  END IF; 

  IF (NVL(:NEW.ESTOQUE,0) <> NVL(:OLD.ESTOQUE,0)) THEN
    :NEW.ESTOQUE := ROUND(:NEW.ESTOQUE, 9);
  END IF; 
  
END;

/
