-- SANKHYA.TRG_INC_UPD_TFPCTB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPCTB
"SANKHYA".TRG_INC_UPD_TFPCTB 
BEFORE INSERT OR UPDATE ON TFPCTB FOR EACH ROW

DECLARE
  P_COUNT              INT;
  P_CODEMP             NUMBER(5);
BEGIN
  
  BEGIN
    SELECT MIN(E.CODEMPPLACTA) INTO P_CODEMP
    FROM TCBEMP E, TFPEMP F 
    WHERE E.CODEMP = NVL(F.EMPDESTINOCTB, F.CODEMP)
    AND F.CODREGFIS = :NEW.CODREGFIS 
    AND EXISTS (SELECT 1 FROM TCBPLA WHERE CODEMP = E.CODEMPPLACTA);    
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_CODEMP := 0;
  END;    

  IF NVL(:NEW.CONTACREDITO, 0) <> 0 THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TCBPLA P, TCBEMP E, TFPEMP F
    WHERE P.CODCTACTB = :NEW.CONTACREDITO
    AND E.CODEMP = NVL(F.EMPDESTINOCTB, F.CODEMP)
    AND F.CODREGFIS = :NEW.CODREGFIS
    AND E.CODEMPPLACTA = P.CODEMP
    AND P.ATIVA = 'S'
    AND P.ANALITICA = 'S';
    
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Conta Contabil de Credito invalida, ou nao ativa, ou nao analitica. Conta: ' || :NEW.CONTACREDITO || ' e Empresa: ' || P_CODEMP ||'.');
    END IF;
  END IF;

  IF NVL(:NEW.CONTADEBITO, 0) <> 0 THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TCBPLA P, TCBEMP E, TFPEMP F
    WHERE P.CODCTACTB = :NEW.CONTADEBITO
    AND E.CODEMP = NVL(F.EMPDESTINOCTB, F.CODEMP)
    AND F.CODREGFIS = :NEW.CODREGFIS
    AND E.CODEMPPLACTA = P.CODEMP
    AND P.ATIVA = 'S'
    AND P.ANALITICA = 'S';
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Conta Contabil de Debito invalida, ou nao ativa, ou nao analitica. Conta: ' || :NEW.CONTADEBITO || ' e Empresa: ' || P_CODEMP ||'.');
    END IF;
  END IF;
  

END;

/
