-- SANKHYA.TRG_INC_UPD_TFPPTR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPPTR
"SANKHYA".TRG_INC_UPD_TFPPTR BEFORE INSERT OR UPDATE ON TFPTPR FOR EACH ROW

DECLARE P_COUNT INT;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  /*
   VALIDAR SE O CODIGO EXISTE
  */
  P_COUNT := 0;
  IF (:NEW.CODAFASTCAGED <> NVL(:OLD.CODAFASTCAGED,0)) THEN
    SELECT
	 NVL(COUNT(1),0) INTO P_COUNT
	FROM TFPAFA AFA
    WHERE (AFA.CODAFAST = :NEW.CODAFASTCAGED)
    AND AFA.TIPTAB = 'C';
    IF (P_COUNT=0) THEN
     RAISE_APPLICATION_ERROR(-20101, 'Código de afastamento CAGED não foi encontrado no cadastro de afastamentos.');
    END IF;
  END IF;
  IF (:NEW.CODAFASTFGTS  <> NVL(:OLD.CODAFASTFGTS,0))  THEN
    SELECT
	 NVL(COUNT(1),0) INTO P_COUNT
	FROM TFPAFA AFA
    WHERE (AFA.CODAFAST = :NEW.CODAFASTFGTS)
    AND AFA.TIPTAB = 'F';
    IF (P_COUNT=0) THEN
     RAISE_APPLICATION_ERROR(-20101, 'Código de afastamento FGTS não foi encontrado no cadastro de afastamentos.');
    END IF;
  END IF;
  IF (:NEW.CODAFASTRAIS  <> NVL(:OLD.CODAFASTRAIS,0))  THEN
    SELECT
	 NVL(COUNT(1),0) INTO P_COUNT
	FROM TFPAFA AFA
    WHERE (AFA.CODAFAST = :NEW.CODAFASTRAIS)
    AND AFA.TIPTAB = 'R';
    IF (P_COUNT=0) THEN
     RAISE_APPLICATION_ERROR(-20101, 'Código de afastamento RAIS não foi encontrado no cadastro de afastamentos.');
    END IF;
  END IF;
END;

/
