-- SANKHYA.TRG_INC_UPD_DLT_TGFDBPC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFDBPC
"SANKHYA".TRG_INC_UPD_DLT_TGFDBPC
BEFORE INSERT OR UPDATE OR DELETE ON TGFDBPC
FOR EACH ROW

BEGIN
  IF INSERTING THEN
    UPDATE TGFCRPC 
    SET SALDO = NVL(SALDO, 0) - NVL(:NEW.VL_CRED_DESC_PA, 0) - NVL(:NEW.VR_CRED_PER_PA, 0) - NVL(:NEW.VL_CRED_DCOMP_PA, 0)
    WHERE CODEMP = :NEW.CODEMP
      AND PER_APU_CRED = :NEW.PER_APU_CRED
      AND ORIG_CRED = :NEW.ORIG_CRED
      AND CNPJ_SUC = :NEW.CNPJ_SUC
      AND CNPJ = :NEW.CNPJ
      AND COD_CRED = :NEW.COD_CRED
      AND TIPO = :NEW.TIPO;
  ELSIF DELETING THEN
    UPDATE TGFCRPC 
    SET SALDO = NVL(SALDO, 0) + NVL(:OLD.VL_CRED_DESC_PA, 0) + NVL(:OLD.VR_CRED_PER_PA, 0) + NVL(:OLD.VL_CRED_DCOMP_PA, 0)
    WHERE CODEMP = :OLD.CODEMP
      AND PER_APU_CRED = :OLD.PER_APU_CRED
      AND ORIG_CRED = :OLD.ORIG_CRED
      AND CNPJ_SUC = :OLD.CNPJ_SUC
      AND CNPJ = :OLD.CNPJ
      AND COD_CRED = :OLD.COD_CRED
      AND TIPO = :OLD.TIPO;
  ELSIF (NVL(:NEW.VL_CRED_DESC_PA, 0) <> NVL(:OLD.VL_CRED_DESC_PA, 0) OR
        NVL(:NEW.VR_CRED_PER_PA, 0) <> NVL(:OLD.VR_CRED_PER_PA, 0) OR
        NVL(:NEW.VL_CRED_DCOMP_PA, 0) <> NVL(:OLD.VL_CRED_DCOMP_PA, 0)) THEN
    UPDATE TGFCRPC 
    SET SALDO = NVL(SALDO, 0) - NVL(:NEW.VL_CRED_DESC_PA, 0) - NVL(:NEW.VR_CRED_PER_PA, 0) - NVL(:NEW.VL_CRED_DCOMP_PA, 0)
    + NVL(:OLD.VL_CRED_DESC_PA, 0) + NVL(:OLD.VR_CRED_PER_PA, 0) + NVL(:OLD.VL_CRED_DCOMP_PA, 0)
    WHERE CODEMP = :NEW.CODEMP
      AND PER_APU_CRED = :NEW.PER_APU_CRED
      AND ORIG_CRED = :NEW.ORIG_CRED
      AND CNPJ_SUC = :NEW.CNPJ_SUC
      AND CNPJ = :NEW.CNPJ
      AND COD_CRED = :NEW.COD_CRED
      AND TIPO = :NEW.TIPO;      
  END IF;  
END;

/
