-- SANKHYA.TRG_DLT_TRIPLDS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIPLDS
TRG_DLT_TRIPLDS
AFTER DELETE  ON TRIPLDS
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDPDE T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.CNPJ = T.CNPJ;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDPDE
		WHERE :OLD.CODEMP = TRIDPDE.CODEMP 
		  AND :OLD.DTREF = TRIDPDE.DTREF 
		  AND :OLD.TPAMB = TRIDPDE.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDPDE.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDPDE.CHAVE
		  AND :OLD.CNPJ = TRIDPDE.CNPJ;
	END IF;	
END;	

/
