-- SANKHYA.TRG_INC_UPD_TGFIMC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFIMC
"SANKHYA".TRG_INC_UPD_TGFIMC BEFORE INSERT OR UPDATE ON TGFIMC FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODCTACTB1') AND :NEW.CODCTACTB1 IS NOT NULL THEN
     SELECT COUNT(1) INTO  P_COUNT
       FROM TCBPLA P
      WHERE P.CODCTACTB = :NEW.CODCTACTB1
        AND P.ATIVA = 'S' AND P.ANALITICA = 'S';
     IF (P_COUNT = 0) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_CTACTB_ATIV_ANALI_EXIST);
     END IF;
  END IF;
  IF UPDATING('CODCTACTB2') AND :NEW.CODCTACTB2 IS NOT NULL THEN
     SELECT COUNT(1) INTO  P_COUNT
       FROM TCBPLA P
      WHERE P.CODCTACTB = :NEW.CODCTACTB2
        AND P.ATIVA = 'S' AND P.ANALITICA = 'S';
     IF (P_COUNT = 0) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_CTACTB_ATIV_ANALI_EXIST);
     END IF;
  END IF;
  IF UPDATING('TIPOIMPOSTO') AND (:NEW.TIPOIMPOSTO <> :OLD.TIPOIMPOSTO) THEN
		UPDATE TGFIMN SET 
			TIPOIMPOSTO = :NEW.TIPOIMPOSTO
		WHERE CODIMP = :NEW.CODIMP;
  END IF;
END;

/
