-- SANKHYA.TRG_FX_TFXECP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXECP
"SANKHYA".TRG_FX_TFXECP
   BEFORE INSERT
   ON TFXECP
   FOR EACH ROW

DECLARE
   P_SEQ     NUMBER (10);
BEGIN
        IF (NVL(:NEW.SEQ, 0) = 0) THEN 
        SELECT MAX(NVL(SEQ, 0))+1 INTO P_SEQ FROM TFXECP WHERE CODPROD = :NEW.CODPROD AND CODTAB = :NEW.CODTAB;
        IF P_SEQ IS NULL THEN
            :NEW.SEQ := 1;
              END IF;
          
       IF P_SEQ IS NOT NULL THEN
        :NEW.SEQ := P_SEQ;
    END IF;
    END IF;
END;

/
