-- SANKHYA.TRG_INC_UPD_TGFPEC_TGFORD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPEC_TGFORD
"SANKHYA".TRG_INC_UPD_TGFPEC_TGFORD
BEFORE INSERT OR UPDATE ON TGFPEC 
FOR EACH ROW

DECLARE
	P_COUNT           INT := 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	IF ((:NEW.ORDEMCARGA IS NOT NULL) AND (:NEW.ORDEMCARGA <> 0)) THEN
		SELECT COUNT(1) INTO P_COUNT
		FROM TGFORD ORD
		WHERE ORD.ORDEMCARGA = :NEW.ORDEMCARGA
		AND ORD.CODEMP = (	
			SELECT CASE WHEN EMP.CODEMPOC IS NULL THEN EMP.CODEMP 
					ELSE CODEMPOC END 
			FROM TGFEMP EMP 
			WHERE EMP.CODEMP = :NEW.CODEMP);
		
		IF (P_COUNT=0) THEN
			 RAISE_APPLICATION_ERROR(-20101, 'Não existe referência para essa ordem de carga.');
		END IF;	
	END IF;
	RETURN;
END;

/
