-- SANKHYA.TRG_INC_UPD_TGFISS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFISS
"SANKHYA".TRG_INC_UPD_TGFISS 
BEFORE INSERT OR UPDATE ON TGFISS
FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	  IF (:NEW.CODPROD <>0 ) AND (:NEW.CODPROD <> :OLD.CODPROD)THEN
	    SELECT COUNT(1) INTO  P_COUNT
	        FROM TGFPRO P
	        WHERE P.CODPROD = (:NEW.CODPROD)
	          AND P.USOPROD = 'S'
	          AND P.ATIVO   = 'S';
	      IF (P_COUNT = 0)   THEN
	       RAISE_APPLICATION_ERROR (-20101, 'Nao e um Servico valido ou nao esta ativo.');
	      END IF;
	  END IF;
  RETURN;
END;

/
