-- SANKHYA.TRG_DLT_TRINFSP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRINFSP
"SANKHYA".TRG_DLT_TRINFSP
BEFORE DELETE ON TRINFSP
FOR EACH ROW

BEGIN
    DELETE TRIINFSP
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND NUNOTA = :OLD.NUNOTA;
END;

/
