-- SANKHYA.TRG_DLT_TGFCFM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCFM
"SANKHYA".TRG_DLT_TGFCFM BEFORE DELETE ON TGFCFM FOR EACH ROW

DECLARE
  P_VALFIDEL    NUMBER(10,0);
  P_COUNT       NUMBER(10,0);
  P_STATUSNOTA  TGFCAB.STATUSNOTA%TYPE;
  P_SALDO       TGFCFS.SALDO%TYPE;

BEGIN
  
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :OLD.SINAL = 1 THEN
    SELECT COUNT(*), MAX(SALDO)
    INTO P_COUNT, P_SALDO
    FROM TGFCFS
    WHERE NUNOTA = :OLD.NUNOTA;
    IF P_COUNT > 0 THEN
      IF P_SALDO <> :OLD.VALOR THEN
        RAISE_APPLICATION_ERROR(-20101, 'Valor de crédito já foi usado, não pode ser excluído.'|| :OLD.NUNOTA);
      END IF;
      DELETE FROM TGFCFS 
      WHERE NUNOTA = :OLD.NUNOTA;
    END IF;
  ELSIF :OLD.SINAL = -1 THEN
    UPDATE TGFCFS SET
      SALDO = SALDO + NVL(:OLD.VALOR,0)
    WHERE NUNOTA = :OLD.NUNOTAORIG;
  END IF;
END;

/
