-- SANKHYA.TRG_DLT_TGFICO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFICO
"SANKHYA".TRG_DLT_TGFICO  
BEFORE DELETE ON TGFICO FOR EACH ROW

DECLARE  P_COUNT NUMBER(10);
BEGIN
  SELECT COUNT(1) INTO P_COUNT
  FROM TGFICO_DLT
  WHERE NUNOTAPO = :OLD.NUNOTAPO 
    AND SEQUENCIAPO = :OLD.SEQUENCIAPO;
  
  IF P_COUNT = 0 THEN
    INSERT INTO TGFICO_DLT(NUNOTAPO, SEQUENCIAPO)
	         VALUES(:OLD.NUNOTAPO, :OLD.SEQUENCIAPO);
  END IF;
END;

/
