-- SANKHYA.TRG_FX_TSIUSU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TSIUSU
"SANKHYA".TRG_FX_TSIUSU 
   BEFORE INSERT OR UPDATE OR DELETE
   ON TSIUSU
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
   
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;
      
   IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S') AND (
     NVL(:OLD.CODUSU, 0) <> NVL(:NEW.CODUSU, 0) OR
     NVL(:OLD.NOMEUSU, '0') <> NVL(:NEW.NOMEUSU, '0') OR
     NVL(:OLD.CONTACESSO, '0') <> NVL(:NEW.CONTACESSO, '0') OR
     NVL(:OLD.INTERNO, '0') <> NVL(:NEW.INTERNO, '0') OR
     NVL(:OLD.CAIXA, '0') <> NVL(:NEW.CAIXA, '0') OR
     NVL(:OLD.CODPERFIL, 0) <> NVL(:NEW.CODPERFIL, 0) OR 
     NVL(:OLD.TEMECF, '0') <> NVL(:NEW.TEMECF, '0') OR
     NVL(:OLD.TOKENCHECKOUT, '0') <> NVL(:NEW.TOKENCHECKOUT, '0'))
   THEN
		SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

		:NEW.NUVERSAO := P_CONTADOR;
		:NEW.ATUNUVERSAO := 'N';
   END IF;
END;

/
