-- SANKHYA.TRG_INC_UPD_TCILOC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCILOC
"SANKHYA".TRG_INC_UPD_TCILOC
BEFORE INSERT OR UPDATE ON TCILOC
FOR EACH ROW

DECLARE 
	P_COUNT			NUMBER(5);
	P_ALTEROU		CHAR(1);
BEGIN
	IF UPDATING  AND :NEW.CODBEM <> :OLD.CODBEM THEN 
		UPDATE TCILOC_ATUAL SET CODBEM = :NEW.CODBEM WHERE CODPROD = :NEW.CODPROD AND CODBEM = :OLD.CODBEM;
	ELSE 
		BEGIN
			SELECT 1, CASE WHEN (DTENTRADA < :NEW.DTENTRADA OR 
											(DTENTRADA = :NEW.DTENTRADA AND 
											  (NVL(CODUSU, 0) <> NVL(:NEW.CODUSU, 0) OR 
											   NVL(CODEMP, 0) <> NVL(:NEW.CODEMP, 0) OR  
											   NVL(CODDEPTO, 0) <> NVL(:NEW.CODDEPTO, 0) OR 
											   NVL(NUNOTA, 0) <> NVL(:NEW.NUNOTA, 0) OR 
											   NVL(SEQUENCIA, 0) <> NVL(:NEW.SEQUENCIA, 0)))
									   ) THEN 'S' ELSE 'N' END  
			INTO P_COUNT, P_ALTEROU
			FROM TCILOC_ATUAL
			WHERE CODPROD = :NEW.CODPROD
				AND CODBEM = :NEW.CODBEM;

		EXCEPTION WHEN NO_DATA_FOUND THEN
			P_COUNT := 0;
		END;

		IF P_COUNT = 0 THEN
			INSERT INTO TCILOC_ATUAL(CODPROD, CODBEM, DTENTRADA, CODUSU, CODEMP, CODDEPTO, NUNOTA, SEQUENCIA, DELETADO)
				VALUES(:NEW.CODPROD, :NEW.CODBEM, :NEW.DTENTRADA, :NEW.CODUSU, :NEW.CODEMP, :NEW.CODDEPTO, :NEW.NUNOTA, :NEW.SEQUENCIA, 'N');

		ELSIF P_ALTEROU = 'S' THEN
			UPDATE TCILOC_ATUAL 
			SET DTENTRADA = :NEW.DTENTRADA
			  , CODUSU = :NEW.CODUSU
			  , CODEMP = :NEW.CODEMP
			  , CODDEPTO = :NEW.CODDEPTO
			  , NUNOTA = :NEW.NUNOTA
			  , SEQUENCIA = :NEW.SEQUENCIA
			WHERE CODPROD = :NEW.CODPROD
				AND CODBEM = :NEW.CODBEM;
		END IF;
	END IF;
END;

/
