-- SANKHYA.TRG_INC_UPD_TGFVEI_PROD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFVEI_PROD
"SANKHYA".TRG_INC_UPD_TGFVEI_PROD 
BEFORE INSERT OR UPDATE 
ON TGFVEI 
FOR EACH ROW


BEGIN

    IF STP_GET_ATUALIZANDO THEN
        RETURN;
    END IF;
  
    TGFVEI_PKG.V_CODPROD := :NEW.CODPROD;
    TGFVEI_PKG.V_CODBEM :=     :NEW.CODBEM;
END;

/
