-- SANKHYA.TRG_INC_UPD_TGFATT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFATT
"SANKHYA".TRG_INC_UPD_TGFATT
BEFORE INSERT OR UPDATE ON TGFATT
FOR EACH ROW

DECLARE
  P_COUNT INTEGER;
  
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	IF ((INSERTING OR (UPDATING('CODTIPTITREC'))) AND (:NEW.CODTIPTITREC IS NOT NULL)) THEN
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TGFTIT
	  WHERE CODTIPTIT = :NEW.CODTIPTITREC
	  AND ATIVO = 'N';
	  IF (P_COUNT > 0) THEN 
	    RAISE_APPLICATION_ERROR(-20101, 'Tipo de Título de receita não está ativo. ');
	  END IF;
    END IF;
    
	IF ((INSERTING OR (UPDATING('CODTIPTITDESP'))) AND (:NEW.CODTIPTITDESP IS NOT NULL)) THEN
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TGFTIT
	  WHERE CODTIPTIT = :NEW.CODTIPTITDESP
	  AND ATIVO = 'N';
	  IF (P_COUNT > 0) THEN 
	    RAISE_APPLICATION_ERROR(-20101, 'Tipo de Título de despesa não está ativo. ');
	  END IF;
    END IF;
          
 	RETURN;
END;

/
