-- SANKHYA.TRG_INC_TGFEXC_CONTROLE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFEXC_CONTROLE
"SANKHYA".TRG_INC_TGFEXC_CONTROLE 
BEFORE INSERT ON TGFEXC
FOR EACH ROW

BEGIN
    IF TRIM(:NEW.CONTROLE) IS NULL AND :NEW.CONTROLE <> ' ' THEN
        RAISE_APPLICATION_ERROR(-20101, 'O campo controle não pode ser inserido com mais de um espaço.');
    END IF;
END;

/
