-- SANKHYA.TRG_DLT_TGFVAR_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVAR_AFTER
"SANKHYA".TRG_DLT_TGFVAR_AFTER 
AFTER DELETE ON TGFVAR 

DECLARE
 P_NUNOTAORIG      INT;
 P_SEQUENCIAORIG   SMALLINT;
 P_QTDATENDIDA     FLOAT;
 P_FIXACAO         VARCHAR2(1);
 P_COUNT           INT; 
 CURSOR DELVAR IS SELECT NUNOTAORIG, SEQUENCIAORIG, QTDATENDIDA, FIXACAO FROM TGFVAR_DLT;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  OPEN DELVAR;
  DELETE FROM TGFVAR_DLT;  
  LOOP
    FETCH DELVAR INTO P_NUNOTAORIG, P_SEQUENCIAORIG, P_QTDATENDIDA, P_FIXACAO;
    EXIT WHEN DELVAR%NOTFOUND;
    UPDATE TGFITE SET QTDENTREGUE = (QTDENTREGUE -(CASE WHEN P_FIXACAO = 'S' THEN 0 ELSE P_QTDATENDIDA END))
                    , QTDFIXADA = (NVL(QTDFIXADA, 0) -(CASE  WHEN P_FIXACAO = 'S' THEN P_QTDATENDIDA ELSE 0 END))
    WHERE (NUNOTA = P_NUNOTAORIG)
      AND (SEQUENCIA = P_SEQUENCIAORIG);
  END LOOP;
  CLOSE DELVAR;

END;

/
