-- SANKHYA.TRG_DLT_TFPCAT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPCAT
"SANKHYA".TRG_DLT_TFPCAT BEFORE DELETE ON TFPCAT FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODCATEG = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;

/
