-- SANKHYA.TRG_ATUALIZA_TGWLBO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_ATUALIZA_TGWLBO
TRG_ATUALIZA_TGWLBO
AFTER UPDATE OF SEQUENCIA ON TGWITT
FOR EACH ROW

BEGIN
    UPDATE TGWLBO
    SET SEQTAREFA = :NEW.SEQUENCIA
    WHERE NUTAREFA = :NEW.NUTAREFA
    AND SEQTAREFA = :OLD.SEQUENCIA;
END;

/
