-- SANKHYA.TRG_INC_UPD_TGFRAT_CERTIFIC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFRAT_CERTIFIC
TRG_INC_UPD_TGFRAT_CERTIFIC BEFORE INSERT OR UPDATE ON TGFRAT FOR EACH ROW

DECLARE
  P_OQUE           VARCHAR2(60);
  P_QUEM           VARCHAR2(60);
  P_COM            VARCHAR2(60);
  P_ERRO           VARCHAR2(4);
  P_TIPO           TGFCER.TIPO%TYPE; 
  P_SEQUENCIA      TGFCER.SEQUENCIA%TYPE; 
  P_CHAVE          TGFCER.CHAVE%TYPE; 
  P_CODREGRA       TGFREG.CODREGRA%TYPE; 
  P_INSTPRINC      TGFREG.INSTPRINC%TYPE; 
  P_INSTSEC        TGFREG.INSTSEC%TYPE;
  P_DESCRREGRA     TGFREG.DESCRREGRA%TYPE;
  P_TIPOREGRA      TGFREG.TIPO%TYPE; 
  P_CODINSTPRINC   NUMBER(10,0);
  P_CODINSTSEC     NUMBER(10,0);
  P_COUNT          NUMBER(10,0);
  P_CODUSU         TGFCAB.CODUSU%TYPE;
  P_CODEMP         TGFCAB.CODEMP%TYPE;
  P_CODVEND        TGFCAB.CODVEND%TYPE;
  P_CODPARC        TGFCAB.CODPARC%TYPE;
  P_CODTIPVENDA    TGFCAB.CODTIPVENDA%TYPE;
  P_CODTIPOPER     TGFCAB.CODTIPOPER%TYPE;
  P_LOGICO         CHAR(1);

  CURSOR  curRegras IS 
    SELECT CER.TIPO, CER.CHAVE, CER.CODREGRA, CER.SEQUENCIA, REG.INSTPRINC, REG.INSTSEC, REG.TIPO, REG.DESCRREGRA
    FROM TGFCER CER
    , TGFREG REG
    WHERE ((CER.TIPO = 'U' AND CER.CHAVE = P_CODUSU) OR
        (CER.TIPO = 'V' AND CER.CHAVE = P_CODVEND) OR
        (CER.TIPO = 'E' AND CER.CHAVE = P_CODEMP) OR
        (CER.TIPO = 'G'))
    AND CER.ATIVO = 'S'
    AND CER.CODREGRA = REG.CODREGRA
    AND REG.INSTPRINC NOT IN ('Conta Bancária','Local', 'Produto', 'Grupo de Produto', 'Departamento')  
    AND (REG.INSTSEC IS NULL OR REG.INSTSEC NOT IN ('Conta Bancária','Local', 'Produto', 'Grupo de Produto', 'Departamento'))  
    ORDER BY CER.SEQUENCIA;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  IF :NEW.ORIGEM = 'E' THEN
    SELECT CODPARC, CODEMP, CODUSU, CODVEND, CODTIPOPER, CODTIPVENDA
    INTO P_CODPARC, P_CODEMP, P_CODUSU, P_CODVEND, P_CODTIPOPER, P_CODTIPVENDA
    FROM TGFCAB
    WHERE NUNOTA = :NEW.NUFIN;
  ELSE
    SELECT CODPARC, CODEMP, CODUSU, CODVEND, CASE WHEN DHBAIXA IS NULL THEN CODTIPOPER ELSE CODTIPOPERBAIXA END 
    INTO P_CODPARC, P_CODEMP, P_CODUSU, P_CODVEND, P_CODTIPOPER
    FROM TGFFIN
    WHERE NUFIN = :NEW.NUFIN;
    P_CODTIPVENDA := -1;
  END IF;
  
  P_LOGICO := GET_TSIPAR_LOGICO('CCRATUSUENTBASE');
  IF P_LOGICO = 'N' THEN
    P_CODUSU := :NEW.CODUSU;
  END IF;
  
  OPEN curRegras;
  LOOP
    <<INI_LOOP>>
    FETCH curRegras INTO 
       P_TIPO, P_CHAVE, P_CODREGRA, P_SEQUENCIA, P_INSTPRINC, P_INSTSEC, P_TIPOREGRA, P_DESCRREGRA;
    EXIT WHEN curRegras%NOTFOUND;
  
    IF P_INSTPRINC = 'Centro de Resultado' THEN
      P_CODINSTPRINC := :NEW.CODCENCUS; 
    ELSIF P_INSTPRINC = 'Natureza' THEN
      P_CODINSTPRINC := :NEW.CODNAT; 
    ELSIF P_INSTPRINC = 'Projeto' THEN
      P_CODINSTPRINC := :NEW.CODPROJ; 
    ELSIF P_INSTPRINC = 'TOP' THEN
      P_CODINSTPRINC := P_CODTIPOPER;
    ELSIF P_INSTPRINC = 'Tipo de Negociação' THEN
		IF P_CODTIPVENDA = -1 THEN 
			GOTO INI_LOOP;
		END IF;
      P_CODINSTPRINC := P_CODTIPVENDA;
    ELSIF P_INSTPRINC = 'Parceiro' THEN
      P_CODINSTPRINC := P_CODPARC;
    ELSIF P_INSTPRINC = 'Empresa' THEN
      P_CODINSTPRINC := P_CODEMP;
    ELSE
      CLOSE curRegras;
      RAISE_APPLICATION_ERROR(-20101, 'Instrução principal "'|| P_INSTPRINC ||'" da regra "' || P_DESCRREGRA || '" não definida.');
    END IF;

    IF P_INSTSEC = 'Centro de Resultado' THEN
      P_CODINSTSEC := :NEW.CODCENCUS;
    ELSIF P_INSTSEC = 'Natureza' THEN
      P_CODINSTSEC := :NEW.CODNAT;
    ELSIF P_INSTSEC = 'Projeto' THEN
      P_CODINSTSEC := :NEW.CODPROJ;
    ELSIF P_INSTSEC = 'TOP' THEN
      P_CODINSTSEC := P_CODTIPOPER;
    ELSIF P_INSTSEC = 'Tipo de Negociação' THEN
		IF P_CODTIPVENDA = -1 THEN 
			 GOTO INI_LOOP;
		END IF;
      P_CODINSTSEC := P_CODTIPVENDA;
    ELSIF P_INSTSEC = 'Parceiro' THEN
      P_CODINSTSEC := P_CODPARC;
    ELSIF P_INSTSEC = 'Empresa' THEN
      P_CODINSTSEC := P_CODEMP;
    ELSIF P_INSTSEC IS NOT NULL AND P_INSTSEC <> '' THEN
      CLOSE curRegras;
      RAISE_APPLICATION_ERROR(-20101, 'Instrução secundária "'|| P_INSTSEC ||'" da regra "' || P_DESCRREGRA || '" não definida.');
    ELSE
      P_CODINSTSEC := 0;  
    END IF;
    
    IF TRIM(P_INSTSEC) IS NULL THEN -- Apenas uma dimensão
      SELECT COUNT(*)
      INTO P_COUNT
      FROM TGFITR ITR
      WHERE ITR.CODREGRA = P_CODREGRA
      AND ITR.CODINSTPRINC <= P_CODINSTPRINC
      AND NVL(ITR.CODINSTPRINCFIN, ITR.CODINSTPRINC) >= P_CODINSTPRINC
      AND ITR.ATIVO = 'S';
    ELSE
      SELECT COUNT(*)
      INTO P_COUNT
      FROM TGFITR ITR
      WHERE ITR.CODREGRA = P_CODREGRA
      AND ITR.CODINSTPRINC <= P_CODINSTPRINC
      AND NVL(ITR.CODINSTPRINCFIN, ITR.CODINSTPRINC) >= P_CODINSTPRINC
      AND ITR.CODINSTSECINI <= P_CODINSTSEC  
      AND ITR.CODINSTSECFIN >= P_CODINSTSEC  
      AND ITR.ATIVO = 'S';
    END IF;
    P_ERRO := '';
    IF P_TIPOREGRA = 'R' THEN
      IF P_COUNT > 0 THEN
        P_ERRO := 'ERRO';
      END IF;
    ELSE
      IF P_COUNT = 0 THEN
        P_ERRO := 'ERRO';
      END IF;
    END IF;
    IF P_ERRO = 'ERRO' THEN
      CLOSE curRegras;
      Stp_Msg_Certific_Tipo(P_TIPO, P_CHAVE, P_QUEM);
      Stp_Msg_Certific_Codinst(P_INSTPRINC, P_CODINSTPRINC, P_OQUE);
      IF TRIM(P_INSTSEC) IS NULL THEN
          RAISE_APPLICATION_ERROR(-20101, P_QUEM ||' não pode usar "'|| P_OQUE ||'" da regra "'||P_DESCRREGRA||'"\'||P_SEQUENCIA||'.');
      ELSE
        Stp_Msg_Certific_Codinst(P_INSTSEC, P_CODINSTSEC, P_COM);
          RAISE_APPLICATION_ERROR(-20101, P_QUEM ||' não pode usar "'|| P_OQUE ||'" com "'|| P_COM ||'" da regra "'||P_DESCRREGRA||'"\'||P_SEQUENCIA||'.');
      END IF;   
    END IF;
  END LOOP;
  CLOSE curRegras;
END;

/
