-- SANKHYA.TRG_INC_TGWUXT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGWUXT
"SANKHYA".TRG_INC_TGWUXT 
BEFORE INSERT ON TGWUXT 
FOR EACH ROW

DECLARE V_SITTAREFA CHAR(1);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  BEGIN
    SELECT TAR.SITUACAO
      INTO V_SITTAREFA
    FROM TGWTAR TAR
    WHERE TAR.NUTAREFA = :NEW.NUTAREFA;
   EXCEPTION WHEN NO_DATA_FOUND THEN
     V_SITTAREFA := 'A';
   END;
   :NEW.SITTAREFA := V_SITTAREFA;
END;

/
