-- SANKHYA.TRG_DLT_TGFNUM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFNUM
"SANKHYA".TRG_DLT_TGFNUM
BEFORE DELETE ON TGFNUM
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  IF :OLD.CODMODDOC = 55 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Modelo 55 não pode ser excluido.');
  END IF;
  
  SELECT COUNT(1)
  INTO P_COUNT    
  FROM V$SESSION V
  WHERE ((UPPER(V.PROGRAM) LIKE '%TOAD%') OR (UPPER(V.PROGRAM) LIKE '%SQL%'))       
    AND V.AUDSID = USERENV('SESSIONID')
    AND STATUS = 'ACTIVE';  
  IF P_COUNT > 0 THEN
   RAISE_APPLICATION_ERROR(-20101,'Não é permitido deletar linhas da TGFNUM por esse software.');
  END IF;
END;

/
