-- SANKHYA.TRG_INC_UPD_TGFICNF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFICNF
"SANKHYA".TRG_INC_UPD_TGFICNF
BEFORE INSERT OR UPDATE ON TGFICNF
FOR EACH ROW

DECLARE
	 P_COUNT  NUMBER(10);
	 P_COUNT2 NUMBER(10);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
	 SELECT COUNT(1) INTO P_COUNT
	 FROM TGFCAB
	 WHERE NUNOTA = :NEW.NUNOTA;

	 SELECT COUNT(1) INTO P_COUNT2
	 FROM TGFCAB_EXC
	 WHERE NUNOTA = :NEW.NUNOTA;
	 	 
	 IF (P_COUNT = 0) AND (P_COUNT2 = 0) THEN
	 	RAISE_APPLICATION_ERROR(-20101,'Não é possível incluir o registro, pois não existe referência para a nota.');
	 END IF;
	 RETURN;
END;

/
