-- SANKHYA.TRG_INC_TGMAIB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGMAIB
"SANKHYA".TRG_INC_TGMAIB AFTER INSERT ON TGMAIB FOR EACH ROW

DECLARE 
P_COUNT  NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGMAI
  WHERE NUAUTINV = :NEW.NUAUTINV;
  
  IF P_COUNT > 0 THEN
    UPDATE TGMAI SET BLOQUEADO = 'S' 
    WHERE NUAUTINV = :NEW.NUAUTINV;
  END IF;
END;

/
