-- SANKHYA.TRG_DLT_TGFITE_TRANSG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_TRANSG
"SANKHYA".TRG_DLT_TGFITE_TRANSG 
AFTER DELETE ON TGFITE 
FOR EACH ROW

DECLARE
P_COUNT     NUMBER(05);
BEGIN

  -- VERIFICANDO SE O CLIENTE UTILIZA ESTA FUNCIONALIDADE
  SELECT COUNT(*) INTO P_COUNT
  FROM TSIVARBD
  WHERE UTILIZA_TRANSG = 'N';
  IF P_COUNT > 0 THEN 
    RETURN;
  END IF;

  DELETE FROM TGAGTM WHERE NUNOTA = :OLD.NUNOTA AND SEQUENCIA = :OLD.SEQUENCIA;
END;

/
