-- SANKHYA.TRG_DLT_TPQQUE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TPQQUE
"SANKHYA".TRG_DLT_TPQQUE BEFORE DELETE ON TPQQUE
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODQUEST = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;   


/
