-- SANKHYA.TRG_INC_TC_HITS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TC_HITS
"SANKHYA".TRG_INC_TC_HITS
BEFORE INSERT ON TC_HITS
FOR EACH ROW

DECLARE
 BEGIN
       SELECT SEQ_TC_HITS_IDLINHA.NEXTVAL INTO :NEW.IDLINHA FROM DUAL;
  END;

/
