-- SANKHYA.TRG_DLT_TFPHOR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPHOR
"SANKHYA".TRG_DLT_TFPHOR BEFORE DELETE ON TFPHOR FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODCARGAHOR = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
