-- SANKHYA.TRG_INC_TGFPPG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFPPG
"SANKHYA".TRG_INC_TGFPPG
BEFORE INSERT ON TGFPPG FOR EACH ROW

DECLARE
    P_COUNT          INT:= 0;
    ERRMSG            VARCHAR2(500);
    ERROR             EXCEPTION;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
   
  IF (:NEW.CODEMP IS NOT NULL) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFEMP
    WHERE CODEMP = :NEW.CODEMP
    AND ATIVO = 'S';
    IF  (P_COUNT = 0) THEN
    ERRMSG := 'Empresa '||:NEW.CODEMP||' não está ativa. ';
      RAISE ERROR;
    END IF;
  END IF;
    
  IF (:NEW.CODTIPTITPAD IS NOT NULL) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFTIT
    WHERE CODTIPTIT = :NEW.CODTIPTITPAD
    AND ATIVO = 'S';
    IF  (P_COUNT = 0) THEN
    ERRMSG := 'Tipo de Título '||:NEW.CODTIPTITPAD||' não está ativo. ';
    RAISE ERROR;
    END IF;
  END IF;      

  IF (:NEW.CODPROJPAD IS NOT NULL) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TCSPRJ
    WHERE CODPROJ = :NEW.CODPROJPAD
    AND ATIVO = 'S'
    AND ANALITICO = 'S';
    IF  (P_COUNT = 0) THEN
      ERRMSG := 'Projeto '||:NEW.CODPROJPAD||' não está ativo ou não é analítico. ';
      RAISE ERROR;
    END IF;
  END IF;
  
  IF (:NEW.CODNATPAD IS NOT NULL) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFNAT
    WHERE CODNAT = :NEW.CODNATPAD
    AND ATIVA = 'S'
    AND ANALITICA = 'S';
    IF (P_COUNT = 0) THEN
      ERRMSG := 'Natureza '||:NEW.CODNATPAD||' não está ativo ou não é analítico. ';
      RAISE ERROR;
    END IF;  
  END IF;
  
  IF (:NEW.CODCENCUSPAD IS NOT NULL) THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TSICUS
    WHERE CODCENCUS = :NEW.CODCENCUSPAD
      AND ATIVO = 'S'
      AND ANALITICO = 'S';
    IF  (P_COUNT = 0) THEN
      ERRMSG := 'Centro de Resultado '||:NEW.CODCENCUSPAD||' não está ativo ou não é analítico. ';
      RAISE ERROR;
    END IF;  
  END IF;
  
  IF (:NEW.CODPARC IS NOT NULL) THEN
    SELECT COUNT(1) INTO  P_COUNT
    FROM TGFPAR
    WHERE CODPARC = :NEW.CODPARC
    AND ATIVO = 'S';
      IF  (P_COUNT = 0) THEN
      ERRMSG := 'Parceiro '||:NEW.CODPARC||' não esta ativo.';
      RAISE ERROR;
      END IF;
  END IF;  
      
  RETURN;
   
EXCEPTION
  WHEN ERROR THEN
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
