-- SANKHYA.TRG_DLT_TRICPPR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRICPPR
"SANKHYA".TRG_DLT_TRICPPR
BEFORE DELETE ON TRICPPR
FOR EACH ROW

BEGIN
    DELETE TRITPCO
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;
END;

/
