-- SANKHYA.TRG_DLT_TFXBPA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFXBPA
"SANKHYA".TRG_DLT_TFXBPA
BEFORE DELETE
   ON TFXBPA
   FOR EACH ROW

BEGIN
	INSERT INTO TFXADE (NOMETAB, STRPK) 
	VALUES('TBANDEIRAPARCEIRO', 'ID = '||:OLD.ID);
END;

/
