-- SANKHYA.TRG_INC_TGWESTVAL_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGWESTVAL_AFTER
"SANKHYA".TRG_INC_TGWESTVAL_AFTER 
AFTER INSERT ON TGWESTVAL 
FOR EACH ROW

DECLARE
--Pragma Autonomous_Transaction;
P_MINDTVAL DATE;

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
	BEGIN 
		SELECT MIN(EST.DTVAL)
	      INTO P_MINDTVAL
		  FROM TGWEST EST 
		 WHERE EST.CODEND = :NEW.CODEND
	       AND EST.CODPROD = :NEW.CODPROD 
	       AND EST.CONTROLE = :NEW.CONTROLE 
	       AND EST.CODEMP = :NEW.CODEMP
	       	;
	EXCEPTION
	   WHEN NO_DATA_FOUND THEN
			P_MINDTVAL := NULL;
	END;
	
	IF (P_MINDTVAL <> NULL) THEN
		IF(P_MINDTVAL > :NEW.DTVAL) THEN
			UPDATE TGWEST EST SET EST.DTVAL = :NEW.DTVAL 
			 WHERE EST.CODEND = :NEW.CODEND
			   AND EST.CODPROD = :NEW.CODPROD 
			   AND EST.CONTROLE = :NEW.CONTROLE 
			   AND EST.CODEMP = :NEW.CODEMP
			   AND EST.CODPARC = :NEW.CODPARC;
			   --COMMIT;
		END IF;
	ELSE
		/*BEGIN 
			SELECT MIN(ESTV.DTVAL)
			  INTO P_MINDTVAL
			  FROM TGWESTVAL ESTV 
			 WHERE ESTV.CODEND = :NEW.CODEND
			   AND ESTV.CODPROD = :NEW.CODPROD 
			   AND ESTV.CONTROLE = :NEW.CONTROLE 
			   AND ESTV.CODEMP = :NEW.CODEMP;
		EXCEPTION
		   WHEN NO_DATA_FOUND THEN
				P_MINDTVAL := NULL;
		END;*/
		
		IF (P_MINDTVAL = NULL OR P_MINDTVAL > :NEW.DTVAL) THEN
			UPDATE TGWEST EST SET EST.DTVAL = :NEW.DTVAL 
			 WHERE EST.CODEND = :NEW.CODEND
			   AND EST.CODPROD = :NEW.CODPROD 
			   AND EST.CONTROLE = :NEW.CONTROLE 
			   AND EST.CODEMP = :NEW.CODEMP
			   AND EST.CODPARC = :NEW.CODPARC;
			   --COMMIT;
		END IF;
	END IF;
END;

/
