-- SANKHYA.TRG_DLT_TCISAL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCISAL
"SANKHYA".TRG_DLT_TCISAL
BEFORE DELETE ON TCISAL
FOR EACH ROW

DECLARE 
	P_COUNT				NUMBER(5);
BEGIN
	SELECT COUNT(1) 
	INTO P_COUNT
	FROM TCISAL_ATUAL
	WHERE CODPROD = :OLD.CODPROD
		AND CODBEM = :OLD.CODBEM
		AND REFERENCIA = :OLD.REFERENCIA;

	IF P_COUNT > 0 THEN
        UPDATE TCISAL_ATUAL
        SET DELETADO = 'S'
        WHERE CODPROD = :OLD.CODPROD
            AND CODBEM = :OLD.CODBEM
            AND REFERENCIA = :OLD.REFERENCIA;
    END IF;
END;

/
