-- SANKHYA.TRG_INC_UPD_TCSNTS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSNTS
"SANKHYA".TRG_INC_UPD_TCSNTS 
BEFORE INSERT OR UPDATE ON TCSNTS
FOR EACH ROW

DECLARE
  P_COUNT                INT:= 0;
  ERROR                  EXCEPTION;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODNAT') THEN
    SELECT COUNT(1) 
      INTO P_COUNT 
    FROM TGFNAT N 
    WHERE :NEW.CODNAT = N.CODNAT 
      AND N.ATIVA = 'S' 
      AND N.ANALITICA = 'S';
      
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101,'Natureza não esta ativa ou não esta cadastrada.');
    END IF;
    
  END IF;
  
  IF UPDATING('CODSERV') THEN
    SELECT COUNT(1) 
      INTO P_COUNT 
    FROM TGFPRO P 
    WHERE :NEW.CODSERV = P.CODPROD 
    AND P.ATIVO = 'S';
    
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101,'Produto não esta ativo ou não esta cadastrado.');
    END IF;
  END IF;
END;

/
