-- SANKHYA.TRG_DLT_TRIRRC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIRRC
"SANKHYA".TRG_DLT_TRIRRC 
AFTER DELETE  ON TRIRRC  
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRINRRC T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
    AND :OLD.CODPARC = T.CODPARC;

	IF P_COUNT > 0 THEN
		DELETE FROM TRINRRC
		WHERE :OLD.CODEMP = TRINRRC.CODEMP 
		  AND :OLD.DTREF = TRINRRC.DTREF 
		  AND :OLD.TPAMB = TRINRRC.TPAMB 
		  AND :OLD.SEQUENCIA = TRINRRC.SEQUENCIA 
		  AND :OLD.CHAVE = TRINRRC.CHAVE
      AND :OLD.CODPARC = TRINRRC.CODPARC;
	END IF;
END;		

/
