-- SANKHYA.TRG_INC_TGFSTA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFSTA
"SANKHYA".TRG_INC_TGFSTA 
BEFORE INSERT ON TGFSTA FOR EACH ROW

DECLARE
    P_DESCROPER     TGFTOP.DESCROPER%TYPE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :NEW.DESCROPER IS NULL THEN 
    SELECT T.DESCROPER
      INTO P_DESCROPER
      FROM TGFCAB C, TGFTOP T
     WHERE C.NUNOTA = :NEW.NUNOTA
       AND C.CODTIPOPER = T.CODTIPOPER
       AND C.DHTIPOPER = T.DHALTER;
  
    :NEW.DESCROPER := P_DESCROPER;
  END IF; 
END;

/
