-- SANKHYA.TRG_INC_AUDITTFPFER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_AUDITTFPFER
"SANKHYA".TRG_INC_AUDITTFPFER 
BEFORE INSERT ON AUDITTFPFER
FOR EACH ROW

BEGIN
  SELECT AUDITTFPFER_SEQ.NEXTVAL
  INTO   :new.ID
  FROM   DUAL;
END;

/
