-- SANKHYA.TRG_INC_UPD_TGFPRO_TGFREA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPRO_TGFREA
"SANKHYA".TRG_INC_UPD_TGFPRO_TGFREA 
BEFORE INSERT OR UPDATE ON TGFPRO 
FOR EACH ROW

DECLARE 
	P_COUNT		NUMBER(10);
	
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	IF :NEW.NUMITEMREA IS NOT NULL THEN
		SELECT COUNT(1) INTO P_COUNT
		  FROM TGFREA
		 WHERE NUMITEMREA = :NEW.NUMITEMREA;

		IF ((P_COUNT =  0) OR (P_COUNT IS NULL)) THEN
			RAISE_APPLICATION_ERROR(-20101,'Não existe referência para esse registro.');
		END IF;
	END IF;	
END;

/
