-- SANKHYA.TRG_FX_TGFEMP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFEMP
TRG_FX_TGFEMP
		  BEFORE INSERT OR UPDATE
		  ON TGFEMP
		  FOR EACH ROW
		
DECLARE
		  P_CONTADOR	 NUMBER (19);
		  P_VALIDAR    	 BOOLEAN;
		  P_TEM_CHECKOUT BOOLEAN;
		BEGIN
		  IF Stp_Get_Atualizando
		  THEN
			 RETURN;
		  END IF;

		  /*
			Sincronização de dados
		  */
		  P_VALIDAR := Fpodevalidar ('TGFEMP');

		  IF (NOT P_VALIDAR)
		  THEN
			 RETURN;
		  END IF;
		  
		  P_TEM_CHECKOUT := FCheckout_Utiliza;
			
		  IF (NOT P_TEM_CHECKOUT) THEN
			  RETURN;
		  END IF;

		  IF (   (NVL (:NEW.TOKENNFCE, '') <> NVL (:OLD.TOKENNFCE, ''))
			  OR (NVL (:NEW.SEQTOKENNFCE, '') <> NVL (:OLD.SEQTOKENNFCE, ''))
			  OR (NVL (:NEW.NUNOTAMODFX, '') <> NVL (:OLD.NUNOTAMODFX, ''))
			  OR (NVL (:NEW.NUNOTADEMFX, '') <> NVL (:OLD.NUNOTADEMFX, ''))
			  OR (NVL (:NEW.NUNOTATRCFX, '') <> NVL (:OLD.NUNOTATRCFX, ''))
			  OR (NVL (:NEW.CHAVEPIXCHECKOUT, ' ') <> NVL (:OLD.CHAVEPIXCHECKOUT, ' '))
			  OR (NVL (:NEW.BANCOPIXCHECKOUT, '') <> NVL (:OLD.BANCOPIXCHECKOUT, ''))
			  OR (NVL (:NEW.APIKEYPIXCHECKOUT, ' ') <> NVL (:OLD.APIKEYPIXCHECKOUT, ' '))
			  OR (NVL (:NEW.CLIENTSECRETPIXCHECKOUT, ' ') <> NVL (:OLD.CLIENTSECRETPIXCHECKOUT, ' '))
			  OR (NVL (:NEW.CLIENTIDPIXCHECKOUT, ' ') <> NVL (:OLD.CLIENTIDPIXCHECKOUT, ' '))
			  OR (NVL (:NEW.URLPIXCHECKOUT, ' ') <> NVL (:OLD.URLPIXCHECKOUT, ' '))
			  OR (NVL (:NEW.CERTIFICADOPIX, ' ') <> NVL (:OLD.CERTIFICADOPIX, ' '))
			  OR (NVL (:NEW.TIPOIMPKITFOX, ' ') <> NVL (:OLD.TIPOIMPKITFOX, ' '))
			  OR (NVL (:NEW.CNPJCTAPIX, ' ') <> NVL (:OLD.CNPJCTAPIX, ' ')))
		  THEN
			 SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

			 :NEW.NUVERSAO := P_CONTADOR;
		  END IF;
		END;

/
