-- SANKHYA.TRG_DLT_TRINRRC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRINRRC
"SANKHYA".TRG_DLT_TRINRRC 
AFTER DELETE  ON TRINRRC  
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRR T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
    AND :OLD.NATREND = T.NATREND
    AND :OLD.CODPARC = T.CODPARC;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRR
		WHERE :OLD.CODEMP = TRIDRR.CODEMP 
		  AND :OLD.DTREF = TRIDRR.DTREF 
		  AND :OLD.TPAMB = TRIDRR.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRR.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRR.CHAVE
      AND :OLD.NATREND = TRIDRR.NATREND
      AND :OLD.CODPARC = TRIDRR.CODPARC;
	END IF;
END;		

/
