-- SANKHYA.TRG_DLT_TGFORD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFORD
"SANKHYA".TRG_DLT_TGFORD
BEFORE DELETE ON TGFORD
FOR EACH ROW

DECLARE
  P_COUNT     NUMBER(5); 
  
  PRAGMA AUTONOMOUS_TRANSACTION;
  
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGFCAB CAB
       INNER JOIN TGFEMP EMP ON EMP.CODEMP = CAB.CODEMP
  WHERE CAB.ORDEMCARGA = :OLD.ORDEMCARGA
    AND (CASE WHEN NVL(EMP.CODEMPOC, 0) <> 0 THEN EMP.CODEMPOC 
              ELSE EMP.CODEMP END) = :OLD.CODEMP;  
  
  
  IF P_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(-20101,'Ordem de carga não pode ser deletada, pois existem notas relacionadas a ela.');
  END IF;
END;

/
