-- SANKHYA.TRG_DLT_TCSEQP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSEQP
"SANKHYA".TRG_DLT_TCSEQP
BEFORE DELETE ON TCSEQP
FOR EACH ROW

DECLARE
  P_COUNT INT:= 0;
  P_NUAPONT TGAAHI.NUAPONT%TYPE;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT NVL(COUNT(1),0)
    INTO P_COUNT
    FROM TGAAHI
   WHERE NUEQUIPE = :OLD.NUEQUIPE;
  IF (P_COUNT <> 0) THEN
    SELECT MAX(NUAPONT)
      INTO P_NUAPONT
      FROM TGAAHI
    WHERE NUEQUIPE = :OLD.NUEQUIPE;
    RAISE_APPLICATION_ERROR (-20101,'Equipe não pode ser excluída,  existe um apontamento de nro. ' || TO_CHAR(P_NUAPONT, '999999999'));
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TCSMEQ
  WHERE NUEQUIPE = :OLD.NUEQUIPE;
  
  IF P_COUNT > 0 THEN
    DELETE
      FROM TCSMEQ
     WHERE NUEQUIPE = :OLD.NUEQUIPE;
  END IF;
  
END;

/
