-- SANKHYA.TRG_INC_TGFRUP_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFRUP_SEQ
"SANKHYA".TRG_INC_TGFRUP_SEQ
BEFORE INSERT
ON TGFRUP
FOR EACH ROW

DECLARE
    P_NURUP TGFRUP.NURUP%TYPE;
BEGIN
    STP_KEYGEN_TGFNUM ('TGFRUP', 1, 'TGFRUP', 'NURUP', 0, P_NURUP);
    
    :NEW.NURUP := P_NURUP;
END;

/
