-- SANKHYA.TRG_INC_UPD_TGFCUS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCUS
"SANKHYA".TRG_INC_UPD_TGFCUS 
BEFORE INSERT OR UPDATE ON TGFCUS
FOR EACH ROW

BEGIN
    
  IF (VARIAVEIS_PKG.V_PROCESSO_ATUAL_CUSTO IS NOT NULL) THEN
    :NEW.PROCESSO := VARIAVEIS_PKG.V_PROCESSO_ATUAL_CUSTO;
  END IF;
  
END;

/
