-- SANKHYA.TRG_DLT_TGFVEN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVEN
"SANKHYA".TRG_DLT_TGFVEN BEFORE DELETE ON TGFVEN FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  EXISTSRESTRICAO('TGFVEN',:OLD.CODVEND);

  IF (:OLD.CODVEND = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
