-- SANKHYA.TRG_INC_UPD_TCSPSS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSPSS
"SANKHYA".TRG_INC_UPD_TCSPSS BEFORE INSERT OR UPDATE ON TCSPSS FOR EACH ROW

DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
  P_NUMCONTRATO INTEGER;
  P_COUNT INTEGER;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT MAX(NUMCONTRATO), COUNT(1) INTO P_NUMCONTRATO, P_COUNT 
  FROM TCSPSS
  WHERE NUMCONTRATO <> :NEW.NUMCONTRATO
  AND CODPROD = :NEW.CODPROD
  AND SERIE = :NEW.SERIE
  AND ATIVO = 'S';
  
  IF P_COUNT > 0 THEN
  	RAISE_APPLICATION_ERROR(-20101, 'Esta série já está lançada no contrato ' || P_NUMCONTRATO || '.');
  END IF;
END;

/
