-- SANKHYA.TRG_INC_UPD_TGWCTE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGWCTE
"SANKHYA".TRG_INC_UPD_TGWCTE
BEFORE INSERT OR UPDATE ON TGWCTE
FOR EACH ROW

DECLARE
  P_COUNT          INT:= 0;
  P_CODLOCAL 	   TGWCTE.CODLOCAL%TYPE;
  P_CONTROLE	   TGWCTE.CONTROLE%TYPE;
  P_CODVOL         TGFPRO.CODVOL%TYPE;
  P_ESTOQUEVOLPAD  TGWCTE.ESTOQUE%TYPE;
  P_TAREFAPENDENTE INT := 0;
  P_PICKING        TGWEND.PICKING%TYPE;
  P_ESTOQUE        TGWEST.ESTOQUE%TYPE;
  P_VOLUME         TGWEXP.CODVOL%TYPE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:NEW.EFETIVAEST = 'N') THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_TAREFAPENDENTE
  FROM TGWITT
  WHERE (CODENDORIGEM = :NEW.CODEND OR
         CODENDDESTINO = :NEW.CODEND)
  AND SITUACAO NOT IN ('F', 'C');

  IF (P_TAREFAPENDENTE <> 0) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Existem tarefas pendentes para o endereço ('|| :NEW.CODEND ||').');
  END IF;

  IF (:NEW.ATUALESTOQUE = 1) AND (:NEW.ESTOQUE = 0) THEN
    DELETE FROM TGWEST
    WHERE CODEND = :NEW.CODEND;
    RETURN;
  END IF;

  P_CODLOCAL := 0;
  P_CONTROLE := CASE WHEN :NEW.CONTROLE IS NULL THEN ' ' ELSE :NEW.CONTROLE END;
  SELECT COUNT(1)
  INTO P_COUNT
  FROM TGWEND
  WHERE CODEND = :NEW.CODEND
  AND EXPEDICAO = 'N';

  IF (P_COUNT <> 0) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Endereços temporarios não podem ser contados.');
  END IF;

  IF (:NEW.ATUALESTOQUE = 1) AND  ((:NEW.ATUALESTOQUE <> :OLD.ATUALESTOQUE) OR (:NEW.ESTOQUE <> :OLD.ESTOQUE)) THEN
    SELECT NVL(COUNT(1),0)
    INTO P_COUNT
    FROM TGWEST
    WHERE CODEND = :NEW.CODEND
    AND CODPROD = :NEW.CODPROD;

    SELECT PICKING
    INTO P_PICKING
    FROM TGWEND
    WHERE CODEND = :NEW.CODEND;

    P_ESTOQUEVOLPAD := Volumealt(:NEW.CODPROD, :NEW.ESTOQUE, :NEW.CODVOL, P_CONTROLE);

	IF (P_PICKING = 'S') THEN
          BEGIN
            SELECT CODVOL 
    	      INTO P_VOLUME
	      FROM TGWEXP
             WHERE CODEND = :NEW.CODEND AND
                   CODPROD = :NEW.CODPROD;
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
              SELECT CODVOL  
    	        INTO P_VOLUME
	            FROM TGFPRO
               WHERE CODPROD = :NEW.CODPROD;          
          END;

      IF P_VOLUME = :NEW.CODVOL THEN
         P_ESTOQUE := :NEW.ESTOQUE;
      ELSE
         P_ESTOQUE := Volumealt(:NEW.CODPROD, P_ESTOQUEVOLPAD, P_VOLUME, P_CONTROLE);
      END IF;
    ELSE
      P_VOLUME := :NEW.CODVOL;
      P_ESTOQUE := :NEW.ESTOQUE;
    END IF;

    IF (P_COUNT = 0) THEN
      INSERT INTO TGWEST
            (CODEMP, CODPROD, CONTROLE, CODPARC, CODLOCAL,
             CODEND, CODVOL, ESTOQUE, ESTOQUEVOLPAD, DTVAL)
      VALUES
            (:NEW.CODEMP, :NEW.CODPROD, P_CONTROLE, :NEW.CODPARC, P_CODLOCAL,
             :NEW.CODEND, P_VOLUME, P_ESTOQUE, P_ESTOQUEVOLPAD, :NEW.DTVAL);
    ELSIF (P_COUNT = 1) THEN
      UPDATE TGWEST SET
        ESTOQUE = P_ESTOQUE
      , ESTOQUEVOLPAD = P_ESTOQUEVOLPAD
      , DTVAL = :NEW.DTVAL
      , CODEMP = :NEW.CODEMP
      , CODPROD = :NEW.CODPROD
      , CONTROLE = P_CONTROLE
      , CODPARC = :NEW.CODPARC
      , CODLOCAL = P_CODLOCAL
      , CODVOL = P_VOLUME
      WHERE CODEND = :NEW.CODEND
      AND CODPROD = :NEW.CODPROD;
    ELSE
      RAISE_APPLICATION_ERROR(-20101, 'Endereço com expedição ('|| :NEW.CODEND ||') com mais de um volume ou produto definido.');
    END IF;
  END IF;
END;

/
