-- SANKHYA.TRG_DLT_TSIBCO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIBCO
"SANKHYA".TRG_DLT_TSIBCO BEFORE DELETE ON TSIBCO FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODBCO = 0) THEN
     raise_application_error(-20101, 'Registro padr?o do sistema. N?o pode ser excluido.');
  END IF;
END;

/
