-- SANKHYA.TRG_INC_UPD_TCBCOM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCBCOM
"SANKHYA".TRG_INC_UPD_TCBCOM BEFORE INSERT OR UPDATE ON TCBCOM FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
    ERROR                  EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
IF UPDATING('CODCTACTB') THEN
   SELECT COUNT(1) INTO P_COUNT FROM TCBPLA
   WHERE CODCTACTB = :NEW.CODCTACTB AND ATIVA = 'S';
   IF (P_COUNT = 0 ) THEN
       RAISE_APPLICATION_ERROR (-20101, 'Conta nao Ativa ou nao Cadastrada');
   END IF;
END IF;
END;

/
