-- SANKHYA.TRG_INC_TJCAPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TJCAPJ
"SANKHYA".TRG_INC_TJCAPJ 
BEFORE INSERT ON TJCAPJ 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFPAR
  WHERE CODPARC = NVL(:NEW.CODPARC, 0)
    AND ATIVO = 'S';
  IF  (P_COUNT = 0) THEN
     Stp_Popula_Msg('TGFPAR');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFCTT
  WHERE CODPARC = :NEW.CODPARC
  AND CODCONTATO = :NEW.CODCONTATO
  AND ATIVO = 'S';
  IF (P_COUNT = 0) THEN
     Stp_Popula_Msg('TGFCTT');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFVEN
  WHERE CODVEND = NVL(:NEW.CODVEND, 0)
    AND ATIVO = 'S';
  IF (P_COUNT = 0) THEN
       Stp_Popula_Msg('TGFVEN');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFNAT
  WHERE CODNAT = NVL(:NEW.CODNAT, 0)
  AND ATIVA = 'S'
  AND ANALITICA = 'S';
  IF (P_COUNT = 0 )THEN
      Stp_Popula_Msg('TGFNAT');
  END IF;
  IF (:NEW.PENDENTE = 'N') AND (:NEW.DTVENDA <> NULL) THEN
      Stp_Inclusao_Tjcapj(:NEW.DTVENDA, :NEW.CODNAT, :NEW.ACRESCIMOCOR, :NEW.PRECOTABELA, :NEW.VLRDESC, :NEW.VLRCOMAGENCIA);
  END IF;
END;

/
