-- SANKHYA.TRG_INC_UPD_TGFCAN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCAN
"SANKHYA".TRG_INC_UPD_TGFCAN 
BEFORE INSERT OR UPDATE ON TGFCAN 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    P_SOLICITANTE          VARCHAR2(30);
    P_COUNT                INT:= 0;
    ERROR                  EXCEPTION;
    P_VALIDAR              BOOLEAN;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  P_VALIDAR := Fpodevalidar('TGFCAN');
  IF (NOT P_VALIDAR) THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO  P_COUNT
  FROM TGFEMP E
  WHERE E.CODEMP = NVL(:NEW.CODEMP, 1)
    AND E.ATIVO = 'S';
  IF UPDATING('CODEMP') AND (P_COUNT = 0) THEN
      Stp_Popula_Msg('TGFEMP');
  END IF;
END;

/
