-- SANKHYA.TRG_INC_UPD_DLT_TGFMOVSS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFMOVSS
"SANKHYA".TRG_INC_UPD_DLT_TGFMOVSS
BEFORE INSERT OR UPDATE OR DELETE
ON TGFMOVSS FOR EACH ROW

DECLARE
  P_VALIDAR   BOOLEAN;  
  P_COUNT     INT;  
  ERROR       EXCEPTION;
  ERRMSG      VARCHAR2(255);
  P_CODUSU    TSIUSU.CODUSU%TYPE;
  
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  --sincronizacão de dados
  P_VALIDAR := Fpodevalidar('TGFMOVSS');  
  --Sincronizacão de dados não faz validacães
  IF NOT P_VALIDAR THEN
    RETURN;
  END IF;

  IF DELETING THEN
    P_CODUSU := STP_GET_CODUSULOGADO;
  ELSE
    P_CODUSU := :NEW.CODUSU;
  END IF;
  
  IF (UPDATING OR DELETING) AND :OLD.VLRMOVIMENTO <> 0 THEN
    SELECT COUNT(1)
    INTO P_COUNT
    FROM TGFSALSS
    WHERE CNPJ = :OLD.CNPJ;
    IF UPDATING AND P_COUNT = 0 THEN
      ERRMSG := 'Não encontrado registro de saldo para o CNPJ '||:OLD.CNPJ||' na tabela TGFSALSS.';
      RAISE ERROR;
    END IF;

    IF P_COUNT > 0 THEN
      UPDATE TGFSALSS 
      SET VLRTOTALCREDITO = CASE WHEN :OLD.SINAL > 0 THEN VLRTOTALCREDITO  - ABS(:OLD.VLRMOVIMENTO) ELSE VLRTOTALCREDITO  END 
      , VLRCREDITOUTILIZ  = CASE WHEN :OLD.SINAL < 0 THEN VLRCREDITOUTILIZ - ABS(:OLD.VLRMOVIMENTO) ELSE VLRCREDITOUTILIZ END
      , CODUSU = P_CODUSU
      , DHALTER = SYSDATE
      WHERE CNPJ = :OLD.CNPJ;
    END IF;
  END IF;
   
  IF (INSERTING OR UPDATING) AND :NEW.VLRMOVIMENTO <> 0 THEN
   
   :NEW.VLRMOVIMENTO := ABS(:NEW.VLRMOVIMENTO);
    
    SELECT COUNT(1)
    INTO P_COUNT
    FROM TGFSALSS
    WHERE CNPJ = :NEW.CNPJ;
    IF P_COUNT = 0 THEN
      IF UPDATING THEN
        ERRMSG := 'Não encontrado registro de saldo para o CNPJ '||:NEW.CNPJ||' na tabela TGFSALSS.';
        RAISE ERROR;
      ELSE
        INSERT INTO TGFSALSS (CNPJ, VLRTOTALCREDITO, VLRCREDITOUTILIZ, CODUSU)
        VALUES (
           :NEW.CNPJ
         , CASE WHEN :NEW.SINAL > 0 THEN ABS(:NEW.VLRMOVIMENTO) ELSE 0 END
         , CASE WHEN :NEW.SINAL < 0 THEN ABS(:NEW.VLRMOVIMENTO) ELSE 0 END
         , P_CODUSU);
      END IF;
    ELSE
      UPDATE TGFSALSS 
      SET VLRTOTALCREDITO = CASE WHEN :NEW.SINAL > 0 THEN VLRTOTALCREDITO  + ABS(:NEW.VLRMOVIMENTO) ELSE VLRTOTALCREDITO  END 
      , VLRCREDITOUTILIZ  = CASE WHEN :NEW.SINAL < 0 THEN VLRCREDITOUTILIZ + ABS(:NEW.VLRMOVIMENTO) ELSE VLRCREDITOUTILIZ END
      , CODUSU = P_CODUSU
      , DHALTER = SYSDATE
      WHERE CNPJ = :NEW.CNPJ;
    END IF;
  END IF;
  
EXCEPTION
  WHEN ERROR THEN
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
