-- SANKHYA.TRG_DLT_TSIFOR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIFOR
"SANKHYA".TRG_DLT_TSIFOR
BEFORE DELETE ON TSIFOR
FOR EACH ROW

DECLARE
  P_COUNT            INT;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF :OLD.TIPFORM = 'C' THEN
     SELECT COUNT(1) INTO P_COUNT
       FROM TGFPRO
      WHERE CODFILTRO = :OLD.CODFORM;
     IF P_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR (-20101, 'Existem produtos referenciando este filtro.');
     END IF;
  END IF;

END;

/
