-- SANKHYA.TRG_INC_UPD_DLT_TGFITE_LIB41
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFITE_LIB41
"SANKHYA".TRG_INC_UPD_DLT_TGFITE_LIB41 
BEFORE INSERT OR UPDATE OR DELETE ON TGFITE 
FOR EACH ROW

DECLARE 
   P_COUNT     INT; 
   ERROR       EXCEPTION;
   ERRMSG      VARCHAR2(4000);
   P_VALIDAR   BOOLEAN;
BEGIN
 
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
   /* 
         sincronização de dados
   */
   P_VALIDAR := FPODEVALIDAR('TGFITE');
   IF NOT (P_VALIDAR) THEN 
      RETURN;
   END IF;
   IF DELETING OR INSERTING OR (
   (:OLD.CODPROD <> :NEW.CODPROD) OR 
   (:OLD.CODLOCALORIG <> :NEW.CODLOCALORIG) OR
   (:OLD.CONTROLE <> :NEW.CONTROLE) OR
   (:OLD.QTDNEG <> :NEW.QTDNEG) OR 
   (:OLD.VLRTOT <> :NEW.VLRTOT)) THEN
      SELECT COUNT(*) 
      INTO P_COUNT 
      FROM TSILIB 
      WHERE EVENTO = 41 
      AND TABELA = 'TGFCAB' 
      AND (DHLIB IS NOT NULL OR REPROVADO = 'S') 
      AND NUCHAVE = NVL(:OLD.NUNOTA,:NEW.NUNOTA); 
      IF (P_COUNT > 0) THEN 
         ERRMSG := 'Pedido/Nota com Liberação por Análise dos Itens não pode ser Alterada ou Excluída.';
         RAISE ERROR;
      END IF;
   END IF;
   RETURN;
EXCEPTION 
    WHEN OTHERS THEN
     IF (P_VALIDAR) THEN
       IF SQLCODE <> 1 THEN
         ERRMSG := ERRMSG || '  ' || SQLERRM;
       END IF;
       RAISE_APPLICATION_ERROR(-20101, ERRMSG);       
     END IF;
END;

/
