-- SANKHYA.TRG_INC_UPD_TGFREJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFREJ
"SANKHYA".TRG_INC_UPD_TGFREJ BEFORE INSERT OR UPDATE ON TGFREJ FOR EACH ROW

DECLARE
  P_COUNT NUMBER(10);
BEGIN 

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(*) INTO P_COUNT 
  FROM TSIOBC
  WHERE CODIGO = :NEW.CODIGO 
  AND CODOCORRENCIA = :NEW.CODOCORRENCIA
  AND SEQUENCIA = :NEW.SEQUENCIA ;

  IF(P_COUNT = 0) THEN 
    RAISE_APPLICATION_ERROR(-20101,'Registro não Cadastrado da TSIOBC. ');
  END IF; 
END;

/
