-- SANKHYA.TRG_DLT_TGFTSP_EXCLUSAO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTSP_EXCLUSAO
TRG_DLT_TGFTSP_EXCLUSAO AFTER DELETE ON TGFTSP
FOR EACH ROW

DECLARE
  P_SOLICITANTE           VARCHAR2(64);
  P_NTUSERNAME            VARCHAR2(30);
  P_PROGRAMNAME           VARCHAR2(80);
BEGIN
    IF Stp_Get_Atualizando THEN
        RETURN;
    END IF;

    SELECT  SUBSTR(OSUSER,1,30), SUBSTR(MACHINE,1,64), PROGRAM 
    INTO P_NTUSERNAME, P_SOLICITANTE, P_PROGRAMNAME 
    FROM V$SESSION
    WHERE AUDSID = USERENV('SESSIONID');

    INSERT INTO TGFTSP_EXC (
      NUMNSU,          DHTRANSACAO,         CHAVE,          NOMEREDE,        
      AUTORIZACAO,     VLRTRANSACAO,        BANDEIRA,       CARTAO,  
      QTDPARCELAS,     CODTIPTIT,           OPERACAO,       RETORNO,           
      CODCONTROLE,     STATUS,              GATEWAY,        CODUSU,         
	  DHINCLUSAO,      CODUSUINCLUSAO,      NT_USERNAME,    HOSTNAME,
	  PROGRAMA)
    VALUES (
     :OLD.NUMNSU,                               :OLD.DHTRANSACAO,           :OLD.CHAVE,         :OLD.NOMEREDE,
     :OLD.AUTORIZACAO,                          :OLD.VLRTRANSACAO,          :OLD.BANDEIRA,      :OLD.CARTAO,
     :OLD.QTDPARCELAS,                          :OLD.CODTIPTIT,             :OLD.OPERACAO,      :OLD.RETORNO,
     :OLD.CODCONTROLE,                          :OLD.STATUS,                :OLD.GATEWAY,       :OLD.CODUSU,            
     SYSDATE,                                   Tsiusu_Log_Pkg.V_CODUSULOG, P_NTUSERNAME,       P_SOLICITANTE,      
     P_PROGRAMNAME);
END;

/
