-- SANKHYA.TRG_DLT_TGFLIV_BEFORE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFLIV_BEFORE
"SANKHYA".TRG_DLT_TGFLIV_BEFORE BEFORE DELETE ON TGFLIV FOR EACH ROW

DECLARE
	P_COUNT INT;
BEGIN

	IF STP_GET_ATUALIZANDO THEN
		RETURN;
	END IF;

	IF :OLD.ORIGEM = 'E' THEN
		SELECT COUNT(1) 
		INTO P_COUNT 
		FROM TCBINT C 
		WHERE C.NUNICO = :OLD.NUNOTA 
		AND C.ORIGEM IN ('L', 'S');
	ELSE 
		SELECT COUNT(1) 
		INTO P_COUNT 
		FROM TCBINT C 
		WHERE C.NUNICO = :OLD.NUNOTA 
		AND C.ORIGEM = :OLD.ORIGEM;
	END IF;

	IF P_COUNT <> 0 THEN
		RAISE_APPLICATION_ERROR(-20101,  'Já foi contabilizada, não pode ser excluída.');
	END IF;
END;

/
