-- SANKHYA.TRG_DLT_TRINFST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRINFST
"SANKHYA".TRG_DLT_TRINFST
BEFORE DELETE ON TRINFST
FOR EACH ROW

BEGIN
    DELETE TRIINFST
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND NUNOTA = :OLD.NUNOTA
        AND TIPODOCUMENTO = :OLD.TIPODOCUMENTO;
END;

/
