-- SANKHYA.TRG_DEL_TGFVOA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGFVOA
"SANKHYA".TRG_DEL_TGFVOA 
BEFORE DELETE ON TGFVOA
FOR EACH ROW

DECLARE 
  P_COUNT       NUMBER(10);
  P_CODVOLIGUAL NUMBER(10);

  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN    
  /* QUANDO SUBSTITUINDO PRODUTO NÃO VALIDAR RASTREAMENTO */     
  IF (VARIAVEIS_PKG.V_SBPRODUTO) THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
    FROM TSIPAR
   WHERE CHAVE = 'SBPRODUTO';
 
 IF (P_COUNT <> 0) THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_CODVOLIGUAL
    FROM TGFPRO PRO
   WHERE PRO.CODPROD = :OLD.CODPROD
     AND PRO.CODVOL = :OLD.CODVOL;
  
  IF P_CODVOLIGUAL > 0 THEN
     RETURN;
  END IF;

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT 
  FROM TGWEST
  WHERE CODPROD = :OLD.CODPROD 
  AND CODVOL = :OLD.CODVOL;
  IF P_COUNT > 0 THEN
     RAISE_APPLICATION_ERROR(-20101, 'Impossivel excluir. Volume alternativo esta sendo utilizado no estoque do WMS !');
  END IF;
    
  IF NOT VARIAVEIS_PKG.V_DLT_PROD THEN
    SELECT COUNT(1) INTO P_COUNT 
    FROM TGFPRO
      WHERE CODPROD = :OLD.CODPROD 
      AND CODVOLCOMPRA = :OLD.CODVOL;
      IF P_COUNT > 0 THEN
         RAISE_APPLICATION_ERROR(-20101, 'Impossivel excluir. Volume alternativo esta sendo utilizado na unidade de compra!');
      END IF;
  END IF;
END;

/
