-- SANKHYA.TRG_DLT_TGWEND
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWEND
"SANKHYA".TRG_DLT_TGWEND 
BEFORE DELETE ON TGWEND FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  RAISE_APPLICATION_ERROR(-20101, 'Registro padrão do sistema. Não pode ser excluído.');          
END;

/
