-- SANKHYA.TRG_FX_TFXFPU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXFPU
"SANKHYA".TRG_FX_TFXFPU
   BEFORE INSERT OR UPDATE
   ON TFXFPU
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S')
	THEN
		SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

		:NEW.NUVERSAO := P_CONTADOR;
		:NEW.ATUNUVERSAO := 'N';
	END IF;
END;

/
