-- SANKHYA.TRG_DLT_TPRIMPS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TPRIMPS
"SANKHYA".TRG_DLT_TPRIMPS BEFORE DELETE
ON TPRIMPS
FOR EACH ROW


BEGIN

DELETE FROM TPRDGIR WHERE NUMPS = :OLD.NUMPS AND SEQIMPS = :OLD.SEQIMPS;

END;

/
