-- SANKHYA.TRG_DLT_TGFDRCSTR2100
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR2100
"SANKHYA".TRG_DLT_TGFDRCSTR2100
BEFORE DELETE ON TGFDRCSTR2100
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    IF VARIAVEIS_PKG.V_REPROCESSANDODRCST = 'S' THEN
        RETURN;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2110
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI = :OLD.REG
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2110
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI = :OLD.REG
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
