-- SANKHYA.TRG_DLT_TFPBAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPBAS
"SANKHYA".TRG_DLT_TFPBAS 
BEFORE DELETE ON TFPBAS 
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 
  IF (:OLD.NUFIN IS NOT NULL) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Este cálculo não pode ser excluído ou recalculado porque seu valor já foi gerado no Financeiro. Exclua primeiramente o lançamento correspondente no Financeiro. Número único do título (' || :OLD.NUFIN || ')');  
  END IF; 
  
  DELETE 
  FROM TFPRTT
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND REFERENCIA = :OLD.REFERENCIA
  AND TIPFOLHA = :OLD.TIPFOLHA;
  
  DELETE 
  FROM TFPMED
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND REFERENCIA = :OLD.REFERENCIA
  AND ORIGEM = :OLD.TIPFOLHA;

  DELETE 
  FROM TFPTFOL
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND REFERENCIA = :OLD.REFERENCIA
  AND TIPFOLHA = :OLD.TIPFOLHA;
  
  DELETE 
  FROM TFPPEN
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND REFERENCIA = :OLD.REFERENCIA
  AND TIPFOLHA = :OLD.TIPFOLHA;
  
END;

/
