-- SANKHYA.TRG_DLT_TCBPLA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCBPLA
"SANKHYA".TRG_DLT_TCBPLA 
BEFORE DELETE ON TCBPLA FOR EACH ROW

DECLARE
     P_COUNT                  INT:= 0;
     ERROR                    EXCEPTION;
     ERRMSG                   VARCHAR2(255);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  IF (:OLD.CODCTACTB = 0) THEN
     ERRMSG := 'Registro padrao do sistema. Nao pode ser excluido.';
     RAISE ERROR;
  END IF;

  SELECT COUNT(1) INTO P_COUNT FROM TGFLIV C WHERE C.CODCTACTB = :OLD.CODCTACTB;
  IF P_COUNT <> 0 THEN
     ERRMSG := 'Existe referência a esta conta na tabela TGFLIV.';
     RAISE ERROR;
  END IF;

EXCEPTION WHEN ERROR THEN
      raise_application_error(-20101, ERRMSG);
END;

/
