-- SANKHYA.TRG_INC_UPD_TGMTRA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGMTRA
"SANKHYA".TRG_INC_UPD_TGMTRA
    BEFORE INSERT OR UPDATE
    ON TGMTRA
    FOR EACH ROW
    
DECLARE
    P_COUNT                  INT := 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO  P_COUNT
  FROM TGMMET
  where CODMETA = :NEW.CODMETA
  AND DTREF = :NEW.DTREF
  AND CODEMP = :NEW.CODEMP
  AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
  AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
  AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
  AND CODPARC = :NEW.CODPARC
  AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
  AND CODTIPPARC = :NEW.CODTIPPARC
  AND CODGRUPONAT = :NEW.CODGRUPONAT;
--  RAISE_APPLICATION_ERROR(-20101, 'Não encontramos a Meta/Orçamento ' || P_COUNT || '-' || :NEW.dtref || :NEW.CODCENCUS || '- '|| :NEW.CODGRUPONAT || ' para atualizar os saldos.');
  IF (P_COUNT = 0) THEN
     INSERT INTO TGMMET (
        CODMETA,
        DTREF,
        CODEMP,
        CODGRUPOPROD, CODPROD, CODLOCAL, CONTROLE, MARCA,
        CODREG, CODGER, CODVEND,
        CODCENCUS, CODNAT, CODPROJ,
        CODPARC,
        CODUF, CODCID, CODPAIS,
        CODTIPPARC, 
		DIA,
		PREVDESP,CODGRUPONAT )
	VALUES (
        :NEW.CODMETA,
        :NEW.DTREF,
        :NEW.CODEMP,
        :NEW.CODGRUPOPROD, :NEW.CODPROD, :NEW.CODLOCAL, :NEW.CONTROLE, :NEW.MARCA,
        :NEW.CODREG, :NEW.CODGER, :NEW.CODVEND,
        :NEW.CODCENCUS, :NEW.CODNAT, :NEW.CODPROJ,
        :NEW.CODPARC,
        :NEW.CODUF, :NEW.CODCID, :NEW.CODPAIS,
        :NEW.CODTIPPARC, 
		:NEW.DIA,
		0,:NEW.CODGRUPONAT);
  --   RAISE_APPLICATION_ERROR(-20101, 'Não encontramos a Meta/Orçamento ' || :NEW.codmeta || '-' || :NEW.dtref || ' para atualizar os saldos.');
  END IF;

  IF :NEW.TIPO = 'A' THEN
    UPDATE TGMMET SET ANTECIPDESP = NVL(ANTECIPDESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
      AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSIF :NEW.TIPO = 'S' THEN
    UPDATE TGMMET SET SUPLEMENTODESP = NVL(SUPLEMENTODESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
    AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSIF :NEW.TIPO = 'R' THEN
    UPDATE TGMMET SET REDUCAODESP = NVL(REDUCAODESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
      AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSIF :NEW.TIPO = 'M' THEN
    UPDATE TGMMET SET TRANSFSALDODESP = NVL(TRANSFSALDODESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
      AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSIF :NEW.TIPO = 'T' THEN
    UPDATE TGMMET SET TRANSFDESP = NVL(TRANSFDESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
      AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSIF :NEW.TIPO = 'C' THEN
    UPDATE TGMMET SET COMPROMISSODESP = NVL(COMPROMISSODESP,0) + (:NEW.VALOR * :NEW.SINAL)
    where CODMETA = :NEW.CODMETA
    AND DTREF = :NEW.DTREF
    AND CODEMP = :NEW.CODEMP
    AND CODGRUPOPROD = :NEW.CODGRUPOPROD AND CODPROD = :NEW.CODPROD AND CODLOCAL = :NEW.CODLOCAL AND CONTROLE = :NEW.CONTROLE AND MARCA = :NEW.MARCA
    AND CODREG = :NEW.CODREG AND CODGER = :NEW.CODGER AND CODVEND = :NEW.CODVEND
    AND CODCENCUS = :NEW.CODCENCUS AND CODNAT = :NEW.CODNAT AND CODPROJ = :NEW.CODPROJ
    AND CODPARC = :NEW.CODPARC
    AND CODUF = :NEW.CODUF AND CODCID = :NEW.CODCID AND CODPAIS = :NEW.CODPAIS
    AND CODTIPPARC = :NEW.CODTIPPARC
        AND CODGRUPONAT = :NEW.CODGRUPONAT;
  ELSE
     RAISE_APPLICATION_ERROR(-20101, 'Tipo de lançamento "' || :NEW.TIPO || '"não previsto para atualizar os saldos.');
  END IF;
END;

/
