-- SANKHYA.TRG_INC_UPD_TGFPEM_IPI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPEM_IPI
"SANKHYA".TRG_INC_UPD_TGFPEM_IPI
BEFORE INSERT OR UPDATE ON TGFPEM FOR EACH ROW
   

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (NVL(:NEW.CODENQIPIENT, 0) <> NVL(:OLD.CODENQIPIENT, 0) OR NVL(:NEW.CSTIPIENT, 0) <> NVL(:OLD.CSTIPIENT, 0)) THEN
    STP_VALIDA_ENQUADRAMENTO_IPI(:NEW.CSTIPIENT, :NEW.CODENQIPIENT);
  END IF;
    
  IF (NVL(:NEW.CODENQIPISAI, 0) <> NVL(:OLD.CODENQIPISAI, 0) OR NVL(:NEW.CSTIPISAI, 0) <> NVL(:OLD.CSTIPISAI, 0)) THEN
    STP_VALIDA_ENQUADRAMENTO_IPI(:NEW.CSTIPISAI, :NEW.CODENQIPISAI);
  END IF; 

END;

/
