-- SANKHYA.TRG_INC_TFPTELASPERM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPTELASPERM
"SANKHYA".TRG_INC_TFPTELASPERM
BEFORE INSERT ON TFPTELASPERM 
FOR EACH ROW

BEGIN
  SELECT TFPTELASPERM_SEQ.NEXTVAL
  INTO   :NEW.CODPERM
  FROM   dual;
END;

/
