-- SANKHYA.TRG_DLT_TGFITC_TGFFRC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITC_TGFFRC
"SANKHYA".TRG_DLT_TGFITC_TGFFRC BEFORE DELETE ON TGFITC FOR EACH ROW

DECLARE
P_COUNT  INT;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

    INSERT INTO TGFITC_DLT VALUES(:OLD.NUMCOTACAO , :OLD.CODPARC);  

END;

/
