-- SANKHYA.TRG_INC_UPD_TGFFIN_VINCNT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFIN_VINCNT
"SANKHYA".TRG_INC_UPD_TGFFIN_VINCNT
BEFORE INSERT OR UPDATE 
ON TGFFIN 
FOR EACH ROW

BEGIN
  IF NOT STP_GET_TIMUTILIZAIMOB THEN
    RETURN;
  END IF;

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  IF UPDATING THEN
    IF :NEW.TIMCONTRATOLTV IS NOT NULL AND :NEW.TIMORIGEM = 'MF' AND :NEW.NUNOTA IS NULL AND :OLD.NUNOTA IS NOT NULL THEN
        :NEW.NUNOTA := :OLD.NUNOTA;
    END IF;
  END IF;
  IF :OLD.NUNOTA IS NOT NULL THEN
    :NEW.TIMNUNOTA := :OLD.NUNOTA;
  END IF;
END;

/
