-- SANKHYA.TRG_DLT_TRIRCST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIRCST
"SANKHYA".TRG_DLT_TRIRCST
BEFORE DELETE ON TRIRCST
FOR EACH ROW

BEGIN
    DELETE TRINFST
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;

    DELETE TRIPPST
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;

    DELETE TRIPAST
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;
END;

/
