-- SANKHYA.TRG_DLT_TGFJUM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFJUM
"SANKHYA".TRG_DLT_TGFJUM 
BEFORE DELETE ON TGFJUM 
FOR EACH ROW


DECLARE 

P_COUNT INTEGER;

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) 
      INTO P_COUNT 
     FROM TCBINT C 
  WHERE C.ORIGEM = 'J'
       AND C.NUNICO = :OLD.NUFIN 
       AND C.REFERENCIA = TRUNC(:OLD.REFERENCIA, 'MONTH');
  
  IF P_COUNT <> 0 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Juro/Multa mensal já foi contabilizado, não pode ser excluído.');
  END IF; 
END;

/
