-- SANKHYA.TRG_DLT_TGFGAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFGAR
"SANKHYA".TRG_DLT_TGFGAR 
BEFORE DELETE ON TGFGAR FOR EACH ROW

DECLARE
     P_COUNT                  INT:= 0;
 BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

   SELECT COUNT(1) INTO P_COUNT 
     FROM TGFPRO 
    WHERE CODGAR = :OLD.CODGAR;

   IF (P_COUNT <> 0) THEN
      RAISE_APPLICATION_ERROR(-20101, 'Extens?o de garantia n?o pode ser excluida porque esta sendo referenciada no cadastro de servico!');
   END IF;
 
  SELECT COUNT(1) INTO P_COUNT 
    FROM TGFITE ITE LEFT JOIN TGFPEM PEM ON (ITE.CODPROD = PEM.CODPROD AND ITE.CODEMP = PEM.CODEMP),
         TGFPRO PRO 
   WHERE PRO.CODPROD = ITE.CODPROD
     AND ITE.CODPROD = :OLD.CODGAR
     AND (CASE WHEN PEM.TIPCONTEST IS NOT NULL THEN PEM.TIPCONTEST ELSE PRO.TIPCONTEST END) = 'N'
     AND PRO.USOPROD = 'S'
     AND ITE.CONTROLE = TO_CHAR(:OLD.CODPLANO)
     AND ITE.USOPROD = 'S';
  
   IF (P_COUNT <> 0) THEN
      RAISE_APPLICATION_ERROR(-20101, 'A Extens?o de garantia n?o pode ser excluida por esta sendo referenciada em algum(ns) pedido(s) ou nota(s).');
   END IF;
END;

/
