-- SANKHYA.TRG_DLT_TGFTAB
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTAB
"SANKHYA".TRG_DLT_TGFTAB BEFORE DELETE ON TGFTAB REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    ERROR                    EXCEPTION;
    ERRMSG                   VARCHAR2(255);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.NUTAB = 0 ) THEN
      ERRMSG := 'Registro padr?o do sistema. N?o pode ser alterado ou excluido.';
      RAISE ERROR;
  END IF;
/*  LOCK TABLE TGFTAB_DLT IN EXCLUSIVE MODE;*/
  INSERT INTO TGFTAB_DLT(NUTAB, CODTAB, DTVIGOR)
  VALUES (:OLD.NUTAB, :OLD.CODTAB, :OLD.DTVIGOR);
/* cod daqui foi para o after*/
  EXCEPTION
    WHEN ERROR THEN
    raise_application_error(-20101, ERRMSG);
END;

/
