-- SANKHYA.TRG_INC_UPD_TGFVEI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFVEI
"SANKHYA".TRG_INC_UPD_TGFVEI
   BEFORE INSERT OR UPDATE
   ON TGFVEI
   FOR EACH ROW

DECLARE
   P_ATIVO       CHAR (1);
   P_MOTORISTA   CHAR (1);
BEGIN
   IF STP_GET_ATUALIZANDO
   THEN
      RETURN;
   END IF;

   IF (:NEW.CODVEICULO = 0)
   THEN
      RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_REGISTRO_PADRAO);
   END IF;

   IF    (INSERTING AND :NEW.CODMOTORISTA <> 0)
      OR (UPDATING AND :NEW.CODMOTORISTA <> :OLD.CODMOTORISTA)
   THEN
      SELECT MOTORISTA, ATIVO
        INTO P_MOTORISTA, P_ATIVO
        FROM TGFPAR
       WHERE CODPARC = :NEW.CODMOTORISTA;
      
      IF :NEW.CODMOTORISTA = 0 THEN
        P_MOTORISTA := 'S';
      END IF;

      IF (P_MOTORISTA <> 'S')
      THEN
         RAISE_APPLICATION_ERROR (
            -20101,
            'Parceiro não está marcado como Motorista.');
      END IF;

      IF (P_ATIVO <> 'S')
      THEN
         RAISE_APPLICATION_ERROR (-20101, 'Motorista não está ativo.');
      END IF;
   END IF;
END;

/
