-- SANKHYA.TRG_INC_TFPNEWFORHIST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPNEWFORHIST
"SANKHYA".TRG_INC_TFPNEWFORHIST
BEFORE INSERT ON TFPNEWFORHIST
FOR EACH ROW

BEGIN SELECT TFPNEWFORHIST_SEQ.NEXTVAL
    INTO :NEW.CODHIST
    FROM DUAL;
END;

/
