-- SANKHYA.TRG_INC_UPD_TGFFIN_TGFORD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFIN_TGFORD
"SANKHYA".TRG_INC_UPD_TGFFIN_TGFORD
BEFORE INSERT OR UPDATE ON TGFFIN 
FOR EACH ROW

DECLARE
  P_COUNT           INT := 0;
P_VALIDAR BOOLEAN;
  
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  P_VALIDAR := Fpodevalidar('TGFFIN');
  IF (NOT P_VALIDAR) THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TSIPAR
  WHERE CHAVE = 'SBPARCEIRO';
  IF (P_COUNT <> 0) THEN
    RETURN;
  END IF;  
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGFORD ORD
  WHERE ORD.ORDEMCARGA = :NEW.ORDEMCARGA
    AND ORD.CODEMP = (SELECT CASE WHEN NVL(EMP.CODEMPOC, 0) = 0 THEN EMP.CODEMP 
                          ELSE CODEMPOC END 
                      FROM TGFEMP EMP 
                      WHERE EMP.CODEMP = :NEW.CODEMP);
    
  IF (P_COUNT=0) THEN
     RAISE_APPLICATION_ERROR(-20101, 'Não existe referência para essa ordem de carga. Financeiro de Nro Único: '|| TO_CHAR(:NEW.NUFIN) ||'.');
  END IF;  
  RETURN;
END;

/
