-- SANKHYA.TRG_DLT_TRIDRPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIDRPJ
"SANKHYA".TRG_DLT_TRIDRPJ 
AFTER DELETE  ON TRIDRPJ
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPRRJ T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPRRJ
		WHERE :OLD.CODEMP = TRIPRRJ.CODEMP 
		  AND :OLD.DTREF = TRIPRRJ.DTREF 
		  AND :OLD.TPAMB = TRIPRRJ.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPRRJ.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPRRJ.CHAVE
          AND :OLD.NRODOCUMENTO = TRIPRRJ.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIPRRJ.TIPODOCUMENTO
          AND :OLD.NATREND = TRIPRRJ.NATREND
          AND :OLD.SEQITE = TRIPRRJ.SEQITE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIAPPJ T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE;      

	IF P_COUNT > 0 THEN
		DELETE FROM TRIAPPJ
		WHERE :OLD.CODEMP = TRIAPPJ.CODEMP 
		  AND :OLD.DTREF = TRIAPPJ.DTREF 
		  AND :OLD.TPAMB = TRIAPPJ.TPAMB 
		  AND :OLD.SEQUENCIA = TRIAPPJ.SEQUENCIA 
		  AND :OLD.CHAVE = TRIAPPJ.CHAVE
          AND :OLD.NRODOCUMENTO = TRIAPPJ.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIAPPJ.TIPODOCUMENTO
          AND :OLD.NATREND = TRIAPPJ.NATREND
          AND :OLD.SEQITE = TRIAPPJ.SEQITE;          
	END IF;
END;		

/
