-- SANKHYA.TRG_DLT_TRITCAE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRITCAE
"SANKHYA".TRG_DLT_TRITCAE
BEFORE DELETE ON TRITCAE
FOR EACH ROW

BEGIN
    DELETE TRINFRB
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND CODATIVECON = :OLD.CODATIVECON;

    DELETE TRIIPSC
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND CODATIVECON = :OLD.CODATIVECON;

    DELETE TRIACPRB
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND CODATIVECON = :OLD.CODATIVECON;
END;

/
