-- SANKHYA.TRG_FX_TFXECE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXECE
"SANKHYA".TRG_FX_TFXECE
   BEFORE INSERT OR UPDATE
   ON TFXECE
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
