-- SANKHYA.TRG_INC_UPD_TFPAFG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPAFG
"SANKHYA".TRG_INC_UPD_TFPAFG BEFORE INSERT OR UPDATE ON TFPAFG  FOR EACH ROW

DECLARE
   P_COUNT          INT;
BEGIN
   IF (:NEW.TIPREG = 'G')  THEN
      BEGIN
         SELECT COUNT(1) INTO P_COUNT
         FROM TFPGRA T
         WHERE T.CODGRAT = :NEW.CODGRAT;
         IF (P_COUNT = 0) THEN
            RAISE_APPLICATION_ERROR(-20101, 'Gratificação não existe.');
         END IF;
      END;
   ELSE
      BEGIN
         SELECT COUNT(1) INTO P_COUNT
         FROM TFPNIV T
         WHERE T.CODNIVELREF = :NEW.CODGRAT;
         IF (P_COUNT = 0) THEN
            RAISE_APPLICATION_ERROR(-20101, 'Nível de referência não existe.');
         END IF;
      END;
   END IF;
END;

/
