-- SANKHYA.TRG_DLT_TCSOSE_CVE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSOSE_CVE
"SANKHYA".TRG_DLT_TCSOSE_CVE
BEFORE DELETE ON TCSOSE
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN  

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TCSCVE 
  WHERE NUMOSINSTAL = :OLD.NUMOS;
  IF P_COUNT > 0 THEN
    UPDATE TCSCVE SET NUMOSINSTAL = NULL , DTINSTAL = NULL 
    WHERE NUMOSINSTAL = :OLD.NUMOS;
  END IF;


  SELECT COUNT(1) INTO P_COUNT
  FROM TCSCVE
  WHERE NUMOSDESINSTAL = :OLD.NUMOS;
  IF P_COUNT > 0 THEN
    UPDATE TCSCVE SET NUMOSDESINSTAL = NULL , DTDESINSTAL = NULL 
    WHERE NUMOSDESINSTAL = :OLD.NUMOS;
  END IF;


  SELECT COUNT(1) INTO P_COUNT
  FROM TCSCVE 
  WHERE NUMOSINSTAL IS NULL AND NUMOSDESINSTAL IS NULL;
  IF P_COUNT> 0 THEN
    DELETE FROM TCSCVE 
    WHERE NUMOSINSTAL IS NULL AND NUMOSDESINSTAL IS NULL;
  END IF;
  
END;

/
