-- SANKHYA.TRG_DLT_TGFMBC_EXCLUSAO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFMBC_EXCLUSAO
TRG_DLT_TGFMBC_EXCLUSAO AFTER DELETE ON TGFMBC
FOR EACH ROW

DECLARE
  P_SOLICITANTE           VARCHAR2(64); 
  P_NTUSERNAME            VARCHAR2(30);
  P_PROGRAMNAME           VARCHAR2(80);
BEGIN
    SELECT  SUBSTR(OSUSER,1,30), SUBSTR(MACHINE,1,64), PROGRAM  
    INTO P_NTUSERNAME, P_SOLICITANTE, P_PROGRAMNAME    
    FROM V$SESSION
    WHERE AUDSID = USERENV('SESSIONID')
      AND ROWNUM = 1;
    
    INSERT INTO TGFMBC_EXC (
      NUBCO,         CODLANC,      DTLANC,        CODTIPOPER,
      DHTIPOPER,     DTCONTAB,     CODCTABCOINT,  NUMDOC,
      VLRLANC,       TALAO,        PREDATA,       CONCILIADO,
      DHCONCILIACAO, ORIGMOV,      NUMTRANSF,     RECDESP,
      HISTORICO,     CODUSU,
      DHEXCLUSAO,    NT_USERNAME,  HOSTNAME, PROGRAMA)
    VALUES (
     :OLD.NUBCO,         :OLD.CODLANC,     :OLD.DTLANC,       :OLD.CODTIPOPER,
     :OLD.DHTIPOPER,     :OLD.DTCONTAB,    :OLD.CODCTABCOINT, :OLD.NUMDOC,
     :OLD.VLRLANC,       :OLD.TALAO,       :OLD.PREDATA,      :OLD.CONCILIADO,
     :OLD.DHCONCILIACAO, :OLD.ORIGMOV,     :OLD.NUMTRANSF,    :OLD.RECDESP,
     :OLD.HISTORICO,     Tsiusu_Log_Pkg.V_CODUSULOG,
     SYSDATE,            P_NTUSERNAME,     P_SOLICITANTE, P_PROGRAMNAME);
END;

/
