-- SANKHYA.TRG_INC_TGFECF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFECF
"SANKHYA".TRG_INC_TGFECF 
BEFORE INSERT ON TGFECF 
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

 :NEW.DTMOV := :NEW.DTEMISSAO; 
END;

/
