-- SANKHYA.TRG_INC_UPD_TGFFIN_DTPRAZO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFIN_DTPRAZO
"SANKHYA".TRG_INC_UPD_TGFFIN_DTPRAZO
   BEFORE INSERT OR UPDATE
   ON TGFFIN
   FOR EACH ROW
   
DECLARE
    NVLDATE DATE;
BEGIN
   IF STP_GET_ATUALIZANDO THEN
      RETURN;
   END IF;

   NVLDATE := TO_DATE('1900/01/01', 'yyyy/mm/dd');

   IF NVL(:NEW.NURENEG,0) = 0  -- nao e titulo renegociado/renegociacao
      AND
      NVL(:NEW.DTPRAZO,NVLDATE) = NVL(:OLD.DTPRAZO,NVLDATE) -- nao transferindo vencimento 
      AND 
      NVL(:NEW.DTVENC,NVLDATE) <> NVL(:OLD.DTVENC,NVLDATE)  -- alterando vencimento
   THEN      
        :NEW.DTPRAZO := :NEW.DTVENC;
   END IF; 

   RETURN;
END;

/
