-- SANKHYA.TRG_DLT_TRIREAD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIREAD
"SANKHYA".TRG_DLT_TRIREAD 
AFTER DELETE  ON TRIREAD
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRRA T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRRA
		WHERE :OLD.CODEMP = TRIDRRA.CODEMP 
		  AND :OLD.DTREF = TRIDRRA.DTREF 
		  AND :OLD.TPAMB = TRIDRRA.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRRA.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRRA.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRCEE T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRCEE
		WHERE :OLD.CODEMP = TRIDRCEE.CODEMP 
		  AND :OLD.DTREF = TRIDRCEE.DTREF 
		  AND :OLD.TPAMB = TRIDRCEE.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRCEE.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRCEE.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIIPRC T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIIPRC
		WHERE :OLD.CODEMP = TRIIPRC.CODEMP 
		  AND :OLD.DTREF = TRIIPRC.DTREF 
		  AND :OLD.TPAMB = TRIIPRC.TPAMB 
		  AND :OLD.SEQUENCIA = TRIIPRC.SEQUENCIA 
		  AND :OLD.CHAVE = TRIIPRC.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIREAD_NFS T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIREAD_NFS
		WHERE :OLD.CODEMP = TRIREAD_NFS.CODEMP 
		  AND :OLD.DTREF = TRIREAD_NFS.DTREF 
		  AND :OLD.TPAMB = TRIREAD_NFS.TPAMB 
		  AND :OLD.SEQUENCIA = TRIREAD_NFS.SEQUENCIA 
		  AND :OLD.CHAVE = TRIREAD_NFS.CHAVE;
	END IF;
END;

/
