-- SANKHYA.AFTERUPDATETFPFOR
CREATE OR REPLACE TRIGGER SANKHYA.AFTERUPDATETFPFOR
"SANKHYA".AFTERUPDATETFPFOR
BEFORE UPDATE
    ON TFPFOR
        FOR EACH ROW

BEGIN

	IF :OLD.CODUSU IS NULL THEN
		INSERT INTO TFPFORHIST(
			
			CODFORM,
			DESCRFORM,
			FORMULA,
			CODFORMIND,
			CODUSU,
			SANKHYA
		)
		VALUES (:OLD.CODFORM,
			:OLD.DESCRFORM,
			:OLD.FORMULA,
			:OLD.CODFORMIND,
			0,
			:OLD.SANKHYA);
	ELSE
		INSERT INTO TFPFORHIST(
			
			CODFORM,
			DESCRFORM,
			FORMULA,
			CODFORMIND,
			CODUSU,
			SANKHYA
		)
		VALUES (:OLD.CODFORM,
			:OLD.DESCRFORM,
			:OLD.FORMULA,
			:OLD.CODFORMIND,
			:OLD.CODUSU,
			:OLD.SANKHYA);
    END IF;
	
END;

/
