-- SANKHYA.TRG_INC_UPD_DLT_TGWITER_BEFORE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGWITER_BEFORE
"SANKHYA".TRG_INC_UPD_DLT_TGWITER_BEFORE
 BEFORE INSERT OR DELETE OR UPDATE ON TGWITER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    P_CODPROD     TGFITE.CODPROD%TYPE;
	P_NUNOTA 	  TGFITE.NUNOTA%TYPE;
	P_SEQNOTA	  TGFITE.SEQUENCIA%TYPE;
	P_QTDWMS      TGFITE.QTDWMS%TYPE;
	P_QTDNEG      TGFITE.QTDNEG%TYPE;
	P_QTDTOTWMS   TGFITE.QTDNEG%TYPE;
	P_COUNT		  NUMBER(10);
	ERRMSG        VARCHAR2(255);
	ERROR         EXCEPTION;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
	IF (DELETING) THEN
		P_NUNOTA    := :OLD.NUNOTA;
		P_SEQNOTA   := :OLD.SEQNOTA;
	ELSE
		P_NUNOTA    := :NEW.NUNOTA;
		P_SEQNOTA   := :NEW.SEQNOTA;
	END IF;

	SELECT ITE.QTDNEG, 
			ITE.QTDWMS
	INTO P_QTDNEG, 
		 P_QTDWMS
	FROM TGFITE ITE
	WHERE ITE.NUNOTA    = P_NUNOTA
	AND   ITE.SEQUENCIA = P_SEQNOTA;

	P_QTDNEG := NVL(P_QTDNEG,0);
	P_QTDWMS := NVL(P_QTDWMS,0) - NVL(:OLD.QTDWMS,0) + NVL(:NEW.QTDWMS,0);
 
	IF ((P_QTDNEG - P_QTDWMS) < 0)  THEN
		SELECT CODPROD INTO P_CODPROD  
		FROM TGFITE
		WHERE NUNOTA    = P_NUNOTA
		AND   SEQUENCIA = P_SEQNOTA;
		ERRMSG := 'A quantidade recebida no WMS é maior que a quantidade negociada do item pela CAF.Qtd.Neg.: ' || TO_CHAR(P_QTDNEG) || ' Qtd.WMS : ' || TO_CHAR(P_QTDWMS) || ' Produto : ' || TO_CHAR(P_CODPROD);
		RAISE ERROR;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TGFITE
	WHERE NUNOTA = P_NUNOTA
	AND SEQUENCIA = P_SEQNOTA;
  
	IF (P_COUNT <> 0) THEN
		UPDATE TGFITE 
		SET QTDWMS = P_QTDWMS
		WHERE NUNOTA    = P_NUNOTA
		AND   SEQUENCIA = P_SEQNOTA;
	END IF;
	RETURN;	  
EXCEPTION
	WHEN ERROR THEN
		RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
