-- SANKHYA.TRG_INC_TGFTOP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFTOP
"SANKHYA".TRG_INC_TGFTOP 
BEFORE INSERT ON TGFTOP FOR EACH ROW 

BEGIN
  IF TO_DATE(:NEW.DHALTER, 'DD-MM-YYYY HH24:MI:SS') <> :NEW.DHALTER THEN
     :NEW.DHALTER := TO_DATE(TO_CHAR(:NEW.DHALTER, 'DD-MM-YYYY HH24:MI:SS'), 'DD-MM-YYYY HH24:MI:SS');
  END IF; 
  
  STP_VALIDA_ENQUADRAMENTO_IPI(:NEW.CSTIPIENT, :NEW.CODENQIPIENT);
  
  STP_VALIDA_ENQUADRAMENTO_IPI(:NEW.CSTIPISAI, :NEW.CODENQIPISAI);  
END;

/
