-- SANKHYA.TRG_DLT_TGFRAP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFRAP
"SANKHYA".TRG_DLT_TGFRAP 
BEFORE DELETE ON TGFRAP FOR EACH ROW

DECLARE
  P_COUNT INT;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) 
    INTO P_COUNT
    FROM TGFFIN
   WHERE NUFIN = :OLD.NUFIN
        AND DHBAIXA IS NOT NULL;
  IF P_COUNT > 0 THEN
     RAISE_APPLICATION_ERROR (-20101, 'Ainda existe financeiro com Baixa, não pode ser excluído.');
  END IF;
END;

/
