-- SANKHYA.TRG_DLT_TRIPPF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIPPF
TRG_DLT_TRIPPF 
AFTER DELETE  ON TRIPPF
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIIRPF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIIRPF
		WHERE :OLD.CODEMP = TRIIRPF.CODEMP 
		  AND :OLD.DTREF = TRIIRPF.DTREF 
		  AND :OLD.TPAMB = TRIIRPF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIIRPF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIIRPF.CHAVE;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDPPF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDPPF
		WHERE :OLD.CODEMP = TRIDPPF.CODEMP 
		  AND :OLD.DTREF = TRIDPPF.DTREF 
		  AND :OLD.TPAMB = TRIDPPF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDPPF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDPPF.CHAVE;
	END IF;
	
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPLDS T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPLDS
		WHERE :OLD.CODEMP = TRIPLDS.CODEMP 
		  AND :OLD.DTREF = TRIPLDS.DTREF 
		  AND :OLD.TPAMB = TRIPLDS.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPLDS.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPLDS.CHAVE;
	END IF;
END;	

/
