-- SANKHYA.TRG_DLT_TFPNCO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPNCO
"SANKHYA".TRG_DLT_TFPNCO
BEFORE DELETE ON TFPNCO
FOR EACH ROW

BEGIN
  RAISE_APPLICATION_ERROR(-20101,'Registro padrão do sistema. Não pode ser excluído.');
END;

/
