-- SANKHYA.TRG_DLT_TCSOSE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSOSE
"SANKHYA".TRG_DLT_TCSOSE
BEFORE DELETE ON TCSOSE 
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TSIATA
  WHERE TIPO = 'O' 
    AND CODATA = :OLD.NUMOS;
  
  IF P_COUNT > 0 THEN
    DELETE TSIATA
    WHERE TIPO = 'O' 
      AND CODATA = :OLD.NUMOS;
  END IF;
END;

/
