-- SANKHYA.TRG_DLT_TCSCON
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSCON
"SANKHYA".TRG_DLT_TCSCON
BEFORE DELETE ON TCSCON 
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TSIATA
  WHERE TIPO = 'C' 
    AND CODATA = :OLD.NUMCONTRATO;
  IF P_COUNT > 0 THEN
    DELETE TSIATA
    WHERE TIPO = 'C' 
      AND CODATA = :OLD.NUMCONTRATO;
  END IF;  
END;

/
