-- SANKHYA.TRG_DLT_TRIPNI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIPNI
"SANKHYA".TRG_DLT_TRIPNI 
AFTER DELETE  ON TRIPNI
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRINRN T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE;

	IF P_COUNT > 0 THEN
		DELETE FROM TRINRN
		WHERE :OLD.CODEMP = TRINRN.CODEMP 
		  AND :OLD.DTREF = TRINRN.DTREF 
		  AND :OLD.TPAMB = TRINRN.TPAMB 
		  AND :OLD.SEQUENCIA = TRINRN.SEQUENCIA 
		  AND :OLD.CHAVE = TRINRN.CHAVE;
	END IF;
END;		

/
