-- SANKHYA.TRG_DLT_TCEITE_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCEITE_AFTER
"SANKHYA".TRG_DLT_TCEITE_AFTER
AFTER DELETE ON TCEITE 
FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TCESER 
  WHERE NUNOTA = :OLD.NUIMP  
  AND SEQUENCIA = :OLD.SEQUENCIA;
  IF P_COUNT > 0 THEN
    DELETE FROM TCESER 
    WHERE NUNOTA = :OLD.NUIMP  
    AND SEQUENCIA = :OLD.SEQUENCIA;
  END IF;
END;

/
