-- SANKHYA.TRG_INC_UPD_TGFPAR_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPAR_AFTER
"SANKHYA".TRG_INC_UPD_TGFPAR_AFTER
   AFTER UPDATE OR INSERT
   ON TGFPAR
   FOR EACH ROW

DECLARE
   P_COUNT   INT;
   
   PRAGMA AUTONOMOUS_TRANSACTION;
   
BEGIN

   SELECT COUNT(*) INTO P_COUNT FROM TGFPAR WHERE PERMITECORTE <> 'N';
   IF :NEW.PERMITECORTE <> 'N' OR P_COUNT > 0 THEN
      UPDATE TSIVARBD SET UTILIZA_VERIFCORTE = 'S';
   ELSE 
      UPDATE TSIVARBD SET UTILIZA_VERIFCORTE = 'N';
   END IF;
   COMMIT;

END;

/
