-- SANKHYA.TRG_INC_TGFCONTROLEDIHBA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFCONTROLEDIHBA
TRG_INC_TGFCONTROLEDIHBA
BEFORE INSERT ON TGFCONTROLEDIHBA
FOR EACH ROW

BEGIN
  SELECT TGFCONTROLEDIHBA_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
