-- SANKHYA.TRG_DLT_TGFITC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITC
"SANKHYA".TRG_DLT_TGFITC BEFORE DELETE ON TGFITC
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  BEGIN
	DELETE FROM TGFANC WHERE NUMCOTACAO = :OLD.NUMCOTACAO 
                         AND CODPROD    = :OLD.CODPROD
	      				 AND CONTROLE   = :OLD.CONTROLE 
						 AND CODLOCAL   = :OLD.CODLOCAL;
    EXCEPTION WHEN NO_DATA_FOUND THEN
    RETURN;
  END;	
END;

/
