-- SANKHYA.TRG_DLT_TGFTPV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTPV
"SANKHYA".TRG_DLT_TGFTPV 
BEFORE DELETE ON TGFTPV 
FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
    ERROR                    EXCEPTION;
    ERRMSG                   VARCHAR2(255);
BEGIN
  IF (:OLD.CODTIPVENDA = 0) THEN
     ERRMSG := 'Registro padrão do sistema. Não pode ser excluído.';
     RAISE ERROR;
  END IF;

/*  LOCK TABLE TGFTPV_DLT IN EXCLUSIVE MODE;*/
  INSERT INTO TGFTPV_DLT (CODTIPVENDA) VALUES (:OLD.CODTIPVENDA);
  EXCEPTION
    WHEN ERROR THEN
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;
/
