-- SANKHYA.TRG_DLT_TPRAPA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TPRAPA
"SANKHYA".TRG_DLT_TPRAPA
AFTER DELETE
ON TPRAPA
FOR EACH ROW

DECLARE
    P_IDIPROD NUMBER;
BEGIN
  SELECT IDIPROC
    INTO P_IDIPROD
  FROM TPRAPO APO INNER JOIN TPRIATV IATV ON (APO.IDIATV = IATV.IDIATV)
    WHERE APO.NUAPO = :OLD.NUAPO;

  UPDATE TPRIPA 
    SET CONCLUIDO  = 'N' 
  WHERE IDIPROC    = P_IDIPROD 
    AND CODPRODPA  = :OLD.CODPRODPA 
  AND CONTROLEPA = :OLD.CONTROLEPA;
END;

/
