-- SANKHYA.TRG_INC_UPD_TFPFCTI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPFCTI
"SANKHYA".TRG_INC_UPD_TFPFCTI
BEFORE INSERT OR UPDATE ON TFPFCTI
FOR EACH ROW

DECLARE 
  P_COUNT INTEGER;
  P_CODEMP TFPCTI.CODEMP%TYPE;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  BEGIN
    SELECT CODEMP
    INTO P_CODEMP
    FROM TFPCTI
    WHERE CODCONV = :NEW.CODCONV;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_CODEMP := NULL;
  END;
  
  IF (P_CODEMP IS NULL OR P_CODEMP <> :NEW.CODEMP) THEN
    RAISE_APPLICATION_ERROR(-20101, 'A empresa do funcionário tem que ser igual à empresa da convocação!');
  END IF;
  
  IF INSERTING THEN
    SELECT COUNT(1)
    INTO P_COUNT
    FROM TFPFUN
    WHERE CODFUNC = :NEW.CODFUNC
    AND CODEMP = :NEW.CODEMP
    AND CODCATEGESOCIAL = 111;
    
    IF P_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20101, 'Funcionário não configurado para trabalho intermitente!');
    END IF;
  END IF;
  
END;

/
