-- SANKHYA.TRG_INC_TFPFORHIST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPFORHIST
"SANKHYA".TRG_INC_TFPFORHIST
BEFORE INSERT ON TFPFORHIST
FOR EACH ROW

BEGIN 
    SELECT TFPFORHIST_SEQ.NEXTVAL
    INTO :NEW.CODHIST
    FROM DUAL;
END;

/
