-- SANKHYA.TRG_DLT_TFPSIN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPSIN
"SANKHYA".TRG_DLT_TFPSIN BEFORE DELETE ON TFPSIN FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODSIND = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
