-- SANKHYA.TRG_INC_UPD_TCSIE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSIE
"SANKHYA".TRG_INC_UPD_TCSIE 
BEFORE INSERT OR UPDATE ON TCSIE 
FOR EACH ROW

DECLARE 
    P_CODUSU INT;  
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
   
  IF INSERTING OR :NEW.CODVEND <> :OLD.CODVEND THEN
    SELECT MIN(USU.CODUSU) 
      INTO P_CODUSU
    FROM TSIUSU USU
       , TGFVEN VEN
    WHERE VEN.CODVEND = :NEW.CODVEND
      AND VEN.CODPARC = USU.CODPARC;
      
    :NEW.CODUSU := P_CODUSU; 
  END IF;
   
END;

/
