-- SANKHYA.TRG_DLT_TGFMAQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFMAQ
"SANKHYA".TRG_DLT_TGFMAQ
BEFORE DELETE ON TGFMAQ FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :OLD.CODMAQ = 0 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Registro padrão do sistema, não pode ser excluido.');
  END IF;  
  RETURN;
END;

/
