-- SANKHYA.TRG_DLT_TGFITE_TGFICO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_TGFICO
"SANKHYA".TRG_DLT_TGFITE_TGFICO
BEFORE DELETE ON TGFITE FOR EACH ROW

DECLARE  P_COUNT INT;
                P_NUNOTACO NUMBER(10);
                PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  BEGIN
    SELECT COUNT(1), NVL(NUNOTACO, 0)
      INTO P_COUNT , P_NUNOTACO
    FROM TGFICO ICO
    WHERE ICO.NUNOTAPO = :OLD.NUNOTA
      AND ICO.SEQUENCIAPO = :OLD.SEQUENCIA
    GROUP BY NUNOTACO;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_COUNT := 0;
  END;
    
  IF P_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(-20101,'É necessário excluir o Pedido Confirmed Order (C.O) ('||P_NUNOTACO||') vinculado.');
  END IF;     
  
  COMMIT;
END;

/
