-- SANKHYA.TRG_INC_UPD_DLT_TGFPMBSS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFPMBSS
"SANKHYA".TRG_INC_UPD_DLT_TGFPMBSS
BEFORE INSERT OR UPDATE OR DELETE
ON TGFPMBSS FOR EACH ROW

DECLARE
  P_VALIDAR   BOOLEAN;
  P_COUNT     INT;  
  P_CODUSU    TSIUSU.CODUSU%TYPE;
  
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  --sincronizacão de dados
  P_VALIDAR := Fpodevalidar('TGFPMBSS');  
  --Sincronizacão de dados não faz validacães
  IF NOT P_VALIDAR THEN
    RETURN;
  END IF;
  
  IF DELETING THEN
    P_CODUSU := STP_GET_CODUSULOGADO;
  ELSE
    P_CODUSU := :NEW.CODUSU;
  END IF;
  
  IF UPDATING OR DELETING THEN
    SELECT COUNT(1)
    INTO P_COUNT
    FROM TGFSALSS
    WHERE CNPJ = :OLD.CNPJ;
    
    IF P_COUNT = 0 AND UPDATING THEN
      INSERT INTO TGFSALSS (CNPJ, VLRTOTALCREDITO, CODUSU)
      VALUES (:OLD.CNPJ, :OLD.VALORFINALCRED, P_CODUSU);
    END IF;
    IF P_COUNT > 0 THEN
      UPDATE TGFSALSS
      SET VLRTOTALCREDITO = VLRTOTALCREDITO - :OLD.VALORFINALCRED
      , CODUSU = P_CODUSU
      , DHALTER = SYSDATE
      WHERE CNPJ = :OLD.CNPJ;
    END IF;
  END IF;
  
  IF INSERTING OR UPDATING THEN
    SELECT COUNT(1)
    INTO P_COUNT
    FROM TGFSALSS
    WHERE CNPJ = :NEW.CNPJ;

    IF P_COUNT = 0 THEN
      INSERT INTO TGFSALSS (CNPJ, VLRTOTALCREDITO, CODUSU) 
      VALUES (:NEW.CNPJ, :NEW.VALORFINALCRED, P_CODUSU); 
    ELSE
      UPDATE TGFSALSS 
      SET VLRTOTALCREDITO = VLRTOTALCREDITO + :NEW.VALORFINALCRED
      , CODUSU = P_CODUSU
      , DHALTER = SYSDATE
      WHERE CNPJ = :NEW.CNPJ;
    END IF;
  END IF;
  
END;

/
