-- SANKHYA.TRG_INC_UPD_TCEVAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCEVAR
"SANKHYA".TRG_INC_UPD_TCEVAR
BEFORE INSERT OR UPDATE ON TCEVAR 
FOR EACH ROW

DECLARE
       P_COUNT           INT := 0;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;


  IF :NEW.TABORIG = 'TCECAB' THEN  
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TCECAB
	  WHERE NUIMP = :NEW.NUNOTAORIG;
	  
	  IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR(-20101, 'A nota ' || :NEW.NUNOTAORIG || ' não é válida.' );
	  END IF;
  END IF;
  
  IF :NEW.TABDEST = 'TGFCAB' THEN  
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TGFCAB
	  WHERE NUNOTA = :NEW.NUNOTADEST;
	  
	  IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR(-20101, 'A nota ' || :NEW.NUNOTADEST || ' não é válida.' );
	  END IF;
  END IF;
  
  IF :NEW.TABORIG = 'TGFITE' THEN  
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TGFITE
	  WHERE NUNOTA = :NEW.NUNOTAORIG
	    AND SEQUENCIA = :NEW.SEQUENCIAORIG;
	  
	  IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR(-20101, 'A nota ' || :NEW.NUNOTAORIG || ', sequência '|| :NEW.SEQUENCIAORIG ||' não é válida.' );
	  END IF;
  END IF;
  
  IF :NEW.TABDEST = 'TCEITE' THEN  
	  SELECT COUNT(1) INTO P_COUNT
	  FROM TCEITE
	  WHERE NUIMP = :NEW.NUNOTADEST
	    AND SEQUENCIA = :NEW.SEQUENCIADEST;
	  
	  IF P_COUNT = 0 THEN
	    RAISE_APPLICATION_ERROR(-20101, 'A nota ' || :NEW.NUNOTADEST || ', sequência '|| :NEW.SEQUENCIADEST ||' não é válida.' );
	  END IF;
  END IF;    
END;

/
