-- SANKHYA.TRG_INC_TGMAIN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGMAIN
"SANKHYA".TRG_INC_TGMAIN BEFORE INSERT ON TGMAIN FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  IF :NEW.VLRUSADO > 0 THEN
    IF :NEW.PENDENTE = 'S' THEN
      :NEW.PENDENTE := 'N';
    END IF;
    
    SELECT COUNT(1)
      INTO P_COUNT
    FROM TGMAI
    WHERE NUAUTINV = :NEW.NUAUTINV;
    IF P_COUNT > 0 THEN
      UPDATE TGMAI SET VLRUSADO = VLRUSADO + :NEW.VLRUSADO 
      WHERE NUAUTINV = :NEW.NUAUTINV;
    END IF;
  ELSIF :NEW.VLRCOMPROMISSO > 0 AND :NEW.PENDENTE = 'S' THEN
    SELECT COUNT(1)
      INTO P_COUNT
    FROM TGMAI  
    WHERE NUAUTINV = :NEW.NUAUTINV;
    
    IF P_COUNT > 0 THEN 
      UPDATE TGMAI SET VLRCOMPROMISSO = VLRCOMPROMISSO + :NEW.VLRCOMPROMISSO 
      WHERE NUAUTINV = :NEW.NUAUTINV;
    END IF;
  END IF;
END ;

/
