-- SANKHYA.TRG_INC_TGFIMN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFIMN
"SANKHYA".TRG_INC_TGFIMN 
BEFORE INSERT ON TGFIMN 
FOR EACH ROW

DECLARE P_TIPOIMPOSTO TGFIMN.TIPOIMPOSTO%TYPE;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT IMC.TIPOIMPOSTO 
    INTO P_TIPOIMPOSTO 
  FROM TGFIMC IMC 
  WHERE IMC.CODIMP = :NEW.CODIMP;
  
  :NEW.TIPOIMPOSTO := P_TIPOIMPOSTO;
END;

/
