-- SANKHYA.TRG_DLT_TGFTRC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTRC
"SANKHYA".TRG_DLT_TGFTRC 
BEFORE DELETE ON TGFTRC 
FOR EACH ROW

DECLARE
PRAGMA AUTONOMOUS_TRANSACTION;
P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
  INTO P_COUNT
  FROM TGFFIN
  WHERE NUFIN = :OLD.NUFIN
    AND CODTIPTIT <> :OLD.CODTIPTITORIG
    AND CODEMPBAIXA <> :OLD.CODEMPBAIXAORIG;
  
  IF P_COUNT > 0 THEN
    UPDATE TGFFIN SET
       CODTIPTIT = :OLD.CODTIPTITORIG,
       CODEMPBAIXA = :OLD.CODEMPBAIXAORIG,
       CODCTABCOINT = :OLD.CODCTABCOINTORIG
    WHERE NUFIN = :OLD.NUFIN
      AND CODTIPTIT <> :OLD.CODTIPTITORIG
      AND CODEMPBAIXA <> :OLD.CODEMPBAIXAORIG;
  ELSE 
    UPDATE TGFFIN SET
       CODCTABCOINT = :OLD.CODCTABCOINTORIG
    WHERE 
       NUFIN = :OLD.NUFIN;
  END IF;

  COMMIT;
  
END;

/
