-- SANKHYA.TRG_DLT_TGFDRCSTR2110
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR2110
"SANKHYA".TRG_DLT_TGFDRCSTR2110
BEFORE DELETE ON TGFDRCSTR2110
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    IF VARIAVEIS_PKG.V_REPROCESSANDODRCST = 'S' THEN
        RETURN;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2111
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2111
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2112
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2112
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2113
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2113
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2120
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI2 = :OLD.REGPAI
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2120
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI2 = :OLD.REGPAI
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
