-- SANKHYA.TRG_DLT_TSIVARBD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIVARBD
"SANKHYA".TRG_DLT_TSIVARBD
AFTER DELETE
ON TSIVARBD
FOR EACH ROW

BEGIN
    RAISE_APPLICATION_ERROR(-20101, 'Esta linha não pode ser apagada.');
END;

/
