-- SANKHYA.TRG_INC_UPD_TCBSAL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCBSAL
"SANKHYA".TRG_INC_UPD_TCBSAL BEFORE INSERT OR UPDATE ON TCBSAL FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
    ERROR                  EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
IF UPDATING('CODCONPAR') THEN
   SELECT COUNT(1) INTO P_COUNT FROM TSIPAR WHERE UPPER(CHAVE) = 'CONSOLIDANDOEMP';
    IF (P_COUNT = 0) THEN
       SELECT COUNT(1) INTO P_COUNT FROM TCBPLA P WHERE P.CODCTACTB = :NEW.CODCTACTB
       AND P.ATIVA = 'S' AND P.ANALITICA = 'S';
       IF (P_COUNT = 0 ) THEN
         RAISE_APPLICATION_ERROR (-20101, 'Conta n?o Ativa ou n?o Cadastrada');
       END IF;
    END IF;
END IF;
IF UPDATING('CODCENCUS') THEN
   SELECT COUNT(1) INTO P_COUNT FROM  TSICUS C WHERE :NEW.CODCENCUS = C.CODCENCUS AND C.ATIVO = 'S' AND C.ANALITICO = 'S';
   IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Centro de Resultado n?o Ativo ou n?o Cadastrado');
   END IF;
END IF;
END;

/
