-- SANKHYA.BI_TBDATABASEINPUTENTRY
CREATE OR REPLACE TRIGGER SANKHYA.BI_TBDATABASEINPUTENTRY
"SANKHYA".BI_TBDATABASEINPUTENTRY 
BEFORE INSERT ON TBDATABASEINPUTENTRY
FOR EACH ROW

BEGIN
    SELECT TBDATABASEINPUTENTRY_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
