-- SANKHYA.TGF_INC_UPD_TGFCER
CREATE OR REPLACE TRIGGER SANKHYA.TGF_INC_UPD_TGFCER
"SANKHYA".TGF_INC_UPD_TGFCER 
BEFORE INSERT OR UPDATE ON TGFCER
FOR EACH ROW


DECLARE  
  P_SOLICITANTE     CHAR(30);
  P_COUNT           NUMBER(10);
  P_ERRMSG          VARCHAR2(255); 
  ERRMSG            VARCHAR2(255);
  ERROR             EXCEPTION;  
BEGIN

  IF :NEW.TIPO = 'U' AND :NEW.CHAVE = 0 THEN
      ERRMSG := 'Usuário SUP não pode ter validações';
      RAISE ERROR;
  END IF;  

  RETURN;   

EXCEPTION
  WHEN ERROR THEN
     RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
