-- SANKHYA.TRG_DLT_TPRMER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TPRMER
"SANKHYA".TRG_DLT_TPRMER
BEFORE DELETE
ON TPRMER
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

DECLARE
  P_COUNT              NUMBER(5);
BEGIN
 SELECT COUNT(1)
 INTO P_COUNT
 FROM TPRESR
 WHERE IDRPA = :OLD.IDRPA
  AND IDIPROC = :OLD.IDIPROC
  AND CODPRODPA = :OLD.CODPRODPA
  AND CONTROLEPA = :OLD.CONTROLEPA
  AND CODCPM = :OLD.CODCPM
  AND STATUSEXEC = :OLD.STATUSEXEC;

 IF (P_COUNT > 0) THEN
  UPDATE TPRESR SET
  ESTOQUE = ESTOQUE - ((NVL(:OLD.QTD, 0) + NVL(:OLD.QTDPERDA, 0)) * :OLD.SINAL),
  ESTOQUEPERDA = ESTOQUEPERDA - (NVL(:OLD.QTDPERDA, 0) * :OLD.SINAL)
  WHERE IDRPA = :OLD.IDRPA
   AND IDIPROC = :OLD.IDIPROC
   AND CODPRODPA = :OLD.CODPRODPA
   AND CONTROLEPA = :OLD.CONTROLEPA
   AND CODCPM = :OLD.CODCPM
   AND STATUSEXEC = :OLD.STATUSEXEC;

  SELECT COUNT(1)
  INTO P_COUNT
  FROM TPRESR
  WHERE IDRPA = :OLD.IDRPA
   AND IDIPROC = :OLD.IDIPROC
   AND CODPRODPA = :OLD.CODPRODPA
   AND CONTROLEPA = :OLD.CONTROLEPA
   AND CODCPM = :OLD.CODCPM
   AND STATUSEXEC = :OLD.STATUSEXEC
   AND ESTOQUE = 0;

  IF (P_COUNT > 0) THEN 
   DELETE FROM TPRESR
   WHERE IDRPA = :OLD.IDRPA
    AND IDIPROC = :OLD.IDIPROC
    AND CODPRODPA = :OLD.CODPRODPA
    AND CONTROLEPA = :OLD.CONTROLEPA
    AND CODCPM = :OLD.CODCPM
    AND STATUSEXEC = :OLD.STATUSEXEC;
  END IF;
 END IF; 
END;

/
