-- SANKHYA.TRG_DLT_TGFVOL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVOL
"SANKHYA".TRG_DLT_TGFVOL BEFORE DELETE ON TGFVOL FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODVOL = '0') THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
  
  -- INTEGRIDADE REFERENCIAL COM TGFUNP
  DELETE FROM TGFUNP WHERE CODVOL = :OLD.CODVOL;
  
END;

/
