-- SANKHYA.TRG_DEL_TGWEXU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGWEXU
"SANKHYA".TRG_DEL_TGWEXU
BEFORE DELETE ON TGWEXU
FOR EACH ROW		  
  
DECLARE P_COUNT       INTEGER;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 
	SELECT COUNT(1) INTO P_COUNT 
	FROM TGWEST
	WHERE CODEND = :OLD.CODEND 
	AND CODVOL = :OLD.CODVOL;		
	IF P_COUNT > 0 THEN
		RAISE_APPLICATION_ERROR(-20101, 'Impossível excluir. Existe estoque no endereço com esta unidade !');
	END IF; 			
END;

/
