-- SANKHYA.TRG_DLT_TGFVAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVAR
"SANKHYA".TRG_DLT_TGFVAR BEFORE DELETE ON TGFVAR FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

 IF ((:OLD.NUNOTAORIG <> :OLD.NUNOTA) AND (:OLD.QTDATENDIDA <> 0)) THEN
   INSERT INTO TGFVAR_DLT(NUNOTA, SEQUENCIA, NUNOTAORIG, SEQUENCIAORIG, QTDATENDIDA, FIXACAO)
   VALUES (:OLD.NUNOTA, :OLD.SEQUENCIA, :OLD.NUNOTAORIG, :OLD.SEQUENCIAORIG, :OLD.QTDATENDIDA, :OLD.FIXACAO);
  END IF;
END;

/
