-- SANKHYA.TRG_DLT_TFPDEP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPDEP
"SANKHYA".TRG_DLT_TFPDEP BEFORE DELETE ON TFPDEP FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.CODDEP = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;

/
