-- SANKHYA.TRG_INC_TFPAPO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPAPO
"SANKHYA".TRG_INC_TFPAPO
BEFORE INSERT ON TFPAPO
FOR EACH ROW

BEGIN
    SELECT TFPAPO_SEQ.NEXTVAL
    INTO :NEW.NUAJUSTE
    FROM DUAL
    END;
END;

/
