-- SANKHYA.TRG_DLT_TFPFOL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPFOL
"SANKHYA".TRG_DLT_TFPFOL 
BEFORE DELETE ON TFPFOL 
FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN 
	IF (:OLD.NUFIN IS NOT NULL) THEN
	  RAISE_APPLICATION_ERROR(-20101, 'Impossivel excluir. Evento (' || TO_CHAR(:OLD.CODEVENTO) || ') esta sendo referenciado pelo título (' ||TO_CHAR(:OLD.NUFIN) || ') na TGFFIN !');  
	END IF; 
    
	IF (:OLD.NUOCOR IS NOT NULL) THEN
    SELECT COUNT(1)
      INTO P_COUNT
    FROM TFPOCO
    WHERE NUOCOR = :OLD.NUOCOR;
  
    IF P_COUNT > 0 THEN
      DELETE FROM TFPOCO WHERE NUOCOR = :OLD.NUOCOR;
    END IF;
    
	END IF;     
    RETURN;
END;

/
