-- SANKHYA.TRG_DLT_UPD_TGFCUS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_UPD_TGFCUS
"SANKHYA".TRG_DLT_UPD_TGFCUS
BEFORE DELETE OR UPDATE
ON TGFCUS
FOR EACH ROW

DECLARE P_COUNT INT; 
BEGIN
  IF :OLD.DTATUAL < Variaveis_Pkg.V_DTLIMALTERCUSTO THEN
    IF Stp_Get_Atualizando THEN
      RETURN;
    END IF;

    SELECT COUNT(1) 
    INTO P_COUNT
    FROM TSIPAR
    WHERE CHAVE = 'SBPRODUTO';
    IF (P_COUNT = 0) OR NOT (VARIAVEIS_PKG.V_SBPRODUTO) THEN
      RAISE_APPLICATION_ERROR(-20101,'Não é permitido excluir/alterar custo com data anterior a '|| TO_CHAR(Variaveis_Pkg.V_DTLIMALTERCUSTO)|| ', conforme definido no parâmetro DIASLIMALTCUSTO.');
    END IF;  
  END IF;   
END;

/
