-- SANKHYA.TRG_DLT_TFPGRA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPGRA
"SANKHYA".TRG_DLT_TFPGRA BEFORE DELETE ON TFPGRA
FOR EACH ROW

BEGIN
  IF (:OLD.CODGRAT = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;
/
