-- SANKHYA.TRG_DLT_TGFAJI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFAJI
"SANKHYA".TRG_DLT_TGFAJI
BEFORE DELETE ON TGFAJI FOR EACH ROW

DECLARE P_COUNT NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFIJI
    WHERE NUNOTA = :OLD.NUNOTA;
    IF P_COUNT > 0 THEN
        DELETE FROM TGFIJI    WHERE NUNOTA = :OLD.NUNOTA;
    END IF;
END;

/
