-- SANKHYA.TRG_INC_UPD_TGFIFE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFIFE
"SANKHYA".TRG_INC_UPD_TGFIFE
BEFORE INSERT OR UPDATE ON TGFIFE
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :NEW.NOMEIMP = 'CSLL' THEN
    :NEW.NOMEIMP := 'CSSL';
  END IF;
END;

/
