-- SANKHYA.TRG_DLT_TFPMED
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPMED
"SANKHYA".TRG_DLT_TFPMED 
BEFORE DELETE ON TFPMED 
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 
  DELETE 
  FROM TFPRMD
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND REFERENCIA = :OLD.REFERENCIA
  AND ORIGEM = :OLD.ORIGEM
  AND TIPOMEDIA = :OLD.TIPOMEDIA;

END;

/
