-- SANKHYA.TRG_INC_TGFCGM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFCGM
"SANKHYA".TRG_INC_TGFCGM
BEFORE INSERT ON TGFCGM
FOR EACH ROW

BEGIN

  IF :NEW.DTREF IS NOT NULL THEN  
    :NEW.DTREF := TRUNC(:NEW.DTREF, 'MM'); 
    :NEW.ANO := TO_NUMBER(TO_CHAR(:NEW.DTREF, 'YYYY'));
    :NEW.MES := TO_NUMBER(TO_CHAR(:NEW.DTREF, 'MM'));  
  END IF;

END;

/
