-- SANKHYA.TRG_DLT_TGFITE_TGFCUSITE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_TGFCUSITE
"SANKHYA".TRG_DLT_TGFITE_TGFCUSITE
BEFORE DELETE ON TGFITE FOR EACH ROW

DECLARE
    ERRMSG                     VARCHAR2(255);
    ERROR                      EXCEPTION;
    P_VALIDAR                  BOOLEAN;
    P_COUNT                    INT:= 0;
    
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  /* 
  sincronização de dados
  */
  P_VALIDAR := Fpodevalidar('TGFITE');
  -- OS 916248
  BEGIN
      SELECT COUNT(*) INTO P_COUNT 
      FROM TGFCUSITE 
      WHERE NUNOTA = :OLD.NUNOTA
      AND SEQUENCIA = :OLD.SEQUENCIA;
  EXCEPTION
      WHEN NO_DATA_FOUND THEN
        P_COUNT := 0;
  END;

  IF P_COUNT > 0 THEN 
      DELETE FROM TGFCUSITE 
      WHERE NUNOTA = :OLD.NUNOTA
      AND SEQUENCIA = :OLD.SEQUENCIA;
  END IF; 
  -- OS 916248

EXCEPTION
  WHEN ERROR THEN
    IF (P_VALIDAR) THEN 
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF; 
END;

/
