-- SANKHYA.TRG_DLT_TGMAIN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGMAIN
"SANKHYA".TRG_DLT_TGMAIN BEFORE DELETE ON TGMAIN FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

    IF :OLD.VLRUSADO > 0 THEN
     UPDATE TGMAI SET VLRUSADO = VLRUSADO - :OLD.VLRUSADO
     WHERE NUAUTINV = :OLD.NUAUTINV;
    ELSIF :OLD.VLRCOMPROMISSO > 0 AND :OLD.PENDENTE = 'S' THEN
     UPDATE TGMAI SET VLRCOMPROMISSO = VLRCOMPROMISSO - :OLD.VLRCOMPROMISSO
     WHERE NUAUTINV = :OLD.NUAUTINV;
    END IF;
END ;

/
