-- SANKHYA.TRG_INC_TC_LOG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TC_LOG
"SANKHYA".TRG_INC_TC_LOG
BEFORE INSERT ON TC_LOG
FOR EACH ROW

DECLARE
 BEGIN
       SELECT SEQ_TC_LOG_IDLINHA.NEXTVAL INTO :NEW.IDLINHA FROM DUAL;
  END;

/
