-- SANKHYA.TRG_INC_UPD_TGFPDV_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPDV_AFTER
TRG_INC_UPD_TGFPDV_AFTER
AFTER INSERT OR UPDATE ON TGFPDV

DECLARE
    v_count INTEGER;
BEGIN
    
    SELECT COUNT(*)
    INTO v_count
    FROM TGFPDV
    WHERE LOWER(IDMAQUINALOCAL) IS NOT NULL
    GROUP BY LOWER(IDMAQUINALOCAL)
    HAVING COUNT(*) > 1;

    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Já existe um registro com esta Identificação PDV.');
    END IF;

EXCEPTION
    
    WHEN NO_DATA_FOUND THEN
        NULL; 
END;

/
