-- SANKHYA.TRG_INC_TFPACD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPACD
TRG_INC_TFPACD
BEFORE INSERT ON TFPACD
FOR EACH ROW

BEGIN
    SELECT TFPACD_SEQ.NEXTVAL
    INTO :NEW.ID
    FROM DUAL
    END;
END;

/
