-- SANKHYA.TRG_DLT_TFPDPD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPDPD
"SANKHYA".TRG_DLT_TFPDPD
BEFORE DELETE  ON TFPDPD 
FOR EACH ROW

DECLARE 
  P_COUNT       INTEGER;
BEGIN
 
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TFPPLS
  WHERE  CODEMP = :OLD.CODEMP
    AND CODFUNC = :OLD.CODFUNC
    AND SEQUENCIA = :OLD.SEQUENCIA;
  IF (P_COUNT <> 0) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Registro não pode ser excluído, existe referência Plano de Saúde.');
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TFPVPS
  WHERE  CODEMP = :OLD.CODEMP
    AND CODFUNC = :OLD.CODFUNC
    AND SEQUENCIA = :OLD.SEQUENCIA;
  IF (P_COUNT <> 0) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Registro não pode ser excluído, existe referência Plano de Saúde.');
  END IF;
END;

/
