-- SANKHYA.TRG_DLT_TGFVEN_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVEN_AFTER
"SANKHYA".TRG_DLT_TGFVEN_AFTER AFTER DELETE ON TGFVEN 
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF; 
  SELECT COUNT(1)
      INTO P_COUNT
  FROM TSIREG 
  WHERE CODVEND = :OLD.CODVEND;  
  IF P_COUNT > 0 THEN
    UPDATE TSIREG SET CODVEND = NULL WHERE CODVEND = :OLD.CODVEND;  
  END IF;

  SELECT COUNT(1)
      INTO P_COUNT
  FROM TGFVIS 
  WHERE CODVEND = :OLD.CODVEND; 
  IF P_COUNT > 0 THEN
    DELETE FROM TGFVIS WHERE CODVEND = :OLD.CODVEND; 
  END IF;
END;

/
