-- SANKHYA.TRG_INC_TGFFRE_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFFRE_SEQ
"SANKHYA".TRG_INC_TGFFRE_SEQ
BEFORE INSERT ON TGFFRE
FOR EACH ROW 
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

 SELECT SEQ_TGFFRE_SEQUENCIA.NEXTVAL INTO :NEW.SEQUENCIA FROM DUAL;
END;

/
