-- SANKHYA.TRG_FX_TFXPFE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXPFE
"SANKHYA".TRG_FX_TFXPFE
   BEFORE INSERT OR UPDATE
   ON TFXPFE
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
