-- SANKHYA.TRG_INC_UPD_TGFANC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFANC
"SANKHYA".TRG_INC_UPD_TGFANC BEFORE INSERT OR UPDATE ON TGFANC
FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
BEGIN
  SELECT COUNT(1) INTO P_COUNT FROM TGFITC WHERE NUMCOTACAO = :NEW.NUMCOTACAO 
                                             AND CODPROD    = :NEW.CODPROD
               		        				 AND CONTROLE   = :NEW.CONTROLE 
				                    		 AND CODLOCAL   = :NEW.CODLOCAL;
  IF (P_COUNT = 0 ) THEN
    RAISE_APPLICATION_ERROR (-20101, 'Item não cadastro na tabela TGFITC.');
  END IF;
	
END;

/
