-- SANKHYA.TRG_DLT_TGFDIRFBPJDEC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDIRFBPJDEC
"SANKHYA".TRG_DLT_TGFDIRFBPJDEC
BEFORE DELETE ON TGFDIRFBPJDEC
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFPJRTRT
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPJRTRT
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFPJRTIRF
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPJRTIRF
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFBASEBPJDEC
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFBASEBPJDEC
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CNPJ = :OLD.CNPJ;
    END IF;
END;

/
