-- SANKHYA.TRG_INC_UPD_TGFSEU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFSEU
"SANKHYA".TRG_INC_UPD_TGFSEU 
BEFORE INSERT OR UPDATE ON TGFSEU
FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
    ERROR                  EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODPROD') THEN
     SELECT COUNT(1) INTO P_COUNT FROM TGFPRO WHERE CODPROD = :NEW.CODPROD AND ATIVO = 'S' AND USOPROD <> 'S';
     IF ( P_COUNT = 0 ) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_PRODUTO_NAO_ATIV_EXIST);
     END IF;
  END IF;	 
  IF UPDATING('CODSERV') THEN 
     SELECT COUNT(1) INTO P_COUNT FROM TGFPRO WHERE CODPROD = :NEW.CODSERV AND ATIVO = 'S' AND USOPROD = 'S';  
     IF ( P_COUNT = 0 ) THEN
        RAISE_APPLICATION_ERROR (-20101, ERROS_PKG.ERRO_SERVICO_NAO_ATIV_EXIST);
     END IF;
  END IF;	 
END;

/
