-- SANKHYA.TRG_INC_TGFVEN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFVEN
"SANKHYA".TRG_INC_TGFVEN BEFORE INSERT ON TGFVEN FOR EACH ROW

DECLARE
  P_COUNT                  INT:= 0;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFPAR
  WHERE CODPARC = :NEW.CODPARC
    AND ATIVO = 'S';
  IF (P_COUNT = 0 ) THEN
    Stp_Popula_Msg('TGFPAR');
  END IF;
  IF :NEW.CODEMP IS NOT NULL THEN 
    SELECT COUNT(1) INTO P_COUNT
    FROM  TGFEMP
    WHERE CODEMP = :NEW.CODEMP
      AND ATIVO = 'S';
  END IF;
  IF  (P_COUNT = 0) THEN
    Stp_Popula_Msg('TGFEMP');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TFPHOR
  WHERE CODCARGAHOR = :NEW.CODCARGAHOR;
  IF  (P_COUNT = 0) AND (:NEW.CODCARGAHOR <> 0) THEN
    RAISE_APPLICATION_ERROR (-20101, 'Carga Horaria n?o Cadastrada');
  END IF;
END;

/
