-- SANKHYA.TRG_DLT_TGPFCP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGPFCP
"SANKHYA".TRG_DLT_TGPFCP
AFTER DELETE ON TGPFCP FOR EACH ROW

BEGIN

    DELETE FROM TGPFCF 
    WHERE CODFUNCAO = :OLD.CODFUNCAO 
      AND CODPERFIL = :OLD.CODCOMPETENCIA;

END;

/
