-- SANKHYA.TRG_DLT_TGWITT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWITT
"SANKHYA".TRG_DLT_TGWITT 
AFTER DELETE ON TGWITT
FOR EACH ROW

DECLARE P_COUNT      NUMBER(10);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGWITTA
  WHERE NUTAREFA = :OLD.NUTAREFA 
    AND SEQUENCIA = :OLD.SEQUENCIA;
  IF P_COUNT > 0 THEN
    DELETE FROM TGWITTA
    WHERE NUTAREFA = :OLD.NUTAREFA 
     AND SEQUENCIA = :OLD.SEQUENCIA;
  END IF;

  SELECT COUNT(1) INTO P_COUNT  
  FROM TGWLBO
  WHERE NUTAREFA = :OLD.NUTAREFA
    AND SEQTAREFA = :OLD.SEQUENCIA;

  IF P_COUNT <> 0 THEN
    DELETE FROM TGWLBO
    WHERE NUTAREFA = :OLD.NUTAREFA
      AND SEQTAREFA = :OLD.SEQUENCIA;
  END IF;

  SELECT COUNT(1) INTO P_COUNT  
  FROM TGWITTVAL
  WHERE NUTAREFA = :OLD.NUTAREFA
    AND SEQUENCIA = :OLD.SEQUENCIA;

  IF P_COUNT <> 0 THEN
    DELETE FROM TGWITTVAL
    WHERE NUTAREFA = :OLD.NUTAREFA
      AND SEQUENCIA = :OLD.SEQUENCIA;
  END IF;
  
END;

/
