-- SANKHYA.TRG_INC_UPD_TCSSER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSSER
"SANKHYA".TRG_INC_UPD_TCSSER BEFORE INSERT OR UPDATE ON TCSSER
FOR EACH ROW

DECLARE
    P_COUNT      INT:=0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODPROD') THEN  
     SELECT COUNT(1) INTO  P_COUNT
       FROM TGFPRO
      WHERE CODPROD = :NEW.CODPROD AND USOPROD = 'S';
     IF (P_COUNT = 0 ) THEN
        RAISE_APPLICATION_ERROR (-20101, 'Deve ser informado um Serviço.');
     END IF;
  END IF;
  
  IF UPDATING('CODNAT') THEN
     SELECT COUNT(1) INTO  P_COUNT
       FROM TGFNAT
      WHERE CODNAT = :NEW.CODNAT
        AND ATIVA = 'S'
        AND ANALITICA = 'S';
     IF (P_COUNT = 0) THEN
        RAISE_APPLICATION_ERROR(-20101,ERROS_PKG.ERRO_NAT_ATIV_ANALI_EXIST);
     END IF;
  END IF;
END;

/
