-- SANKHYA.TRG_INC_UPD_TGFVCE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFVCE
"SANKHYA".TRG_INC_UPD_TGFVCE BEFORE INSERT OR UPDATE ON TGFVCE REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
  P_COUNT     INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFEMP
  WHERE CODEMP = :NEW.CODEMP
    AND ATIVO = 'S';
  IF UPDATING('CODEMP') AND (P_COUNT = 0) THEN
      Stp_Popula_Msg('TGFEMP');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFLOC
  WHERE CODLOCAL = :NEW.CODLOCAL
  AND ATIVO = 'S'
  AND ANALITICO = 'S';
  IF UPDATING('CODLOCAL') AND (P_COUNT = 0) THEN
     Stp_Popula_Msg('TGFLOC');
  END IF;
  SELECT COUNT(1) INTO P_COUNT
  FROM  TGFPRO
  WHERE CODPROD = :NEW.CODPROD
  AND ATIVO = 'S';
  IF UPDATING('CODPROD') AND (P_COUNT = 0) THEN
      Stp_Popula_Msg('TGFPRO');
  END IF;
END;

/
