-- SANKHYA.TRG_DLT_TCBINT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCBINT
"SANKHYA".TRG_DLT_TCBINT 
BEFORE DELETE ON TCBINT 
FOR EACH ROW

DECLARE
  P_VALIDAR      BOOLEAN;
BEGIN
  IF Stp_Get_Atualizando THEN
    RETURN;
  END IF;
  
  /* 
  Sincronização de dados
  */
  P_VALIDAR := Fpodevalidar('TCBINT');
  
  IF :OLD.ORIGEM = '2' THEN
    UPDATE TGFFIN SET PDD = 'S' WHERE NUFIN = :OLD.NUNICO;
  END IF;

END;

/
