-- SANKHYA.TRG_INC_DLT_TFPFAL_FALTPER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_DLT_TFPFAL_FALTPER
"SANKHYA".TRG_INC_DLT_TFPFAL_FALTPER
BEFORE INSERT OR DELETE ON TFPFAL
FOR EACH ROW

DECLARE
	P_DTINIAQUI DATE;
    P_DTFINAQUI DATE;
    P_FALTAS NUMBER;
	P_CODEMP NUMBER;
	P_CODFUNC NUMBER;
    P_DESABILITAR_TRIGGER NUMBER;
    P_DTFALTA DATE;
BEGIN
    IF STP_GET_ATUALIZANDO THEN
        RETURN;
     END IF;

    SELECT COUNT(1) INTO P_DESABILITAR_TRIGGER
    FROM TSIPAR 
    WHERE CHAVE = 'DISABLEDTRGFER'
    AND LOGICO = 'S';

    IF (P_DESABILITAR_TRIGGER > 0) THEN
      RETURN;
    END IF;

    IF (INSERTING) THEN
		P_CODEMP := :NEW.CODEMP;
		P_CODFUNC := :NEW.CODFUNC;
        P_DTFALTA := :NEW.DTFALTA;
    ELSIF(DELETING) THEN
		P_CODEMP := :OLD.CODEMP;
		P_CODFUNC := :OLD.CODFUNC;
        P_DTFALTA := :OLD.DTFALTA;
    END IF;
	
    BEGIN
	  SELECT DTINIAQUI, DTFINAQUI INTO P_DTINIAQUI, P_DTFINAQUI
	  FROM TFPFER
	  WHERE 
	     CODEMP = P_CODEMP 
	     AND CODFUNC = P_CODFUNC
	     AND DTSAIDA IS NULL
	     AND ATUALFERGOZ='N'
         AND P_DTFALTA >= DTINIAQUI AND P_DTFALTA <= DTFINAQUI;
      EXCEPTION WHEN NO_DATA_FOUND THEN
      P_DTINIAQUI:= NULL; 
      P_DTFINAQUI := NULL;  
    END;

    IF (P_DTINIAQUI IS NOT NULL) AND (P_DTFINAQUI IS NOT NULL) THEN
       INSERT INTO TFPFAL_INC_DLT (CODEMP, CODFUNC, DTINIAQUI, DTFINAQUI) VALUES(P_CODEMP, P_CODFUNC, P_DTINIAQUI, P_DTFINAQUI);
    END IF;
 END;

/
