-- SANKHYA.TRG_INC_TGFNUM_INC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFNUM_INC
"SANKHYA".TRG_INC_TGFNUM_INC
AFTER INSERT ON TGFNUM_INC 
FOR EACH ROW

DECLARE
    P_COUNT     NUMBER(05);
    P_VALIDAR   BOOLEAN;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  P_VALIDAR := FPODEVALIDAR('TGFNUM_INC');
  IF P_VALIDAR THEN
    RETURN;
  END IF;

  SELECT COUNT(*) INTO P_COUNT
  FROM TGFNUM I 
  WHERE I.ARQUIVO = :NEW.ARQUIVO 
    AND I.CODEMP = :NEW.CODEMP
    AND I.SERIE = :NEW.SERIE
    AND I.CODMODDOC = :NEW.CODMODDOC;
    
  IF P_COUNT = 0 THEN

    INSERT INTO TGFNUM (ARQUIVO, CODEMP, SERIE, CODMODDOC, NOMEARQ, AUTOMATICO, ULTCOD, TIPOIMPRESSORA, IMPNOTA, TOTITENSNOTA,
                        TOTSERVNOTA, ULTNOTATALAO, MODNOTAFIS, QTDAVISO, CODMAQ, DIASAVISO, DTVAL)
                VALUES (:NEW.ARQUIVO, :NEW.CODEMP, :NEW.SERIE, :NEW.CODMODDOC, :NEW.NOMEARQ, :NEW.AUTOMATICO, :NEW.ULTCOD, :NEW.TIPOIMPRESSORA, :NEW.IMPNOTA, :NEW.TOTITENSNOTA,
                        :NEW.TOTSERVNOTA, :NEW.ULTNOTATALAO, :NEW.MODNOTAFIS, :NEW.QTDAVISO, :NEW.CODMAQ, :NEW.DIASAVISO, :NEW.DTVAL);    

    COMMIT;
  END IF;
  
END;

/
