-- SANKHYA.TRG_FX_TGFGRU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFGRU
"SANKHYA".TRG_FX_TGFGRU
   BEFORE INSERT OR UPDATE
   ON TGFGRU
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
   
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;
     /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFGRU');

   IF (NOT P_VALIDAR)
   THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;


   IF (   (NVL (:NEW.CODGRUPOPROD, 0) <> NVL (:OLD.CODGRUPOPROD, 0))
       OR (:NEW.GRUPOICMS <> :OLD.GRUPOICMS)
       OR (:NEW.PERCCMTNAC <> :OLD.PERCCMTNAC)
       OR (:NEW.PERCCMTIMP <> :OLD.PERCCMTIMP)
       OR (:NEW.ALIQNAC <> :OLD.ALIQNAC)
       OR (:NEW.ALIQIMP <> :OLD.ALIQIMP)
       OR (:NEW.PERCCMTFED <> :OLD.PERCCMTFED)
       OR (:NEW.PERCCMTEST <> :OLD.PERCCMTEST)
       OR (:NEW.PERCCMTMUN <> :OLD.PERCCMTMUN))
   THEN
      SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

      :NEW.NUVERSAO := P_CONTADOR;
   END IF;
END;

/
