-- SANKHYA.TRG_DLT_TGFVEI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFVEI
"SANKHYA".TRG_DLT_TGFVEI BEFORE DELETE ON TGFVEI REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    ERROR                    EXCEPTION;
    ERRMSG                   VARCHAR2(255);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODVEICULO = 0 ) THEN
      ERRMSG := 'Registro padrao do sistema. Nao pode ser excluido.';
      RAISE ERROR;
  END IF;
  EXCEPTION
    WHEN ERROR THEN
    raise_application_error(-20101, ERRMSG);
END;

/
