-- SANKHYA.DDL_OBJETOS
CREATE OR REPLACE TRIGGER SANKHYA.DDL_OBJETOS
"SANKHYA".DDL_OBJETOS
BEFORE CREATE OR ALTER OR DROP
ON SCHEMA


DECLARE
    SQL_TEXT        ORA_NAME_LIST_T;
    TEXTO_SQL       CLOB;
    I               PLS_INTEGER;
    V_NOMEMAQUINA   VARCHAR2(60);

BEGIN
    I := SQL_TXT(SQL_TEXT);
    
    SELECT userenv('TERMINAL') INTO V_NOMEMAQUINA FROM DUAL;
      
    FOR N IN 1..I LOOP
        TEXTO_SQL := TEXTO_SQL || SQL_TEXT(N);
    END LOOP;

    INSERT INTO DDL_LOG
        SELECT ORA_SYSEVENT, ORA_DICT_OBJ_OWNER,
        ORA_DICT_OBJ_NAME, TEXTO_SQL, USER, SYSDATE,
        V_NOMEMAQUINA
        FROM DUAL;

END;

/
