-- SANKHYA.TRG_DLT_TGFDRCSTRH005
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTRH005
"SANKHYA".TRG_DLT_TGFDRCSTRH005
BEFORE DELETE ON TGFDRCSTRH005
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    IF VARIAVEIS_PKG.V_REPROCESSANDODRCST = 'S' THEN
        RETURN;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTRH010
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI = :OLD.REG
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTRH010
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI = :OLD.REG
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
