-- SANKHYA.TRG_DLT_TCSITE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSITE
"SANKHYA".TRG_DLT_TCSITE
BEFORE DELETE
ON TCSITE
FOR EACH ROW

DECLARE
	P_COUNT   	  	   NUMBER(10) := 0;
	P_NUFIN			   NUMBER(10);
	P_CODFUNC		   NUMBER(10);
    P_VALIDAR 		   BOOLEAN;	
    ERROR             EXCEPTION;	
    ERRMSG            VARCHAR2(255);	
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
	/* 
	Sincronização de dados
	*/
    P_VALIDAR := Fpodevalidar('TCSITE');

	SELECT COUNT(1) 
	INTO P_COUNT
	FROM TGFCOM
	WHERE NUMOSORIG = :OLD.NUMOS
	AND NUMITEMORIG = :OLD.NUMITEM;
	
	IF (P_COUNT>0) THEN
		SELECT NVL(MAX(NUFIN),0), NVL(MAX(CODFUNC),0) 
		INTO P_NUFIN,  P_CODFUNC
		FROM TGFCOM
		WHERE NUMOSORIG = :OLD.NUMOS
		AND NUMITEMORIG = :OLD.NUMITEM;
		
		IF ((P_NUFIN <> 0) OR (P_CODFUNC <> 0))	THEN
		   ERRMSG :=  'Essa comissão já foi paga. Exclusão proibida.';
		   RAISE ERROR;	   
		ELSE 
		   DELETE FROM TGFCOM 		
		   WHERE NUMOSORIG = :OLD.NUMOS
		     AND NUMITEMORIG = :OLD.NUMITEM;
		END IF;
	END IF;	
  RETURN;
EXCEPTION
  WHEN ERROR THEN
    /* 
    Sincronização de dados não faz validações
    */
    IF (P_VALIDAR) THEN 
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF; 
END;

/
