-- SANKHYA.TRG_INC_TFPFUN_TGPFCF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPFUN_TGPFCF
"SANKHYA".TRG_INC_TFPFUN_TGPFCF
AFTER INSERT ON TFPFUN FOR EACH ROW

BEGIN

    INSERT INTO TGPFCF (CODFUNCAO, CODPERFIL, CODEMP, CODFUNC, CODUSU, DHALTER)
    SELECT FCP.CODFUNCAO, FCP.CODCOMPETENCIA, :NEW.CODEMP, :NEW.CODFUNC, 0, SYSDATE
    FROM TGPFCP FCP
    WHERE FCP.CODFUNCAO = :NEW.CODFUNCAO;

END;

/
