-- SANKHYA.TRG_INC_TFPNEWFORM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPNEWFORM
"SANKHYA".TRG_INC_TFPNEWFORM
BEFORE INSERT ON TFPNEWFORM
FOR EACH ROW


BEGIN SELECT TFPNEWFORM_SEQ.NEXTVAL
    INTO :NEW.CODFORM
    FROM DUAL;
END;

/
