-- SANKHYA.TRG_INC_TGFNUM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFNUM
"SANKHYA".TRG_INC_TGFNUM
AFTER INSERT ON TGFNUM 
FOR EACH ROW

DECLARE
    P_COUNT     NUMBER(05);
    P_VALIDAR   BOOLEAN;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  BEGIN
      SELECT COUNT(*) 
      INTO P_COUNT
      FROM TSDPAR;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_COUNT := 0;
  END;

  IF P_COUNT = 0 THEN
    RETURN;
  END IF;

  P_VALIDAR := FPODEVALIDAR('TGFNUM_INC');
  IF NOT P_VALIDAR THEN
    RETURN;
  END IF;

  SELECT COUNT(*) INTO P_COUNT
  FROM TGFNUM_INC I 
  WHERE I.ARQUIVO = :NEW.ARQUIVO 
    AND I.CODEMP = :NEW.CODEMP
    AND I.SERIE = :NEW.SERIE
    AND I.CODMODDOC = :NEW.CODMODDOC;
    
  IF P_COUNT = 0 THEN

    INSERT INTO TGFNUM_INC (ARQUIVO, CODEMP, SERIE, CODMODDOC, NOMEARQ, AUTOMATICO, ULTCOD, TIPOIMPRESSORA, IMPNOTA, TOTITENSNOTA,
                            TOTSERVNOTA, ULTNOTATALAO, MODNOTAFIS, QTDAVISO, CODMAQ, DIASAVISO, DTVAL)
                    VALUES (:NEW.ARQUIVO, :NEW.CODEMP, :NEW.SERIE, :NEW.CODMODDOC, :NEW.NOMEARQ, :NEW.AUTOMATICO, :NEW.ULTCOD, :NEW.TIPOIMPRESSORA, :NEW.IMPNOTA, :NEW.TOTITENSNOTA,
                            :NEW.TOTSERVNOTA, :NEW.ULTNOTATALAO, :NEW.MODNOTAFIS, :NEW.QTDAVISO, :NEW.CODMAQ, :NEW.DIASAVISO, :NEW.DTVAL);    

    COMMIT;
  END IF;
  
END;

/
