-- SANKHYA.TRG_INC_UPD_TCENCM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCENCM
"SANKHYA".TRG_INC_UPD_TCENCM 
BEFORE INSERT OR UPDATE ON TCENCM FOR EACH ROW

DECLARE P_COUNT   NUMBER(10);
        P_VALIDAR BOOLEAN;
BEGIN
  P_VALIDAR := Fpodevalidar('TGFCAB');
  
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  IF (NVL(:NEW.CODENQIPIENT, 0) <> NVL(:OLD.CODENQIPIENT, 0) OR NVL(:NEW.CSTIPI, 0) <> NVL(:OLD.CSTIPI, 0)) THEN
    STP_VALIDA_ENQUADRAMENTO_IPI(:NEW.CSTIPI, :NEW.CODENQIPIENT);
  END IF;

  IF :NEW.CODEMP <> 0 AND (INSERTING OR :NEW.CODEMP <> :OLD.CODEMP) THEN
    BEGIN
      SELECT 1 INTO P_COUNT
      FROM TGFEMP
      WHERE CODEMP = :NEW.CODEMP
        AND ATIVO = 'S';
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 AND P_VALIDAR THEN
      RAISE_APPLICATION_ERROR(-20101, 'A empresa que está sendo inserida não existe ou não está ativa.');
    END IF;      
  END IF;

END;

/
