-- SANKHYA.TRG_DLT_TGFISS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFISS
"SANKHYA".TRG_DLT_TGFISS BEFORE DELETE ON TGFISS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE P_COUNT INT;
BEGIN
  IF (:OLD.CODPROD <>0) AND (:OLD.PERCINSS <>0) THEN
    SELECT
     COUNT(1)
    INTO
     P_COUNT
    FROM
     TGFITE ITE,
     TGFCAB CAB,
     TSIEMP EMP
    WHERE ITE.NUNOTA  = CAB.NUNOTA
    AND CAB.CODEMP    = EMP.CODEMP
    AND CAB.ISSRETIDO = 'N'
    AND ITE.USOPROD   = 'S'
    AND CAB.VLRISS    > 0
    AND EMP.CODCID    = :OLD.CODCID
    AND ITE.CODPROD   = :OLD.CODPROD
    AND ITE.CODEMP    = :OLD.CODEMP;
    IF (P_COUNT IS NULL) OR (P_COUNT=0) THEN
      SELECT
       COUNT(1)
      INTO
       P_COUNT
      FROM
       TGFITE ITE,
       TGFCAB CAB,
       TGFPAR PAR
      WHERE ITE.NUNOTA  = CAB.NUNOTA
      AND CAB.CODPARC   = PAR.CODPARC
      AND CAB.ISSRETIDO = 'S'
      AND ITE.USOPROD   = 'S'
      AND CAB.VLRISS    > 0
      AND PAR.CODCID    = :OLD.CODCID
      AND ITE.CODPROD   = :OLD.CODPROD
      AND ITE.CODEMP    = :OLD.CODEMP;
    END IF;
    IF (P_COUNT IS NOT NULL) AND (P_COUNT>0) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Nao pode ser excluido a aliquota de ISS, existe referencia nos movimentos.');
    END IF;
  END IF;
END;

/
