-- SANKHYA.TRG_INC_UPD_TGFITE_VERIFCORTE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFITE_VERIFCORTE
"SANKHYA".TRG_INC_UPD_TGFITE_VERIFCORTE BEFORE INSERT OR UPDATE ON TGFITE FOR EACH ROW

DECLARE
  P_PERMITECORTE   VARCHAR2(1);
  P_VALIDAR        BOOLEAN;
  P_COUNT          NUMBER(05);
BEGIN
   BEGIN


  -- VERIFICANDO SE O CLIENTE UTILIZA ESTA FUNCIONALIDADE
  SELECT COUNT(*) INTO P_COUNT
  FROM TSIVARBD
  WHERE UTILIZA_VERIFCORTE = 'N';
  IF P_COUNT > 0 THEN 
    RETURN;
  END IF;

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  P_VALIDAR := Fpodevalidar('TGFITE');
  IF (NOT P_VALIDAR) THEN
    RETURN;
  END IF;
  
     SELECT PAR.PERMITECORTE INTO P_PERMITECORTE
     FROM TGFPAR PAR, TGFCAB CAB
     WHERE PAR.CODPARC = CAB.CODPARC
     AND CAB.NUNOTA = :NEW.NUNOTA;
   EXCEPTION WHEN NO_DATA_FOUND THEN
     RETURN;
   END;
   IF P_PERMITECORTE <> 'S' THEN
     RAISE_APPLICATION_ERROR(-20101, 'Corte não permitido para o parceiro deste pedido.');
   END IF;
END;

/
