-- SANKHYA.TRG_INC_UPD_TGFTOD
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFTOD
"SANKHYA".TRG_INC_UPD_TGFTOD
BEFORE INSERT OR UPDATE ON TGFTOD  FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO  P_COUNT
    FROM TGFTOP
   WHERE CODTIPOPER = :NEW.CODTIPOPER;
   
  IF (P_COUNT = 0) THEN
     RAISE_APPLICATION_ERROR(-20101, ERROS_PKG.ERRO_TIPOPER_NAOEXISTE);
  END IF;
END;

/
