-- SANKHYA.TRG_DLT_TCBLAN_AFTER_STATEMENT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCBLAN_AFTER_STATEMENT
TRG_DLT_TCBLAN_AFTER_STATEMENT
AFTER DELETE ON TCBLAN

BEGIN
  FOR rec_origem IN (SELECT CODEMP_ORIG, REFERENCIA_ORIG, NUMLOTE_ORIG, NUMLANC_ORIG, SEQUENCIA_ORIG, TIPLANC_ORIG FROM TCBLAN_UPD) LOOP
    UPDATE TCBLAN
    SET INDESTORNADO = CASE
                        WHEN INDESTORNADO = 'A' THEN 'S'
                        WHEN INDESTORNADO = 'F' THEN 'N'
                        ELSE INDESTORNADO
                       END,
        CODRASTROESTORNO = NULL
    WHERE CODEMP = rec_origem.CODEMP_ORIG
      AND REFERENCIA = rec_origem.REFERENCIA_ORIG
      AND NUMLOTE = rec_origem.NUMLOTE_ORIG
      AND NUMLANC = rec_origem.NUMLANC_ORIG
      AND SEQUENCIA = rec_origem.SEQUENCIA_ORIG
      AND TIPLANC = rec_origem.TIPLANC_ORIG;
  END LOOP;
END;

/
