-- SANKHYA.TRG_DLT_TFPFCO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPFCO
"SANKHYA".TRG_DLT_TFPFCO BEFORE DELETE ON TFPFCO FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODFUNCAO = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;

/
