-- SANKHYA.TRG_DLT_TGFCTT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCTT
"SANKHYA".TRG_DLT_TGFCTT 
BEFORE DELETE ON TGFCTT FOR EACH ROW

DECLARE
         P_COUNT   INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT  
    FROM TGFCAB CAB  
   WHERE CAB.CODPARC    = :OLD.CODPARC  
     AND CAB.CODCONTATO = :OLD.CODCONTATO; 
  IF P_COUNT <> 0 THEN  
     RAISE_APPLICATION_ERROR(-20101,'Contato não pode ser excluído porque está informado em algum pedido/nota.');  
  END IF;  

  SELECT COUNT(1) INTO P_COUNT  
    FROM TCSOSE OSE  
   WHERE OSE.CODPARC    = :OLD.CODPARC  
     AND OSE.CODCONTATO = :OLD.CODCONTATO; 
  IF P_COUNT <> 0 THEN  
     RAISE_APPLICATION_ERROR(-20101,'Contato não pode ser excluído porque está informado em alguma OS.');  
  END IF;  
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGFPPA
  WHERE CODPARC = :OLD.CODPARC 
  AND CODCONTATO = :OLD.CODCONTATO;
  
  IF P_COUNT > 0 THEN
  DELETE FROM TGFPPA
         WHERE CODPARC = :OLD.CODPARC 
         AND CODCONTATO = :OLD.CODCONTATO;
  END IF;
  
         
  EXCEPTION WHEN OTHERS THEN
  IF (SQLCODE <> -4091) THEN
      RAISE_APPLICATION_ERROR(-20101, SUBSTR(SQLERRM,1,200));
  END IF;
END;

/
