-- SANKHYA.TRG_INC_UPD_TCBPLA_LOG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCBPLA_LOG
"SANKHYA".TRG_INC_UPD_TCBPLA_LOG 
BEFORE INSERT OR UPDATE 
ON TCBPLA 
FOR EACH ROW

DECLARE 
	P_ACAO VARCHAR2(10); 
	P_CHAVEPK VARCHAR(400);

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	P_CHAVEPK := :NEW.CODCTACTB;
	
	IF INSERTING THEN
		IF (:NEW.DESCRCTA IS NOT NULL) THEN    
			STP_LOGTSIALT('TCBPLA', P_CHAVEPK,'DESCRCTA', :NEW.DESCRCTA);
		END IF;
		RETURN;  
	ELSIF UPDATING THEN 
		IF ((NVL(:OLD.DESCRCTA,'null')) <> (NVL(:NEW.DESCRCTA,'null'))) THEN 
			STP_LOGTSIALT('TCBPLA', P_CHAVEPK,'DESCRCTA', :NEW.DESCRCTA);
		END IF;
		RETURN;
	END IF;            
END;

/
