-- SANKHYA.TRG_DLT_TGFFDM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFFDM
"SANKHYA".TRG_DLT_TGFFDM BEFORE DELETE ON TGFFDM FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODFORM = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluído.');
  END IF;
END;

/
