-- SANKHYA.TRG_DLT_TGFTOP_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTOP_AFTER
"SANKHYA".TRG_DLT_TGFTOP_AFTER
AFTER DELETE ON TGFTOP

DECLARE
    P_CODTIPOPER                  INT:= 0;
    P_COUNT                       INT:= 0;
	P_CODTIPOPER_REF			  INT:= 0;
    CURSOR DELETADAS IS SELECT CODTIPOPER FROM TGFTOP_DLT;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  OPEN DELETADAS;
  DELETE FROM TGFTOP_DLT;
  LOOP
    FETCH DELETADAS INTO P_CODTIPOPER;
    EXIT WHEN DELETADAS%NOTFOUND;

    SELECT NVL(COUNT(1),0) INTO P_COUNT
    FROM TGFTOP
    WHERE CODTIPOPER = P_CODTIPOPER;
    IF P_COUNT = 0 THEN
      SELECT NVL(COUNT(1),0) INTO P_COUNT
      FROM TGFETA T
      WHERE ( (T.TOPENTRADA = P_CODTIPOPER) OR
              (T.TOPSAIDA   = P_CODTIPOPER) OR
              (T.TOPDEVMP   = P_CODTIPOPER));
      IF (P_COUNT > 0)  THEN
        RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP nas etapas de produção!');
      END IF;

      SELECT COUNT(1) INTO P_COUNT
      FROM TGFICM
      WHERE TIPRESTRICAO = 'O' AND CODRESTRICAO = P_CODTIPOPER;
      IF (P_COUNT<>0) THEN
        RAISE_APPLICATION_ERROR(-20101, Erros_Pkg.ERRO_EXCECOES_ICMS);
      END IF;

      SELECT COUNT(1)  INTO P_COUNT
      FROM TGFICM
      WHERE TIPRESTRICAO2 = 'O' AND CODRESTRICAO2 = P_CODTIPOPER;
      IF (P_COUNT<>0) THEN
        RAISE_APPLICATION_ERROR(-20101, Erros_Pkg.ERRO_EXCECOES_ICMS);
      END IF;

      SELECT COUNT(1) INTO P_COUNT
      FROM TGFORD
      WHERE CODTIPOPERTRANSB = P_CODTIPOPER;
      IF (P_COUNT <> 0) THEN
        RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP em Ordens de Carga.');
      END IF;

      SELECT COUNT(1)  INTO P_COUNT
      FROM TGFACO
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF (P_COUNT<>0) THEN
        RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP nos Acordos p/Pedido Eletrônico!');
      END IF;

      SELECT COUNT(1) INTO P_COUNT
      FROM TSIUSU
      WHERE TOPBAIXADESPESA = P_CODTIPOPER OR TOPBAIXARECEITA = P_CODTIPOPER;
      IF (P_COUNT <> 0) THEN
        RAISE_APPLICATION_ERROR(-20101,'Existe referência desta TOP no cadastro de usuários');
      END IF;

      /* Não permitir a exclusão da TGFTOD caso seja o ultimo registro da top sendo excluido.*/
      SELECT COUNT(1) INTO P_COUNT
      FROM TGFTOD
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF P_COUNT <> 0 THEN
        RAISE_APPLICATION_ERROR(-20101,'A TOP não pode ser excluída pois está sendo referenciada na aba ''Documentação''. Exclua primeiro a documentação existente.');		  
      END IF;

      /* Não permitir a exclusão da TSIUFI caso seja o ultimo registro da top sendo excluido.*/
      SELECT COUNT(1) INTO P_COUNT
      FROM TSIUFI
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF P_COUNT <> 0 THEN
        RAISE_APPLICATION_ERROR(-20101,'Existe referência desta TOP na fila de impressão por TOP e usuário.');
      END IF;

      SELECT COUNT(1) INTO P_COUNT
      FROM TGFCTB
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF P_COUNT <> 0 THEN
         RAISE_APPLICATION_ERROR(-20101,'Existe referência desta TOP na Tabela de Parâmetros de Contabilização.');
      END IF;

      SELECT COUNT(1) INTO P_COUNT
      FROM TGFOSL
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF P_COUNT <> 0 THEN
        RAISE_APPLICATION_ERROR(-20101,'Existe referência desta TOP na Tabela de Ordem de Sugestão de Local.');
      END IF;
       
      SELECT COUNT(1)  INTO P_COUNT
      FROM TGFIFE
      WHERE CODTIPOPER = P_CODTIPOPER;
      IF (P_COUNT<>0) THEN
        RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP nas definições de Alíquotas de Impostos!');
      END IF;
	  
	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERDESTINO = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como Top p/ Faturamento, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;

  	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERSEPARACAO = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como TOP p/Separação, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;

  	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERPENRET = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como TOP para NF-e Pendente de Retorno, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;	  

  	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERDENEG = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como TOP para NF-e Denegada, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;	  

  	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERREM = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como Top p/ NF de Remessa na confirmação, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;	

  	  BEGIN
	    SELECT MAX(CODTIPOPER) INTO P_CODTIPOPER_REF
		FROM TGFTOP
		WHERE CODTIPOPERPRODUZAUT = P_CODTIPOPER
		  AND CODTIPOPER <> P_CODTIPOPER;
		IF P_CODTIPOPER_REF <> 0 THEN
 	      RAISE_APPLICATION_ERROR(-20101, 'Existe referência desta TOP('||TO_CHAR(P_CODTIPOPER)||') como TOP para Produção Automática, na Top: '||TO_CHAR(P_CODTIPOPER_REF));
		END IF;
	  EXCEPTION WHEN NO_DATA_FOUND THEN
	    P_CODTIPOPER_REF := 0;
	  END;	
   
      DELETE FROM TGFREP WHERE CODTIPOPER = P_CODTIPOPER;
      DELETE FROM TGFIMA WHERE TIPO = 'T' AND CODIGO = P_CODTIPOPER;
    END IF;
  END LOOP;
  CLOSE DELETADAS;
END;

/
