-- SANKHYA.TRG_DLT_TCSBLO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSBLO
"SANKHYA".TRG_DLT_TCSBLO BEFORE DELETE ON TCSBLO
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

   RAISE_APPLICATION_ERROR (-20101, 'Locação do Bem já foi faturada ou a medição já foi concluída, não pode excluir o envio.');	  
END;

/
