-- SANKHYA.TRG_INC_TCSPNP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TCSPNP
"SANKHYA".TRG_INC_TCSPNP    
AFTER INSERT ON TCSPNP  
FOR EACH ROW

DECLARE 
    V_CAMPOS        VARCHAR2(4000);
    V_CAMPOS_SELECT VARCHAR2(4000);
    V_EXECUTA       VARCHAR2(4000);
    
    CURSOR CAMPOS(TAB1 VARCHAR, TAB2 VARCHAR) IS
      SELECT T1.COLUMN_NAME 
      FROM USER_TAB_COLUMNS T1 
      WHERE T1.TABLE_NAME = TAB1 
        AND T1.COLUMN_NAME IN (SELECT T2.COLUMN_NAME FROM USER_TAB_COLUMNS T2 WHERE T2.TABLE_NAME = TAB2);
        
    CURSOR EXECUTA IS
      SELECT 'TCSSPN' TAB1,'TCSSPNSEQ' TAB2,'SPN' APELIDO FROM DUAL
      UNION
      SELECT 'TCSPRN' TAB1,'TCSPRNSEQ' TAB2,'PRN' APELIDO FROM DUAL
      UNION
      SELECT 'TCSRPN' TAB1,'TCSRPNSEQ' TAB2,'RPN' APELIDO FROM DUAL
      UNION
      SELECT 'TCSPOS' TAB1,'TCSPOSSEQ' TAB2,'POS' APELIDO FROM DUAL
      UNION
      SELECT 'TPQPES' TAB1,'TPQPESSEQ' TAB2,'PES' APELIDO FROM DUAL
      UNION
      SELECT 'TPQRPE' TAB1,'TPQRPESEQ' TAB2,'RPE' APELIDO FROM DUAL;    
        
BEGIN

  FOR X IN EXECUTA
  LOOP
      EXECUTE IMMEDIATE 'DELETE FROM ' || X.TAB2 || ' WHERE NUMOS = ' || TO_CHAR(:NEW.NUMOS) || ' AND SEQPROPOSTA = ' || TO_CHAR(:NEW.SEQPROPOSTA);
      
      V_CAMPOS := '';    
      V_CAMPOS_SELECT := '';    
      
      FOR C IN CAMPOS(X.TAB1, X.TAB2)
      LOOP
          IF C.COLUMN_NAME <> 'SEQPROPOSTA' THEN
              IF X.TAB1 IN ('TPQPES','TPQRPE') THEN
                  IF C.COLUMN_NAME <> 'NUMOS' THEN
                      V_CAMPOS := V_CAMPOS || ' , ' || C.COLUMN_NAME;
                      V_CAMPOS_SELECT := V_CAMPOS_SELECT || ' , ' || X.APELIDO || '.' || C.COLUMN_NAME;
                  END IF;
              ELSE
                  V_CAMPOS := V_CAMPOS || ' , ' || C.COLUMN_NAME;
                  V_CAMPOS_SELECT := V_CAMPOS_SELECT || ' , ' || X.APELIDO || '.' || C.COLUMN_NAME;
              END IF;
          END IF;
      END LOOP;
      
      IF X.TAB1 IN ('TPQPES','TPQRPE') THEN
        V_EXECUTA := 'INSERT INTO ' || X.TAB2 || ' (NUMOS, SEQPROPOSTA' || V_CAMPOS || ')' ||   
                     ' SELECT ' || TO_CHAR(:NEW.NUMOS) || ',' || TO_CHAR(:NEW.SEQPROPOSTA) || V_CAMPOS_SELECT || 
                     ' FROM ' || X.TAB1 || ' ' || X.APELIDO || ', TCSPOS POS' || 
                     ' WHERE ' || X.APELIDO || '.NUPESQ = POS.NUPESQ AND POS.NUMOS = ' || TO_CHAR(:NEW.NUMOS);
      ELSE
        V_EXECUTA :=  'INSERT INTO ' || X.TAB2 || ' (SEQPROPOSTA' || V_CAMPOS || ')' || 
                      ' SELECT ' || TO_CHAR(:NEW.SEQPROPOSTA) || V_CAMPOS_SELECT || 
                      ' FROM ' || X.TAB1 || ' ' || X.APELIDO || 
                      ' WHERE ' || X.APELIDO || '.NUMOS = ' || TO_CHAR(:NEW.NUMOS);
      END IF;
      
      EXECUTE IMMEDIATE V_EXECUTA;
      
  END LOOP;

END;

/
