-- SANKHYA.TRG_FX_TGFPEM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFPEM
"SANKHYA".TRG_FX_TGFPEM
   BEFORE INSERT OR UPDATE
   ON TGFPEM
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
   
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFPEM');

   IF (NOT P_VALIDAR)
   THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;

   IF (   (NVL (:NEW.CODPROD, 0) <> NVL (:OLD.CODPROD, 0))
       OR (NVL (:NEW.GRUPOICMS, 0) <> NVL (:OLD.GRUPOICMS, 0))
       OR (:NEW.TEMICMS <> :OLD.TEMICMS)
       OR (:NEW.TIPSUBST <> :OLD.TIPSUBST)
       OR (:NEW.DESCMAX <> :OLD.DESCMAX)
       OR (:NEW.ALIQICMSINTEFD <> :OLD.ALIQICMSINTEFD)
       OR (:NEW.PERCCMTNAC <> :OLD.PERCCMTNAC)
       OR (:NEW.PERCCMTFED <> :OLD.PERCCMTFED)
       OR (:NEW.PERCCMTEST <> :OLD.PERCCMTEST)
       OR (:NEW.PERCCMTIMP <> :OLD.PERCCMTIMP)
       OR (:NEW.GRUPOICMS2 <> :OLD.GRUPOICMS2)
       OR (:NEW.ALIQGERAL <> :OLD.ALIQGERAL)
       OR (:NEW.MVAPADRAO <> :OLD.MVAPADRAO)
       OR (:NEW.CALCDIFAL <> :OLD.CALCDIFAL))
   THEN
      SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

      :NEW.NUVERSAO := P_CONTADOR;
   END IF;
END;

/
