-- SANKHYA.TRG_INC_UPD_TGFEST_BAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFEST_BAR
"SANKHYA".TRG_INC_UPD_TGFEST_BAR
BEFORE INSERT OR UPDATE ON TGFEST 
FOR EACH ROW

DECLARE P_COUNT  NUMBER(10); 
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF GET_TSIPAR_LOGICO('INTCODBARDTSYNC') = 'N' THEN
    RETURN;
  END IF;
  
  IF Variaveis_Pkg.CODBARRA_EST <> 'BAR' THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFESTBAR
    WHERE CODEMP = :NEW.CODEMP
      AND CODPROD = :NEW.CODPROD
      AND CODLOCAL = :NEW.CODLOCAL
      AND CONTROLE = :NEW.CONTROLE
      AND CODPARC = :NEW.CODPARC
      AND TIPO = :NEW.TIPO;
    Variaveis_Pkg.CODBARRA_EST := 'EST';    
    IF P_COUNT > 0 THEN      
      UPDATE TGFESTBAR SET CODBARRA = :NEW.CODBARRA
      WHERE CODEMP = :NEW.CODEMP
        AND CODPROD = :NEW.CODPROD
        AND CODLOCAL = :NEW.CODLOCAL
        AND CONTROLE = :NEW.CONTROLE
        AND CODPARC = :NEW.CODPARC
        AND TIPO = :NEW.TIPO;
    ELSE
      INSERT INTO TGFESTBAR (CODEMP, CODPROD, CODLOCAL, CONTROLE, CODPARC, TIPO, CODBARRA)
                     VALUES (:NEW.CODEMP, :NEW.CODPROD, :NEW.CODLOCAL, :NEW.CONTROLE, :NEW.CODPARC, :NEW.TIPO, :NEW.CODBARRA);
    END IF;
    Variaveis_Pkg.CODBARRA_EST := ' ';
  END IF;    
END;

/
