-- SANKHYA.TRG_DLT_EVTFILA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_EVTFILA
"SANKHYA".TRG_DLT_EVTFILA
BEFORE DELETE ON EVTFILA

BEGIN
  RAISE_APPLICATION_ERROR(-20101, 'NÃO É PERMITIDO DELETAR AS INFORMAÇÕES DE ENVIO PARA O ESOCIAL. ESTAS TAMBÉM SÃO UTILIZADAS COMO LOG.');  
END;

/
