-- SANKHYA.TRG_DLT_TFPVPS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPVPS
"SANKHYA".TRG_DLT_TFPVPS 
BEFORE DELETE ON TFPVPS 
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 
  DELETE 
  FROM TFPTVPS
  WHERE CODEMP = :OLD.CODEMP
  AND CODFUNC = :OLD.CODFUNC
  AND SEQUENCIA = :OLD.SEQUENCIA
  AND CODCONVENIO = :OLD.CODCONVENIO
  AND REFERENCIAVPS = :OLD.REFERENCIA
  AND TIPFOLHA = :OLD.TIPFOLHA;
END;

/
