-- SANKHYA.TRG_INC_TFPBAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPBAS
"SANKHYA".TRG_INC_TFPBAS 
BEFORE INSERT ON TFPBAS FOR EACH ROW

DECLARE
  P_SITUACAO     CHAR(1);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  :NEW.BLOQUEIAPORTALRH := GET_TSIPAR_LOGICO ('FPBLOQPORTALRH');  

  :NEW.BLOQUEIAPORTALPTO := GET_TSIPAR_LOGICO ('FPBLOQPORTALPTO');
  
    IF :NEW.TIPFOLHA = 'R' THEN 
      BEGIN 
          SELECT SITUACAO 
          INTO   P_SITUACAO 
          FROM   TFPFUN 
          WHERE  CODEMP = :NEW.CODEMP 
                 AND CODFUNC = :NEW.CODFUNC; 
      EXCEPTION 
          WHEN NO_DATA_FOUND THEN 
            P_SITUACAO := NULL; 
      END; IF P_SITUACAO = '0' THEN :NEW.RESCISAODEFINITIVA := 'S'; END IF; 
    END IF;
  
END;

/
