-- SANKHYA.TRG_DEL_TSIOBC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TSIOBC
"SANKHYA".TRG_DEL_TSIOBC BEFORE DELETE ON TSIOBC 
FOR EACH ROW

DECLARE
P_COUNT NUMBER(1);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
   
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGFREJ
  WHERE CODIGO = :OLD.CODIGO 
  AND CODOCORRENCIA = :OLD.CODOCORRENCIA
  AND SEQUENCIA = :OLD.SEQUENCIA ;
  
  IF P_COUNT > 0 THEN
    DELETE FROM TGFREJ
    WHERE CODIGO = :OLD.CODIGO 
    AND CODOCORRENCIA = :OLD.CODOCORRENCIA
    AND SEQUENCIA = :OLD.SEQUENCIA ; 
  END IF;
END;

/
