-- SANKHYA.TRG_DEL_TSIPER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TSIPER
"SANKHYA".TRG_DEL_TSIPER 
AFTER DELETE ON TSIPER


DECLARE 
    P_COUNT     NUMBER(05);

BEGIN
    BEGIN
        SELECT COUNT(1) INTO P_COUNT 
        FROM TSIPER
        WHERE CODGRUPO = 0 
        AND PERMISSAO = 464700 
        AND CODUSU = 0;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 THEN
        UPDATE TSIVARBD SET EXISTE_REGISTRO_TSIPER = 'N';
    END IF;
END;

/
