-- SANKHYA.TFPREQSANPKG_TRG_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TFPREQSANPKG_TRG_SEQ
"SANKHYA".TFPREQSANPKG_TRG_SEQ
BEFORE INSERT ON TFPREQSANPKG 
FOR EACH ROW

BEGIN
  SELECT TFPREQSANPKG_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;

/
