-- SANKHYA.TRG_DLT_TFPAFDT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPAFDT
"SANKHYA".TRG_DLT_TFPAFDT 
BEFORE DELETE  ON TFPAFDT
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.TIPREGISTRO = 'O') THEN
    RAISE_APPLICATION_ERROR(-20101, 'Registro ORIGINAL (importado do Relógio de Ponto) não pode ser excluído!');
  END IF;
END;

/
