-- SANKHYA.TRG_DEL_TGFREG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGFREG
"SANKHYA".TRG_DEL_TGFREG 
AFTER DELETE ON TGFREG


DECLARE 
    P_COUNT     NUMBER(05);
    
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    BEGIN
        SELECT COUNT(*) INTO P_COUNT FROM TGFREG;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 THEN
        UPDATE TSIVARBD SET UTILIZA_CERTIFIC = 'N';
        COMMIT;
    END IF;
END;

/
