-- SANKHYA.TRG_DEL_TGMCFG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGMCFG
"SANKHYA".TRG_DEL_TGMCFG 
AFTER DELETE ON TGMCFG


DECLARE 
    P_COUNT     NUMBER(05);
    
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    BEGIN
        SELECT COUNT(*) INTO P_COUNT FROM TGMCFG;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_COUNT := 0;
    END;
    
    IF P_COUNT = 0 THEN
        UPDATE TSIVARBD SET UTILIZA_METAS = 'N';
        COMMIT;
    END IF;
END;

/
