-- SANKHYA.TRG_DLT_TGFDRCSTR0200
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR0200
"SANKHYA".TRG_DLT_TGFDRCSTR0200
BEFORE DELETE ON TGFDRCSTR0200
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR0206
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR0206
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR0220
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI = :OLD.REG
        AND CODPROD = :OLD.CODPROD
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR0220
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI = :OLD.REG
            AND CODPROD = :OLD.CODPROD
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
