-- SANKHYA.TRG_DLT_TGWIVL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWIVL
"SANKHYA".TRG_DLT_TGWIVL BEFORE DELETE ON TGWIVL
FOR EACH ROW
   
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
  	P_COUNTVPOL NUMBER(5);
    P_COUNTIVL NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNTIVL
  FROM TGWIVL
  WHERE NUCONFERENCIA = :OLD.NUCONFERENCIA
    AND SEQUENCIA <> :OLD.SEQUENCIA
    AND CODPROD <> :OLD.CODPROD
    AND CONTROLE <> :OLD.CONTROLE
   	AND NUMVOL = :OLD.NUMVOL;
   
  COMMIT;
   
  IF P_COUNTIVL <= 0 THEN 
	  SELECT COUNT(1) INTO P_COUNTVPOL
	  FROM TGWPVOL
	  WHERE NUCONFERENCIA = :OLD.NUCONFERENCIA
	    AND NUMVOL = :OLD.NUMVOL;
	   
	  COMMIT;
	    
	  IF P_COUNTVPOL > 0 THEN
	    DELETE FROM TGWPVOL
	     WHERE NUCONFERENCIA = :OLD.NUCONFERENCIA
	       AND NUMVOL = :OLD.NUMVOL;
	      
	    COMMIT;
	  END IF;
  END IF;  
END;

/
