-- SANKHYA.TRG_INC_UPD_DLT_TGMTME
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGMTME
"SANKHYA".TRG_INC_UPD_DLT_TGMTME
BEFORE INSERT OR UPDATE OR DELETE ON TGMTME
FOR EACH ROW

DECLARE P_COUNT	 NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TGMCFG CFG 
  WHERE CFG.CODMETA = :NEW.CODMETA
    AND CFG.SIMPLIFICADA IS NOT NULL;
  IF P_COUNT <> 0 THEN
	 Tgmtme_Pkg.V_CODMETA       := :NEW.CODMETA;
	 Tgmtme_Pkg.V_CODTIPOPER    := :NEW.CODTIPOPER;
	 Tgmtme_Pkg.V_RECDESP       := :NEW.RECDESP; 
	 Tgmtme_Pkg.V_CODUSU        := :NEW.CODUSU; 
	 Tgmtme_Pkg.V_DTALTER       := :NEW.DTALTER; 
	 Tgmtme_Pkg.V_COMPROMISSO   := :NEW.COMPROMISSO; 
	 Tgmtme_Pkg.V_CODMETA_D     := :OLD.CODMETA;
	 Tgmtme_Pkg.V_CODTIPOPER_D  := :OLD.CODTIPOPER;
  END IF; 
  RETURN;
END;

/
