-- SANKHYA.TRG_INC_TGMTRA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGMTRA
"SANKHYA".TRG_INC_TGMTRA
BEFORE INSERT ON TGMTRA
FOR EACH ROW

DECLARE
	P_COUNT INT;
BEGIN
	IF STP_GET_ATUALIZANDO THEN
		RETURN;
	END IF;
	:NEW.VALOR_ORIG := :NEW.VALOR;
	SELECT
		COUNT(1)
	INTO
		P_COUNT
	FROM
		TGMMET
	WHERE
		CODMETA          = :NEW.CODMETA
		AND DTREF        = :NEW.DTREF
		AND CODEMP       = :NEW.CODEMP
		AND CODGRUPOPROD = :NEW.CODGRUPOPROD
		AND CODPROD      = :NEW.CODPROD
		AND CODLOCAL     = :NEW.CODLOCAL
		AND CONTROLE     = :NEW.CONTROLE
		AND MARCA        = :NEW.MARCA
		AND CODREG       = :NEW.CODREG
		AND CODGER       = :NEW.CODGER
		AND CODVEND      = :NEW.CODVEND
		AND CODCENCUS    = :NEW.CODCENCUS
		AND CODNAT       = :NEW.CODNAT
		AND CODPROJ      = :NEW.CODPROJ
		AND CODPARC      = :NEW.CODPARC
		AND CODUF        = :NEW.CODUF
		AND CODCID       = :NEW.CODCID
		AND CODPAIS      = :NEW.CODPAIS
		AND CODTIPPARC   = :NEW.CODTIPPARC
		AND CODGRUPONAT  = :NEW.CODGRUPONAT
	;
	
	IF (P_COUNT = 0) THEN
		SELECT
			COUNT(1)
		INTO
			P_COUNT
		FROM
			TGMCFG
		WHERE
			CODMETA          = :NEW.CODMETA
			AND INVESTIMENTO = 'S'
		;
	
	END IF;
	IF P_COUNT = 0 THEN
		INSERT INTO TGMMET
			( CODMETA
				, DTREF
				, CODEMP
				, CODPROD
				, CODGRUPOPROD
				, CODLOCAL
				, CODPROJ
				, CODCENCUS
				, CODNAT
				, CODREG
				, CODGER
				, CODVEND
				, CODPARC
				, CODUF
				, CODCID
				, CODPAIS
				, CODTIPPARC
				, CONTROLE
				, MARCA
				, DIA
				, PREVDESP
				, CODGRUPONAT
			)
			VALUES
			( :NEW.CODMETA
				, :NEW.DTREF
				, :NEW.CODEMP
				, :NEW.CODPROD
				, :NEW.CODGRUPOPROD
				, :NEW.CODLOCAL
				, :NEW.CODPROJ
				, :NEW.CODCENCUS
				, :NEW.CODNAT
				, :NEW.CODREG
				, :NEW.CODGER
				, :NEW.CODVEND
				, :NEW.CODPARC
				, :NEW.CODUF
				, :NEW.CODCID
				, :NEW.CODPAIS
				, :NEW.CODTIPPARC
				, :NEW.CONTROLE
				, :NEW.MARCA
				, :NEW.DIA
				, 0
				, :NEW.CODGRUPONAT
			)
		;
	
	END IF;
END;

/
