-- SANKHYA.TRG_INC_EVTFILAREINF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_EVTFILAREINF
"SANKHYA".TRG_INC_EVTFILAREINF
BEFORE INSERT ON EVTFILAREINF
FOR EACH ROW

DECLARE P_CHAVEEVENTO       VARCHAR2(36);
BEGIN
    SELECT  'ID'|| --CAMPO FIXO
            CASE WHEN LENGTH(CGC) = 14 THEN 1 ELSE 2 END ||-- TIPO( 1:CNPJ OU 2:CPF)
            CASE WHEN LENGTH(CGC) = 14 THEN CASE WHEN EMPC.EMPADMPUBDIR = 'S' THEN CGC 
                                                 ELSE RPAD(SUBSTR(CGC,1,8),14, '0') END 
                 ELSE RPAD(CGC, 14, '0') END || --CNPJ OU CPJ COM 14 D?GITOS COMPLETANDO COM ZERO A DIREITA
            TO_CHAR(:NEW.DHINC, 'YYYYMMDDHH24MISS') || --DATA E HORA DA GERAÇÃO NO FORMADO YYYYMMDDHH24MISS SENDO QUE A HORA VAI DE 0 À 23
            LPAD(TO_CHAR(:NEW.SEQEVENTO), 5, '0') --Número sequêncial de livre preenchimento.
        INTO P_CHAVEEVENTO
    FROM TSIEMP EMP INNER JOIN TGFEMP EMPC ON (EMP.CODEMP = EMPC.CODEMP)
    WHERE EMP.CODEMP = :NEW.CODEMP;    

   :NEW.CHAVEEVENTO := P_CHAVEEVENTO;
END;

/
