-- SANKHYA.TRG_FX_TSIEND
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TSIEND
"SANKHYA".TRG_FX_TSIEND
	BEFORE INSERT OR UPDATE
	ON TSIEND
	FOR EACH ROW

DECLARE
	P_CONTADOR   NUMBER (19);
	P_VALIDAR    BOOLEAN;
	P_TEM_CHECKOUT BOOLEAN;
BEGIN
	IF Stp_Get_Atualizando
	THEN
		RETURN;
	END IF;
	
	-- Sincronização de dados
	P_VALIDAR := Fpodevalidar ('TSIEND');
	
	IF (NOT P_VALIDAR)
	THEN
		RETURN;
	END IF;
	
	P_TEM_CHECKOUT := FCheckout_Utiliza;
	
	IF (NOT P_TEM_CHECKOUT) THEN
		RETURN;
	END IF;

	IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S')
	THEN
		SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;
		:NEW.NUVERSAO := P_CONTADOR;
		:NEW.ATUNUVERSAO := 'N';
	END IF;
END;

/
