-- SANKHYA.TRG_INC_UPD_TGFGIR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFGIR
"SANKHYA".TRG_INC_UPD_TGFGIR
BEFORE INSERT OR UPDATE ON TGFGIR
FOR EACH ROW

BEGIN
  :NEW.MARCA := NVL(:NEW.MARCA, '.');
END;

/
