-- SANKHYA.TRG_INC_TGMCFG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGMCFG
"SANKHYA".TRG_INC_TGMCFG 
AFTER INSERT ON TGMCFG

BEGIN
    UPDATE TSIVARBD SET UTILIZA_METAS = 'S' WHERE UTILIZA_METAS = 'N';
END;

/
