-- SANKHYA.TRG_FX_TFXEAN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXEAN
"SANKHYA".TRG_FX_TFXEAN
   BEFORE INSERT OR UPDATE
   ON TFXEAN
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
	IF (INSERTING) THEN
		SELECT SEQ_TFXEAN.NEXTVAL INTO P_CONTADOR FROM DUAL;
      	:NEW.ID := P_CONTADOR;
   	END IF;
	  
   	IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S')
	THEN
		SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

		:NEW.NUVERSAO := P_CONTADOR;
		:NEW.ATUNUVERSAO := 'N';
	END IF;
END;

/
