-- SANKHYA.TRG_INC_UPD_TFPFER_ROTINA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPFER_ROTINA
"SANKHYA".TRG_INC_UPD_TFPFER_ROTINA
BEFORE INSERT
ON TFPFER
FOR EACH ROW

BEGIN
  IF :NEW.DIGITADO = 'N' THEN 
    :NEW.DTPREVISTA := NULL;
  ELSE
    :NEW.DTPREVISTA := :NEW.DTSAIDA;
  END IF;
END;

/
