-- SANKHYA.TRG_FX_TGFNFENT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFNFENT
TRG_FX_TGFNFENT
   BEFORE INSERT OR UPDATE
   ON TGFNFENT
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_TEM_CHECKOUT BOOLEAN;
   P_NUNOTAMODFX NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   P_TEM_CHECKOUT := FCheckout_Utiliza;
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;
  
   SELECT EMP.NUNOTAMODFX INTO P_NUNOTAMODFX FROM TGFEMP EMP WHERE EMP.CODEMP = :NEW.CODEMP;
   IF (NVL(P_NUNOTAMODFX,0) = 0) THEN 
   	 RETURN;
   END IF;
 
   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
