-- SANKHYA.TRG_INC_TGFPEL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFPEL
"SANKHYA".TRG_INC_TGFPEL
BEFORE INSERT ON TGFPEL
FOR EACH ROW

DECLARE P_COUNT  NUMBER(5);
  P_VALIDAR                  BOOLEAN;
  ERRMSG                     VARCHAR2(255);
  ERROR                      EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  /* 
  sincronização de dados
  */
  P_VALIDAR := Fpodevalidar('TGFPEL');

  SELECT COUNT(1) INTO P_COUNT
  FROM TGFCAB CAB
  WHERE CAB.NUNOTA = :NEW.NUNOTA;
  
  IF P_COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Nota não localizada.');
  END IF;
  
  SELECT SEQ_TGFPEL_CODPEL.NEXTVAL INTO :NEW.CODPEL
  FROM DUAL;
  
  RETURN;  
EXCEPTION

  WHEN ERROR THEN
    /* 
    Sincronização de dados não faz validações
    */
    IF (P_VALIDAR) THEN 
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF; 

END;

/
