-- SANKHYA.TRG_INC_UPD_TGFITS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFITS
"SANKHYA".TRG_INC_UPD_TGFITS
BEFORE INSERT OR UPDATE ON TGFITS
FOR EACH ROW

BEGIN
  IF ROUND(:NEW.QTDSAI, 5) > ROUND(:NEW.QTDENT, 5) THEN
    RAISE_APPLICATION_ERROR(-20101, 'A Qtd. Saída não pode ser maior que a Qtd. Entrada.');
  END IF;
END;

/
