-- SANKHYA.TRG_DLT_TGFDIRFBPFDEC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDIRFBPFDEC
"SANKHYA".TRG_DLT_TGFDIRFBPFDEC
BEFORE DELETE ON TGFDIRFBPFDEC
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFPFRTRT
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPFRTRT
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFPFRTIRF
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPFRTIRF
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;
    END IF;
   
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFPFRTPO
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFPFRTPO
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFBASEBPFDEC
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFBASEBPFDEC
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI3 = :OLD.REGPAI2
          AND REGPAI2 = :OLD.REGPAI
          AND REGPAI = :OLD.REG
          AND CODREC = :OLD.CODREC
          AND CPF = :OLD.CPF;
    END IF;
END;

/
