-- SANKHYA.TRG_INC_UPD_TCSEAG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TCSEAG
"SANKHYA".TRG_INC_UPD_TCSEAG
BEFORE INSERT OR UPDATE ON TCSEAG FOR EACH ROW	

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :NEW.DHINICIO >  :NEW.DHFINAL THEN
    RAISE_APPLICATION_ERROR(-20101, 'Não é possível Incluir/Editar registro com Data Inicial maior que a Data Final.');
  END IF; 
END;

/
