-- SANKHYA.TRG_DLT_TGAAH
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGAAH
"SANKHYA".TRG_DLT_TGAAH BEFORE DELETE ON TGAAH FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGAAHI 
  WHERE NUAPONT = :OLD.NUAPONT;
  IF P_COUNT > 0 THEN
  DELETE FROM TGAAHI WHERE NUAPONT = :OLD.NUAPONT;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGAAHP 
  WHERE NUAPONT = :OLD.NUAPONT;
  IF P_COUNT > 0 THEN
  DELETE FROM TGAAHP WHERE NUAPONT = :OLD.NUAPONT;
  END IF;
  
END;

/
