-- SANKHYA.TRG_INC_UPD_TGFTEL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFTEL
"SANKHYA".TRG_INC_UPD_TGFTEL BEFORE INSERT OR UPDATE ON TGFTEL
FOR EACH ROW

DECLARE
	P_CODPARC TGFPAR.CODPARC%TYPE;
BEGIN
	P_CODPARC :=0;
	BEGIN 
		SELECT VEN.CODPARC INTO P_CODPARC FROM TGFVEN VEN WHERE VEN.CODVEND = :NEW.CODVEND;
	EXCEPTION WHEN NO_DATA_FOUND THEN 
		P_CODPARC :=0;
	END;
	:NEW.CODPARC := P_CODPARC;
END;

/
