-- SANKHYA.TRG_INC_UPD_DLT_TFPVPS_LOG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TFPVPS_LOG
"SANKHYA".TRG_INC_UPD_DLT_TFPVPS_LOG BEFORE  INSERT OR UPDATE OR DELETE  ON TFPVPS FOR EACH ROW

DECLARE P_ACAO VARCHAR2(10); P_CHAVEPK VARCHAR(400);
BEGIN
  P_CHAVEPK := 'PK [' || 'CODEMP' || '=' || :NEW.CODEMP  || 'CODFUNC' || '=' || :NEW.CODFUNC  || 'SEQUENCIA' || '=' || :NEW.SEQUENCIA  || 'CODCONVENIO' || '=' || :NEW.CODCONVENIO  || 'REFERENCIA' || '=' || :NEW.REFERENCIA || ']';
  IF INSERTING THEN  
    IF :NEW.CODCONVENIO IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODCONVENIO',:NEW.CODUSU,'INSERT',:NEW.CODCONVENIO,' ');
    END IF;  
    IF :NEW.CODEMP IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODEMP',:NEW.CODUSU,'INSERT',:NEW.CODEMP,' ');
    END IF;  
    IF :NEW.CODFUNC IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODFUNC',:NEW.CODUSU,'INSERT',:NEW.CODFUNC,' ');
    END IF;  
    IF :NEW.CODUSU IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODUSU',:NEW.CODUSU,'INSERT',:NEW.CODUSU,' ');
    END IF;  
    IF TO_CHAR(:NEW.DHALTER,'dd/mm/yyyy hh24:mm:ss') IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DHALTER',:NEW.CODUSU,'INSERT',TO_CHAR(:NEW.DHALTER,'dd/mm/yyyy hh24:mm:ss'),' ');
    END IF;  
    IF :NEW.DIGITADO IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DIGITADO',:NEW.CODUSU,'INSERT',:NEW.DIGITADO,' ');
    END IF;  
    IF TO_CHAR(:NEW.REFERENCIA,'dd/mm/yyyy hh24:mm:ss') IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'REFERENCIA',:NEW.CODUSU,'INSERT',TO_CHAR(:NEW.REFERENCIA,'dd/mm/yyyy hh24:mm:ss'),' ');
    END IF;  
    IF :NEW.SEQUENCIA IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'SEQUENCIA',:NEW.CODUSU,'INSERT',:NEW.SEQUENCIA,' ');
    END IF;  
    IF :NEW.VALOR IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'VALOR',:NEW.CODUSU,'INSERT',:NEW.VALOR,' ');
    END IF;  
    RETURN;
  ELSIF DELETING THEN 
    P_CHAVEPK := 'PK [' || 'CODEMP' || '=' || :OLD.CODEMP  || 'CODFUNC' || '=' || :OLD.CODFUNC  || 'SEQUENCIA' || '=' || :OLD.SEQUENCIA  || 'CODCONVENIO' || '=' || :OLD.CODCONVENIO  || 'REFERENCIA' || '=' || :OLD.REFERENCIA || ']';
    IF :OLD.CODCONVENIO IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODCONVENIO',:OLD.CODUSU,'DELETE',' ',:OLD.CODCONVENIO);
    END IF;  
    IF :OLD.CODEMP IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODEMP',:OLD.CODUSU,'DELETE',' ',:OLD.CODEMP);
    END IF;  
    IF :OLD.CODFUNC IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODFUNC',:OLD.CODUSU,'DELETE',' ',:OLD.CODFUNC);
    END IF;  
    IF :OLD.CODUSU IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODUSU',:OLD.CODUSU,'DELETE',' ',:OLD.CODUSU);
    END IF;  
    IF TO_CHAR(:OLD.DHALTER,'dd/mm/yyyy hh24:mm:ss') IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DHALTER',:OLD.CODUSU,'DELETE',' ',TO_CHAR(:OLD.DHALTER,'dd/mm/yyyy hh24:mm:ss'));
    END IF;  
    IF :OLD.DIGITADO IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DIGITADO',:OLD.CODUSU,'DELETE',' ',:OLD.DIGITADO);
    END IF;  
    IF TO_CHAR(:OLD.REFERENCIA,'dd/mm/yyyy hh24:mm:ss') IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'REFERENCIA',:OLD.CODUSU,'DELETE',' ',TO_CHAR(:OLD.REFERENCIA,'dd/mm/yyyy hh24:mm:ss'));
    END IF;  
    IF :OLD.SEQUENCIA IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'SEQUENCIA',:OLD.CODUSU,'DELETE',' ',:OLD.SEQUENCIA);
    END IF;  
    IF :OLD.VALOR IS NOT NULL THEN   
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'VALOR',:OLD.CODUSU,'DELETE',' ',:OLD.VALOR);
    END IF;  
    RETURN;
  ELSIF UPDATING THEN 
    IF NVL(:OLD.CODCONVENIO, 0) <> NVL(:NEW.CODCONVENIO, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODCONVENIO', :NEW.CODUSU, 'UPDATE',:NEW.CODCONVENIO,:OLD.CODCONVENIO);
    END IF;
    IF NVL(:OLD.CODEMP, 0) <> NVL(:NEW.CODEMP, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODEMP', :NEW.CODUSU, 'UPDATE',:NEW.CODEMP,:OLD.CODEMP);
    END IF;
    IF NVL(:OLD.CODFUNC, 0) <> NVL(:NEW.CODFUNC, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODFUNC', :NEW.CODUSU, 'UPDATE',:NEW.CODFUNC,:OLD.CODFUNC);
    END IF;
    IF NVL(:OLD.CODUSU, 0) <> NVL(:NEW.CODUSU, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'CODUSU', :NEW.CODUSU, 'UPDATE',:NEW.CODUSU,:OLD.CODUSU);
    END IF;
    IF :OLD.DHALTER <> :NEW.DHALTER THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DHALTER', :NEW.CODUSU, 'UPDATE',TO_CHAR(:NEW.DHALTER,'dd/mm/yyyy hh24:mm:ss'),TO_CHAR(:OLD.DHALTER,'dd/mm/yyyy hh24:mm:ss'));
    END IF;
    IF NVL(:OLD.DIGITADO, 0) <> NVL(:NEW.DIGITADO, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'DIGITADO', :NEW.CODUSU, 'UPDATE',:NEW.DIGITADO,:OLD.DIGITADO);
    END IF;
    IF :OLD.REFERENCIA <> :NEW.REFERENCIA THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'REFERENCIA', :NEW.CODUSU, 'UPDATE',TO_CHAR(:NEW.REFERENCIA,'dd/mm/yyyy hh24:mm:ss'),TO_CHAR(:OLD.REFERENCIA,'dd/mm/yyyy hh24:mm:ss'));
    END IF;
    IF NVL(:OLD.SEQUENCIA, 0) <> NVL(:NEW.SEQUENCIA, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'SEQUENCIA', :NEW.CODUSU, 'UPDATE',:NEW.SEQUENCIA,:OLD.SEQUENCIA);
    END IF;
    IF NVL(:OLD.VALOR, 0) <> NVL(:NEW.VALOR, 0) THEN 
      STP_GRAVATABLOG('TFPVPS', P_CHAVEPK,'VALOR', :NEW.CODUSU, 'UPDATE',:NEW.VALOR,:OLD.VALOR);
    END IF;
    RETURN;
  END IF;            
END;

/
