-- SANKHYA.TRG_EXC_TJCAPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_EXC_TJCAPJ
"SANKHYA".TRG_EXC_TJCAPJ BEFORE DELETE ON TJCAPJ REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
    ERROR                    EXCEPTION;
    ERRMSG                   VARCHAR2(255);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:NEW.PENDENTE = 'N') THEN
     STP_EXCLUSAO_TJCAPJ( :OLD.DTVENDA, :OLD.CODNAT, :OLD.ACRESCIMOCOR, :OLD.PRECOTABELA, :OLD.VLRDESC, :OLD.VLRCOMAGENCIA);
  END IF;
  EXCEPTION
    WHEN ERROR THEN
    raise_application_error(-20101, ERRMSG);
END;

/
