-- SANKHYA.TRG_DLT_TGWARS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWARS
"SANKHYA".TRG_DLT_TGWARS
BEFORE DELETE ON TGWARS FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  RAISE_APPLICATION_ERROR(-20101, 'Registro padrão do sistema. Não pode ser excluído.');          
END;

/
