-- SANKHYA.TRG_INC_UPD_TFPCTF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPCTF
"SANKHYA".TRG_INC_UPD_TFPCTF
BEFORE INSERT OR UPDATE ON TFPCTF FOR EACH ROW

DECLARE
  P_COUNT              INT;
  P_CODEMP             NUMBER(5);
BEGIN

  BEGIN
    SELECT CODEMP INTO P_CODEMP
    FROM TFPEMP
    WHERE CODREGFIS = :NEW.CODREGFIS;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_CODEMP := 0;
  END;

  IF NVL(:NEW.CONTACREDITO, 0) <> 0 THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TCBPLA P, TCBEMP E, TFPEMP F
    WHERE P.CODCTACTB = :NEW.CONTACREDITO
    AND E.CODEMP = CASE WHEN NVL(F.EMPDESTINOCTB , F.CODEMP) <> 0 THEN F.EMPDESTINOCTB  ELSE F.CODEMP END
    AND F.CODREGFIS = :NEW.CODREGFIS
    AND E.CODEMPPLACTA = P.CODEMP
    AND P.ATIVA = 'S'
    AND P.ANALITICA = 'S';
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Código Contábil de Débito inválida, ou não ativa, ou não analítica. Conta: ' || :NEW.CONTACREDITO || ' - Empresa: ' || P_CODEMP ||'.');
    END IF;
  END IF;

  IF NVL(:NEW.CONTADEBITO, 0) <> 0 THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TCBPLA P, TCBEMP E, TFPEMP F
    WHERE P.CODCTACTB = :NEW.CONTADEBITO
    AND E.CODEMP = CASE WHEN NVL(F.EMPDESTINOCTB , F.CODEMP) <> 0 THEN F.EMPDESTINOCTB  ELSE F.CODEMP END
    AND F.CODREGFIS = :NEW.CODREGFIS
    AND E.CODEMPPLACTA = P.CODEMP
    AND P.ATIVA = 'S'
    AND P.ANALITICA = 'S';
    IF (P_COUNT = 0 ) THEN
      RAISE_APPLICATION_ERROR (-20101, 'Código Contábil de Débito inválida, ou não ativa, ou não analítica. Conta: ' || :NEW.CONTADEBITO || ' - Empresa: ' || P_CODEMP ||'.');
    END IF;
  END IF;

END;

/
