-- SANKHYA.TRG_DLT_TGFREA_TGFLREA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFREA_TGFLREA
"SANKHYA".TRG_DLT_TGFREA_TGFLREA 
BEFORE DELETE ON TGFREA 
FOR EACH ROW

DECLARE 
	P_COUNT		NUMBER(10);
	
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	SELECT COUNT(1) INTO P_COUNT
	  FROM TGFLREA
	 WHERE NUMITEMREA = :OLD.NUMITEMREA;
	 
	IF ((P_COUNT =  0) OR (P_COUNT IS NOT NULL)) THEN
		RAISE_APPLICATION_ERROR(-20101,'Não é possível excluir pois existe dependência para esse registro.');
	END IF;
RETURN;
END;

/
