-- SANKHYA.TRG_DLT_TGFITC_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITC_AFTER
"SANKHYA".TRG_DLT_TGFITC_AFTER AFTER DELETE ON TGFITC 

DECLARE
P_NUMCOTACAO INT;
P_CODPARC INT;
P_COUNT INT;
CURSOR CUR_TGFITC_DLT IS SELECT NUMCOTACAO, CODPARC FROM TGFITC_DLT;

BEGIN
 
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

   OPEN CUR_TGFITC_DLT;
   DELETE FROM TGFITC_DLT;
   LOOP
    FETCH CUR_TGFITC_DLT INTO 
       P_NUMCOTACAO, P_CODPARC;
    EXIT WHEN CUR_TGFITC_DLT%NOTFOUND;
    
SELECT COUNT(1) INTO P_COUNT FROM TGFITC 
    WHERE NUMCOTACAO = P_NUMCOTACAO
    AND CODPARC = P_CODPARC ;
    IF (P_COUNT = 0) THEN
      DELETE FROM TGFFRC WHERE NUMCOTACAO = P_NUMCOTACAO AND CODPARC = P_CODPARC ;
    END IF;
   END LOOP;
  CLOSE CUR_TGFITC_DLT;

END;

/
