-- SANKHYA.TRG_INC_UPD_TGFEXC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFEXC
"SANKHYA".TRG_INC_UPD_TGFEXC 
BEFORE INSERT OR UPDATE ON TGFEXC
FOR EACH ROW

DECLARE
    P_DECVENDA                TGFNTA.DECVENDA%TYPE;
    P_DECVLR                  TGFPRO.DECVLR%TYPE;
    P_USADECPREC              CHAR(1);
    P_UTILIZADECCUSTO         CHAR(1);
	P_CUSTODEC                TSIPAR.INTEIRO%TYPE;
BEGIN
    BEGIN
        IF STP_GET_ATUALIZANDO THEN
          RETURN;
        END IF;
        
        SELECT LOGICO 
        INTO P_USADECPREC
        FROM TSIPAR
        WHERE CHAVE = 'USADECPREC';

        IF (P_USADECPREC='N') THEN
           RETURN;  
        END IF;

        SELECT NVL(DECVLR, 2) 
        INTO P_DECVLR
        FROM TGFPRO
        WHERE CODPROD = :NEW.CODPROD;
        
        
    EXCEPTION WHEN NO_DATA_FOUND THEN
        RETURN;
    END;
    
    BEGIN     
        SELECT DECVENDA,NVL(TBL.UTILIZADECCUSTO,'N')
        INTO P_DECVENDA,P_UTILIZADECCUSTO
        FROM 
             TGFNTA NTA,
             TGFTAB TBL
        WHERE TBL.NUTAB =:NEW.NUTAB
        AND TBL.CODTAB = NTA.CODTAB;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        RETURN;         
    END;
    
    IF P_UTILIZADECCUSTO = 'S' THEN
	   BEGIN
		   	SELECT NVL(INTEIRO,2)
		   	INTO P_CUSTODEC
		   	FROM TSIPAR WHERE CHAVE='CUSTODEC';
	   EXCEPTION WHEN NO_DATA_FOUND THEN
		  	P_CUSTODEC := 2;
	   END;
	   :NEW.VLRVENDA := ROUND (:NEW.VLRVENDA, P_CUSTODEC);
    ELSIF (P_DECVENDA < P_DECVLR) THEN    
       :NEW.VLRVENDA := ROUND (:NEW.VLRVENDA, P_DECVENDA);
    ELSE 
       :NEW.VLRVENDA := ROUND (:NEW.VLRVENDA, P_DECVLR);
    END IF;
END;

/
