-- SANKHYA.TRG_DLT_TGFITS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITS
"SANKHYA".TRG_DLT_TGFITS
BEFORE DELETE ON TGFITS
FOR EACH ROW

DECLARE
  P_COUNT NUMBER(5);
BEGIN

  /* QDO SUBSTITUINDO PRODUTO, NÃO VALIDAR ESTOQUE */
  IF (VARIAVEIS_PKG.V_SBPRODUTO) THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TSIPAR
  WHERE CHAVE = 'SBPRODUTO';
  IF (P_COUNT <> 0 OR Rastrestoque_Pkg.V_LIB_EXEC) THEN
    RETURN;
  END IF; 

  IF :OLD.QTDSAI > 0 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Não é permitido excluir registros de saldo de entrada que tenham movimentações associadas.');
  END IF;

END;

/
