-- SANKHYA.TRG_INC_UPD_TGFORD_FK
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFORD_FK
"SANKHYA".TRG_INC_UPD_TGFORD_FK
  BEFORE INSERT OR UPDATE
  ON TGFORD
  FOR EACH ROW

DECLARE
  P_COUNT   INT;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  IF :NEW.ORDEMCARGAPAI IS NOT NULL AND (INSERTING OR :NEW.ORDEMCARGAPAI <> :OLD.ORDEMCARGAPAI) THEN
    IF :NEW.ORDEMCARGAPAI = :NEW.ORDEMCARGA THEN
      RAISE_APPLICATION_ERROR (-20101, 'A ordem de carga não pode referenciar ela mesma');
    END IF;

    SELECT COUNT (1)
      INTO P_COUNT
      FROM TGFORD
     WHERE ORDEMCARGA = :NEW.ORDEMCARGAPAI;

    IF P_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR (-20101, Erros_Pkg.ERRO_ORDEMCARGA_NAOEXISTE);
    END IF;
  END IF;
END;

/
