-- SANKHYA.TRG_INC_UPD_TGFLIV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFLIV
"SANKHYA".TRG_INC_UPD_TGFLIV  
BEFORE INSERT OR UPDATE ON TGFLIV
FOR EACH ROW

DECLARE
 P_COUNT   INT;
 ERROR     EXCEPTION;
 ERRMSG    VARCHAR2(255);
 P_VALIDAR BOOLEAN;
BEGIN
 IF STP_GET_ATUALIZANDO THEN
   RETURN;
 END IF;

/* 
sincronização de dados
*/
 P_VALIDAR := Fpodevalidar('TGFLIV');
   
   SELECT COUNT (1) INTO P_COUNT
   FROM TGFCTT
   WHERE CODPARC = :NEW.CODPARC
     AND CODCONTATO = :NEW.CODCONTATOENTREGA
     AND ATIVO = 'S';
   
   IF (P_COUNT = 0) THEN
       ERRMSG := 'Contato entrega não está ativo.';
       RAISE ERROR;
   END IF;
   RETURN;
EXCEPTION
 WHEN ERROR THEN
   /* 
   Sincronização de dados não faz validações
   */
   IF (P_VALIDAR) THEN 
     RAISE_APPLICATION_ERROR(-20101, ERRMSG);
   END IF;

END;

/
