-- SANKHYA.TRG_INC_UPD_TGMTRA_SINAL_BF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGMTRA_SINAL_BF
"SANKHYA".TRG_INC_UPD_TGMTRA_SINAL_BF
BEFORE INSERT OR UPDATE ON TGMTRA
FOR EACH ROW

BEGIN
	TGMTRA_PKG.V_NUNOTA       := :NEW.NUNOTA;
	TGMTRA_PKG.V_NUFIN        := :NEW.NUFIN;
	TGMTRA_PKG.V_STATUS       := :NEW.STATUS;
	TGMTRA_PKG.V_CODMETA      := :NEW.CODMETA;
	TGMTRA_PKG.V_DTREF        := :NEW.DTREF;
	TGMTRA_PKG.V_CODEMP       := :NEW.CODEMP;
	TGMTRA_PKG.V_CODGRUPOPROD := :NEW.CODGRUPOPROD;
	TGMTRA_PKG.V_CODPROD      := :NEW.CODPROD;
	TGMTRA_PKG.V_CODLOCAL     := :NEW.CODLOCAL;
	TGMTRA_PKG.V_CONTROLE     := :NEW.CONTROLE;
	TGMTRA_PKG.V_MARCA        := :NEW.MARCA;
	TGMTRA_PKG.V_CODREG       := :NEW.CODREG;
	TGMTRA_PKG.V_CODGER       := :NEW.CODGER;
	TGMTRA_PKG.V_CODVEND      := :NEW.CODVEND;
	TGMTRA_PKG.V_CODCENCUS    := :NEW.CODCENCUS;
	TGMTRA_PKG.V_CODNAT       := :NEW.CODNAT;
	TGMTRA_PKG.V_CODPROJ      := :NEW.CODPROJ;
	TGMTRA_PKG.V_CODPARC      := :NEW.CODPARC;
	TGMTRA_PKG.V_CODUF        := :NEW.CODUF;
	TGMTRA_PKG.V_CODCID       := :NEW.CODCID;
	TGMTRA_PKG.V_CODPAIS      := :NEW.CODPAIS;
	TGMTRA_PKG.V_CODTIPPARC   := :NEW.CODTIPPARC;
	TGMTRA_PKG.V_CODGRUPONAT  := :NEW.CODGRUPONAT;
	IF (:NEW.STATUS = 'R') THEN
		TGMTRA_PKG.V_SINAL := 0;
	ELSE
		TGMTRA_PKG.V_SINAL := 1;
	END IF;
END;

/
