-- SANKHYA.TRG_DLT_TGFCAT42R1050
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCAT42R1050
"SANKHYA".TRG_DLT_TGFCAT42R1050
BEFORE DELETE ON TGFCAT42R1050
FOR EACH ROW

DECLARE
    P_COUNT    NUMBER;
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFCAT42R1050NAE
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REG = :OLD.REG
        AND CODPROD = :OLD.CODPROD;

    IF P_COUNT > 0 THEN
        DELETE TGFCAT42R1050NAE
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REG = :OLD.REG
            AND CODPROD = :OLD.CODPROD;
    END IF;
END;

/
