-- SANKHYA.TRG_DLT_TGFCON
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCON
"SANKHYA".TRG_DLT_TGFCON BEFORE DELETE ON TGFCON REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
 SELECT COUNT(1)
   INTO P_COUNT
 FROM TGFCOI COI
 WHERE COI.NUCONF = :OLD.NUCONF
 AND   COI.SEQUENCIA = :OLD.SEQUENCIA;
 
 IF P_COUNT > 0 THEN
   DELETE FROM TGFCOI COI
   WHERE COI.NUCONF = :OLD.NUCONF
   AND   COI.SEQUENCIA = :OLD.SEQUENCIA;
 END IF;
 
END TRG_DLT_TGFCON;

/
