-- SANKHYA.TRG_FX_TFXBPA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXBPA
"SANKHYA".TRG_FX_TFXBPA
   BEFORE INSERT OR UPDATE
   ON TFXBPA
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF (INSERTING)
   THEN
      SELECT SEQ_TFXBPA.NEXTVAL INTO P_CONTADOR FROM DUAL;

      :NEW.ID := P_CONTADOR;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
