-- SANKHYA.TRG_DLT_TFPORG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPORG
"SANKHYA".TRG_DLT_TFPORG BEFORE DELETE ON TFPORG FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODORGAO = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
