-- SANKHYA.TRG_INC_TGPFCP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGPFCP
"SANKHYA".TRG_INC_TGPFCP
AFTER INSERT ON TGPFCP FOR EACH ROW

BEGIN

    INSERT INTO TGPFCF (CODFUNCAO, CODPERFIL, CODEMP, CODFUNC, CODUSU, DHALTER)
    SELECT :NEW.CODFUNCAO, :NEW.CODCOMPETENCIA, FUN.CODEMP, FUN.CODFUNC, 0, SYSDATE
    FROM TFPFUN FUN
    WHERE FUN.CODFUNCAO = :NEW.CODFUNCAO
      AND NOT EXISTS(SELECT 1 
                     FROM TGPFCF FCF 
                     WHERE FCF.CODFUNCAO = :NEW.CODFUNCAO 
                       AND FCF.CODPERFIL = :NEW.CODCOMPETENCIA
                       AND FCF.CODEMP = FUN.CODEMP
                       AND FCF.CODFUNC = FUN.CODFUNC);

END;

/
