-- SANKHYA.TRG_FX_TFXIMP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXIMP
"SANKHYA".TRG_FX_TFXIMP
   BEFORE INSERT OR UPDATE
   ON TFXIMP
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
