-- SANKHYA.TRG_DLT_TGFITE_HCRUZADAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_HCRUZADAS
"SANKHYA".TRG_DLT_TGFITE_HCRUZADAS
AFTER DELETE ON TGFITE FOR EACH ROW

DECLARE P_COUNT   NUMBER(10);
BEGIN

  -- VERIFICANDO SE O CLIENTE UTILIZA ESTA FUNCIONALIDADE
  SELECT COUNT(*) INTO P_COUNT
  FROM TSIVARBD
  WHERE UTILIZA_HCRUZADAS = 'N';
  IF P_COUNT > 0 THEN 
    RETURN;
  END IF;

  IF Stp_Get_Atualizando THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TCSFATHC
  WHERE NUNOTA = :OLD.NUNOTA
    AND SEQUENCIA = :OLD.SEQUENCIA;
  IF P_COUNT > 0 THEN
    DELETE FROM TCSFATHC 
    WHERE NUNOTA = :OLD.NUNOTA
      AND SEQUENCIA = :OLD.SEQUENCIA;
  END IF;
END;

/
