-- SANKHYA.TRG_INC_UPD_TGFREC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFREC
"SANKHYA".TRG_INC_UPD_TGFREC BEFORE INSERT OR UPDATE ON TGFREC   FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF UPDATING('CODPROD')  THEN
     SELECT COUNT(1) INTO P_COUNT
     FROM  TGFPRO
     WHERE CODPROD = :NEW.CODPROD
     AND ATIVO = 'S';
     IF ( P_COUNT = 0) THEN
         RAISE_APPLICATION_ERROR(-20101,'Produto não esta ativo. ');
     END IF;
  END IF;
END;

/
