-- SANKHYA.TFPREQSANFOR_TRG_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TFPREQSANFOR_TRG_SEQ
"SANKHYA".TFPREQSANFOR_TRG_SEQ
BEFORE INSERT ON TFPREQSANFOR 
FOR EACH ROW

BEGIN
  SELECT TFPREQSANFOR_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;

/
