-- SANKHYA.TRG_FX_TGFVEN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TGFVEN
"SANKHYA".TRG_FX_TGFVEN
   BEFORE INSERT OR UPDATE OR DELETE
   ON TGFVEN
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
   P_VALIDAR    BOOLEAN;
   P_TEM_CHECKOUT BOOLEAN;
BEGIN
   IF Stp_Get_Atualizando
   THEN
      RETURN;
   END IF;
   
   P_TEM_CHECKOUT := FCheckout_Utiliza;
	
   IF (NOT P_TEM_CHECKOUT) THEN
	  RETURN;
   END IF;

   /*
   Sincronização de dados
   */
   P_VALIDAR := Fpodevalidar ('TGFVEN');

   IF (NOT P_VALIDAR)
   THEN
      RETURN;
   END IF;
   
   IF (DELETING OR (UPDATING AND (NVL (:NEW.CODEMP, 0) <> NVL (:OLD.CODEMP, 0)))) THEN
		INSERT INTO TFXADE (NOMETAB, STRPK)
        VALUES ('TVENDEDOR', 'CODVENDEDOR = ' || TO_CHAR (NVL(:OLD.CODVEND,0)) || ' AND CODEMPRESA = ' || TO_CHAR (NVL(:OLD.CODEMP,0)) || ' AND NUVERSAO = ' || TO_CHAR (NVL(:OLD.NUVERSAO,0)) );
		
		IF (DELETING) THEN
			RETURN;
		END IF;
   END IF;
   
   IF ((NVL (:NEW.CODVEND, 0) <> NVL (:OLD.CODVEND, 0))
       OR (NVL (:NEW.APELIDO, '') <> NVL (:OLD.APELIDO, ''))
       OR (NVL (:NEW.CODEMP, 0) <> NVL (:OLD.CODEMP, 0))
       OR (NVL (:NEW.ATIVO, 'S') <> NVL (:OLD.ATIVO, 'S')))
   THEN
      SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

      :NEW.NUVERSAO := P_CONTADOR;
   END IF;
END;

/
