-- SANKHYA.TRG_DLT_TGFIRR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFIRR
"SANKHYA".TRG_DLT_TGFIRR BEFORE DELETE ON TGFIRR FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF(:OLD.NUNOTARET IS NOT NULL) THEN
    RAISE_APPLICATION_ERROR (-20101, 'A nota ja foi remetida e retornada.');
  END IF;  
  IF(:OLD.NUNOTAREM IS NOT NULL) THEN
    RAISE_APPLICATION_ERROR (-20101, 'A nota ja foi remetida.');
  END IF;  

END;

/
