-- SANKHYA.TRG_INC_TGWTRA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGWTRA
"SANKHYA".TRG_INC_TGWTRA 
BEFORE INSERT ON TGWTRA FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT  
  FROM TGWREC
  WHERE NURECEBIMENTO = :NEW.NURECEBIMENTO
    AND SITUACAO < 4;
  IF P_COUNT > 0 THEN
    UPDATE TGWREC SET SITUACAO = 4
	WHERE NURECEBIMENTO = :NEW.NURECEBIMENTO
      AND SITUACAO < 4;  
  END IF;
END;

/
