-- SANKHYA.TRG_DLT_TRIIRPF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIIRPF
"SANKHYA".TRG_DLT_TRIIRPF
AFTER DELETE  ON TRIIRPF
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRPF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NATREND = T.NATREND;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRPF
		WHERE :OLD.CODEMP = TRIDRPF.CODEMP 
		  AND :OLD.DTREF = TRIDRPF.DTREF 
		  AND :OLD.TPAMB = TRIDRPF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRPF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRPF.CHAVE
          AND :OLD.NATREND = TRIDRPF.NATREND;
	END IF;
END;		

/
