-- SANKHYA.TRG_INC_UPD_TGFFRC_FK
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFFRC_FK
"SANKHYA".TRG_INC_UPD_TGFFRC_FK BEFORE INSERT OR UPDATE ON TGFFRC
FOR EACH ROW

DECLARE
    P_COUNT                INT:= 0;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(*) INTO P_COUNT  
  FROM TGFITC  
  WHERE NUMCOTACAO = :NEW.NUMCOTACAO
  AND CODPARC = :NEW.CODPARC;
   
  IF (P_COUNT = 0) THEN
     RAISE_APPLICATION_ERROR (-20101, 'Não existe nenhuma Cotação cadastrada na TGFICT para o parceiro :'||:new.codparc|| '.');
  END IF;
END;

/
