-- SANKHYA.TRG_INC_TGFEMP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFEMP
"SANKHYA".TRG_INC_TGFEMP
AFTER INSERT ON TGFEMP

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  INSERT INTO TGFORD (CODEMP, ORDEMCARGA, CODPARCTRANSP, CODVEICULO, CODREG, SITUACAO, TIPCARGA)
    SELECT CODEMP, 0, 0, 0, 0, 'A', 'R' 
    FROM TGFEMP
    WHERE ATIVO = 'S' 
    AND CODEMP NOT IN (SELECT CODEMP
                       FROM TGFORD
                       WHERE ORDEMCARGA = 0);

  INSERT INTO TGFCGM (CODEMP, ANO, MES, DTREF, PERCCFFAB, PERCCFOUTROS, PERCCFSERVICO, PERCCOFINS, 
                      PERCCSL, PERCCUSVAR, PERCCVARSEMST, PERCMARGEM, PERCPIS)
    SELECT CODEMP
    , 1900
    , 1
    , '01/01/1900'
    , PERCCFFAB
    , PERCCFOUTROS
    , PERCCFSERVICO
    , NVL(PERCCOFINS, 0)
    , PERCCSL
    , PERCCUSVAR
    , PERCCVARSEMST
    , PERCMARGEM
    , NVL(PERCPIS, 0)
    FROM TGFEMP
    WHERE NOT EXISTS(SELECT 1 FROM TGFCGM WHERE CODEMP = TGFEMP.CODEMP);

END;

/
