-- SANKHYA.TRG_INC_UPD_TGFMST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFMST
"SANKHYA".TRG_INC_UPD_TGFMST 
BEFORE INSERT OR UPDATE  ON TGFMST
FOR EACH ROW

DECLARE
  P_COUNT     NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF NVL(:NEW.CODVEND, 0) = 0 THEN
     RAISE_APPLICATION_ERROR(-20101, 'O códgigo do Vendedor não pode ser zero na TGFMST dentro do processo de troca.');
  ELSIF NVL(:NEW.CODPARC, 0) = 0 THEN
     RAISE_APPLICATION_ERROR(-20101, 'O códgigo do Parceiro não pode ser zero na TGFMST dentro do processo de troca.');
  END IF;
END;

/
