-- SANKHYA.TRG_DLT_TCSBME
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCSBME
"SANKHYA".TRG_DLT_TCSBME BEFORE DELETE ON TCSBME
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  RAISE_APPLICATION_ERROR (-20101, 'Medição final definida ou faturada!');  
END;

/
