-- SANKHYA.TRG_FX_TFXADE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXADE
"SANKHYA".TRG_FX_TFXADE
   BEFORE INSERT
   ON TFXADE
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   SELECT SEQ_TFXADE.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.ID := P_CONTADOR;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
