-- SANKHYA.TRG_INC_UPD_DLT_TGFVAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFVAS
TRG_INC_UPD_DLT_TGFVAS
   BEFORE INSERT OR UPDATE OR DELETE
   ON TGFVAS
   FOR EACH ROW

DECLARE
   P_COUNT   NUMBER (5);
BEGIN
   IF STP_GET_ATUALIZANDO THEN
    RETURN;
   END IF;

   /* QUANDO SUBSTITUINDO PRODUTO NAO VALIDAR RASTREAMENTO */
    IF (VARIAVEIS_PKG.V_SBPRODUTO) THEN
      RETURN;
    END IF;
	
   SELECT COUNT (1)
     INTO P_COUNT
     FROM TSIPAR
    WHERE CHAVE = 'SBPRODUTO';

   IF (P_COUNT <> 0 OR RASTRESTOQUE_PKG.V_RASTREA_VIA_SIS)
   THEN
      RETURN;
   END IF;

   IF INSERTING
   THEN
      GET_IMPOSTOS_RAT_EST (:NEW.NUNOTAORIG,
                            :NEW.SEQUENCIAORIG,
                            :NEW.QTDSAI,
                            :NEW.VLRICMS,
                            :NEW.BASESUBST,
                            :NEW.VLRSUBST,
                            :NEW.BASESTFCPINT,
                            :NEW.VLRSTFCPINT,
                            :NEW.PERCSTFCPINT,
                            :NEW.PERCSUBST);

      UPDATE TGFITS
         SET QTDSAI = NVL (QTDSAI, 0) + :NEW.QTDSAI
       WHERE NUNOTA = :NEW.NUNOTAORIG AND SEQUENCIA = :NEW.SEQUENCIAORIG;
   ELSIF UPDATING
   THEN
      IF    (:NEW.NUNOTA <> :OLD.NUNOTA)
         OR (:NEW.SEQUENCIA <> :OLD.SEQUENCIA)
         OR (:NEW.NUNOTAORIG <> :OLD.NUNOTAORIG)
         OR (:NEW.SEQUENCIAORIG <> :OLD.SEQUENCIAORIG)
      THEN
         RAISE_APPLICATION_ERROR (
            -20101,
            'Rotina nao preparada para alteracao de registro de origem ou de destino.');
      END IF;

      IF :NEW.QTDSAI <> :OLD.QTDSAI
      THEN
         :NEW.VLRICMS := (:OLD.VLRICMS / :OLD.QTDSAI) * :NEW.QTDSAI;
         :NEW.BASESUBST := (:OLD.BASESUBST / :OLD.QTDSAI) * :NEW.QTDSAI;
         :NEW.VLRSUBST := (:OLD.VLRSUBST / :OLD.QTDSAI) * :NEW.QTDSAI;
         :NEW.BASESTFCPINT := (:OLD.BASESTFCPINT / :OLD.QTDSAI) * :NEW.QTDSAI;
         :NEW.VLRSTFCPINT := (:OLD.VLRSTFCPINT / :OLD.QTDSAI) * :NEW.QTDSAI;

         UPDATE TGFITS
            SET QTDSAI = QTDSAI - :OLD.QTDSAI + :NEW.QTDSAI
          WHERE NUNOTA = :OLD.NUNOTAORIG AND SEQUENCIA = :OLD.SEQUENCIAORIG;
      END IF;
   ELSIF DELETING
   THEN
      UPDATE TGFITS
         SET QTDSAI = QTDSAI - :OLD.QTDSAI
       WHERE NUNOTA = :OLD.NUNOTAORIG AND SEQUENCIA = :OLD.SEQUENCIAORIG;
   END IF;
END;

/
