-- SANKHYA.TRG_INC_UPD_TGFCFM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCFM
"SANKHYA".TRG_INC_UPD_TGFCFM 
AFTER INSERT OR UPDATE 
ON TGFCFM 
FOR EACH ROW

DECLARE
	P_VALFIDEL    NUMBER(10,0);
	P_COUNT       NUMBER(10,0);
	P_STATUSNOTA  TGFCAB.STATUSNOTA%TYPE;
	P_SALDO       TGFCFS.SALDO%TYPE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;


	IF NVL(:NEW.SINAL,0) NOT IN (-1, 0, 1) THEN
	   RAISE_APPLICATION_ERROR(-20101, 'Sinal deve ser Crédito (1), Débito (-1) ou Acompanhamento (0).');
	END IF;
	IF :NEW.VALOR <= 0 THEN 
	   RAISE_APPLICATION_ERROR(-20101, 'Valor deve ser maior que zero.');
	END IF;
	IF :NEW.NUNOTAORIG IS NOT NULL AND :NEW.SINAL = 1 THEN
	   RAISE_APPLICATION_ERROR(-20101, 'Pedido/Nota de Origem só pode ser preenchido para Débito de Cartão Fidelidade.');
	END IF;
	IF :NEW.NUNOTA IS NULL AND :NEW.SINAL = 1 THEN
	   RAISE_APPLICATION_ERROR(-20101, 'Pedido/Nota deve ser preenchido para Crédito de Cartão Fidelidade.');
	END IF;
	IF UPDATING THEN
		IF :NEW.NUFIDEL <> :OLD.NUFIDEL THEN
		   RAISE_APPLICATION_ERROR(-20101, 'Número do Cartão Fidelidade não pode ser alterado.');
		END IF;
		IF NVL(:NEW.NUNOTA,0) <> NVL(:OLD.NUNOTA,0) THEN
		   RAISE_APPLICATION_ERROR(-20101, 'Número do Pedido/Nota não pode ser alterado.');
		END IF;
		IF NVL(:NEW.NUNOTAORIG,0) <> NVL(:OLD.NUNOTAORIG,0) THEN
		   RAISE_APPLICATION_ERROR(-20101, 'Número do Pedido/Nota de Origem não pode ser alterado.');
		END IF;
		IF NVL(:NEW.SINAL,0) <> NVL(:OLD.SINAL,0) THEN
		   RAISE_APPLICATION_ERROR(-20101, 'Sinal não pode ser alterado.');
		END IF;
	END IF;
  
	IF :NEW.SINAL = 1 THEN
		SELECT STATUSNOTA
		INTO P_STATUSNOTA
		FROM TGFCAB
		WHERE NUNOTA = :NEW.NUNOTA;
		
		IF P_STATUSNOTA = 'L' THEN
			BEGIN
				 SELECT NVL(INTEIRO,0) INTO P_VALFIDEL FROM TSIPAR WHERE CHAVE = 'VALFIDEL';
			EXCEPTION WHEN NO_DATA_FOUND THEN
				 P_VALFIDEL := 0;
			END;
		
		SELECT COUNT(*)
		INTO P_COUNT
		FROM TGFCFS
		WHERE NUNOTA = :NEW.NUNOTA;
		
		IF P_COUNT = 0 THEN
			INSERT INTO TGFCFS
			(NUNOTA, NUFIDEL, SALDO, DTVAL)
			VALUES
			(:NEW.NUNOTA, :NEW.NUFIDEL, :NEW.VALOR, TRUNC(SYSDATE) + P_VALFIDEL);
		ELSE
			UPDATE TGFCFS SET
			SALDO = SALDO + :NEW.VALOR - NVL(:OLD.VALOR,0)
			WHERE NUNOTA = :NEW.NUNOTA;
		END IF;
	END IF;
  ELSIF :NEW.SINAL = -1 THEN
      IF :NEW.NUNOTAORIG IS NULL THEN
        RAISE_APPLICATION_ERROR(-20101, 'Pedido/Nota de Origem deve ser informado para Débito de Cartão Fidelidade.');
      END IF;
      SELECT COUNT(*), MAX(SALDO)
      INTO P_COUNT, P_SALDO
      FROM TGFCFS
      WHERE NUNOTA = :NEW.NUNOTAORIG
      AND NUFIDEL = :NEW.NUFIDEL;
      IF P_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'Não encontramos o Pedido/Nota de Origem do Cartão Fidelidade.');
      END IF;
      IF (P_SALDO + NVL(:OLD.VALOR,0)) < :NEW.VALOR THEN
        RAISE_APPLICATION_ERROR(-20101, 'Saldo insuficiente no Pedido/Nota de Origem do Cartão Fidelidade.');
      END IF;
      UPDATE TGFCFS SET
        SALDO = SALDO + NVL(:OLD.VALOR,0) - :NEW.VALOR
      WHERE NUNOTA = :NEW.NUNOTAORIG;
  END IF;
END;

/
