-- SANKHYA.TRG_INC_TGFNAT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFNAT
"SANKHYA".TRG_INC_TGFNAT BEFORE INSERT ON TGFNAT REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
    ERROR                    EXCEPTION;
    ERRMSG                   VARCHAR2(255);
    P_VALCTA				 CHAR(1);
BEGIN
  BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

    SELECT LOGICO INTO P_VALCTA
    FROM TSIPAR 
    WHERE CHAVE = 'VALCTA';
  EXCEPTION WHEN NO_DATA_FOUND THEN
    P_VALCTA := 'N';
  END;
  IF (P_VALCTA = 'S') THEN
	  IF (:NEW.CODCTACTB IS NOT NULL) AND (:NEW.CODCTACTB <> 0) THEN /*Bial*/
	     SELECT NVL(COUNT(1),0) INTO P_COUNT
	     FROM TCBPLA
	     WHERE CODCTACTB = NVL(:NEW.CODCTACTB, 0)
	     AND ATIVA = 'S'
	     AND ANALITICA = 'S';
	     IF (P_COUNT = 0) THEN
	         Stp_Popula_Msg('TCBPLA');
	     END IF;
	  END IF;
	  
	  IF (:NEW.CODCTACTB2 IS NOT NULL) AND (:NEW.CODCTACTB2 <> 0) THEN
	     SELECT NVL(COUNT(1),0) INTO P_COUNT
	     FROM TCBPLA
	     WHERE CODCTACTB = NVL(:NEW.CODCTACTB2, 0)
	     AND ATIVA = 'S'
	     AND ANALITICA = 'S';
	     IF (P_COUNT = 0) THEN
	         Stp_Popula_Msg('TCBPLA');
	     END IF;
	  END IF;
	  
	  IF ((:NEW.CODHISTCTB<>:OLD.CODHISTCTB) OR INSERTING) AND (:NEW.CODHISTCTB IS NOT NULL) AND (:NEW.CODHISTCTB <> 0) THEN
	     SELECT COUNT(1) INTO P_COUNT
	       FROM TCBHIS
	      WHERE CODHISTCTB = :NEW.CODHISTCTB;
	     IF (P_COUNT = 0) THEN
		    Stp_Popula_Msg('TCBHIS');
	     END IF;
	  END IF;
	  
	  IF ((:NEW.CODHISTCTB2<>:OLD.CODHISTCTB2) OR INSERTING) AND (:NEW.CODHISTCTB2 IS NOT NULL) AND (:NEW.CODHISTCTB2 <> 0) THEN
	     SELECT COUNT(1) INTO P_COUNT
	       FROM TCBHIS
	      WHERE CODHISTCTB = :NEW.CODHISTCTB2;
	     IF (P_COUNT = 0) THEN
		    Stp_Popula_Msg('TCBHIS');
	     END IF;
	  END IF;
    END IF;
  
  SELECT NVL(COUNT(1),0) INTO P_COUNT
  FROM TSICUS
  WHERE CODCENCUS = NVL(:NEW.CODCENCUS, 0)
  AND ATIVO = 'S'
  AND ANALITICO = 'S';
  IF (P_COUNT = 0) THEN
      Stp_Popula_Msg('TSICUS');
  END IF;
END;

/
