-- SANKHYA.TRG_INC_UPD_TGFRAM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFRAM
"SANKHYA".TRG_INC_UPD_TGFRAM
BEFORE INSERT OR UPDATE ON TGFRAM
FOR EACH ROW

DECLARE P_COUNT   NUMBER(5);
BEGIN
  IF(:NEW.IDIPROC IS NULL) THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFITE
    WHERE NUNOTA = :NEW.NUNOTA
      AND SEQUENCIA = :NEW.SEQUENCIA;
    IF P_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20101, 'Informe uma Nunota e Sequência válidos');
    END IF;
  END IF;
END;

/
