-- SANKHYA.TRG_DLT_TGFDIRFDECPJ
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDIRFDECPJ
"SANKHYA".TRG_DLT_TGFDIRFDECPJ
BEFORE DELETE ON TGFDIRFDECPJ
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDIRFIDREC
    WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI = :OLD.REG;

    IF P_COUNT > 0 THEN
        DELETE TGFDIRFIDREC
        WHERE CODEMP = :OLD.CODEMP
          AND DTINICIAL = :OLD.DTINICIAL
          AND DTFINAL = :OLD.DTFINAL
          AND REGPAI = :OLD.REG;
    END IF;
END;

/
