-- SANKHYA.TRG_INC_AUDITTFPMOV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_AUDITTFPMOV
"SANKHYA".TRG_INC_AUDITTFPMOV
BEFORE INSERT ON AUDITTFPMOV 
FOR EACH ROW


BEGIN
  SELECT AUDITTFPMOV_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;

/
