-- SANKHYA.TRG_DLT_TGFPLM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFPLM
"SANKHYA".TRG_DLT_TGFPLM
BEFORE DELETE ON TGFPLM
FOR EACH ROW

DECLARE
    P_COUNT          NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    
  IF SNK_TGFTOKCFG AND SNK_TGFTOKCAM('TGFMVE') THEN
    INSERT INTO TGFATUTOK (CODPROD, DHALTER) VALUES(:OLD.CODPROD, SYSDATE);
  END IF;
END;

/
