-- SANKHYA.TRG_INC_UPD_TGFTOP_CFNFE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFTOP_CFNFE
"SANKHYA".TRG_INC_UPD_TGFTOP_CFNFE 
BEFORE INSERT OR UPDATE ON TGFTOP
FOR EACH ROW

DECLARE
  ERRMSG    VARCHAR2(255);
  ERROR     EXCEPTION;
  P_VALIDAR BOOLEAN;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	/*Sincronizac?o de dados*/
	P_VALIDAR := Fpodevalidar('TGFTOP');
	 IF (P_VALIDAR) AND (:NEW.CUPOMFISCAL = 'S') THEN
	   IF (:NEW.NFE <> 'M') THEN
	     ERRMSG := 'Top de cupom fiscal não pode ter marcacao de NFE.';
	     RAISE ERROR;
	   ELSIF (:NEW.NFSE <> 'M') THEN
	     ERRMSG := 'Top de cupom fiscal não pode ter marcacao de NFSE.';
	     RAISE ERROR;
  	   END IF;
	 END IF;
EXCEPTION
  WHEN ERROR THEN
    /*Sincronizac?o de dados n?o faz validac?es*/
    IF (P_VALIDAR) THEN 
      RAISE_APPLICATION_ERROR(-20101, ERRMSG);
    END IF; 
END;

/
