-- SANKHYA.TRG_DLT_TGFICO_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFICO_AFTER
"SANKHYA".TRG_DLT_TGFICO_AFTER  
AFTER DELETE ON TGFICO

DECLARE 
	CURSOR DEL_TGFICO IS 
	  SELECT NUNOTAPO, SEQUENCIAPO
	  FROM TGFICO_DLT;

	  P_NUNOTAPO	 		NUMBER(10);
	  P_SEQUENCIAPO			NUMBER(5);
	    
BEGIN
  OPEN DEL_TGFICO;
  DELETE FROM TGFICO_DLT;
  LOOP
     FETCH DEL_TGFICO INTO P_NUNOTAPO, P_SEQUENCIAPO;
     EXIT WHEN DEL_TGFICO%NOTFOUND;
	 
	 UPDATE TGFITE SET PENDENTE = 'S'
	 WHERE NUNOTA = P_NUNOTAPO
	   AND SEQUENCIA = P_SEQUENCIAPO;
  END LOOP;
  CLOSE DEL_TGFICO;

END;

/
