-- SANKHYA.TRG_DLT_TRIDAPR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIDAPR
"SANKHYA".TRG_DLT_TRIDAPR 
BEFORE DELETE ON TRIDAPR 
FOR EACH ROW

BEGIN
    DELETE TRINFAP
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND INDAQUIS = :OLD.INDAQUIS;
        
    DELETE TRIIPRJ
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE
        AND INDAQUIS = :OLD.INDAQUIS;
END;

/
