-- SANKHYA.TRG_INC_TSISRVLOG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TSISRVLOG
"SANKHYA".TRG_INC_TSISRVLOG BEFORE INSERT ON TSISRVLOG FOR EACH ROW
  
DECLARE P_NULOG NUMBER(10);
BEGIN
  SELECT SEQ_TSISRVLOG_NULOG.NEXTVAL INTO P_NULOG
  FROM DUAL;
 :NEW.NULOG := P_NULOG;
END;

/
