-- SANKHYA.TRG_DLT_TFPMOV
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPMOV
"SANKHYA".TRG_DLT_TFPMOV BEFORE DELETE  ON TFPMOV
FOR EACH ROW

DECLARE P_COUNT       INTEGER;
        P_NUNOTAORIG  INTEGER;
        P_NUFINORIG   INTEGER;
        P_NUMOSORIG   INTEGER;
        P_NUMITEMORIG INTEGER;
        P_CODVEND     INTEGER;
        P_VLRCOM      FLOAT;
        P_TOTAL       FLOAT;
  CURSOR CURCOM IS /* notas que dariam chave duplicada */
    SELECT NUNOTAORIG, NUFINORIG, CODVEND, VLRCOM, NUMOSORIG, NUMITEMORIG
    FROM TGFCOM C1
    WHERE REFERENCIA = :OLD.REFERENCIA
    AND CODEMP = :OLD.CODEMP
    AND CODFUNC = :OLD.CODFUNC
    AND CODEVENTO = :OLD.CODEVENTO
    AND SEQUENCIA = :OLD.SEQUENCIA
    FOR UPDATE;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.NUFIN IS NOT NULL) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Impossivel excluir. Movimento esta sendo referenciado pelo título (' || :OLD.NUFIN || ') na TGFFIN !');
  END IF;

  IF (:OLD.NUOCOR IS NOT NULL) THEN
    RAISE_APPLICATION_ERROR(-20101, 'Impossivel excluir. Movimento esta sendo referenciada pela ocorrência (' || :OLD.NUOCOR || ') na TFPOCO !');
  END IF;

  IF (:OLD.NUFALTA IS NOT NULL) THEN
    SELECT COUNT(1) INTO P_COUNT FROM TFPFAL
    WHERE NUFALTA = :OLD.NUFALTA
      AND CODEMP = :OLD.CODEMP
      AND CODFUNC = :OLD.CODFUNC;
    IF P_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20101, 'Impossível excluir. Movimento esta sendo referenciado pela falta/restituição de falta (' || :OLD.NUFALTA || ') na TFPFAL !');
    END IF;
  END IF;

  IF (:OLD.TIPMOV IN ('M', 'C')) AND (VARIAVEIS_PKG.V_DLT_MOV_COMISSAO) THEN
    DELETE FROM TGFCOM
    WHERE REFERENCIA = :OLD.REFERENCIA
    AND CODEMP = :OLD.CODEMP
    AND CODFUNC = :OLD.CODFUNC
    AND CODEVENTO = :OLD.CODEVENTO
    AND SEQUENCIA = :OLD.SEQUENCIA
    AND (VLRCOM = 0 OR TIPO = 'D');

    OPEN CURCOM;
    FETCH CURCOM INTO P_NUNOTAORIG, P_NUFINORIG, P_CODVEND, P_TOTAL, P_NUMOSORIG, P_NUMITEMORIG;
    WHILE  CURCOM%FOUND LOOP
      SELECT COUNT(1) INTO P_COUNT
      FROM TGFCOM
      WHERE NUNOTAORIG = P_NUNOTAORIG
      AND CODVEND = P_CODVEND
      AND NUMOSORIG = P_NUMOSORIG
      AND NUMITEMORIG = P_NUMITEMORIG
      AND NUFIN = 0
      AND NUFINORIG = 0
      AND REFERENCIA IS NULL;
      IF (P_COUNT > 0) THEN                          /* tem um pouco a pagar */
        UPDATE TGFCOM SET VLRCOM = VLRCOM + P_TOTAL  /* recompor o valor no que esta pendente */
        WHERE NUNOTAORIG = P_NUNOTAORIG
        AND CODVEND = P_CODVEND
        AND NUMOSORIG = P_NUMOSORIG
        AND NUMITEMORIG = P_NUMITEMORIG
        AND NUFIN = 0
        AND NUFINORIG = 0
        AND REFERENCIA IS NULL;

        UPDATE TGFCOM SET VLRCOM = 0                 /* para evitar a trigger de delecao */
        WHERE CURRENT OF CURCOM;

        DELETE FROM TGFCOM                           /* apaga o valor que foi recomposto anteriormente */
        WHERE CURRENT OF CURCOM;
      ELSE                                           /* tudo ja foi pago */
        UPDATE TGFCOM SET
          NUFINORIG = DECODE(NUNOTAORIG,0,NUFINORIG,0),
          REFERENCIA = NULL,
          CODEMP     = NULL,
          CODFUNC    = NULL,
          CODEVENTO  = NULL,
          SEQUENCIA  = NULL
        WHERE CURRENT OF CURCOM;
      END IF;
      FETCH CURCOM INTO P_NUNOTAORIG, P_NUFINORIG, P_CODVEND, P_TOTAL, P_NUMOSORIG, P_NUMITEMORIG;
    END LOOP;
    CLOSE CURCOM;
  END IF;

  DELETE FROM TFPRTM
   WHERE REFERENCIA = :OLD.REFERENCIA
    AND CODEMP = :OLD.CODEMP
    AND CODFUNC = :OLD.CODFUNC
    AND CODEVENTO =  :OLD.CODEVENTO
    AND SEQUENCIA = :OLD.SEQUENCIA;

END;

/
