-- SANKHYA.TRG_BEFORE_DELETE_TCBLAN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_BEFORE_DELETE_TCBLAN
TRG_BEFORE_DELETE_TCBLAN
  BEFORE DELETE ON TCBLAN
  FOR EACH ROW
  
DECLARE
      v_logico CHAR(1);
  BEGIN
  	BEGIN
      SELECT LOGICO INTO v_logico
      FROM TSIPAR
      WHERE TSIPAR.CHAVE = 'CTBPERMEXCLT';
	  EXCEPTION
          WHEN NO_DATA_FOUND THEN
              v_logico := 'S';
	END;
      IF v_logico = 'S' THEN
          INSERT INTO TCBLAN_EXC (
              CODEMP, REFERENCIA, NUMLOTE, NUMLANC, TIPLANC, CODCTACTB, CODCONPAR,
              CODCENCUS, DTMOV, VLRLANC, CODHISTCTB, COMPLHIST, NUMDOC, VENCIMENTO,
              LIBERADO, CODUSU, CODPROJ, PARTLALUR_A, SEQUENCIA, EXTEMPORANEO, DTEXTEMPORANEO,
              CODEMPORIG, CONCILIADO, CHAVE, CODUSUEXC, DHEXC
          )
          VALUES (
              :OLD.CODEMP, :OLD.REFERENCIA, :OLD.NUMLOTE, :OLD.NUMLANC, :OLD.TIPLANC, :OLD.CODCTACTB,
              :OLD.CODCONPAR, :OLD.CODCENCUS, :OLD.DTMOV, :OLD.VLRLANC, :OLD.CODHISTCTB, :OLD.COMPLHIST,
              :OLD.NUMDOC, :OLD.VENCIMENTO, :OLD.LIBERADO, :OLD.CODUSU, :OLD.CODPROJ, :OLD.PARTLALUR_A,
              SEQ_TCBLAN_EXC_SEQUENCIA.NEXTVAL, :OLD.EXTEMPORANEO, :OLD.DTEXTEMPORANEO, :OLD.CODEMPORIG, :OLD.CONCILIADO,
              :OLD.CHAVE, Tsiusu_Log_Pkg.V_CODUSULOG, SYSDATE
          );
      ELSE
          RAISE_APPLICATION_ERROR(-20001, 'Exclusão não permitida.');
      END IF;
  END;

/
