-- SANKHYA.TRG_DLT_TSIREM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIREM
"SANKHYA".TRG_DLT_TSIREM BEFORE DELETE ON TSIREM FOR EACH ROW

DECLARE
  P_COUNT INT;
  P_CODTIPOPER  TGFTOP.CODTIPOPER%TYPE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(*), MIN(CODTIPOPER) 
  INTO P_COUNT, P_CODTIPOPER
  FROM TGFTOP
  WHERE CODREMEDI = :OLD.CODIGO;
  
  IF P_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20101, 'Registro referenciado por TOP não pode ser excluído. Veja a TOP ' || TO_CHAR(P_CODTIPOPER) || '.');
  END IF;
END;

/
