-- SANKHYA.TRG_DLT_TSIGRU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIGRU
"SANKHYA".TRG_DLT_TSIGRU 
BEFORE DELETE ON TSIGRU 
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.CODGRUPO = 0) THEN
    raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluido.');
  END IF;
END;

/
