-- SANKHYA.TRG_INC_TGFSBC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFSBC
"SANKHYA".TRG_INC_TGFSBC
AFTER INSERT ON TGFSBC 
FOR EACH ROW

DECLARE
    P_COUNT     NUMBER(05);
    P_VALIDAR   BOOLEAN;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  BEGIN
      SELECT COUNT(*) 
      INTO P_COUNT
      FROM TSDPAR;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_COUNT := 0;
  END;

  IF P_COUNT = 0 THEN
    RETURN;
  END IF;

  P_VALIDAR := FPODEVALIDAR('TGFSBC_INC');
  IF NOT P_VALIDAR THEN
    RETURN;
  END IF;

  BEGIN
      SELECT COUNT(*) INTO P_COUNT
      FROM TGFSBC_INC I 
      WHERE I.CODCTABCOINT = :NEW.CODCTABCOINT 
        AND I.REFERENCIA = :NEW.REFERENCIA;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_COUNT := 0;
  END;
    
  IF P_COUNT = 0 THEN

    INSERT INTO TGFSBC_INC (CODCTABCOINT, REFERENCIA, SALDOREAL, SALDOBCO)
    VALUES (:NEW.CODCTABCOINT, :NEW.REFERENCIA, :NEW.SALDOREAL, :NEW.SALDOBCO);  

    COMMIT;
  END IF;
  
END;

/
