-- SANKHYA.TRG_DLT_TGFDRCSTR2120
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFDRCSTR2120
"SANKHYA".TRG_DLT_TGFDRCSTR2120
BEFORE DELETE ON TGFDRCSTR2120
FOR EACH ROW

DECLARE
    P_COUNT        NUMBER(10);
BEGIN
    IF VARIAVEIS_PKG.V_REPROCESSANDODRCST = 'S' THEN
        RETURN;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFDRCSTR2130
    WHERE CODEMP = :OLD.CODEMP
        AND DTINICIAL = :OLD.DTINICIAL
        AND DTFINAL = :OLD.DTFINAL
        AND REGPAI3 = :OLD.REGPAI2
        AND REGPAI2 = :OLD.REGPAI
        AND CODPROD = :OLD.CODPROD
        AND REGPAI = :OLD.REG
	AND NVL(DIGITADO, 'N') = 'N';

    IF P_COUNT > 0 THEN
        DELETE TGFDRCSTR2130
        WHERE CODEMP = :OLD.CODEMP
            AND DTINICIAL = :OLD.DTINICIAL
            AND DTFINAL = :OLD.DTFINAL
            AND REGPAI3 = :OLD.REGPAI2
            AND REGPAI2 = :OLD.REGPAI
            AND CODPROD = :OLD.CODPROD
            AND REGPAI = :OLD.REG
	    AND NVL(DIGITADO, 'N') = 'N';
    END IF;
END;

/
