-- SANKHYA.TRG_INC_TFPEVEHIST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TFPEVEHIST
"SANKHYA".TRG_INC_TFPEVEHIST
BEFORE INSERT ON TFPEVEHIST 
FOR EACH ROW

BEGIN
   IF STP_GET_ATUALIZANDO THEN 
     RETURN;
   END IF;

  SELECT TFPEVEHIST_SEQ.NEXTVAL
  INTO   :NEW.CODHIST
  FROM   dual;
END;

/
