-- SANKHYA.TRG_INC_UPD_DLT_TGFFNF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGFFNF
"SANKHYA".TRG_INC_UPD_DLT_TGFFNF
BEFORE INSERT OR UPDATE OR DELETE 
ON TGFFNF FOR EACH ROW


DECLARE
    P_COUNT              NUMBER(05);
    P_VALOR              FLOAT := 0;
BEGIN

    IF GET_TSIPAR_LOGICO('RATEXTNOTAFRINC') = 'S' THEN
        IF(INSERTING OR UPDATING) THEN
            P_VALOR := NVL(:NEW.VLRFRETE, 0) + GET_VLRFRETE_TGFFNF(NVL(:OLD.NUFIN, :NEW.NUFIN), NVL(:OLD.NUNOTA, :NEW.NUNOTA));
        ELSE --DELETING
            P_VALOR := GET_VLRFRETE_TGFFNF(NVL(:OLD.NUFIN, :NEW.NUFIN), NVL(:OLD.NUNOTA, :NEW.NUNOTA));
        END IF;

        SELECT COUNT(*)
        INTO P_COUNT
        FROM TGFCAB CAB
           WHERE CAB.NUNOTA = NVL(:OLD.NUNOTA, :NEW.NUNOTA)
             AND CASE WHEN CAB.TIPFRETE = 'N' THEN 0 ELSE NVL(VLRFRETE, 0) END + P_VALOR <> NVL(CAB.VLRFRETETOTAL, 0);      
         IF P_COUNT > 0 THEN
            UPDATE TGFCAB CAB
            SET VLRFRETETOTAL = CASE WHEN CAB.TIPFRETE = 'N' THEN 0 ELSE NVL(VLRFRETE, 0) END + P_VALOR
           WHERE CAB.NUNOTA = NVL(:OLD.NUNOTA, :NEW.NUNOTA);
         END IF;
    END IF;

END;

/
