-- SANKHYA.TRG_DLT_TSIPAI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIPAI
"SANKHYA".TRG_DLT_TSIPAI 
BEFORE DELETE ON TSIPAI 
FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF (:OLD.CODPAIS = 0) THEN
    raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser alterado ou excluido.');
  END IF;
END;

/
