-- SANKHYA.TRG_INC_UPD_TGMTRA_UNICO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGMTRA_UNICO
"SANKHYA".TRG_INC_UPD_TGMTRA_UNICO BEFORE INSERT OR UPDATE ON TGMTRA FOR EACH ROW

DECLARE
  P_PERIODO   TGMCFG.PERIODO%TYPE;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  SELECT PERIODO
  INTO P_PERIODO
  FROM TGMCFG
  WHERE CODMETA = :NEW.CODMETA;
  IF P_PERIODO = 10 THEN
     RAISE_APPLICATION_ERROR(-20101, 'Não pode fazer antecipação em meta de Intervalo Único');
  END IF;
END;

/
