-- SANKHYA.TRG_DLT_TGFRPV_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFRPV_AFTER
"SANKHYA".TRG_DLT_TGFRPV_AFTER AFTER DELETE ON TGFRPV
FOR EACH ROW

DECLARE P_LOGICO CHAR(1);
P_COUNT NUMBER(5);
BEGIN
  SELECT LOGICO 
    INTO P_LOGICO 
  FROM TSIPAR 
  WHERE CHAVE = 'VISSEMANAL';
  
  IF P_LOGICO IS NULL OR P_LOGICO <> 'S' THEN
    SELECT COUNT(1)
      INTO P_COUNT
    FROM TGFVIS 
    WHERE CODVEND = :OLD.CODVEND 
      AND CODPARC = :OLD.CODPARC;
    
    IF P_COUNT > 0 THEN
      DELETE FROM TGFVIS 
      WHERE CODVEND = :OLD.CODVEND 
        AND CODPARC = :OLD.CODPARC;
    END IF;
  END IF;
  
END;

/
