-- SANKHYA.TRG_DLT_TFPVCO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPVCO
"SANKHYA".TRG_DLT_TFPVCO 
BEFORE DELETE ON TFPVCO
FOR EACH ROW

BEGIN
  IF NOT VARIAVEIS_PKG.V_DLT_REG_COMPENSACAO THEN 
    RAISE_APPLICATION_ERROR(-20101, 'Compensações só pode ser deletadas pela guia de GPS.');
  END IF;
END;

/
