-- SANKHYA.TRG_DLT_TGFITE_METAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFITE_METAS
"SANKHYA".TRG_DLT_TGFITE_METAS
AFTER DELETE ON TGFITE FOR EACH ROW

DECLARE P_COUNT   NUMBER(10);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TGMTRA
  WHERE NUNOTA = :OLD.NUNOTA
    AND SEQUENCIAITE = :OLD.SEQUENCIA;
  IF P_COUNT > 0 THEN
    DELETE FROM TGMTRA 
    WHERE NUNOTA = :OLD.NUNOTA
      AND SEQUENCIAITE = :OLD.SEQUENCIA;
  END IF;
END;

/
