-- SANKHYA.TRG_DLT_TRIAQPR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIAQPR
"SANKHYA".TRG_DLT_TRIAQPR 
BEFORE DELETE ON TRIAQPR 
FOR EACH ROW

BEGIN
    DELETE TRIDAPR
    WHERE CODEMP = :OLD.CODEMP
        AND DTREF = :OLD.DTREF
        AND TPAMB = :OLD.TPAMB
        AND SEQUENCIA = :OLD.SEQUENCIA
        AND CHAVE = :OLD.CHAVE;
END;

/
