-- SANKHYA.TRG_INC_UPD_TGFGEM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFGEM
"SANKHYA".TRG_INC_UPD_TGFGEM  BEFORE UPDATE OR INSERT ON TGFGEM 
FOR EACH ROW

DECLARE
    P_COUNT                  INT:= 0;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF UPDATING('CODGRUPOPROD') OR NVL(:NEW.CODGRUPOPROD,0) <> NVL(:OLD.CODGRUPOPROD,0) THEN
     SELECT COUNT(1) INTO P_COUNT
     FROM TGFGRU
     WHERE CODGRUPOPROD = :NEW.CODGRUPOPROD
     AND ANALITICO = 'S';
     IF (P_COUNT = 0) THEN
        Stp_Popula_Msg('TGFGRU');
     END IF;
  END IF;
 
END;


/
