-- SANKHYA.TRG_DLT_TCIIBE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCIIBE
"SANKHYA".TRG_DLT_TCIIBE
AFTER DELETE ON TCIIBE
FOR EACH ROW

DECLARE
  P_COUNT             INT:= 0;
  ERROR               EXCEPTION;
  ERRMSG              VARCHAR2(255);
  P_NUMCONTRATO_BEM   INT;
  P_NUNOTA            INT;
  P_NUMNOTA           INT;
  P_NUNOTASAIDA       INT;
  P_NUNOTADEV         INT;
  P_NUNOTABAIXA       INT;
  P_NUNOTADEVVENDA    INT;
  P_ULT_NUNOTA        INT;
  P_FATCONTLOCBEM     CHAR(1);
  P_LOCACAOBEM        CHAR(1);  
  P_DTINICIO          DATE;
  P_NUMCONTRATO_NF    NUMBER(10);
  P_ATUALBEM          CHAR(1);
  P_DTNEG             DATE;
  P_DHALTER           DATE;
  P_CONTRATO_ENCONTRADO CHAR(1) := 'S';
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  BEGIN
    SELECT NVL(NUNOTA,0), NVL(NUMNOTA,0), NVL(NUNOTASAIDA,0), NVL(NUNOTADEV,0), NVL(NUNOTABAIXA,0), 
           NVL(NUNOTADEVVENDA, 0), NUMCONTRATO
    INTO P_NUNOTA, P_NUMNOTA, P_NUNOTASAIDA, P_NUNOTADEV, P_NUNOTABAIXA, P_NUNOTADEVVENDA, P_NUMCONTRATO_BEM
    FROM TCIBEM
    WHERE CODBEM = :OLD.CODBEM AND CODPROD = :OLD.CODPROD;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN;
  END;  
  
  BEGIN   
     SELECT LOGICO INTO P_FATCONTLOCBEM
   FROM TSIPAR WHERE CHAVE = 'FATCONTLOCBEM';
  EXCEPTION
     WHEN NO_DATA_FOUND THEN
     P_FATCONTLOCBEM := 'N';
  END;
 
  IF P_FATCONTLOCBEM = 'S' THEN
    BEGIN
      SELECT C.NUMCONTRATO, T.ATUALBEM, (CASE WHEN C.DTREMRET  IS NOT NULL THEN C.DTREMRET ELSE C.DTNEG END), NVL(CON.LOCACAOBEM, 'N')
      INTO P_NUMCONTRATO_NF, P_ATUALBEM, P_DTNEG, P_LOCACAOBEM
      FROM TGFCAB C
         LEFT JOIN TCSCON CON ON CON.NUMCONTRATO = C.NUMCONTRATO  
         , TGFTOP T
      WHERE C.NUNOTA = :OLD.NUNOTA 
        AND C.CODTIPOPER = T.CODTIPOPER 
        AND C.DHTIPOPER = T.DHALTER;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      BEGIN
        SELECT C.NUMCONTRATO, T.ATUALBEM, (CASE WHEN C.DTREMRET  IS NOT NULL THEN C.DTREMRET ELSE C.DTNEG END), NVL(CON.LOCACAOBEM, 'N')
        INTO P_NUMCONTRATO_NF, P_ATUALBEM, P_DTNEG, P_LOCACAOBEM
        FROM TGFCAB_EXC C
           LEFT JOIN TCSCON CON ON CON.NUMCONTRATO = C.NUMCONTRATO  
           , TGFTOP T
        WHERE C.NUNOTA = :OLD.NUNOTA 
          AND C.CODTIPOPER = T.CODTIPOPER 
          AND C.DHTIPOPER = T.DHALTER;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        P_LOCACAOBEM := 'N';
      END;
    END;
    IF P_LOCACAOBEM = 'S' THEN
      IF P_ATUALBEM = 'T' THEN
        SELECT COUNT(1)
          INTO P_COUNT
        FROM TCSBLO 
        WHERE CODPROD = :OLD.CODPROD
          AND CODBEM  = :OLD.CODBEM
          AND NUMCONTRATO = P_NUMCONTRATO_NF
          AND DTINICIO    = P_DTNEG;
        IF P_COUNT > 0 THEN
          DELETE FROM TCSBLO 
          WHERE CODPROD = :OLD.CODPROD
            AND CODBEM  = :OLD.CODBEM
            AND NUMCONTRATO = P_NUMCONTRATO_NF
            AND DTINICIO    = P_DTNEG;
        END IF;        
        
      ELSIF P_ATUALBEM = 'D' THEN
        --RETIRADO OS 819313, CAUSA MUTANTE
        /*SELECT COUNT(1) INTO P_COUNT
        FROM TCIIBE
        WHERE NUNOTA > :OLD.NUNOTA
        AND CODPROD = :OLD.CODPROD
        AND CODBEM = :OLD.CODBEM;*/        
        
        --COLOCADA VERIFICACAO COM VALORES DA TCIBEM, QUE J¿ ERAM SELECIONADOS NESTA TRIGGER
        IF P_NUNOTASAIDA > :OLD.NUNOTA OR P_NUNOTABAIXA > :OLD.NUNOTA OR P_NUNOTADEVVENDA > :OLD.NUNOTA THEN
          ERRMSG := 'O bem já foi movimentado.';
          RAISE ERROR;
        ELSE
          BEGIN
            SELECT MAX(DTINICIO) INTO P_DTINICIO
            FROM TCSBLO
            WHERE CODPROD = :OLD.CODPROD
              AND CODBEM  = :OLD.CODBEM
            AND NUMCONTRATO = P_NUMCONTRATO_NF;
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
            ERRMSG := 'Produto: '||TO_CHAR(:OLD.CODPROD)||' Bem: '||:OLD.CODBEM||' Contrato: '||TO_CHAR(P_NUMCONTRATO_NF)||'. Não existe movimentação de locação para limpar a data da devolução.';
            RAISE ERROR;
          END;
          
          UPDATE TCSBLO SET DTFIM = NULL
              , TIPOFECHA = NULL
          WHERE CODPROD = :OLD.CODPROD
          AND CODBEM  = :OLD.CODBEM
          AND NUMCONTRATO = P_NUMCONTRATO_NF
          AND DTINICIO    = P_DTINICIO;
          P_COUNT := 0;
          /*VERIFICA SE O PRODUTO TEM MEDIÇÃO PARA AJUSTAR*/
          SELECT COUNT(1) INTO P_COUNT
          FROM TGFPRO
          WHERE CODPROD = :OLD.CODPROD
          AND TEMMEDICAO = 'S';
          
          IF P_COUNT > 0 THEN
            BEGIN
              SELECT MAX(DHALTER) INTO P_DHALTER
              FROM TCSBME
              WHERE CODPROD = :OLD.CODPROD 
              AND CODBEM  = :OLD.CODBEM 
              AND NUMCONTRATO = P_NUMCONTRATO_NF 
              AND DTINICIO    = P_DTINICIO
              AND NUNOTAFAT IS NULL;            
            EXCEPTION
              WHEN NO_DATA_FOUND THEN
              ERRMSG := 'Medição não existe ou já foi faturada.';
              RAISE ERROR;
            END;
          
            UPDATE TCSBME SET MEDFIM = NULL
            WHERE CODPROD = :OLD.CODPROD 
              AND CODBEM  = :OLD.CODBEM 
              AND NUMCONTRATO = P_NUMCONTRATO_NF 
              AND DTINICIO    = P_DTINICIO
              AND NUNOTAFAT IS NULL
              AND DHALTER = P_DHALTER;                
          END IF;        
        END IF;
      
      ELSIF P_ATUALBEM = 'F' THEN
        UPDATE TCSBME SET NUNOTAFAT = NULL
        WHERE CODPROD = :OLD.CODPROD 
        AND CODBEM  = :OLD.CODBEM 
        AND NUMCONTRATO = P_NUMCONTRATO_NF
        AND NUNOTAFAT   = :OLD.NUNOTA;         
        RETURN;
      END IF;
     END IF;
  END IF;  

  P_ULT_NUNOTA := 0;
  IF (P_NUNOTA > P_NUNOTASAIDA) AND
     (P_NUNOTA > P_NUNOTADEV) AND
     (P_NUNOTA > P_NUNOTABAIXA) AND
     (P_NUNOTA > P_NUNOTADEVVENDA) THEN
    P_ULT_NUNOTA := P_NUNOTA;  /* Compra */
  ELSIF (P_NUNOTASAIDA > P_NUNOTADEV) AND
     (P_NUNOTASAIDA > P_NUNOTABAIXA) AND
     (P_NUNOTASAIDA > P_NUNOTADEVVENDA) THEN
    P_ULT_NUNOTA := P_NUNOTASAIDA;  /* Transf. */
  ELSIF (P_NUNOTADEV > P_NUNOTABAIXA) AND
     (P_NUNOTADEV > P_NUNOTADEVVENDA) THEN
    P_ULT_NUNOTA := P_NUNOTADEV; /* Retorno */
  ELSIF (P_NUNOTABAIXA > P_NUNOTADEVVENDA) THEN
    P_ULT_NUNOTA := P_NUNOTABAIXA;  /* Baixa */
  ELSE /* Devolu¿¿o de Venda */
    P_ULT_NUNOTA := P_NUNOTADEVVENDA;  
  END IF;

  IF (:OLD.NUNOTA <> P_ULT_NUNOTA) THEN
    ERRMSG := 'O nro único desta operação é diferente do último registrado no cad.Bens. último NuNota:' || TO_CHAR(P_ULT_NUNOTA,'999999999');
    RAISE ERROR;
  END IF;

  DELETE FROM TCILOC WHERE NUNOTA = :OLD.NUNOTA AND SEQUENCIA = :OLD.SEQUENCIA AND CODPROD = :OLD.CODPROD AND CODBEM = :OLD.CODBEM;
  IF (P_NUNOTA = :OLD.NUNOTA) THEN --Compra
    INSERT INTO TCIIBE_DLT (CODPROD, CODBEM, NUMCONTRATO_BEM, NUNOTA, NUNOTADEV, NUNOTADEVVENDA, ATUALBEM)
    VALUES (:OLD.CODPROD, :OLD.CODBEM, P_NUMCONTRATO_BEM, P_NUNOTA, P_NUNOTADEV, P_NUNOTADEVVENDA, 'C');
  ELSIF (P_NUNOTASAIDA = :OLD.NUNOTA) THEN --Transf.
    INSERT INTO TCIIBE_DLT (CODPROD, CODBEM, NUMCONTRATO_BEM, NUNOTA, NUNOTADEV, NUNOTADEVVENDA, ATUALBEM)
    VALUES (:OLD.CODPROD, :OLD.CODBEM, P_NUMCONTRATO_BEM, P_NUNOTA, P_NUNOTADEV, P_NUNOTADEVVENDA, 'T');
  ELSIF (P_NUNOTADEV = :OLD.NUNOTA) THEN --Retorno
    BEGIN
	    SELECT NUMCONTRATO INTO P_NUMCONTRATO_BEM
	    FROM TGFCAB
	    WHERE NUNOTA = P_NUNOTASAIDA;
   	EXCEPTION
   	WHEN NO_DATA_FOUND THEN
   		P_CONTRATO_ENCONTRADO := 'N';
    END; 

    IF (P_CONTRATO_ENCONTRADO = 'S') THEN
	    UPDATE TCIBEM SET
	      NUMCONTRATO = P_NUMCONTRATO_BEM
	    , NUNOTADEV = 0
	    WHERE CODBEM = :OLD.CODBEM
	    AND CODPROD = :OLD.CODPROD;
	END IF;
  ELSIF (P_NUNOTABAIXA = :OLD.NUNOTA) THEN --Baixa
    UPDATE TCIBEM SET
    NUNOTABAIXA = 0,
    DTBAIXA = NULL,
    NUMNOTABAIXA = NULL
    WHERE CODBEM = :OLD.CODBEM
    AND CODPROD = :OLD.CODPROD;
  ELSE  --Devolução de Venda
    INSERT INTO TCIIBE_DLT (CODPROD, CODBEM, NUMCONTRATO_BEM, NUNOTA, NUNOTADEV, NUNOTADEVVENDA, ATUALBEM)
    VALUES (:OLD.CODPROD, :OLD.CODBEM, P_NUMCONTRATO_BEM, P_NUNOTA, P_NUNOTADEV, P_NUNOTADEVVENDA, 'E');
  END IF;  
  EXCEPTION
    WHEN ERROR THEN
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
