-- SANKHYA.TRG_DLT_TGWARC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWARC
"SANKHYA".TRG_DLT_TGWARC
BEFORE DELETE ON TGWARC FOR EACH ROW

BEGIN
  RAISE_APPLICATION_ERROR(-20101, 'Registro padrão do sistema. Não pode ser excluído.');          
END;

/
