-- SANKHYA.TRG_INC_EVTFILA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_EVTFILA
"SANKHYA".TRG_INC_EVTFILA
BEFORE INSERT ON EVTFILA
FOR EACH ROW

DECLARE P_CHAVEEVENTO       VARCHAR2(36);
BEGIN
   SELECT  'ID'|| --CAMPO FIXO
           CASE WHEN LENGTH(CGC) = 14 THEN 1 ELSE 2 END ||-- TIPO( 1:CNPJ OU 2:CPF)
           CASE WHEN (SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'FPTRIBUNAL') = 'N' AND LENGTH (CGC) = 14 THEN RPAD(substr(CGC,1,8),14, '0') ELSE RPAD(CGC, 14, '0') END ||--CNPJ OU CPJ COM 14 DÍGITOS COMPLETANDO COM ZERO A DIREITA
           TO_CHAR(:NEW.DHINC, 'YYYYMMDDHH24MISS') || --DATA E HORA DA GERAÇÃO NO FORMADO YYYYMMDDHH24MISS SENDO QUE A HORA VAI DE 0 À 23
           LPAD(TO_CHAR(:NEW.SEQEVENTO), 5, '0') --Número sequêncial de livre preenchimento.
       INTO P_CHAVEEVENTO
   FROM TSIEMP
   WHERE CODEMP = :NEW.CODEMP;    

   :NEW.CHAVEEVENTO := P_CHAVEEVENTO;
END;

/
