-- SANKHYA.TFPREQFOR_TRG_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TFPREQFOR_TRG_SEQ
"SANKHYA".TFPREQFOR_TRG_SEQ
BEFORE INSERT ON TFPREQFOR 
FOR EACH ROW

BEGIN
  SELECT TFPREQFOR_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;

/
