-- SANKHYA.TRG_INC_TGFREG
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFREG
"SANKHYA".TRG_INC_TGFREG 
AFTER INSERT ON TGFREG

BEGIN
    UPDATE TSIVARBD SET UTILIZA_CERTIFIC = 'S' WHERE UTILIZA_CERTIFIC = 'N';
END;

/
