-- SANKHYA.TRG_INC_UPD_TGPIGS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGPIGS
"SANKHYA".TRG_INC_UPD_TGPIGS
BEFORE INSERT OR UPDATE ON TGPIGS
FOR EACH ROW

DECLARE P_COUNT		 NUMBER(5);
        PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  SELECT COUNT(1) INTO P_COUNT
  FROM TGPIGS
  WHERE CODGRELHA = :NEW.CODGRELHA
    AND ((CODCLASSE <> :NEW.CODCLASSE) OR (CODSTEP <> :NEW.CODSTEP))
	AND CODCARGO = :NEW.CODCARGO;	
  COMMIT;
  IF P_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(-20101,'Não é permitido cadastrar o mesmo cargo('||TO_CHAR(:NEW.CODCARGO)||') mais de uma vez para mesma grelha('||TO_CHAR(:NEW.CODGRELHA)||')');
  END IF;
END;

/
