-- SANKHYA.TRG_INC_UPD_TGMTRA_SINAL_AF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGMTRA_SINAL_AF
"SANKHYA".TRG_INC_UPD_TGMTRA_SINAL_AF
AFTER INSERT OR UPDATE ON TGMTRA

BEGIN
	IF STP_GET_ATUALIZANDO THEN
		RETURN;
	END IF;
	IF (TGMTRA_PKG.V_FLAG = 0) THEN
		TGMTRA_PKG.V_FLAG := 1;
		UPDATE
			TGMTRA
		SET SINAL = TGMTRA_PKG.V_SINAL
		WHERE
			NUNOTA           = TGMTRA_PKG.V_NUNOTA
			AND NUFIN        = TGMTRA_PKG.V_NUFIN
			AND CODMETA      = TGMTRA_PKG.V_CODMETA
			AND DTREF        = TGMTRA_PKG.V_DTREF
			AND CODEMP       = TGMTRA_PKG.V_CODEMP
			AND CODGRUPOPROD = TGMTRA_PKG.V_CODGRUPOPROD
			AND CODPROD      = TGMTRA_PKG.V_CODPROD
			AND CODLOCAL     = TGMTRA_PKG.V_CODLOCAL
			AND CONTROLE     = TGMTRA_PKG.V_CONTROLE
			AND MARCA        = TGMTRA_PKG.V_MARCA
			AND CODREG       = TGMTRA_PKG.V_CODREG
			AND CODGER       = TGMTRA_PKG.V_CODGER
			AND CODVEND      = TGMTRA_PKG.V_CODVEND
			AND CODCENCUS    = TGMTRA_PKG.V_CODCENCUS
			AND CODNAT       = TGMTRA_PKG.V_CODNAT
			AND CODPROJ      = TGMTRA_PKG.V_CODPROJ
			AND CODPARC      = TGMTRA_PKG.V_CODPARC
			AND CODUF        = TGMTRA_PKG.V_CODUF
			AND CODCID       = TGMTRA_PKG.V_CODCID
			AND CODPAIS      = TGMTRA_PKG.V_CODPAIS
			AND CODTIPPARC   = TGMTRA_PKG.V_CODTIPPARC
			AND CODGRUPONAT  = TGMTRA_PKG.V_CODGRUPONAT
			AND TIPO         = 'C'
		;
		
		TGMTRA_PKG.V_FLAG := 0;
	END IF;
END;

/
