-- SANKHYA.TRG_FX_TFXTPA
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXTPA
"SANKHYA".TRG_FX_TFXTPA
   BEFORE INSERT OR UPDATE
   ON TFXTPA
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   IF (NVL(:NEW.ATUNUVERSAO, 'N') = 'S') THEN 
      SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;
            :NEW.NUVERSAO := P_CONTADOR;
            :NEW.ATUNUVERSAO := 'N';
   END IF;
END;

/
