-- SANKHYA.TRG_INC_UPD_TGFCUS_DATA_LAKE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCUS_DATA_LAKE
TRG_INC_UPD_TGFCUS_DATA_LAKE
BEFORE INSERT OR UPDATE ON TGFCUS
FOR EACH ROW

BEGIN
	:NEW.DHALTER := SYSTIMESTAMP;
END;

/
