-- SANKHYA.TRG_DLT_TGFNAT
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFNAT
"SANKHYA".TRG_DLT_TGFNAT 
BEFORE DELETE ON TGFNAT
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN
  
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODNAT = 0) THEN
     raise_application_error(-20101, ERROS_PKG.ERRO_REGISTRO_PADRAO);
  END IF;
  
  EXISTSRESTRICAO('TGFNAT',:OLD.CODNAT);
    
  SELECT COUNT(1)
  INTO P_COUNT
  FROM TSIFOP 
  WHERE TABELA = 'TGFNAT' 
  AND CODCHAVE = :OLD.CODNAT; 
 
  IF P_COUNT > 0 THEN
    DELETE FROM TSIFOP 
    WHERE TABELA = 'TGFNAT' 
    AND CODCHAVE = :OLD.CODNAT;
  END IF;
   
END;

/
