-- SANKHYA.TRG_INC_UPD_TGFPDV_BEFORE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFPDV_BEFORE
TRG_INC_UPD_TGFPDV_BEFORE
BEFORE INSERT OR UPDATE ON TGFPDV
FOR EACH ROW

BEGIN
    
    IF UPDATING THEN
        
        IF LOWER(:OLD.IDMAQUINALOCAL) IS NOT NULL AND LOWER(:NEW.IDMAQUINALOCAL) <> LOWER(:OLD.IDMAQUINALOCAL) THEN
            RAISE_APPLICATION_ERROR(-20002, 'Não é permitido atualizar o campo Identificação PDV quando ele já possui valor.');
        END IF;

      
        IF :OLD.IDMAQUINALOCAL IS NOT NULL AND :NEW.IDMAQUINALOCAL IS NULL THEN
            RAISE_APPLICATION_ERROR(-20003, 'O campo Identificação PDV não pode ser alterado para vazio.');
        END IF;
    END IF;
END;

/
