-- SANKHYA.TRG_DLT_TFPFOR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TFPFOR
"SANKHYA".TRG_DLT_TFPFOR BEFORE DELETE ON TFPFOR FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF (:OLD.CODFORM = 0) THEN
     raise_application_error(-20101, 'Registro padrao do sistema. Nao pode ser excluido.');
  END IF;
END;

/
