-- SANKHYA.TRG_DLT_TSIUSU
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TSIUSU
"SANKHYA".TRG_DLT_TSIUSU 
BEFORE DELETE ON TSIUSU 
FOR EACH ROW

DECLARE P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  EXISTSRESTRICAO('TSIUSU',:OLD.CODUSU);
  
  IF (:OLD.CODUSU = 0) THEN
     raise_application_error(-20101, 'Registro padrão do sistema. Não pode ser excluido.');
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TSILOG
  WHERE CODUSU = :OLD.CODUSU;
  
  IF P_COUNT > 0 THEN
    DELETE FROM TSILOG
    WHERE CODUSU = :OLD.CODUSU;
  END IF;

END;

/
