-- SANKHYA.TRG_DLT_TGFRECLAS
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFRECLAS
TRG_DLT_TGFRECLAS
  BEFORE DELETE
  ON TGFRECLAS 
  FOR EACH ROW

DECLARE
  ERRMSG VARCHAR2(255);
BEGIN
  	
  IF( :OLD.NUNOTAORIG IS NOT NULL OR :OLD.NUNOTADEST IS NOT NULL  ) THEN      
    ERRMSG := 'Não é possível excluir um registro que já houve a geração da nota';
    RAISE_APPLICATION_ERROR(-20101, ERRMSG);
  END IF;

END;

/
