-- SANKHYA.TRG_DLT_TGFTAB_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFTAB_AFTER
"SANKHYA".TRG_DLT_TGFTAB_AFTER 
AFTER DELETE ON TGFTAB

DECLARE
	P_COUNT INT:= 0;
	P_COUNT1 INT:= 0;
	ERROR EXCEPTION;
	ERRMSG VARCHAR2(255);
	P_NUTAB TGFTAB.NUTAB%TYPE;
	P_CODTAB SMALLINT;
	P_DTVIGOR DATE;

	CURSOR DLTTAB IS 
		SELECT NUTAB, CODTAB, DTVIGOR FROM TGFTAB_DLT;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	OPEN DLTTAB;
	LOOP
		FETCH DLTTAB INTO P_NUTAB, P_CODTAB, P_DTVIGOR;
		EXIT WHEN DLTTAB%NOTFOUND;
		
		SELECT COUNT(1) INTO P_COUNT
		FROM TGFTAB
		WHERE CODTAB = P_CODTAB
		AND DTVIGOR > P_DTVIGOR
	  AND NUTAB <> P_NUTAB;
    
    IF (P_COUNT <> 0 ) THEN
      ERRMSG := 'Não pode Excluir uma tabela com data anterior a última data da tabela.';
      RAISE ERROR;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFTAB
    WHERE CODTABORIG = P_CODTAB;
    
    SELECT COUNT(1) INTO P_COUNT1
    FROM TGFTAB
    WHERE CODTAB = P_CODTAB;
    
    IF ((P_COUNT <> 0 ) AND (P_COUNT1 = 0)) THEN
      ERRMSG := 'Tabela não pode ser excluída, pois ela dá origem a outra tabela.';
      RAISE ERROR;
    END IF;
    
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFTAB
    WHERE CODTAB = P_CODTAB;
    
    IF (P_COUNT = 0 ) THEN
      DELETE FROM TGFNTA
      WHERE CODTAB = P_CODTAB;
    END IF;
  END LOOP;
  CLOSE DLTTAB;
  DELETE FROM TGFTAB_DLT;
  RETURN;
EXCEPTION
  WHEN ERROR THEN
  RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
