-- SANKHYA.TRG_DLT_TRIDRPF
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIDRPF
"SANKHYA".TRG_DLT_TRIDRPF 
AFTER DELETE  ON TRIDRPF
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIDRTF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE
      AND :OLD.CODIMP = T.CODIMP;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIDRTF
		WHERE :OLD.CODEMP = TRIDRTF.CODEMP 
		  AND :OLD.DTREF = TRIDRTF.DTREF 
		  AND :OLD.TPAMB = TRIDRTF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIDRTF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIDRTF.CHAVE
          AND :OLD.NRODOCUMENTO = TRIDRTF.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIDRTF.TIPODOCUMENTO
          AND :OLD.NATREND = TRIDRTF.NATREND
          AND :OLD.SEQITE = TRIDRTF.SEQITE
          AND :OLD.CODIMP = TRIDRTF.CODIMP;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIIAPF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE
      AND :OLD.CODIMP = T.CODIMP;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIIAPF
		WHERE :OLD.CODEMP = TRIIAPF.CODEMP 
		  AND :OLD.DTREF = TRIIAPF.DTREF 
		  AND :OLD.TPAMB = TRIIAPF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIIAPF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIIAPF.CHAVE
          AND :OLD.NRODOCUMENTO = TRIIAPF.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIIAPF.TIPODOCUMENTO
          AND :OLD.NATREND = TRIIAPF.NATREND
          AND :OLD.SEQITE = TRIIAPF.SEQITE
          AND :OLD.CODIMP = TRIIAPF.CODIMP;
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIRNTF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE
      AND :OLD.CODIMP = T.CODIMP;
      
	IF P_COUNT > 0 THEN
		DELETE FROM TRIRNTF
		WHERE :OLD.CODEMP = TRIRNTF.CODEMP 
		  AND :OLD.DTREF = TRIRNTF.DTREF 
		  AND :OLD.TPAMB = TRIRNTF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIRNTF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIRNTF.CHAVE
          AND :OLD.NRODOCUMENTO = TRIRNTF.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIRNTF.TIPODOCUMENTO
          AND :OLD.NATREND = TRIRNTF.NATREND
          AND :OLD.SEQITE = TRIRNTF.SEQITE
          AND :OLD.CODIMP = TRIRNTF.CODIMP;          
	END IF;

	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPRTF T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND
      AND :OLD.SEQITE = T.SEQITE
      AND :OLD.CODIMP = T.CODIMP;      

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPRTF
		WHERE :OLD.CODEMP = TRIPRTF.CODEMP 
		  AND :OLD.DTREF = TRIPRTF.DTREF 
		  AND :OLD.TPAMB = TRIPRTF.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPRTF.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPRTF.CHAVE
          AND :OLD.NRODOCUMENTO = TRIPRTF.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIPRTF.TIPODOCUMENTO
          AND :OLD.NATREND = TRIPRTF.NATREND
          AND :OLD.SEQITE = TRIPRTF.SEQITE
          AND :OLD.CODIMP = TRIPRTF.CODIMP;          
	END IF;
END;		

/
