-- SANKHYA.TRG_DLT_TGFEMP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFEMP
"SANKHYA".TRG_DLT_TGFEMP
BEFORE DELETE ON TGFEMP FOR EACH ROW

DECLARE
P_COUNT  NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  EXISTSRESTRICAO('TGFEMP',:OLD.CODEMP);
    
  SELECT COUNT(1) INTO P_COUNT FROM TGFLIV C WHERE C.CODEMP = :OLD.CODEMP;
  IF P_COUNT <> 0 THEN
     raise_application_error(-20101, 'Existe referência a esta empresa na tabela TGFLIV.');
  END IF;

  SELECT COUNT(1) INTO P_COUNT
  FROM TGFORD 
  WHERE CODEMP = :OLD.CODEMP 
    AND ORDEMCARGA = 0; 
   
  IF P_COUNT > 0 THEN
    DELETE FROM TGFORD WHERE CODEMP = :OLD.CODEMP AND ORDEMCARGA = 0;
  END IF;
  
END;

/
