-- SANKHYA.TRG_FX_TFXPKI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_FX_TFXPKI
"SANKHYA".TRG_FX_TFXPKI
   BEFORE INSERT OR UPDATE OR DELETE
   ON TFXPKI
   FOR EACH ROW

DECLARE
   P_CONTADOR   NUMBER (19);
BEGIN
   
   IF (DELETING) THEN
	  INSERT INTO TFXADE (NOMETAB, STRPK)
		VALUES ('TPRODUTOKIT', 'ID = ' || TO_CHAR (:OLD.ID) || ' AND CODPRODUTO = ' || TO_CHAR (:OLD.CODPRODUTO) || ' AND MATERIAPRIMA = ' || TO_CHAR (:OLD.MATERIAPRIMA) || ' AND NUVERSAO = ' || TO_CHAR (:OLD.NUVERSAO));
      RETURN;
   END IF;
   
   IF (INSERTING) THEN
	  SELECT SEQ_TFXPKI.NEXTVAL INTO P_CONTADOR FROM DUAL;
	  :NEW.ID := P_CONTADOR;
   END IF;

   SELECT SEQ_GLOBALFOX.NEXTVAL INTO P_CONTADOR FROM DUAL;

   :NEW.NUVERSAO := P_CONTADOR;
END;

/
