-- SANKHYA.TRG_DEL_TGWSEP
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DEL_TGWSEP
"SANKHYA".TRG_DEL_TGWSEP 
BEFORE DELETE ON TGWSEP
FOR EACH ROW

DECLARE
  P_COUNT                  NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGWTAR TAR 
     , TGWITT ITT
  WHERE TAR.NUTAREFA = ITT.NUTAREFA
    AND TAR.NUTAREFA = :OLD.NUTAREFA
    AND TAR.CODTAREFA = 3
    AND ITT.SITUACAO NOT IN ('C','F');
    
  IF P_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(-20101,'Existe uma linha na TGWTAR que tem dependência com esses dados. Nao pode ser excluído.');
  END IF;        
   
END;

/
