-- SANKHYA.TRG_INC_UPD_TFPCTI
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TFPCTI
"SANKHYA".TRG_INC_UPD_TFPCTI
BEFORE UPDATE ON TFPCTI
FOR EACH ROW

BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  RAISE_APPLICATION_ERROR(-20101, 'A empresa da convocação não pode ser alterada!');
  
END;

/
