-- SANKHYA.TRG_INC_TCSFATHC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TCSFATHC
"SANKHYA".TRG_INC_TCSFATHC 
AFTER INSERT ON TCSFATHC

BEGIN
    UPDATE TSIVARBD SET UTILIZA_HCRUZADAS = 'S' WHERE UTILIZA_HCRUZADAS = 'N';
END;

/
