-- SANKHYA.TRG_INC_TGFIII
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFIII
"SANKHYA".TRG_INC_TGFIII    
BEFORE INSERT ON TGFIII  
FOR EACH ROW

DECLARE
  P_LOGICO           CHAR(1);
BEGIN

    BEGIN
        SELECT NVL(LOGICO, 'N')
        INTO P_LOGICO
        FROM TSIPAR
        WHERE CHAVE = 'IMPTAGEXCNOTNAC';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_LOGICO := 'N';
    END;
    
    :NEW.IMPTAGEXCNOTNAC := P_LOGICO; 

END;

/
