-- SANKHYA.TRG_INC_UPD_TGFMDC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFMDC
"SANKHYA".TRG_INC_UPD_TGFMDC
BEFORE INSERT OR UPDATE ON TGFMDC
FOR EACH ROW

DECLARE
  P_COUNT INTEGER; 
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  IF ((INSERTING OR (UPDATING('CODTIPTIT'))) AND (:NEW.CODTIPTIT IS NOT NULL)) THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFTIT
    WHERE CODTIPTIT = :NEW.CODTIPTIT
    AND ATIVO = 'N';
    IF (P_COUNT > 0) THEN 
      RAISE_APPLICATION_ERROR(-20101, 'Tipo de Título de receita não está ativo. ');
    END IF;
              END IF;              

END;

/
