-- SANKHYA.TRG_INC_UPD_TGFOSL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFOSL
"SANKHYA".TRG_INC_UPD_TGFOSL BEFORE UPDATE OR INSERT ON TGFOSL FOR EACH ROW

DECLARE
  P_COUNT INT;
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF; 
  
   SELECT COUNT(*) INTO P_COUNT  
   FROM TGFTOP
   WHERE CODTIPOPER = :NEW.CODTIPOPER ;
	
   IF (P_COUNT = 0) THEN 
     RAISE_APPLICATION_ERROR(-20101,'A TOP de código: '||:NEW.CODTIPOPER||' não existe.');
   END IF;
END;

/
