-- SANKHYA.TRG_DLT_TGFCCM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFCCM
"SANKHYA".TRG_DLT_TGFCCM BEFORE DELETE ON TGFCCM FOR EACH ROW

DECLARE
	P_CONT         	INT;
	P_NUMCONTRATO	NUMBER(10);
	P_CODPROD		NUMBER(10);
	P_SEQUENCIA		NUMBER(10);
	P_QTDFAT		NUMBER(10);
	PRAGMA AUTONOMOUS_TRANSACTION;
	CURSOR CUR_TCSCCF IS			
	  SELECT NUMCONTRATO, CODPROD, SEQUENCIA		
	  FROM TCSCCF
	  WHERE NUNOTA = :OLD.NUNOTA
        AND CODVEND = :OLD.CODVEND;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

	SELECT COUNT(1) INTO P_CONT
  FROM TGFCOM
  WHERE CODVEND = :OLD.CODVEND
       AND NUNOTAORIG = :OLD.NUNOTA
    AND TIPO = 'M'
    AND (NUFIN <> 0 OR REFERENCIA IS NOT NULL);

  IF P_CONT > 0 THEN
    RAISE_APPLICATION_ERROR (-20101, 'Ja existe comissão calculada e paga p/este vendedor.');
  END IF;

  DELETE
  FROM TGFCOM
  WHERE CODVEND = :OLD.CODVEND
    AND NUNOTAORIG = :OLD.NUNOTA
    AND TIPO = 'M';
  
  /* Comissão múltipla de contratos */
    OPEN CUR_TCSCCF;
  
  LOOP
    FETCH CUR_TCSCCF INTO P_NUMCONTRATO, P_CODPROD, P_SEQUENCIA;
    
    EXIT WHEN CUR_TCSCCF%NOTFOUND;
    
    IF P_NUMCONTRATO > 0 THEN
      SELECT NVL(QTDFAT, 0) INTO P_QTDFAT
    FROM TCSVPC
    WHERE NUMCONTRATO = P_NUMCONTRATO
      AND CODPROD = P_CODPROD
      AND CODVEND = :OLD.CODVEND
      AND SEQUENCIA = P_SEQUENCIA;      
    
    IF P_QTDFAT > 0 THEN
      P_QTDFAT := P_QTDFAT - 1;
      UPDATE TCSVPC SET QTDFAT = P_QTDFAT
      WHERE NUMCONTRATO = P_NUMCONTRATO
        AND CODPROD = P_CODPROD
        AND CODVEND = :OLD.CODVEND
        AND SEQUENCIA = P_SEQUENCIA;
    END IF;
        
    END IF;
    
  END LOOP;
    CLOSE CUR_TCSCCF;
  
  DELETE
  FROM TCSCCF
  WHERE NUNOTA = :OLD.NUNOTA
    AND CODVEND = :OLD.CODVEND;  
    
  COMMIT;
END;

/
