-- SANKHYA.TRG_DLT_TRIPBN
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TRIPBN
"SANKHYA".TRG_DLT_TRIPBN 
AFTER DELETE  ON TRIPBN 
FOR EACH ROW

DECLARE P_COUNT	NUMBER(10);
BEGIN
	SELECT COUNT(1) INTO P_COUNT
	FROM TRIPRRT T
	WHERE :OLD.CODEMP = T.CODEMP 
	  AND :OLD.DTREF = T.DTREF 
	  AND :OLD.TPAMB = T.TPAMB 
	  AND :OLD.SEQUENCIA = T.SEQUENCIA 
	  AND :OLD.CHAVE = T.CHAVE
      AND :OLD.NRODOCUMENTO = T.NRODOCUMENTO
      AND :OLD.TIPODOCUMENTO = T.TIPODOCUMENTO
      AND :OLD.NATREND = T.NATREND      
	  AND :OLD.SEQITE = T.SEQITE
      AND :OLD.CODIMP = T.CODIMP;

	IF P_COUNT > 0 THEN
		DELETE FROM TRIPRRT
		WHERE :OLD.CODEMP = TRIPRRT.CODEMP 
		  AND :OLD.DTREF = TRIPRRT.DTREF 
		  AND :OLD.TPAMB = TRIPRRT.TPAMB 
		  AND :OLD.SEQUENCIA = TRIPRRT.SEQUENCIA 
		  AND :OLD.CHAVE = TRIPRRT.CHAVE
          AND :OLD.NRODOCUMENTO = TRIPRRT.NRODOCUMENTO
          AND :OLD.TIPODOCUMENTO = TRIPRRT.TIPODOCUMENTO
          AND :OLD.NATREND = TRIPRRT.NATREND
		 AND :OLD.SEQITE = TRIPRRT.SEQITE
		 AND :OLD.CODIMP = TRIPRRT.CODIMP;
	END IF;
END;		

/
