-- SANKHYA.TRG_INC_UPD_TGFCAB_TGFGXE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCAB_TGFGXE
"SANKHYA".TRG_INC_UPD_TGFCAB_TGFGXE
   AFTER UPDATE
   ON TGFCAB
   FOR EACH ROW
   
DECLARE
   P_COUNT   NUMBER (05);
BEGIN

   IF STP_GET_ATUALIZANDO THEN 
     RETURN;
   END IF;

   SELECT COUNT (1)
     INTO P_COUNT
     FROM TGFTOP T
    WHERE     T.CODTIPOPER = :NEW.CODTIPOPER
          AND T.DHALTER = :NEW.DHTIPOPER
          AND T.ATUALLIVFIS <> 'N'
          AND EXISTS
                 (SELECT 1
                    FROM TGFTOP TOLD
                   WHERE     TOLD.CODTIPOPER = :OLD.CODTIPOPER
                         AND TOLD.DHALTER = :OLD.DHTIPOPER
                         AND T.ATUALLIVFIS <> TOLD.ATUALLIVFIS);

   IF P_COUNT > 0
   THEN
      SNK_VAL_UTIL_PRODUTO_GENERICO (:NEW.NUNOTA);
   END IF;
END;

/
