-- SANKHYA.TRG_INC_UPD_DLT_TGWEST
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_DLT_TGWEST
TRG_INC_UPD_DLT_TGWEST
BEFORE INSERT OR UPDATE OR DELETE ON TGWEST FOR EACH ROW

DECLARE    
    P_COUNT            NUMBER(5);
    P_CODEND           NUMBER(10);
    P_ESTOQUE          FLOAT;
	P_WMSBLOQUEADO     FLOAT;
    P_CODEMP           NUMBER(10);
    P_CODLOCAL           NUMBER(10);     
    P_CODPROD           NUMBER(10);
    P_CONTROLE           TGWEST.CONTROLE%TYPE;
    P_CODPARC           NUMBER(10);
    P_WMSLOCALAJEST    NUMBER(10);
	P_TIPO	           VARCHAR2(1);
BEGIN
 BEGIN 
      IF STP_GET_ATUALIZANDO THEN
        RETURN;
      END IF;

        SELECT NVL(WMSLOCALAJEST, 0) INTO P_WMSLOCALAJEST 
        FROM TGFEMP
        WHERE CODEMP = NVL(:OLD.CODEMP, :NEW.CODEMP);
        
  EXCEPTION WHEN NO_DATA_FOUND THEN
    BEGIN 
        SELECT INTEIRO INTO P_WMSLOCALAJEST
        FROM TSIPAR
        WHERE CHAVE = 'WMSLOCALAJEST';
        
    EXCEPTION WHEN NO_DATA_FOUND THEN
        P_WMSLOCALAJEST  := 0;
    END;
  END;
  
  P_CODLOCAL := :NEW.CODLOCAL;     
  P_CODEMP   := :NEW.CODEMP;  
  P_CODPROD  := :NEW.CODPROD;
  P_CONTROLE := :NEW.CONTROLE;        
  P_CODPARC  := :NEW.CODPARC;
  
  IF INSERTING THEN
    P_CODEND := :NEW.CODEND;
    P_ESTOQUE := NVL(:NEW.ESTOQUEVOLPAD,0);
  ELSIF UPDATING THEN
    P_CODEND := :NEW.CODEND;
    P_ESTOQUE := NVL(:NEW.ESTOQUEVOLPAD,0) - NVL(:OLD.ESTOQUEVOLPAD, 0);
  ELSE
    P_CODEND := NVL(:OLD.CODEND,0);
    P_ESTOQUE := NVL(:OLD.ESTOQUEVOLPAD,0) * -1;
    P_CODEMP   := :OLD.CODEMP;
    P_CODLOCAL := :OLD.CODLOCAL;
    P_CODPROD  := :OLD.CODPROD;
    P_CONTROLE := :OLD.CONTROLE;        
    P_CODPARC  := :OLD.CODPARC;    
  END IF;
  
  IF P_WMSLOCALAJEST <> 0 THEN
    P_CODLOCAL := P_WMSLOCALAJEST;
  END IF;       
    
  IF P_ESTOQUE <> 0 THEN    

	P_TIPO := 'P';
   
    IF P_CODPARC > 0 THEN
       P_TIPO := 'T';
    END IF;

    SELECT COUNT(1) INTO P_COUNT
    FROM TGFEST
    WHERE CODEMP = P_CODEMP
    AND CODLOCAL = P_CODLOCAL
    AND CODPROD = P_CODPROD
    AND CONTROLE = P_CONTROLE
    AND TIPO = P_TIPO
    AND CODPARC = P_CODPARC;
    
    IF (P_COUNT = 0) THEN
      IF NOT DELETING THEN
          INSERT INTO TGFEST(CODEMP
           , CODLOCAL
           , CODPROD
           , CONTROLE
           , CODPARC
           , TIPO
           , WMSBLOQUEADO)VALUES(P_CODEMP
           , P_CODLOCAL
           , P_CODPROD
           , P_CONTROLE
           , P_CODPARC
           , P_TIPO
           , P_ESTOQUE);
      END IF;
    ELSE
		SELECT NVL(WMSBLOQUEADO, 0) INTO P_WMSBLOQUEADO
	    FROM TGFEST
	    WHERE CODEMP = P_CODEMP
	    AND CODLOCAL = P_CODLOCAL
	    AND CODPROD = P_CODPROD
	    AND CONTROLE = P_CONTROLE
	    AND TIPO = P_TIPO
	    AND CODPARC = P_CODPARC;
      
		IF (P_WMSBLOQUEADO <> 0) THEN
	      UPDATE TGFEST SET WMSBLOQUEADO = NVL(WMSBLOQUEADO, 0) + P_ESTOQUE
	      WHERE CODEMP = P_CODEMP
	      AND CODLOCAL = P_CODLOCAL
	      AND CODPROD = P_CODPROD
	      AND CONTROLE = P_CONTROLE
	      AND TIPO = P_TIPO
	      AND CODPARC = P_CODPARC;
    	END IF;
    END IF;
  END IF;
END;

/
