-- SANKHYA.TRG_DLT_TGWAJE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGWAJE
"SANKHYA".TRG_DLT_TGWAJE 
AFTER DELETE ON TGWAJE 
FOR EACH ROW

DECLARE
P_COUNT NUMBER(5);
BEGIN

  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
  
  SELECT COUNT(1)
    INTO P_COUNT
  FROM TGWESI 
  WHERE NUAJUSTE = :OLD.NUAJUSTE;
  
  IF P_COUNT > 0 THEN
    DELETE FROM TGWESI 
    WHERE NUAJUSTE = :OLD.NUAJUSTE;
  END IF;
  
END;

/
