-- SANKHYA.TRG_INC_UPD_TGFESTBAR
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFESTBAR
"SANKHYA".TRG_INC_UPD_TGFESTBAR
BEFORE INSERT OR UPDATE ON TGFESTBAR
FOR EACH ROW

DECLARE P_COUNT  NUMBER(10); 
BEGIN
  IF Variaveis_Pkg.CODBARRA_EST <> 'EST' THEN
    SELECT COUNT(1) INTO P_COUNT
    FROM TGFEST
    WHERE CODEMP = :NEW.CODEMP
      AND CODPROD = :NEW.CODPROD
      AND CODLOCAL = :NEW.CODLOCAL
      AND CONTROLE = :NEW.CONTROLE
      AND CODPARC = :NEW.CODPARC
      AND TIPO = :NEW.TIPO;
    Variaveis_Pkg.CODBARRA_EST := 'BAR';    
    IF P_COUNT > 0 THEN      
      UPDATE TGFEST SET CODBARRA = :NEW.CODBARRA
      WHERE CODEMP = :NEW.CODEMP
        AND CODPROD = :NEW.CODPROD
        AND CODLOCAL = :NEW.CODLOCAL
        AND CONTROLE = :NEW.CONTROLE
        AND CODPARC = :NEW.CODPARC
        AND TIPO = :NEW.TIPO;
    END IF;
    Variaveis_Pkg.CODBARRA_EST := ' ';
  END IF;    
END;

/
