-- SANKHYA.TRG_DLT_TGFPRO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFPRO
"SANKHYA".TRG_DLT_TGFPRO
   BEFORE DELETE
   ON TGFPRO
   FOR EACH ROW

DECLARE
   P_COUNT   INT:= 0;

 BEGIN

   IF STP_GET_ATUALIZANDO THEN
    RETURN;
   END IF;

   EXISTSRESTRICAO('TGFPRO',:OLD.CODPROD);

   BEGIN
    VARIAVEIS_PKG.V_DLT_PROD := TRUE;
   END;

   SELECT COUNT (1) INTO P_COUNT
   FROM TGFTEL T WHERE T.CODPROD = :OLD.CODPROD;
   IF P_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20101,'Produto está sendo referenciado no Telemarketing, não pode ser excluído.');
   END IF;
   
   
   SELECT COUNT(1) INTO P_COUNT
   FROM TGFICM
   WHERE (TIPRESTRICAO2 = 'P' AND CODRESTRICAO2 = :OLD.CODPROD) OR
         (TIPRESTRICAO = 'P' AND CODRESTRICAO = :OLD.CODPROD);
   IF P_COUNT > 0 THEN
     DELETE FROM TGFICM
     WHERE (TIPRESTRICAO2 = 'P' AND CODRESTRICAO2 = :OLD.CODPROD) OR
           (TIPRESTRICAO = 'P' AND CODRESTRICAO = :OLD.CODPROD);
   END IF;
   
   
   SELECT COUNT(1) INTO P_COUNT
   FROM TSIATA
   WHERE TIPO = 'R' AND CODATA = :OLD.CODPROD;
   IF P_COUNT > 0 THEN
     DELETE FROM TSIATA
     WHERE TIPO = 'R' AND CODATA = :OLD.CODPROD;
   END IF;
         

   SELECT COUNT(1) INTO P_COUNT
   FROM TGFIMA
   WHERE TIPO IN ('R', 'S') AND CODIGO = :OLD.CODPROD;
   IF P_COUNT > 0 THEN
     DELETE FROM TGFIMA
     WHERE TIPO IN ('R', 'S') AND CODIGO = :OLD.CODPROD;
   END IF;
   
   
   SELECT COUNT(1) INTO P_COUNT
   FROM TGFFCP
   WHERE CODPROD = :OLD.CODPROD AND VARIACAO = 30000;
   IF P_COUNT > 0 THEN
     DELETE FROM TGFFCP  
     WHERE CODPROD = :OLD.CODPROD AND VARIACAO = 30000;
   END IF;
  
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGFDFO
  WHERE CODPROD = :OLD.CODPROD;
  IF P_COUNT > 0 THEN
    DELETE FROM TGFDFO 
    WHERE CODPROD = :OLD.CODPROD;
  END IF;
  
  
  SELECT COUNT(1) INTO P_COUNT
  FROM TGFPMA
  WHERE CODPROD = :OLD.CODPROD;
  IF P_COUNT > 0 THEN
    DELETE FROM TGFPMA
    WHERE CODPROD = :OLD.CODPROD;
  END IF;
        
  
END;

/
