-- SANKHYA.TRG_DLT_TGFMBC_AFTER
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFMBC_AFTER
"SANKHYA".TRG_DLT_TGFMBC_AFTER AFTER DELETE ON TGFMBC

DECLARE
    P_NUMTRANSF         INT;
	P_ORIGMOV           VARCHAR2(1);
	P_RECDESP			INT;
	P_COUNT				INT;
    P_COUNT2			INT;
	ERRMSG            VARCHAR2(255);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
    SELECT COUNT(1) INTO P_COUNT
	FROM TGFMBC_DLT;
	IF P_COUNT = 1 THEN
	    SELECT NUMTRANSF, ORIGMOV, RECDESP 
  		INTO P_NUMTRANSF, P_ORIGMOV, P_RECDESP
		FROM TGFMBC_DLT;
		
	    IF (P_NUMTRANSF IS NOT NULL) THEN
	    
	    	SELECT COUNT(1) INTO P_COUNT2
			FROM TGFMBC
			WHERE NUMTRANSF = P_NUMTRANSF
	        AND RECDESP = (P_RECDESP * -1)
	        AND ORIGMOV = P_ORIGMOV;
	    
	        IF P_COUNT2 = 1 THEN
		 	   DELETE FROM TGFMBC
			   WHERE NUMTRANSF = P_NUMTRANSF
			     AND RECDESP = (P_RECDESP * -1)
			     AND ORIGMOV = P_ORIGMOV;
		    END IF;
		END IF;		
	END IF;

	IF P_COUNT > 0 THEN
 	  DELETE FROM TGFMBC_DLT;			
	END IF;	

	EXCEPTION WHEN NO_DATA_FOUND THEN
	  NULL;
END;

/
