-- SANKHYA.TRG_INC_UPD_TGFACO
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFACO
"SANKHYA".TRG_INC_UPD_TGFACO BEFORE INSERT OR UPDATE ON TGFACO REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW

DECLARE
   P_COUNT            INT;
   ERRMSG             VARCHAR2(255);
   ERROR                    EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

   SELECT COUNT(1) INTO P_COUNT
   FROM TGFEMP E
   WHERE E.CODEMP = :NEW.CODEMP AND E.ATIVO = 'S';
   IF (P_COUNT = 0 ) THEN
      Stp_Popula_Msg('TGFEMP');
   END IF;
  SELECT COUNT(1) INTO P_COUNT
   FROM TGFPAR P
   WHERE P.CODPARC = :NEW.CODPARC
      AND P.ATIVO = 'S';
   IF (P_COUNT = 0 ) THEN
      Stp_Popula_Msg('TGFPAR');
   END IF;
  IF (P_COUNT = 0) THEN
     ERRMSG := 'Codigo do parceiro obrigatorio. N?o pode ser zero(0).';
     RAISE ERROR;
   END IF;
   SELECT COUNT(1) INTO P_COUNT FROM TGFTOP T
   WHERE T.CODTIPOPER = :NEW.CODTIPOPER;
  IF (P_COUNT = 0) THEN
    ERRMSG := 'Codigo da operac?o inexistente. Atualizac?o cancelada.';
  END IF;
  EXCEPTION
       WHEN ERROR THEN
       RAISE_APPLICATION_ERROR(-20101, ERRMSG);
END;

/
