-- SANKHYA.TRG_INC_UPD_TGPREL
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGPREL
"SANKHYA".TRG_INC_UPD_TGPREL
BEFORE INSERT OR UPDATE ON TGPREL FOR EACH ROW

DECLARE
  P_COUNT NUMBER(5);
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  SELECT COUNT(1) 
    INTO P_COUNT
  FROM TFPFUN
  WHERE CODFUNC = :NEW.CODFUNC
    AND CODEMP = :NEW.CODEMPFUNC;
  IF P_COUNT = 0 THEN
    RAISE_APPLICATION_ERROR(-20101,'Funcionario nao cadastrado para esta empresa (TFPFUN).');
  END IF;
END;

/
