-- SANKHYA.TRG_DLT_TCILOC
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TCILOC
TRG_DLT_TCILOC
BEFORE DELETE ON TCILOC
FOR EACH ROW

DECLARE 
	P_COUNT				NUMBER(5);
BEGIN
	SELECT COUNT(1) 
	INTO P_COUNT
	FROM TCILOC_ATUAL
	WHERE CODPROD = :OLD.CODPROD
		AND CODBEM = :OLD.CODBEM
		AND DTENTRADA = :OLD.DTENTRADA;

	IF P_COUNT > 0 THEN
        UPDATE TCILOC_ATUAL
        SET DELETADO = 'S'
        WHERE CODPROD = :OLD.CODPROD
            AND CODBEM = :OLD.CODBEM
            AND DTENTRADA = :OLD.DTENTRADA;
    END IF;
END;

/
