-- SANKHYA.TRG_INC_UPD_TGFCVE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFCVE
"SANKHYA".TRG_INC_UPD_TGFCVE BEFORE  INSERT OR UPDATE  ON TGFCVE FOR EACH ROW

BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

 
   IF UPDATING('CODVEICULO') AND :NEW.CODVEICULO IS NOT NULL THEN
     STP_VALIDA_VEICULO(:NEW.CODVEICULO);
  END IF;
END;

/
