-- SANKHYA.TFPREQPKG_TRG_SEQ
CREATE OR REPLACE TRIGGER SANKHYA.TFPREQPKG_TRG_SEQ
"SANKHYA".TFPREQPKG_TRG_SEQ
BEFORE INSERT ON TFPREQPKG 
FOR EACH ROW

BEGIN
  SELECT TFPREQPKG_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   DUAL;
END;

/
