-- SANKHYA.TRG_DLT_TGFFRE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TGFFRE
"SANKHYA".TRG_DLT_TGFFRE 
BEFORE DELETE ON TGFFRE FOR EACH ROW

DECLARE
  P_COUNT INT;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;

  IF :OLD.TIPACERTO = 'C' THEN /* compensação financeira*/
  /*validando somente os titulos que ainda pertencem ao :OLD.NUACERTO*/
    SELECT COUNT(1) INTO P_COUNT
      FROM TGFFIN
      WHERE NUFIN = :OLD.NUFIN
      AND DHBAIXA IS NOT NULL
	  AND NUCOMPENS IS NOT NULL
	  AND NUCOMPENS = :OLD.NUACERTO;
  ELSE /* outros */
    SELECT COUNT(1) INTO P_COUNT
      FROM TGFFIN
      WHERE NUFIN = :OLD.NUFIN
      AND DHBAIXA IS NOT NULL;
  END IF;
  IF P_COUNT > 0 THEN
     RAISE_APPLICATION_ERROR (-20101, 'Financeiro Número Único: ' || TO_CHAR(:OLD.NUFIN) || ' ainda está baixado, não pode ser excluido.');
  END IF;
END;

/
