-- SANKHYA.TRG_INC_TGFFAM
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_TGFFAM
"SANKHYA".TRG_INC_TGFFAM
AFTER INSERT ON TGFFAM


DECLARE 
    P_COUNT     NUMBER(05);

BEGIN
    UPDATE TSIVARBD SET EXISTE_REGISTRO_TGFFAM = 'S' WHERE EXISTE_REGISTRO_TGFFAM = 'N';
END;

/
