-- SANKHYA.TRG_DLT_TMIRME
CREATE OR REPLACE TRIGGER SANKHYA.TRG_DLT_TMIRME
"SANKHYA".TRG_DLT_TMIRME
BEFORE DELETE ON TMIRME
FOR EACH ROW
  
DECLARE P_COUNT   NUMBER(10);
BEGIN
  SELECT COUNT(1) INTO P_COUNT
  FROM TMIMXE
  WHERE CODEXE = :OLD.CODEXE
    AND NUMET = :OLD.NUMET;
  
  IF P_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(-20101, 'Resultado de meta não pode ser deletado, pois o exercício ainda está vinculado a meta.');
  END IF;
END;

/
