-- SANKHYA.TRG_INC_UPD_TGFEST_TGFGXE
CREATE OR REPLACE TRIGGER SANKHYA.TRG_INC_UPD_TGFEST_TGFGXE
"SANKHYA".TRG_INC_UPD_TGFEST_TGFGXE
AFTER INSERT OR UPDATE 
ON TGFEST 
FOR EACH ROW

DECLARE
    P_COUNT     NUMBER(05);
    
BEGIN    
  
    SELECT COUNT(1) INTO P_COUNT 
    FROM TGFGXE
    WHERE CODPROD = :NEW.CODPROD;
 
    IF (P_COUNT > 0) THEN
       RAISE_APPLICATION_ERROR(-20101, 'Não é permitido movimentação de estoque para produto genérico. Produto: ' || TO_CHAR(:NEW.CODPROD) || '.');
    END IF;

END;

/
