# Generated by Django 6.0.4 on 2026-04-28 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RastreioAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ATRIBUIR', 'Atribuir lote ao pedido'), ('DESVINCULAR', 'Desvincular lote do pedido')], db_index=True, max_length=16)),
                ('nunota', models.IntegerField(db_index=True)),
                ('sequencia', models.IntegerField()),
                ('codagregacao', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('qtd', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('codusu', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nomeusu', models.CharField(blank=True, max_length=80, null=True)),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Rastreio',
                'verbose_name_plural': 'Auditoria do Rastreio',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('lote', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulação Comercial',
                'verbose_name_plural': 'Simulações Comerciais',
                'ordering': ('-created_at',),
            },
        ),
    ]
