from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="sankhya_index"),
    path("health/", views.health, name="sankhya_health"),
    path("produtos/", views.produtos_list, name="produtos_list"),
    path("parceiros/", views.parceiros_list, name="parceiros_list"),
    path("parceiros/search/", views.parceiros_search, name="parceiros_search"),
    path("top/search/", views.top_search, name="top_search"),
    path("natureza/search/", views.natureza_search, name="natureza_search"),
    path("empresa/search/", views.empresa_search, name="empresa_search"),
    path("cencus/search/", views.cencus_search, name="cencus_search"),
    path("produtos/search/", views.produtos_search, name="produtos_search"),
    path("lote/next/", views.next_lote, name="next_lote"),
    path("vendedor/search/", views.vendedor_search, name="vendedor_search"),
    path("transportadora/search/", views.transportadora_search, name="transportadora_search"),
    path("vol/search/", views.vol_search, name="vol_search"),
    path("lote/search/", views.lote_search, name="lote_search"),
    path("entrada/preview/", views.entrada_preview, name="entrada_preview"),
    path("compras/portal/", views.compras_portal, name="compras_portal"),
    path("compras/central/", views.compras_central, name="compras_central"),
    path("compras/classificacao/", views.compras_classificacao, name="compras_classificacao"),
    path("comercial/", views.comercial_dashboard, name="comercial_dashboard"),
    path("comercial/lista/", views.comercial_lista, name="comercial_lista"),
    path("packing/portal/", views.packing_portal, name="packing_portal"),
    path("packing/central/", views.packing_central, name="packing_central"),
    path("packing/central/validar/", views.packing_central_validar, name="packing_central_validar"),
    path("packing/central/salvar/", views.packing_central_salvar, name="packing_central_salvar"),
    path("item/plan/", views.item_plan, name="item_plan"),
    path("item/list/", views.item_list, name="item_list"),
    path("unit/debug/", views.unit_factor_debug, name="unit_factor_debug"),
    path("unit/debug/details/", views.unit_factor_debug_details, name="unit_factor_debug_details"),
    path("item/debug/tgfite/", views.item_debug_tgfite, name="item_debug_tgfite"),
    path("item/weight/debug/", views.item_weight_debug, name="item_weight_debug"),
    path("item/save/", views.item_save, name="item_save"),
    path("item/delete/", views.item_delete, name="item_delete"),
    path("item/duplicate/", views.item_duplicate, name="item_duplicate"),
    path("item/get_lote/", views.item_get_lote, name="item_get_lote"),
    path("nota/delete/", views.nota_delete, name="nota_delete"),
    path("nota/diagnose/", views.nota_diagnose, name="nota_diagnose"),
    path("class/plan/", views.class_plan, name="class_plan"),
    path("class/execute/", views.class_execute, name="class_execute"),
    path("lote/consultar/", views.lote_consultar, name="lote_consultar"),
    path("header/update/", views.header_update, name="header_update"),
    path("header/status/", views.header_status_toggle, name="header_status_toggle"),
    path("header/status/get/", views.header_status_get, name="header_status_get"),
    path("header/plan/", views.header_plan, name="header_plan"),
    path("comercial/sim/save/", views.comercial_sim_save, name="comercial_sim_save"),
    path("comercial/sim/list/", views.comercial_sim_list, name="comercial_sim_list"),
    path("classificacao/resumo/", views.classificacao_resumo, name="classificacao_resumo"),
    # Duplicação automática/rotas removidas a pedido: sem duplicar TOP 11→26 via portal
]
